/**
 * Frosthaven — première partie tutorielle, et campagne.
 *
 * Source : « Frosthaven Rulebook », Cephalofair Games, en ANGLAIS, livré en
 * trois fichiers PDF à numérotation continue (pages 1 à 38, 39 à 72, 73 à
 * 84). Les trois parties sont fusionnées en un seul fichier par
 * `npm run merge` (voir GUIDE_CREATION_TUTO.md) : la page imprimée N est la
 * N-ième page du PDF, d'où `pageOffset: 0`.
 *
 * Le texte des étapes est une traduction du livret. Les termes imprimés sur
 * le matériel (Move, Attack, Shield, long rest, Outpost Phase…) sont
 * conservés tels quels après une première mention traduite : c'est ce que
 * le joueur lit sur ses cartes. Les titres de section du champ `ref` sont
 * ceux du livret, pour le retrouver.
 *
 * Une partie du livret est sous autocollants scellés (étapes 10, 13 et 14
 * de la mise en place, et d'autres plus loin). Leur contenu n'est PAS
 * reconstitué : chaque étape concernée renvoie au livret.
 *
 * Périmètre : création des six personnages de départ, mise en place et
 * déroulement d'un scénario, fin de scénario, phase d'avant-poste, et
 * reprise d'une campagne en cours à partir des fiches.
 */

import type { Tutorial } from '../engine/types'

export const frosthaven: Tutorial = {
  id: 'frosthaven',
  title: 'Frosthaven',
  tagline:
    'Un avant-poste aux confins du nord, une compagnie de mercenaires, et des scénarios enchaînés en campagne. La suite de Gloomhaven.',
  contentVersion: '1.0',
  publisher: 'Cephalofair Games',
  author: 'Isaac Childres',
  players: {
    min: 1,
    max: 4,
    recommended: 2,
    labels: { 1: 'Solo' },
    notes: {
      1: 'Le livret prévoit le solo comme variante (p.69) : un seul joueur contrôle au moins deux personnages. Le niveau de scénario se calcule alors sur (niveau moyen + 1) ÷ 2, arrondi au supérieur.',
      2: 'À deux personnages, les monstres de chaque salle sont ceux de la barre du haut dans le livre de scénarios.',
      3: 'À trois personnages, les monstres de chaque salle sont ceux de la barre du milieu.',
      4: 'À quatre personnages, les monstres de chaque salle sont ceux de la barre du bas.',
    },
  },
  minutes: 120,

  // Nuit polaire et glace : fond bleu-noir, accents de givre. Le livret
  // lui-même est sombre, à titres blancs.
  theme: {
    bg: '#0a1119',
    bg2: '#101a25',
    bg3: '#182534',
    stroke: '#2b3f52',
    strokeSoft: '#1f3042',
    fg: '#eaf2f8',
    fgDim: '#a3b7c7',
    fgFaint: '#6f8698',
    accent: '#8fd3f4',
    accent2: '#3d7fc4',
    accentInk: '#06131d',
    radius: '8px',
  },

  source: {
    pdf: 'Frosthaven - Regles.pdf',
    assetId: 'frosthaven',
    pageOffset: 0,
    credit: 'Règles officielles EN — Cephalofair Games (trois PDF fusionnés)',
  },

  cover: { page: 1, x: 0.05, y: 0.235, w: 0.9, h: 0.232 },

  scope: {
    covered: [
      'La création d’un personnage de départ, des six classes ouvertes',
      'La mise en place d’un scénario, dans les 18 étapes du livret',
      'La manche : choix des cartes, initiative, tours, fin de manche',
      'Le tour d’un personnage : deux actions, cartes actives, défaussées et perdues, éléments, repos',
      'Se déplacer et attaquer : portée, ligne de vue, modificateurs, avantage, bouclier, conditions',
      'Le tour des monstres : focus, mouvement, attaque, mort et butin',
      'Les tuiles de carte et les overlays : portes, pièges, terrains, obstacles, trésors',
      'La fin d’un scénario, réussi ou perdu, et la phase d’avant-poste qui suit',
      'La reprise d’une campagne à partir des fiches et du paquet de bâtiments',
    ],
    skipped: [
      'Le contenu sous autocollants scellés : étapes 10, 13 et 14 de la mise en place, et les suivants',
      'Les nouvelles classes et les enveloppes de bâtiment, débloquées par la campagne',
      'Les améliorations de cartes (bâtiment 44), les faveurs (bâtiment 81) et le puzzle book',
      'Les donjons aléatoires, la mort permanente, la respécialisation et les autres variantes',
      'Le détail des six classes : traits, cartes et invocations',
    ],
  },

  /* ------------------------------------------------------------ matériel */

  components: [
    {
      id: 'boite-perso',
      name: 'Grande boîte de personnage (character tuck box)',
      qty: '17 boîtes, 6 ouvertes',
      note: 'Une par classe. Elle contient tout ce qu’il faut pour jouer la classe : fiches, tapis, cartes, pions, jetons.',
      glyph: 'card',
      tint: '#8fd3f4',
      crop: { page: 4, x: 0.5, y: 0.3, w: 0.42, h: 0.63 },
    },
    {
      id: 'petite-boite',
      name: 'Petite boîte : figurine',
      qty: '18 boîtes',
      note: 'La figurine plastique de la classe. Le Geminate en a deux.',
      glyph: 'figure',
      crop: { page: 4, x: 0.5, y: 0.13, w: 0.42, h: 0.15 },
    },
    {
      id: 'feuille-perso',
      name: 'Feuille de personnage (character sheet)',
      qty: '17 blocs',
      note: 'Nom, niveau, XP, or, ressources, coches, perks. C’est elle qui porte le personnage d’une séance à l’autre.',
      glyph: 'card',
      crop: { page: 53, x: 0.52, y: 0.12, w: 0.45, h: 0.4 },
    },
    {
      id: 'tapis',
      name: 'Tapis de personnage (character mat)',
      qty: '17 tapis',
      note: 'Taille de main, traits, points de vie par niveau. Les dés de dégâts et les conditions se posent dessus.',
      glyph: 'board',
      crop: { page: 4, x: 0.57, y: 0.52, w: 0.28, h: 0.15 },
    },
    {
      id: 'standees',
      name: 'Pions de personnage et d’invocation (standees)',
      qty: '18 + 45 pions',
      note: 'Le pion du personnage va sur la carte à la place de la figurine si on préfère. Les invocations n’ont que des pions.',
      glyph: 'meeple',
      crop: { page: 4, x: 0.53, y: 0.71, w: 0.34, h: 0.14 },
    },
    {
      id: 'jetons-perso',
      name: 'Jetons de personnage et jeton d’initiative',
      qty: '85 + 17 jetons',
      note: 'Les jetons de personnage suivent les cases d’usage (use slots) des cartes et des objets. Le jeton d’initiative marque l’ordre du tour.',
      glyph: 'token',
      crop: { page: 4, x: 0.53, y: 0.87, w: 0.36, h: 0.05 },
    },
    {
      id: 'cartes-capacite',
      name: 'Cartes de capacité (ability cards)',
      qty: '503 cartes',
      note: 'Le niveau est en haut à gauche. Une action en haut, une action en bas.',
      glyph: 'card',
      tint: '#8fd3f4',
      crop: { page: 5, x: 0.6, y: 0.14, w: 0.28, h: 0.24 },
    },
    {
      id: 'modificateurs',
      name: 'Cartes de modificateur d’attaque',
      qty: '165 + 303 cartes',
      note: 'Six paquets standard de 20 cartes (1 à 4, A pour les alliés, M pour les monstres), plus les cartes avancées de chaque classe.',
      glyph: 'card',
      crop: { page: 5, x: 0.55, y: 0.57, w: 0.36, h: 0.09 },
    },
    {
      id: 'quetes',
      name: 'Cartes de quête personnelle (personal quest)',
      qty: '10 cartes',
      note: 'L’objectif à long terme du personnage. Accompli, il déclenche sa retraite.',
      glyph: 'card',
      crop: { page: 64, x: 0.5, y: 0.11, w: 0.42, h: 0.24 },
    },
    {
      id: 'cadran',
      name: 'Cadran de personnage (character dial)',
      qty: '4 cadrans',
      note: 'Points de vie en rouge, expérience en bleu.',
      glyph: 'marker',
      tint: '#e04b3a',
      crop: { page: 5, x: 0.55, y: 0.83, w: 0.38, h: 0.09 },
    },
    {
      id: 'objets',
      name: 'Cartes d’objet (item cards)',
      qty: '379 cartes',
      note: 'Numérotées au dos. Au départ, seuls les objets 120 à 128 sont achetables.',
      glyph: 'card',
      crop: { page: 35, x: 0.52, y: 0.11, w: 0.44, h: 0.29 },
    },
    {
      id: 'tuiles-carte',
      name: 'Tuiles de carte (map tiles)',
      qty: '38 tuiles',
      note: 'Des hexagones vides bordés de murs. Le livre de scénarios dit lesquelles poser et comment.',
      glyph: 'tile',
      crop: { page: 72, x: 0.04, y: 0.45, w: 0.31, h: 0.22 },
    },
    {
      id: 'overlays',
      name: 'Tuiles overlay (overlay tiles)',
      qty: '225 tuiles',
      note: 'Portes, pièges, obstacles, terrains, trésors. Leur type est donné par la couleur de bordure dans le livre de scénarios.',
      glyph: 'tile',
      crop: { page: 13, x: 0.1, y: 0.65, w: 0.84, h: 0.27 },
    },
    {
      id: 'monstres',
      name: 'Pions de monstre et socles',
      qty: '327 pions, 30+ socles',
      note: 'Socle gris pour un monstre normal, jaune pour une élite, rouge pour un boss ou un monstre nommé. Le numéro est sur le socle.',
      glyph: 'meeple',
      tint: '#e0b13a',
      crop: { page: 39, x: 0.54, y: 0.12, w: 0.42, h: 0.43 },
    },
    {
      id: 'stats-monstre',
      name: 'Cartes de stats et pochettes',
      qty: '48 + 32 cartes, 6 pochettes',
      note: 'Recto-verso, glissée dans une pochette qui ne montre que le niveau du scénario. Les dégâts et conditions se posent sur la pochette.',
      glyph: 'card',
      crop: { page: 39, x: 0.53, y: 0.58, w: 0.44, h: 0.38 },
    },
    {
      id: 'capacites-monstre',
      name: 'Cartes de capacité de monstre',
      qty: '344 cartes',
      note: 'Huit par groupe (set). Une est tirée par manche pour chaque groupe présent sur la carte.',
      glyph: 'card',
      crop: { page: 40, x: 0.5, y: 0.1, w: 0.42, h: 0.26 },
    },
    {
      id: 'elements',
      name: 'Plateau d’éléments, jetons et marqueur de manche',
      qty: '1 plateau, 6 jetons, 1 marqueur',
      note: 'Feu, glace, air, terre, lumière, ténèbres : fort, faiblissant ou inerte. La piste des manches est en haut du plateau.',
      glyph: 'board',
      tint: '#8fd3f4',
      crop: { page: 23, x: 0.54, y: 0.17, w: 0.42, h: 0.3 },
    },
    {
      id: 'butin',
      name: 'Cartes et jetons de butin (loot)',
      qty: '59 cartes, 20+ jetons',
      note: 'Un paquet de butin propre à chaque scénario. Un jeton de butin apparaît là où un monstre meurt.',
      glyph: 'token',
      tint: '#e0b13a',
      crop: { page: 16, x: 0.05, y: 0.21, w: 0.43, h: 0.33 },
    },
    {
      id: 'battle-goals',
      name: 'Cartes d’objectif de combat (battle goals)',
      qty: '60 cartes',
      note: 'Un objectif secret par personnage et par scénario. Réussi, il rapporte des coches.',
      glyph: 'card',
      crop: { page: 17, x: 0.53, y: 0.28, w: 0.2, h: 0.22 },
    },
    {
      id: 'jetons',
      name: 'Jetons de dégâts, de conditions et d’aide de scénario',
      qty: '60+ dégâts, 100+ conditions, 25 aides',
      note: 'Ils se rangent dans le plateau de jetons, à portée de tous.',
      glyph: 'token',
      crop: { page: 73, x: 0.26, y: 0.86, w: 0.4, h: 0.07 },
    },
    {
      id: 'livres',
      name: 'Livre de scénarios et livre de sections',
      qty: '1 + 1',
      note: '138 scénarios. Le livre de sections se lit quand une icône de livre l’indique : page, puis numéro de section.',
      glyph: 'card',
      crop: { page: 72, x: 0.36, y: 0.14, w: 0.56, h: 0.18 },
    },
    {
      id: 'plateau-carte',
      name: 'Plateau-carte, flowcharts et autocollants',
      qty: '1 plateau, 5 flowcharts, 6 planches',
      note: 'La carte de la campagne. Un scénario débloqué y reçoit son autocollant, un bâtiment construit le sien.',
      glyph: 'board',
      crop: { page: 72, x: 0.05, y: 0.14, w: 0.3, h: 0.3 },
    },
    {
      id: 'feuille-campagne',
      name: 'Feuille de campagne (campaign sheet)',
      qty: '1 bloc',
      note: 'Calendrier, réserve de Frosthaven, inspiration, défense, soldats, morale, prospérité, retraités.',
      glyph: 'card',
      crop: { page: 72, x: 0.74, y: 0.32, w: 0.18, h: 0.18 },
    },
    {
      id: 'batiments',
      name: 'Cartes de bâtiment (building cards)',
      qty: '29 cartes',
      note: 'Une par bâtiment et par niveau, face normale et face détruite. Le paquet reste trié par numéro.',
      glyph: 'card',
      crop: { page: 52, x: 0.5, y: 0.12, w: 0.33, h: 0.3 },
    },
    {
      id: 'evenements',
      name: 'Cartes d’événement et paquet de garde',
      qty: '247 événements, 55 town guard',
      note: 'Événements de route et d’avant-poste, en deux saisons chacun. Le paquet de garde sert aux jets de défense.',
      glyph: 'card',
      crop: { page: 12, x: 0.5, y: 0.11, w: 0.42, h: 0.24 },
    },
  ],

  /* ------------------------------------------------------------ chapitres */

  chapters: [
    {
      id: 'brief',
      title: 'Avant de commencer',
      kind: 'brief',
      goal: 'Savoir ce que ce tutoriel installe, et ce qu’il laisse au livret.',
      steps: [
        {
          id: 'b1',
          kind: 'info',
          title: 'Posez la tablette à côté du livre de scénarios',
          body: [
            'Ce tutoriel crée les personnages, installe le premier scénario et déroule les règles d’une manche, jusqu’à la fin du scénario.',
            'Le livret de règles est en anglais. Les termes imprimés sur le matériel sont gardés tels quels : Move, Attack, Shield, long rest…',
          ],
          warn: 'Une partie du livret est sous autocollants scellés. Ces étapes ne sont pas décrites ici : quand une étape le dit, suivez votre livret.',
        },
        {
          id: 'b2',
          kind: 'info',
          title: 'Le but : garder l’avant-poste de Frosthaven',
          body: [
            'Vous formez une compagnie de mercenaires. Vous jouez des scénarios, et chaque scénario a un objectif.',
            'Entre deux scénarios, vous revenez à Frosthaven pour la phase d’avant-poste (Outpost Phase) : construire, monter de niveau, acheter.',
          ],
          ref: 'Getting Started — p.3',
        },
        {
          id: 'b3',
          kind: 'info',
          title: 'Deux à quatre joueurs, un personnage chacun',
          body: [
            'Six classes sont ouvertes au départ. Les onze autres boîtes sont scellées : la campagne dit quand les ouvrir.',
            'Banner Spear et Drifter sont de complexité faible ; Boneshaper et Deathwalker, moyenne ; Blinkblade et Geminate, élevée.',
          ],
          components: ['boite-perso'],
          crop: { page: 3, x: 0.08, y: 0.36, w: 0.87, h: 0.57 },
          ref: 'Getting Started — p.3',
        },
        {
          id: 'b4',
          kind: 'info',
          title: 'En solo : au moins deux personnages',
          only: [1],
          body: [
            'Un seul joueur contrôle deux personnages ou plus, et joue leurs tours normalement.',
            'Le niveau de scénario se calcule alors sur (niveau moyen + 1) ÷ 2, arrondi au supérieur.',
          ],
          ref: 'Solo Variant — p.69',
        },
        {
          id: 'b5',
          kind: 'info',
          title: 'Premier scénario : le 0 ou le 1',
          body: [
            'Nouveau dans le système Gloomhaven : lisez tout le livret et commencez par le scénario 0, court et à faible enjeu.',
            'Sinon, commencez directement par le scénario 1.',
            'Pour apprendre, on ignore les événements de route (aucun aux scénarios 0 et 1) et on joue au niveau de scénario 1.',
          ],
          warn: 'Il n’y a pas de phase d’avant-poste entre le scénario 0 et le scénario 1. Après le 1, lisez la suite du livret, page 49.',
          ref: 'The Adventure Begins — p.49',
        },
        {
          id: 'b6',
          kind: 'check',
          title: 'Ce que vous saurez faire',
          body: [
            'Créer un personnage de départ et l’équiper.',
            'Installer un scénario dans les 18 étapes du livret.',
            'Jouer une manche : choisir vos cartes, résoudre les tours, les monstres, la fin de manche.',
            'Clore le scénario et savoir ce qui se passe au retour à Frosthaven.',
          ],
        },
      ],
    },

    {
      id: 'materiel',
      title: 'Le matériel',
      kind: 'setup',
      goal: 'Reconnaître ce qui sert au scénario, ce qui sert à la campagne, et ce qui reste scellé.',
      steps: [
        {
          id: 'm1',
          kind: 'take',
          title: 'La grande boîte : livres, tuiles, plateau',
          body: [
            'Un livre de scénarios, un livre de sections, un guide de mise en place, une table d’alchimie.',
            '38 tuiles de carte, 225 tuiles overlay, 327 pions de monstre, le plateau d’éléments avec ses six jetons et le marqueur de manche.',
            'Le plateau-carte, cinq flowcharts, six planches d’autocollants, un bloc de feuilles de campagne.',
          ],
          warn: 'Le puzzle book et les 17 enveloppes sont scellés. Ne les ouvrez que quand la campagne le demande.',
          components: ['livres', 'tuiles-carte', 'overlays', 'elements', 'plateau-carte', 'feuille-campagne'],
          crop: { page: 72, x: 0.04, y: 0.13, w: 0.92, h: 0.82 },
          ref: 'Appendix A: Component Inventory — p.72',
        },
        {
          id: 'm2',
          kind: 'take',
          title: 'Les boîtes de personnage',
          body: [
            '17 grandes boîtes : les six classes de départ sont ouvertes, les onze autres scellées.',
            '18 petites boîtes : les figurines. Une par classe, deux pour le Geminate.',
          ],
          components: ['boite-perso', 'petite-boite'],
          crop: { page: 73, x: 0.09, y: 0.08, w: 0.86, h: 0.31 },
          ref: 'Appendix A: Component Inventory — p.73',
        },
        {
          id: 'm3',
          kind: 'take',
          title: 'Les paquets de cartes communs',
          body: [
            '29 cartes de bâtiment, 10 quêtes personnelles, 247 événements, 379 objets, 60 battle goals, 59 cartes de butin.',
            '344 cartes de capacité de monstre, 48 cartes de stats de monstre, 32 de boss, 165 cartes de modificateur, 55 cartes de garde (town guard).',
            'Les 24 cartes de salle et de mise en place aléatoires servent aux donjons aléatoires, plus tard.',
          ],
          components: ['batiments', 'quetes', 'evenements', 'objets', 'battle-goals', 'butin', 'capacites-monstre', 'stats-monstre', 'modificateurs'],
          crop: { page: 73, x: 0.1, y: 0.4, w: 0.84, h: 0.34 },
          ref: 'Appendix A: Component Inventory — p.73',
        },
        {
          id: 'm4',
          kind: 'take',
          title: 'Jetons, cadrans, socles',
          body: [
            'Jetons de dégâts, de butin, de conditions ; 49 jetons d’initiative de monstre ; 25 jetons d’aide de scénario.',
            'Quatre cadrans de personnage, six pochettes de stats, les socles en plastique, et le plateau de jetons.',
          ],
          components: ['jetons', 'cadran', 'monstres'],
          crop: { page: 73, x: 0.1, y: 0.73, w: 0.84, h: 0.21 },
          ref: 'Appendix A: Component Inventory — p.73',
        },
      ],
    },

    {
      id: 'perso',
      title: 'Créer un personnage',
      kind: 'setup',
      goal: 'Chaque joueur a un personnage de niveau 1, ses cartes, son paquet de modificateurs et ses objets.',
      steps: [
        {
          id: 'c1',
          kind: 'take',
          title: 'Choisissez une classe et ouvrez ses deux boîtes',
          body: [
            'La petite boîte contient la figurine.',
            'La grande boîte contient le reste : fiches, tapis, pions, jetons, cartes.',
          ],
          components: ['boite-perso', 'petite-boite'],
          crop: { page: 4, x: 0.5, y: 0.13, w: 0.42, h: 0.8 },
          ref: 'Creating a Character — p.4',
        },
        {
          id: 'c2',
          kind: 'take',
          title: 'Feuille de personnage : nom, niveau 1, 30 d’or',
          body: [
            'Détachez une feuille du bloc (A). Écrivez un nom, le niveau 1, et 30 d’or.',
            'Posez le tapis (B) devant vous : taille de main, traits, points de vie par niveau.',
          ],
          components: ['feuille-perso', 'tapis'],
          crop: { page: 4, x: 0.55, y: 0.35, w: 0.32, h: 0.32 },
          ref: 'Creating a Character — p.4',
        },
        {
          id: 'c3',
          kind: 'take',
          title: 'Pion, invocations, jetons, jeton d’initiative',
          body: [
            'Le pion de personnage (C) et les pions d’invocation (D) : ils vont sur la carte.',
            'Les jetons de personnage (E) : ils suivront les cases d’usage. Le jeton d’ordre d’initiative (F) : il marque votre place dans le tour.',
          ],
          components: ['standees', 'jetons-perso'],
          crop: { page: 4, x: 0.53, y: 0.71, w: 0.36, h: 0.21 },
          ref: 'Creating a Character — p.4',
        },
        {
          id: 'c4',
          kind: 'take',
          title: 'Cartes de capacité : le niveau 1 seulement',
          body: [
            'Le niveau est imprimé en haut à gauche de chaque carte (G).',
            'Pour une première partie, prenez uniquement les cartes de niveau 1 : autant que la taille de main indiquée sur le tapis.',
            'Les cartes de niveau X sont facultatives : une carte X remplace une carte de niveau 1, une pour une.',
          ],
          warn: 'Laissez dans la boîte les cartes de modificateur avancées et les cartes de rappel de perk (H). Elles ne servent pas encore.',
          components: ['cartes-capacite'],
          crop: { page: 5, x: 0.55, y: 0.14, w: 0.36, h: 0.36 },
          ref: 'Creating a Character — p.5',
        },
        {
          id: 'c5',
          kind: 'shuffle',
          title: 'Prenez un paquet de modificateurs standard',
          body: [
            'Dans l’insert, six paquets de 20 cartes : 1, 2, 3, 4, A (alliés) et M (monstres). Chaque joueur prend l’un des paquets 1 à 4.',
            'Composition : six +0, cinq −1, cinq +1, un −2, un +2, un null, un 2x.',
          ],
          components: ['modificateurs'],
          crop: { page: 5, x: 0.55, y: 0.57, w: 0.36, h: 0.09 },
          ref: 'Creating a Character — p.5',
        },
        {
          id: 'c6',
          kind: 'take',
          title: 'Quête personnelle : piochez 2, gardez 1',
          body: [
            'Remélangez l’autre dans le paquet.',
            'Secrète ou publique : le groupe en décide pour toute la campagne.',
          ],
          components: ['quetes'],
          crop: { page: 5, x: 0.55, y: 0.68, w: 0.36, h: 0.12 },
          ref: 'Creating a Character — p.5',
        },
        {
          id: 'c7',
          kind: 'take',
          title: 'Prenez un cadran de personnage',
          body: ['Le cadran rouge suivra vos points de vie, le bleu votre expérience.'],
          components: ['cadran'],
          crop: { page: 5, x: 0.55, y: 0.83, w: 0.38, h: 0.09 },
          ref: 'Creating a Character — p.5',
        },
        {
          id: 'c8',
          kind: 'take',
          title: 'Dépensez vos 30 d’or en objets',
          body: [
            'Les objets achetables au départ sont les numéros 120 à 128. Le prix est sur la carte.',
            'Suggestions du livret : Banner Spear 124 et 128 ; Drifter 120 et 124 ; Boneshaper 122 ; Deathwalker 125 ; Blinkblade 123 et 127 ; Geminate 120 et 123.',
          ],
          warn: 'L’or non dépensé est perdu. Si vous possédez Gloomhaven, ajoutez d’abord les objets 10, 25, 72, 105, 109 et 116 à la réserve achetable.',
          components: ['objets'],
          crop: { page: 6, x: 0.5, y: 0.09, w: 0.42, h: 0.32 },
          ref: 'Creating a Character — p.6',
        },
        {
          id: 'c9',
          kind: 'check',
          title: 'Personnage prêt',
          body: [
            'Fiche remplie, tapis, figurine, cartes de niveau 1, paquet de modificateurs, quête personnelle, cadran, objets.',
            'En cas d’ambiguïté sur une règle, le livret le dit : le groupe décide.',
          ],
          ref: 'Learning the Rules — p.6',
        },
      ],
    },

    {
      id: 'setup',
      title: 'Mise en place d’un scénario',
      kind: 'setup',
      modes: ['tuto', 'setup'],
      goal: 'La carte, les monstres, les paquets et les personnages sont en place, dans l’ordre des 18 étapes du livret.',
      steps: [
        {
          id: 's0',
          kind: 'info',
          title: 'L’aventure commence',
          modes: ['tuto'],
          body: [
            'Lisez le texte au début du livre de scénarios. Il débloque les scénarios 0 et 1.',
            'Détachez leurs autocollants de la fenêtre du flowchart et collez-les sur le plateau-carte, à la position indiquée.',
          ],
          components: ['plateau-carte', 'livres'],
          crop: { page: 51, x: 0.54, y: 0.12, w: 0.42, h: 0.43 },
          ref: 'The Adventure Begins — p.49 ; Scenario Flowcharts — p.51',
        },
        {
          id: 's1',
          kind: 'take',
          title: '1. Choisissez le scénario',
          body: [
            'Un scénario débloqué dont les prérequis sont remplis. Ouvrez le livre de scénarios à sa page, le livre de sections à côté.',
            'Un scénario déjà réussi peut être rejoué.',
          ],
          components: ['livres'],
          crop: { page: 7, x: 0.55, y: 0.13, w: 0.37, h: 0.33 },
          ref: 'Beginning a Scenario — p.8',
        },
        {
          id: 's2',
          kind: 'take',
          title: '2. Résolvez un événement de route, s’il y a lieu',
          body: [
            'Piochez dans le paquet d’événements de route (road event) de la saison en cours, été ou hiver, selon le calendrier de campagne.',
            'Lisez le recto ; le groupe choisit une option ; lisez le résultat au verso et appliquez-le aux personnages présents ; retirez la carte du jeu, sauf icône de retour.',
          ],
          warn: 'Aucun événement de route aux scénarios 0 et 1, ni en rejouant un scénario perdu sans revenir à Frosthaven, ni en enchaînant un scénario lié.',
          components: ['evenements'],
          crop: { page: 12, x: 0.5, y: 0.11, w: 0.42, h: 0.24 },
          ref: 'Road Events — p.12',
        },
        {
          id: 's3',
          kind: 'info',
          title: 'Lire l’entrée du scénario',
          modes: ['tuto'],
          body: [
            'A nom et numéro ; B coordonnées sur la carte ; C prérequis ; D complexité ; E lieu ; G objectif ; H introduction ; I règles spéciales ; J effets de scénario.',
            'K liens de section : à lire dès que leur condition est remplie. L plan de la carte. M composition du paquet de butin. N clé du scénario : monstres et overlays.',
          ],
          warn: 'Le plan (L) montre toutes les tuiles, mais ne regardez pas la mise en place des salles suivantes.',
          components: ['livres'],
          crop: { page: 10, x: 0.5, y: 0.13, w: 0.5, h: 0.5 },
          ref: 'Scenario Entries — p.10',
        },
        {
          id: 's4',
          kind: 'place',
          title: '3. Posez toutes les tuiles de carte',
          body: ['Selon le plan de la carte (L) de l’entrée du scénario.'],
          components: ['tuiles-carte'],
          crop: { page: 9, x: 0.03, y: 0.33, w: 0.95, h: 0.36 },
          ref: 'Beginning a Scenario — p.8',
        },
        {
          id: 's5',
          kind: 'take',
          title: '4. Sortez le matériel des monstres',
          body: [
            'La clé du scénario (N) liste les monstres. Pour chacun : le paquet de capacités, la carte de stats, les pions, le jeton d’initiative.',
            'Mélangez chaque paquet de capacités. Glissez chaque carte de stats dans une pochette pour ne montrer que le niveau du scénario.',
          ],
          components: ['capacites-monstre', 'stats-monstre', 'monstres'],
          crop: { page: 9, x: 0.05, y: 0.2, w: 0.65, h: 0.16 },
          ref: 'Beginning a Scenario — p.8',
        },
        {
          id: 's6',
          kind: 'take',
          title: '5. Sortez les tuiles overlay',
          body: ['Celles listées dans la clé du scénario (N), pour tout le scénario.'],
          components: ['overlays'],
          ref: 'Beginning a Scenario — p.8',
        },
        {
          id: 's7',
          kind: 'place',
          title: '6. Installez la première salle',
          body: [
            'La carte principale de l’entrée montre la première salle : A hexagones de départ, B overlays, C jetons de butin, D emplacements de monstres, E hexagones notables.',
            'Un pion de monstre par hexagone indiqué. Blanc : monstre normal, socle gris. Jaune : élite, socle jaune. Noir : aucun.',
            'Les numéros des pions sont tirés au hasard. Une icône verte sur un hexagone notable : posez-y un jeton d’aide de scénario.',
          ],
          warn: 'Sur chaque emplacement, trois barres : haut à deux personnages, milieu à trois, bas à quatre.',
          components: ['monstres', 'overlays', 'butin', 'jetons'],
          crop: { page: 11, x: 0.13, y: 0.34, w: 0.4, h: 0.31 },
          ref: 'Scenario Entries — p.11',
        },
        {
          id: 's8',
          kind: 'shuffle',
          title: '7. Mélangez les paquets de modificateurs',
          body: [
            'Le paquet de chaque personnage, le paquet M des monstres, et le paquet A si le scénario a des alliés.',
            'Ajoutez les cartes que le scénario demande : bénédictions, malédictions…',
          ],
          components: ['modificateurs'],
          ref: 'Beginning a Scenario — p.8',
        },
        {
          id: 's9',
          kind: 'info',
          title: '8. Lisez l’objectif, l’introduction et les règles spéciales',
          body: [
            'L’objectif (G) : quand il est atteint, on lit la section indiquée à la fin de la manche.',
            'Les règles spéciales (I) expliquent les hexagones notables de la salle.',
          ],
          components: ['livres'],
          ref: 'Beginning a Scenario — p.8',
        },
        {
          id: 's10',
          kind: 'take',
          title: '9. Battle goals : trois par personnage, un gardé',
          body: [
            'Chacun pioche trois cartes en secret, en garde une et défausse les autres face cachée.',
            'L’objectif reste secret jusqu’à la fin du scénario.',
          ],
          components: ['battle-goals'],
          crop: { page: 17, x: 0.53, y: 0.28, w: 0.2, h: 0.22 },
          ref: 'Battle Goals — p.17',
        },
        {
          id: 's11',
          kind: 'info',
          title: '10. Étape sous autocollant',
          body: [
            'L’étape 10 est sous l’autocollant 1 du livret. Son contenu n’est pas repris ici.',
            'Si l’autocollant est décollé, faites ce qu’il dit. Sinon, passez à l’étape 11.',
          ],
          ref: 'Beginning a Scenario — p.8',
        },
        {
          id: 's12',
          kind: 'place',
          title: '11. Le plateau de jetons à portée de main',
          body: ['Dégâts, conditions, butin, aides de scénario : à portée de tous.'],
          components: ['jetons'],
          ref: 'Beginning a Scenario — p.8',
        },
        {
          id: 's13',
          kind: 'shuffle',
          title: '12. Construisez le paquet de butin',
          body: [
            'La table de butin (M) de l’entrée donne le nombre de cartes de chaque type : Money, Material, Herb, Random Item.',
            'Tirez ce nombre au hasard dans le paquet de chaque type, puis mélangez le tout en un seul paquet.',
          ],
          components: ['butin'],
          crop: { page: 16, x: 0.05, y: 0.21, w: 0.43, h: 0.33 },
          ref: 'Loot Deck — p.16',
        },
        {
          id: 's14',
          kind: 'info',
          title: '13 et 14. Étapes sous autocollants',
          body: [
            'Les étapes 13 et 14 sont sous les autocollants 2 et 3 du livret. Leur contenu n’est pas repris ici.',
            'Si les autocollants sont décollés, faites ce qu’ils disent. Sinon, passez à l’étape 15.',
          ],
          ref: 'Beginning a Scenario — p.8',
        },
        {
          id: 's15',
          kind: 'take',
          title: '15. Choisissez les objets de chaque personnage',
          body: [
            'Par scénario : 1 tête, 1 corps, 1 pieds, 2 objets à une main ou 1 à deux mains, et des petits objets à hauteur de la moitié du niveau, arrondi au supérieur.',
            'Ajoutez au paquet de modificateurs les cartes −1 des objets qui en portent (F). Appliquez les effets de début de scénario.',
          ],
          warn: 'Les objets se posent sous le tapis. On peut en posséder plus qu’on n’en porte, mais un seul exemplaire de chaque, et jamais d’échange entre personnages.',
          components: ['objets'],
          crop: { page: 35, x: 0.52, y: 0.11, w: 0.44, h: 0.29 },
          ref: 'Items — p.35',
        },
        {
          id: 's16',
          kind: 'take',
          title: '16. Prenez vos cartes de capacité en main',
          body: [
            'Autant de cartes que la taille de main, sous le portrait sur le tapis.',
            'Elles commencent toutes en main.',
          ],
          components: ['cartes-capacite', 'tapis'],
          ref: 'Beginning a Scenario — p.8',
        },
        {
          id: 's17',
          kind: 'place',
          title: '17. Réglez les cadrans',
          body: [
            'Cadran rouge : les points de vie maximum de votre niveau, dans le tableau au bas du tapis.',
            'Cadran bleu : 0.',
          ],
          components: ['cadran'],
          ref: 'Beginning a Scenario — p.8',
        },
        {
          id: 's18',
          kind: 'check',
          title: '18. Appliquez les effets en attente',
          body: [
            'Les effets de l’événement de route, s’il y en a eu un.',
            'Les effets de scénario (J) de l’entrée.',
          ],
          crop: { page: 9, x: 0.04, y: 0.09, w: 0.94, h: 0.88 },
          ref: 'Beginning a Scenario — p.8',
        },
      ],
    },

    {
      id: 'manche',
      title: 'Une manche',
      kind: 'play',
      goal: 'Savoir ce qui se passe du choix des cartes à la fin de la manche.',
      steps: [
        {
          id: 'r1',
          kind: 'info',
          title: 'Quatre étapes',
          body: [
            '1. Choix des cartes (Card Selection). 2. Ordre d’initiative. 3. Tours des personnages et des monstres. 4. Fin de manche.',
            'Avant tout, les effets de début de manche : les apparitions de monstres (spawns) ont lieu en même temps.',
          ],
          crop: { page: 18, x: 0.05, y: 0.19, w: 0.42, h: 0.11 },
          ref: 'Playing a Scenario — p.18',
        },
        {
          id: 'r2',
          kind: 'action',
          title: 'Choisissez deux cartes de votre main, face cachée',
          body: [
            'L’une des deux est votre carte d’initiative : sa valeur, au centre de la carte, fixe votre place dans la manche.',
            'Chaque personnage choisit en même temps.',
          ],
          warn: 'On ne montre pas ses cartes, on ne donne ni valeur ni titre. On peut parler stratégie en termes généraux.',
          components: ['cartes-capacite'],
          crop: { page: 18, x: 0.12, y: 0.61, w: 0.34, h: 0.23 },
          ref: 'Card Selection — p.18',
        },
        {
          id: 'r3',
          kind: 'info',
          title: 'Ou déclarez un repos long',
          body: [
            'Avec au moins deux cartes dans votre défausse, vous pouvez déclarer un repos long (long rest) au lieu de choisir deux cartes.',
            'Votre initiative est 99. Vous ne jouez aucune carte ce tour.',
          ],
          ref: 'Card Selection — p.18 ; Resting — p.38',
        },
        {
          id: 'r4',
          kind: 'action',
          title: 'Révélez, puis ordonnez l’initiative',
          body: [
            'Chacun révèle ses deux cartes, la carte d’initiative par-dessus.',
            'Tirez une carte de capacité pour chaque groupe de monstres présent sur la carte.',
            'Alignez les jetons d’initiative du plus petit au plus grand.',
          ],
          warn: 'Égalité entre personnages : comparez la deuxième carte, sinon le groupe décide. Égalité personnage-monstre : le personnage agit d’abord.',
          components: ['jetons-perso', 'capacites-monstre'],
          crop: { page: 19, x: 0.1, y: 0.54, w: 0.4, h: 0.38 },
          ref: 'Ordering of Initiative — p.19',
        },
        {
          id: 'r5',
          kind: 'info',
          title: 'Chaque figure joue un tour',
          body: [
            'Un personnage joue deux actions : le haut d’une carte et le bas de l’autre.',
            'Un monstre joue une action : toute sa carte de capacité. Les élites d’un type d’abord, par numéro croissant, puis les normaux.',
            'Une invocation joue juste avant son invocateur.',
          ],
          ref: 'Turns — p.20',
        },
        {
          id: 'r6',
          kind: 'check',
          title: 'Fin de manche',
          body: [
            '1. Effets de fin de manche : scénario, objets, cartes.',
            '2. Si une carte à icône de mélange a été tirée, remélangez la défausse dans son paquet.',
            '3. Les cartes actives à bonus de manche vont en défausse ou en perte.',
            '4. Repos court possible, avec au moins deux cartes en défausse.',
            '5. Les éléments reculent d’une colonne. Avancez le marqueur de manche.',
          ],
          components: ['elements'],
          crop: { page: 46, x: 0.05, y: 0.13, w: 0.9, h: 0.19 },
          ref: 'End of Round — p.46',
        },
      ],
    },

    {
      id: 'tour',
      title: 'Le tour d’un personnage',
      kind: 'play',
      goal: 'Jouer ses deux actions, ranger ses cartes, gérer les éléments, l’XP, le butin et les repos.',
      steps: [
        {
          id: 't1',
          kind: 'action',
          title: 'Le haut d’une carte, le bas de l’autre',
          body: [
            'Jamais deux hauts ni deux bas. L’ordre est libre. La carte d’initiative n’a plus d’importance.',
            'Toute carte peut servir d’action de base : Attack 2 en haut, Move 2 en bas. Elle est alors défaussée sans rien d’autre.',
          ],
          components: ['cartes-capacite'],
          crop: { page: 34, x: 0.5, y: 0.67, w: 0.42, h: 0.29 },
          ref: 'Character Turn — p.34',
        },
        {
          id: 't2',
          kind: 'info',
          title: 'Lire une carte de capacité',
          body: [
            'A nom. B initiative. C niveau (X vaut niveau 1). D action du haut et action du bas, capacités de haut en bas.',
            'Les icônes de l’action disent où va la carte ensuite : zone active, défausse, ou perte. F marques d’amélioration, pour plus tard.',
          ],
          components: ['cartes-capacite'],
          crop: { page: 34, x: 0.52, y: 0.38, w: 0.33, h: 0.28 },
          ref: 'Ability Cards — p.34',
        },
        {
          id: 't3',
          kind: 'info',
          title: 'Résoudre les capacités',
          body: [
            'Les capacités d’une action sont séparées par des lignes et se résolvent dans l’ordre. On ne commence pas une capacité pendant qu’une autre se résout.',
            'Les capacités d’un personnage sont facultatives, sauf celles marquées « ! » : capacité négative, infusion, XP, icône de perte, icône active.',
            'On peut ne pas faire l’action du tout : la carte est défaussée sans effet.',
          ],
          ref: 'Abilities — p.20 ; Mandatory Triggers — p.37',
        },
        {
          id: 't4',
          kind: 'place',
          title: 'Ranger ses cartes',
          body: [
            'Défausse à gauche du tapis, cartes perdues à droite, cartes actives au-dessus. La main reste à part.',
            'Une carte à icône de perte va en perte dès qu’une partie de l’action est faite. Son bonus actif s’applique d’abord.',
          ],
          warn: 'Une icône de perte définitive : tournez la carte à 180°. Elle ne revient plus de tout le scénario.',
          crop: { page: 34, x: 0.48, y: 0.11, w: 0.46, h: 0.25 },
          ref: 'Character Turn — p.34 ; Lost Actions — p.38',
        },
        {
          id: 't5',
          kind: 'info',
          title: 'L’expérience',
          body: [
            'L’icône XP en bas à droite d’une action : si une partie de l’action est faite, avancez le cadran bleu.',
            'Certaines XP sont conditionnelles : consommer un élément, passer une case d’usage.',
          ],
          warn: 'Tuer un monstre ne rapporte aucune XP en soi.',
          components: ['cadran'],
          ref: 'Experience — p.37',
        },
        {
          id: 't6',
          kind: 'action',
          title: 'Fin de tour : pillez votre hexagone',
          body: [
            'À la fin de son tour, un personnage doit ramasser le jeton de butin ou le trésor de l’hexagone où il se trouve.',
            'Un jeton : retirez-le, piochez une carte du paquet de butin. Or et ressources ne comptent qu’à la fin du scénario ; un objet aléatoire est utilisable tout de suite.',
          ],
          warn: 'Seuls les personnages pillent. Une capacité Loot X ramasse tous les jetons et trésors à portée X, hexagone courant compris.',
          components: ['butin'],
          ref: 'End-of-Turn Looting — p.37 ; Loot — p.32',
        },
        {
          id: 't7',
          kind: 'info',
          title: 'Les éléments',
          body: [
            'Six éléments : feu, glace, air, terre, lumière, ténèbres. Chaque jeton est fort (strong), faiblissant (waning) ou inerte.',
            'Infuser : à la FIN de votre tour, le jeton va en colonne forte. Il faut avoir fait au moins une capacité de l’action.',
            'Consommer : au DÉBUT de votre tour, un élément fort ou faiblissant passe inerte pour l’effet indiqué. Le même élément ne se consomme pas deux fois par tour.',
          ],
          warn: 'Une consommation en haut à gauche de l’action est obligatoire pour toute l’action. Sur une capacité, c’est un coût facultatif.',
          components: ['elements'],
          crop: { page: 23, x: 0.54, y: 0.17, w: 0.42, h: 0.3 },
          ref: 'Elements — p.23',
        },
        {
          id: 't8',
          kind: 'info',
          title: 'Les bonus actifs',
          body: [
            'Une carte à bonus actif reste dans la zone active, pas en main.',
            'Bonus de manche : jusqu’à la fin de la manche. Bonus persistant : jusqu’à sa condition de retrait ; avec des cases d’usage, le jeton avance à chaque déclenchement.',
            'Sans condition, il dure jusqu’à la fin du scénario. On peut retirer un bonus persistant volontairement, hors capacité.',
          ],
          components: ['jetons-perso'],
          crop: { page: 30, x: 0.5, y: 0.62, w: 0.41, h: 0.3 },
          ref: 'Active Bonuses — p.30',
        },
        {
          id: 't9',
          kind: 'info',
          title: 'Repos court, repos long',
          body: [
            'Repos court, en fin de manche : perdez une carte de la défausse AU HASARD, reprenez les autres en main. Pour la garder : subissez 1 dégât et perdez-en une autre au hasard, une fois par repos.',
            'Repos long, déclaré au choix des cartes : perdez une carte de la défausse AU CHOIX, reprenez les autres ; Heal 2 sur vous ; récupérez tous les objets dépensés (spent).',
          ],
          warn: 'Il faut au moins deux cartes en défausse pour se reposer, et un repos coûte toujours une carte.',
          crop: { page: 38, x: 0.05, y: 0.46, w: 0.42, h: 0.16 },
          ref: 'Resting — p.38',
        },
        {
          id: 't10',
          kind: 'info',
          title: 'Subir des dégâts, ou les annuler',
          body: [
            'Après Ward et Brittle, baissez le cadran rouge. Ou annulez tous les dégâts : par une capacité, ou en perdant une carte de la main ou deux de la défausse.',
            'Les deux cartes choisies pour le tour ne peuvent pas servir à annuler. Les conditions s’appliquent même si les dégâts sont annulés.',
          ],
          components: ['cadran'],
          ref: 'Damage — p.38',
        },
        {
          id: 't11',
          kind: 'info',
          title: 'L’épuisement',
          body: [
            'Un personnage est épuisé quand ses points de vie tombent à 0, ou quand, au début d’une manche, il a moins de deux cartes en main ET moins de deux en défausse.',
            'Toutes ses cartes vont en perte, sa figure et ses invocations sont retirées. Il ne participe plus au scénario.',
          ],
          warn: 'Tous les personnages épuisés : le scénario est perdu.',
          ref: 'Exhaustion — p.38',
        },
      ],
    },

    {
      id: 'combat',
      title: 'Se déplacer et attaquer',
      kind: 'play',
      goal: 'Résoudre un Move, un Attack, et tout ce qui les modifie.',
      steps: [
        {
          id: 'a1',
          kind: 'action',
          title: 'Move X',
          body: [
            'X points de mouvement, un hexagone par point. On traverse les alliés, pas les ennemis, les obstacles, les objectifs ni les murs.',
            'Un piège traversé se déclenche. Un terrain difficile coûte 2 points. On termine sur un hexagone libre.',
          ],
          crop: { page: 24, x: 0.05, y: 0.12, w: 0.42, h: 0.5 },
          ref: 'Move — p.24',
        },
        {
          id: 'a2',
          kind: 'info',
          title: 'Jump, Flying, Teleport',
          body: [
            'Jump : ignore ennemis, obstacles, objectifs, pièges et terrain dangereux, sauf pour le dernier hexagone. Jamais les murs.',
            'Flying : bonus actif ; ignore tout, dernier hexagone compris, mais ne termine pas sur une figure.',
            'Teleport X : n’importe quel hexagone libre à X, sans évaluer le chemin. Pas dans une salle non révélée.',
          ],
          crop: { page: 24, x: 0.5, y: 0.37, w: 0.42, h: 0.36 },
          ref: 'Move — p.24',
        },
        {
          id: 'a3',
          kind: 'info',
          title: 'Portée, cibles, alliés',
          body: [
            'Range X : jusqu’à X hexagones, pas à travers un mur ; à travers obstacles et figures, oui. Sans portée, une attaque est de mêlée : portée 1.',
            'Target X : jusqu’à X figures différentes. Sans valeur, une seule.',
            'Les personnages sont alliés entre eux, les monstres entre eux. Une figure n’est pas son propre allié.',
          ],
          crop: { page: 21, x: 0.53, y: 0.76, w: 0.4, h: 0.16 },
          ref: 'Targeting — p.21',
        },
        {
          id: 'a4',
          kind: 'info',
          title: 'Ligne de vue',
          body: [
            'Il faut pouvoir tracer une ligne d’un point de votre hexagone à un point de l’hexagone cible sans toucher un trait de mur.',
            'Seuls les murs et les portes fermées bloquent la ligne de vue.',
          ],
          crop: { page: 21, x: 0.1, y: 0.31, w: 0.4, h: 0.26 },
          ref: 'Line of Sight — p.21',
        },
        {
          id: 'a5',
          kind: 'info',
          title: 'Zone d’effet',
          body: [
            'Gris : l’hexagone de l’acteur, pour une zone de mêlée. Bleu : l’hexagone qu’un allié doit occuper. Rouge : les hexagones ciblés, dont un seul doit être à portée. Blanc : espace.',
            'La zone peut être tournée et retournée.',
          ],
          crop: { page: 22, x: 0.05, y: 0.17, w: 0.42, h: 0.38 },
          ref: 'Area of Effect — p.22',
        },
        {
          id: 'a6',
          kind: 'action',
          title: 'Attack X',
          body: [
            'X dégâts de base à un ennemi à portée, dans cet ordre : 1. bonus et malus d’attaque ; 2. une carte de modificateur tirée du paquet de l’attaquant ; 3. le Shield de la cible ; 4. Ward et Brittle.',
            'La cible subit le résultat. Pierce X réduit le Shield de X. On recommence pour chaque cible.',
          ],
          components: ['modificateurs'],
          crop: { page: 25, x: 0.09, y: 0.38, w: 0.41, h: 0.28 },
          ref: 'Attack — p.25',
        },
        {
          id: 'a7',
          kind: 'info',
          title: 'La carte de modificateur',
          body: [
            'A valeur : null ramène l’attaque à 0, 2x la double. B effets ajoutés. C icône rolling, verte : tirez encore, jusqu’à une carte sans rolling, et cumulez.',
            'D bénédiction et malédiction retournent à la réserve après usage. E icône de mélange : remélangez la défausse en fin de manche.',
          ],
          warn: 'Une carte par cible, et seulement pour les attaques. Les effets d’attaque se décident avant de tirer la carte.',
          components: ['modificateurs'],
          crop: { page: 26, x: 0.06, y: 0.7, w: 0.4, h: 0.23 },
          ref: 'Attack Modifier Cards — p.26',
        },
        {
          id: 'a8',
          kind: 'info',
          title: 'Avantage, désavantage',
          body: [
            'Avantage : tirez deux cartes, gardez la meilleure. Désavantage : deux cartes, la pire. Les deux s’annulent ; rien ne se cumule.',
            'Avec rolling : on continue jusqu’à une carte sans rolling, puis une de plus. L’avantage garde les rolling initiaux, le désavantage les ignore.',
          ],
          warn: 'Une attaque à distance sur un ennemi adjacent a automatiquement désavantage.',
          crop: { page: 27, x: 0.55, y: 0.13, w: 0.38, h: 0.15 },
          ref: 'Advantage and Disadvantage — p.27',
        },
        {
          id: 'a9',
          kind: 'info',
          title: 'Shield, Retaliate',
          body: [
            'Shield X réduit de X chaque attaque subie, après bonus et modificateurs. Il se cumule. Il ne réduit pas les dégâts qui ne sont pas des attaques.',
            'Retaliate X inflige X dégâts à qui attaque la figure à portée, adjacent par défaut, après la résolution de l’attaque. Ce n’est pas une attaque.',
          ],
          crop: { page: 31, x: 0.09, y: 0.17, w: 0.42, h: 0.48 },
          ref: 'Shield and Retaliate — p.31',
        },
        {
          id: 'a10',
          kind: 'info',
          title: 'Invoquer (Summon)',
          body: [
            'Une figure alliée sur un hexagone vide adjacent, socle bleu. C’est un bonus persistant : à 0 point de vie, elle est retirée.',
            'Elle joue juste avant son invocateur, avec les règles de monstre, Move +0 et Attack +0, et le paquet de modificateurs de l’invocateur.',
          ],
          warn: 'Une invocation ne joue pas de tour la manche où elle est invoquée.',
          components: ['standees'],
          crop: { page: 31, x: 0.55, y: 0.7, w: 0.36, h: 0.26 },
          ref: 'Summon — p.31',
        },
        {
          id: 'a11',
          kind: 'info',
          title: 'Push, Pull',
          body: [
            'Push X éloigne la cible de X hexagones, Pull X la rapproche. Un personnage choisit direction et distance ; pour un monstre, le groupe choisit, à la distance maximale.',
            'Le terrain difficile est ignoré. Une figure immobilisée ou étourdie peut être poussée. Résolu après l’effet principal.',
          ],
          crop: { page: 32, x: 0.03, y: 0.22, w: 0.45, h: 0.16 },
          ref: 'Forced Movement — p.32',
        },
        {
          id: 'a12',
          kind: 'info',
          title: 'Conditions positives',
          body: [
            'Regenerate : Heal 1 sur soi au début de chaque tour ; retiré dès que la figure subit des dégâts. Ward : les prochains dégâts sont divisés par deux, arrondi au bas.',
            'Invisible : ne peut être ni focus ni cible d’un ennemi, jusqu’à la fin de son prochain tour. Strengthen : avantage sur toutes ses attaques, jusqu’à la fin de son prochain tour.',
            'Bless : une carte 2x mélangée dans le paquet, qui retourne à la réserve une fois tirée.',
          ],
          warn: 'Une condition ne se cumule pas : la durée repart. On ne retire jamais une condition volontairement.',
          components: ['jetons'],
          crop: { page: 28, x: 0.48, y: 0.09, w: 0.45, h: 0.66 },
          ref: 'Conditions — p.28',
        },
        {
          id: 'a13',
          kind: 'info',
          title: 'Conditions négatives',
          body: [
            'Wound : 1 dégât au début de chaque tour. Brittle : les prochains dégâts sont doublés. Bane : 10 dégâts à la fin du prochain tour. Poison : toutes les attaques subies +1. Un soin retire ces quatre-là.',
            'Immobilize : pas de Move. Disarm : pas d’Attack. Impair : pas d’objet. Stun : aucune capacité ni objet. Muddle : désavantage. Chacune jusqu’à la fin du prochain tour.',
            'Curse : une carte null mélangée dans le paquet, qui retourne à la réserve une fois tirée.',
          ],
          warn: 'Étourdi, on choisit quand même deux cartes, défaussées sans effet ; un repos long se joue normalement.',
          components: ['jetons'],
          crop: { page: 29, x: 0.07, y: 0.09, w: 0.43, h: 0.83 },
          ref: 'Conditions — p.29',
        },
        {
          id: 'a14',
          kind: 'info',
          title: 'Heal X',
          body: [
            'La cible regagne X points de vie : cadran rouge pour un personnage, jetons de dégâts retirés pour un monstre. Jamais au-dessus du maximum.',
            'Un seul soin retire Wound, Brittle, Bane et Poison. Avec Poison, le soin retire la condition mais ne rend aucun point de vie.',
          ],
          ref: 'Heal — p.29',
        },
        {
          id: 'a15',
          kind: 'info',
          title: 'Autres capacités',
          body: [
            'Suffer damage : des dégâts qui ne sont pas une attaque, modifiés seulement par Ward et Brittle.',
            'Recover : reprendre en main des cartes défaussées ou perdues, jusqu’au nombre indiqué.',
            'Grant : donner une capacité à une autre figure. Control : jouer une capacité d’un ennemi comme si c’était la vôtre.',
          ],
          ref: 'Other Abilities — p.32-33',
        },
      ],
    },

    {
      id: 'monstres',
      title: 'Les monstres',
      kind: 'play',
      goal: 'Jouer le tour d’un monstre à sa place : focus, mouvement, attaque, mort.',
      steps: [
        {
          id: 'mo1',
          kind: 'info',
          title: 'La carte de stats',
          body: [
            'A nom. B niveau. C rang : normal à gauche, élite à droite. D points de vie. E mouvement. F attaque. G bonus persistants. H effets d’attaque. I immunités.',
            'La pochette a 6 ou 10 sections, une par numéro de pion : les jetons de dégâts et de conditions d’un monstre vont dans la sienne.',
          ],
          components: ['stats-monstre', 'monstres'],
          crop: { page: 39, x: 0.53, y: 0.58, w: 0.44, h: 0.38 },
          ref: 'Monster Stat Cards — p.39',
        },
        {
          id: 'mo2',
          kind: 'info',
          title: 'La carte de capacité',
          body: [
            'Huit cartes par groupe. Une est tirée après le choix des personnages, pour chaque groupe ayant au moins une figure sur la carte.',
            'A nom. B initiative. C capacités, de haut en bas. D icône de mélange : remélangez en fin de manche.',
          ],
          warn: 'Un monstre ne fait QUE ce que sa carte liste. Pas de Move sur la carte : il ne bouge pas. En cas d’ambiguïté, le groupe décide.',
          components: ['capacites-monstre'],
          crop: { page: 40, x: 0.5, y: 0.1, w: 0.42, h: 0.26 },
          ref: 'Monster Ability Cards — p.40',
        },
        {
          id: 'mo3',
          kind: 'action',
          title: 'Trouver le focus',
          body: [
            'Au début de son tour, le monstre prend pour focus l’ennemi qu’il peut attaquer en dépensant le moins de points de mouvement : jusqu’à un hexagone adjacent en mêlée, jusqu’à un hexagone à portée à distance.',
            'Égalité : le plus proche en portée ; puis celui qui agit le plus tôt. Le chemin retenu est celui qui traverse le moins d’hexagones négatifs, même s’il est plus long.',
          ],
          warn: 'Sans attaque sur sa carte, ou désarmé, il cherche son focus comme une mêlée à une cible. Sans focus possible, il ne bouge ni n’attaque, et fait le reste.',
          crop: { page: 41, x: 0.09, y: 0.46, w: 0.42, h: 0.37 },
          ref: 'Monster Focus — p.41',
        },
        {
          id: 'mo4',
          kind: 'action',
          title: 'Se déplacer',
          body: [
            'Seulement avec « Move ±X » sur sa carte : la stat de base, plus ou moins X.',
            'Il dépense le moins de points possible pour attaquer le plus de cibles. S’il ne peut pas attaquer ce tour, il ne bouge que si cela raccourcit son chemin.',
          ],
          warn: 'Une attaque à distance sur une cible adjacente : il s’éloigne d’abord, s’il le peut, pour éviter le désavantage.',
          crop: { page: 42, x: 0.5, y: 0.56, w: 0.42, h: 0.37 },
          ref: 'Monster Movement — p.42',
        },
        {
          id: 'mo5',
          kind: 'action',
          title: 'Attaquer',
          body: [
            'Seulement avec « Attack ±X ». La portée est celle de la carte, sinon mêlée. Il attaque son focus, et toutes ses attaques visent le focus.',
            'Cibles supplémentaires : le focus, puis autant d’autres ennemis que possible. Tous les monstres partagent le paquet de modificateurs M.',
          ],
          components: ['modificateurs'],
          ref: 'Monster Attacks — p.42',
        },
        {
          id: 'mo6',
          kind: 'info',
          title: 'Ses autres capacités',
          body: [
            'Heal : le monstre du groupe qui a le plus de points de vie manquants. Loot : les jetons à portée, jamais les trésors. Condition positive : lui-même ou l’allié le plus proche qui ne l’a pas.',
            'Invocation : hexagone vide adjacent le plus proche d’un ennemi ; sans pion disponible, rien n’est invoqué.',
            'Élément consommé quand le premier du groupe commence, infusé quand le dernier termine. Élément « wild » : le groupe décide.',
          ],
          crop: { page: 43, x: 0.53, y: 0.63, w: 0.42, h: 0.32 },
          ref: 'Other Monster Abilities — p.43',
        },
        {
          id: 'mo7',
          kind: 'action',
          title: 'Dégâts et mort',
          body: [
            'Les jetons de dégâts vont dans la section du numéro du monstre, sur la pochette. À hauteur de ses points de vie, il meurt : pion retiré, section vidée.',
            'Posez un jeton de butin sur son hexagone, même s’il a été invoqué ou apparu en cours de scénario.',
          ],
          warn: 'Sauf pour un allié de scénario : lui ne laisse pas de butin.',
          components: ['butin', 'jetons'],
          crop: { page: 45, x: 0.54, y: 0.5, w: 0.42, h: 0.42 },
          ref: 'Monster Damage — p.45',
        },
        {
          id: 'mo8',
          kind: 'info',
          title: 'Révéler une salle, faire apparaître',
          body: [
            'Une salle se révèle immédiatement, comme à la mise en place, quand un personnage ouvre sa porte ou quand le livre de sections le dit.',
            'Les monstres révélés ou apparus jouent dans la même manche : tirez une carte de capacité s’il n’y en a pas. Initiative après l’acteur : place normale ; avant : juste après l’acteur.',
          ],
          warn: 'Pions manquants : placez-en le plus possible, élites d’abord, au plus près d’un ennemi. Un monstre nommé a un socle rouge et agit avant les élites.',
          crop: { page: 44, x: 0.5, y: 0.12, w: 0.42, h: 0.82 },
          ref: 'Revealing Rooms and Spawning — p.44',
        },
        {
          id: 'mo9',
          kind: 'info',
          title: 'Les boss',
          body: [
            'Une carte de stats spéciale et un paquet de capacités spécial. Socle rouge, ni normal ni élite.',
            'Sur ses stats, « C » vaut le nombre de personnages.',
          ],
          crop: { page: 45, x: 0.53, y: 0.11, w: 0.4, h: 0.33 },
          ref: 'Bosses — p.45',
        },
        {
          id: 'mo10',
          kind: 'info',
          title: 'Le guide du tour de monstre',
          body: [
            'L’appendice B, pages 74 à 75, déroule le tour d’un monstre en trois temps : vérification initiale, focus, capacités et règles de mouvement A à F.',
            'Gardez-le ouvert les premières manches.',
          ],
          crop: { page: 74, x: 0.04, y: 0.12, w: 0.92, h: 0.84 },
          ref: 'Appendix B: Monster Turn Guide — p.74',
        },
      ],
    },

    {
      id: 'carte',
      title: 'La carte',
      kind: 'play',
      goal: 'Lire une tuile, une overlay, et savoir ce que coûte chaque terrain.',
      steps: [
        {
          id: 'k1',
          kind: 'info',
          title: 'Tuiles, murs, salles',
          body: [
            'Une tuile de carte est pleine d’hexagones vides, bordée de murs. Un trait de mur ne se traverse pas.',
            'Un groupe d’hexagones entouré de murs est une salle. Deux tuiles se joignent par un corridor : des hexagones vides, pas des overlays.',
          ],
          components: ['tuiles-carte'],
          crop: { page: 13, x: 0.55, y: 0.15, w: 0.36, h: 0.16 },
          ref: 'Map Tiles and Walls — p.13',
        },
        {
          id: 'k2',
          kind: 'info',
          title: 'Les overlays : lire la bordure, pas l’image',
          body: [
            'Le type d’une overlay est donné par la couleur de sa bordure dans le livre de scénarios, pas par son illustration.',
            'Un hexagone sans overlay est « featureless » ; sans figure, « unoccupied » ; les deux, « empty ». Les jetons ne sont pas des overlays.',
          ],
          components: ['overlays'],
          crop: { page: 13, x: 0.55, y: 0.34, w: 0.4, h: 0.17 },
          ref: 'Overlay Tiles — p.13',
        },
        {
          id: 'k3',
          kind: 'info',
          title: 'Portes',
          body: [
            'Fermée au départ. Un personnage qui y entre par son mouvement la retourne : elle est ouverte, et la salle derrière est révélée.',
            'Fermée, elle vaut un mur pour tout sauf le mouvement normal des personnages. Ouverte, elle vaut un corridor, mais sépare toujours les deux salles.',
          ],
          crop: { page: 14, x: 0.06, y: 0.34, w: 0.4, h: 0.3 },
          ref: 'Doors — p.14',
        },
        {
          id: 'k4',
          kind: 'info',
          title: 'Pièges et terrains',
          body: [
            'Piège : se déclenche quand on y entre, puis est retiré. « Damage » vaut 2 + niveau du scénario.',
            'Terrain dangereux : 1 + un tiers du niveau, arrondi au supérieur, en y entrant ; il reste. Terrain difficile : 2 points de mouvement. Terrain glacé : on glisse d’un hexagone de plus dans la même direction.',
          ],
          warn: 'Jump et Flying ignorent pièges et terrain dangereux, sauf l’hexagone d’arrivée pour Jump.',
          crop: { page: 14, x: 0.5, y: 0.09, w: 0.42, h: 0.74 },
          ref: 'Traps and Terrain — p.14',
        },
        {
          id: 'k5',
          kind: 'info',
          title: 'Obstacles, objectifs, murs',
          body: [
            'Obstacle : infranchissable sauf Jump et Flying ; ne bloque pas la ligne de vue.',
            'Objectif : une figure avec des points de vie fixés par les règles spéciales ; attaquable, immunisé aux conditions et au mouvement forcé ; initiative 99 pour le focus.',
            'Mur en overlay : infranchissable même en volant.',
          ],
          crop: { page: 15, x: 0.05, y: 0.09, w: 0.45, h: 0.25 },
          ref: 'Obstacles, Objectives, Walls — p.15',
        },
        {
          id: 'k6',
          kind: 'info',
          title: 'Trésors',
          body: [
            'Un trésor se pille comme un jeton de butin. Son effet s’applique, puis la tuile est retirée. Seul le pilleur gagne.',
            '« Goal » : lié au scénario. Numéroté : voir l’index des trésors, page 78. Cochez-le dans l’index et rayez-le dans le livre : il ne se pille plus jamais.',
          ],
          warn: 'Un objet gagné se prend dans la réserve indisponible et se porte tout de suite, même au-delà de la limite. Les monstres ne pillent pas les trésors.',
          crop: { page: 15, x: 0.53, y: 0.23, w: 0.4, h: 0.2 },
          ref: 'Treasures — p.15',
        },
        {
          id: 'k7',
          kind: 'info',
          title: 'Le niveau du scénario',
          body: [
            'Niveau moyen des personnages ÷ 2, arrondi au supérieur. Le groupe peut le régler de 0 à 7.',
            'Niveau 0 à 7 : or par pièce 2, 2, 3, 3, 4, 4, 5, 6 ; dégâts de piège 2 à 9 ; terrain dangereux 1, 2, 2, 2, 3, 3, 3, 4 ; XP bonus 4, 6, 8, 10, 12, 14, 16, 18.',
          ],
          crop: { page: 16, x: 0.5, y: 0.74, w: 0.41, h: 0.16 },
          ref: 'Scenario Level — p.16',
        },
        {
          id: 'k8',
          kind: 'info',
          title: 'Le paquet de butin',
          body: [
            'Money : 20 cartes, 1 à 3 pièces, converties en or selon le niveau. Material : 8 par matériau, bois (lumber), métal, cuir (hide). Herb : 2 par herbe. Random Item : 1 carte.',
            'Un objet aléatoire : cochez la table, piochez, il est utilisable tout de suite. Paquet d’objets aléatoires vide : 3 pièces.',
          ],
          components: ['butin'],
          crop: { page: 16, x: 0.05, y: 0.21, w: 0.43, h: 0.33 },
          ref: 'Loot Deck — p.16',
        },
      ],
    },

    {
      id: 'fin',
      title: 'Fin du scénario',
      kind: 'debrief',
      goal: 'Clore le scénario, réussi ou perdu, et savoir ce qui vient ensuite.',
      steps: [
        {
          id: 'f1',
          kind: 'info',
          title: 'Réussi, ou perdu',
          body: [
            'Perdu : tous les personnages épuisés, ou la condition de perte du scénario. Réussi : l’objectif est atteint.',
            'Quand la fin est déclenchée, on termine la manche. Perdu et réussi dans la même manche : perdu.',
          ],
          crop: { page: 47, x: 0.08, y: 0.13, w: 0.86, h: 0.34 },
          ref: 'Ending a Scenario — p.47',
        },
        {
          id: 'f2',
          kind: 'check',
          title: 'Chacun remet son personnage en état',
          body: [
            'Reprenez vos cartes défaussées et perdues, vos objets dépensés et perdus. Cadran rouge au maximum, conditions retirées.',
            'Retirez des paquets les cartes bless, curse et à étoile. Remélangez les battle goals. Le butin resté sur la carte est perdu.',
          ],
          components: ['modificateurs', 'battle-goals'],
          ref: 'Ending a Scenario — p.47',
        },
        {
          id: 'f3',
          kind: 'check',
          title: 'Notez l’XP et l’or',
          body: [
            'XP : le cadran bleu, plus le bonus du niveau de scénario si le scénario est réussi. Sur la fiche.',
            'Or : chaque pièce des cartes de butin, au taux de conversion du niveau. Sur la fiche, réussi ou non.',
          ],
          components: ['feuille-perso', 'butin'],
          crop: { page: 47, x: 0.52, y: 0.2, w: 0.42, h: 0.26 },
          ref: 'Ending a Scenario — p.47',
        },
        {
          id: 'f4',
          kind: 'info',
          title: 'Scénario perdu : revenir, ou rejouer',
          body: [
            'A. Retour à Frosthaven : vous gagnez les ressources des cartes de butin, gardez XP, or et trésors, jouez la phase d’avant-poste, et un événement de route en repartant.',
            'B. Rejouer tout de suite : pas de ressources de butin, XP, or et trésors gardés, pas de phase d’avant-poste, pas d’événement de route.',
          ],
          crop: { page: 47, x: 0.05, y: 0.53, w: 0.45, h: 0.32 },
          ref: 'Ending a Scenario — p.47',
        },
        {
          id: 'f5',
          kind: 'check',
          title: 'Scénario réussi : les huit points',
          body: [
            '1. Ressources des cartes de butin, sur la fiche. 2. Battle goal atteint : ses coches ; trois coches font un perk. 3. Maîtrise accomplie : un perk, une fois par personnage.',
            '4. Sous autocollant 8 : suivez le livret. 5. Lisez la conclusion. 6. Récompenses du scénario, une fois par campagne ; scénario débloqué : son autocollant sur la carte.',
            '7. Inspiration : 4 moins le nombre de personnages, sur la feuille de campagne. 8. Cochez le scénario sur la carte.',
          ],
          warn: 'Un personnage épuisé dans un scénario réussi garde tout.',
          components: ['feuille-campagne', 'plateau-carte'],
          crop: { page: 48, x: 0.04, y: 0.12, w: 0.92, h: 0.52 },
          ref: 'Ending a Scenario — p.48',
        },
        {
          id: 'f6',
          kind: 'info',
          title: 'Et ensuite',
          body: [
            'Retour à Frosthaven pour la phase d’avant-poste, sauf si le scénario suivant est lié (on peut sauter la phase) ou lié de force (on doit la sauter).',
            'Un scénario rejoué ignore ses liens : retour à Frosthaven.',
          ],
          ref: 'Ending a Scenario — p.48',
        },
        {
          id: 'f7',
          kind: 'info',
          title: 'Après le scénario 1 : lisez la suite',
          body: [
            'La phase d’avant-poste, les bâtiments, les objets, la retraite : pages 49 à 68.',
            'Il n’y a pas de phase d’avant-poste entre le scénario 0 et le scénario 1.',
          ],
          ref: 'The Adventure Begins — p.49',
        },
      ],
    },

    {
      id: 'avant-poste',
      title: 'La phase d’avant-poste',
      kind: 'play',
      goal: 'Dérouler les cinq étapes du retour à Frosthaven.',
      steps: [
        {
          id: 'o1',
          kind: 'info',
          title: 'Quand, et en cinq étapes',
          body: [
            'Après chaque phase de scénario, sauf en rejouant un scénario perdu, ou en enchaînant un scénario lié.',
            '1. Passage du temps. 2. Événement d’avant-poste. 3. Opérations des bâtiments. 4. Temps libre (Downtime). 5. Construction.',
          ],
          crop: { page: 59, x: 0.53, y: 0.2, w: 0.42, h: 0.15 },
          ref: 'Outpost Phase — p.59',
        },
        {
          id: 'o2',
          kind: 'action',
          title: '1. Passage du temps',
          body: [
            'Cochez la case suivante du calendrier de la feuille de campagne : une semaine.',
            'Un numéro de section écrit dans une case se lit au moment de la cocher. Dix cases : la saison change, été puis hiver.',
          ],
          components: ['feuille-campagne'],
          crop: { page: 59, x: 0.54, y: 0.5, w: 0.42, h: 0.44 },
          ref: 'Passage of Time — p.59',
        },
        {
          id: 'o3',
          kind: 'action',
          title: '2. Événement d’avant-poste',
          body: [
            'Piochez dans le paquet d’événements d’avant-poste de la saison. Résolvez-le comme un événement de route.',
            'Un événement d’attaque vise des bâtiments : pour chacun, tirez une carte de garde et ajoutez la défense totale. Résultat au moins égal à l’attaque : défendu. Sinon, endommagé, ou détruit.',
          ],
          warn: 'Endommagé : payez tout de suite le coût de réparation, ou perdez 1 de morale. Détruit : retournez la carte du bâtiment.',
          components: ['evenements'],
          crop: { page: 61, x: 0.53, y: 0.09, w: 0.43, h: 0.45 },
          ref: 'Outpost Event — p.60 ; Defense Checks — p.61',
        },
        {
          id: 'o4',
          kind: 'action',
          title: '3. Opérations des bâtiments',
          body: [
            'Parcourez le paquet de bâtiments dans l’ordre des numéros. Appliquez l’effet normal de chaque carte, ou son effet détruit.',
            'Les gains vont dans la réserve de votre choix, personnage ou Frosthaven.',
          ],
          warn: 'Un contenu sous autocollant 10 complète cette étape : suivez le livret.',
          components: ['batiments'],
          crop: { page: 52, x: 0.5, y: 0.12, w: 0.43, h: 0.59 },
          ref: 'Building Operations — p.62',
        },
        {
          id: 'o5',
          kind: 'action',
          title: '4. Temps libre',
          body: [
            'Dans n’importe quel ordre : monter de niveau, prendre sa retraite, créer un personnage, fabriquer, préparer des potions, vendre.',
            'Un bâtiment détruit ne permet aucune interaction.',
          ],
          warn: 'Des contenus sous autocollants 11 à 14 complètent cette étape : suivez le livret.',
          ref: 'Downtime — p.62',
        },
        {
          id: 'o6',
          kind: 'info',
          title: 'Monter de niveau',
          body: [
            'Obligatoire dès que l’XP atteint le seuil : 45, 95, 150, 210, 275, 345, 420, 500. L’XP ne repart pas à zéro. Seulement en phase d’avant-poste.',
            'Vous gagnez une carte de capacité de votre classe, de niveau au plus égal au nouveau ; vos nouveaux points de vie maximum ; et un perk.',
          ],
          warn: 'La taille de main ne change pas. Un personnage sous la moitié de la prospérité peut monter sans XP : elle est alors réglée au seuil.',
          components: ['feuille-perso', 'cartes-capacite'],
          crop: { page: 63, x: 0.52, y: 0.01, w: 0.44, h: 0.27 },
          ref: 'Leveling Up — p.62-63',
        },
        {
          id: 'o7',
          kind: 'info',
          title: 'Retraite et nouveau personnage',
          body: [
            'Quête personnelle accomplie : le personnage prend sa retraite au temps libre. Prospérité +2, et l’enveloppe de bâtiment indiquée sur la carte.',
            'Nouveau personnage : une classe sans personnage actif, or = 10 × prospérité + 20, à dépenser tout de suite ; un perk par retraité du joueur ; niveau 1, montée facultative jusqu’à la moitié de la prospérité.',
          ],
          components: ['quetes', 'feuille-campagne'],
          crop: { page: 64, x: 0.5, y: 0.11, w: 0.42, h: 0.24 },
          ref: 'Retiring — p.64 ; Creating a New Character — p.65',
        },
        {
          id: 'o8',
          kind: 'info',
          title: 'Fabriquer, potions, vendre',
          body: [
            'Fabriquer, au Craftsman : les ressources et objets requis par la carte ; matériaux du personnage seulement, herbes des deux réserves.',
            'Potion, à l’Alchemist : deux herbes, et la fenêtre correspondante de la table d’alchimie s’ouvre la première fois.',
            'Vendre : un doublon se vend obligatoirement ; la moitié du prix d’un objet achetable, 2 d’or par ressource d’un objet fabriqué.',
          ],
          ref: 'Crafting — p.65 ; Potions — p.66 ; Selling — p.67',
        },
        {
          id: 'o9',
          kind: 'action',
          title: '5. Construction',
          body: [
            'Une construction ou une amélioration par phase ; une deuxième coûte 2 de morale. Les reconstructions sont illimitées, après.',
            'Construire : payez le coût de l’autocollant L0 avec la réserve de Frosthaven, collez l’autocollant L1, ajoutez la carte L1 au paquet. L’effet commence à la phase suivante.',
          ],
          warn: 'Un contenu sous autocollant 15 complète cette étape : suivez le livret.',
          components: ['batiments', 'plateau-carte'],
          crop: { page: 68, x: 0.5, y: 0.12, w: 0.42, h: 0.75 },
          ref: 'Construction — p.68',
        },
      ],
    },

    {
      id: 'rp',
      title: 'Reprendre la campagne',
      kind: 'setup',
      modes: ['reprise'],
      goal: 'Remonter la campagne à partir de la feuille de campagne, des fiches et du paquet de bâtiments, puis reprendre au bon point.',
      steps: [
        {
          id: 'rp1',
          kind: 'info',
          title: 'Ce que la campagne conserve',
          body: [
            'La campagne se suit sur cinq supports : le plateau-carte, les flowcharts, le paquet de bâtiments, les fiches de personnage et la feuille de campagne.',
            'Un scénario se joue en une seule séance : le livret ne prévoit pas de sauvegarde en cours de scénario. On reprend entre deux scénarios.',
          ],
          warn: 'Si la table est restée montée au milieu d’un scénario, reprenez à l’étape de la manche où vous étiez. Sinon, le scénario se réinstalle depuis le début.',
          components: ['plateau-carte', 'batiments', 'feuille-perso', 'feuille-campagne'],
          crop: { page: 50, x: 0.5, y: 0.13, w: 0.42, h: 0.28 },
          ref: 'Campaign — p.50 ; Scenario Phase — p.7',
        },
        {
          id: 'rp2',
          kind: 'take',
          title: 'Sortez la feuille de campagne',
          body: [
            'A calendrier : la dernière case cochée est votre dernier retour à Frosthaven. Dix cases par saison, été puis hiver. B réserve de Frosthaven. C inspiration.',
            'D défense totale. E soldats. F morale. G autocollants de campagne. H prospérité. I retraités. J perks de la garde.',
          ],
          components: ['feuille-campagne'],
          crop: { page: 59, x: 0.54, y: 0.5, w: 0.42, h: 0.44 },
          ref: 'Campaign Sheet — p.54',
        },
        {
          id: 'rp3',
          kind: 'check',
          title: 'Où vous en étiez',
          body: [
            'Une phase d’avant-poste suit chaque phase de scénario, sauf en rejouant un scénario perdu ou en enchaînant un scénario lié.',
            'Si la dernière séance s’est arrêtée après un scénario sans jouer cette phase, jouez-la maintenant, dans ses cinq étapes. Sinon, la prochaine chose à faire est de choisir un scénario.',
          ],
          ref: 'Outpost Phase — p.59',
        },
        {
          id: 'rp4',
          kind: 'place',
          title: 'Le plateau-carte et les flowcharts',
          body: [
            'Les scénarios débloqués portent leur autocollant ; les scénarios réussis sont cochés ; un scénario verrouillé porte un autocollant rouge.',
            'Chaque bâtiment construit porte son autocollant de niveau. Les autocollants de campagne notés sur la feuille (G) sont posés.',
          ],
          components: ['plateau-carte'],
          crop: { page: 51, x: 0.08, y: 0.57, w: 0.88, h: 0.33 },
          ref: 'Campaign Stickers — p.50 ; Scenario Flowcharts — p.51',
        },
        {
          id: 'rp5',
          kind: 'take',
          title: 'Le paquet de bâtiments',
          body: [
            'Trié par numéro. Pour chaque bâtiment, seule la carte de son niveau actuel est dans le paquet, face normale ; face détruite s’il est détruit.',
            'Au départ d’une campagne : Barracks 1, Craftsman 1, Alchemist 1, Workshop 1.',
          ],
          components: ['batiments'],
          crop: { page: 52, x: 0.5, y: 0.12, w: 0.43, h: 0.59 },
          ref: 'Building Deck — p.52',
        },
        {
          id: 'rp6',
          kind: 'take',
          title: 'Les réserves d’objets',
          body: [
            'Réserve disponible et réserve indisponible, séparées par un intercalaire, puis chacune en objets achetables et objets fabricables.',
            'Un objet revient à la réserve disponible quand il est vendu ou quand son propriétaire part en retraite.',
          ],
          components: ['objets'],
          crop: { page: 35, x: 0.52, y: 0.11, w: 0.44, h: 0.29 },
          ref: 'Items — p.58',
        },
        {
          id: 'rp7',
          kind: 'take',
          title: 'Chaque joueur reprend sa fiche de personnage',
          body: [
            'A classe. B nom. C niveau, avec le seuil d’XP de chaque niveau. D XP. E or. F ressources du personnage. G notes. H maîtrises. I coches. J perks.',
            'Sortez le tapis, la figurine ou le pion, les pions d’invocation, les jetons, le jeton d’initiative et un cadran.',
          ],
          components: ['feuille-perso', 'tapis', 'standees', 'jetons-perso', 'cadran'],
          crop: { page: 53, x: 0.52, y: 0.12, w: 0.45, h: 0.4 },
          ref: 'Character Sheet — p.53',
        },
        {
          id: 'rp8',
          kind: 'take',
          title: 'Ses cartes de capacité',
          body: [
            'Toutes les cartes de niveau 1 et X de la classe, plus une carte par niveau gagné, choisie à chaque montée de niveau.',
            'La main d’un scénario se choisit à la mise en place : autant de cartes que la taille de main, prises dans ce lot.',
          ],
          tip: 'Le livret ne prévoit pas de noter les cartes choisies. Rangez-les avec vos cartes de niveau 1 à la fin de chaque séance.',
          components: ['cartes-capacite'],
          ref: 'Leveling Up — p.63',
        },
        {
          id: 'rp9',
          kind: 'shuffle',
          title: 'Son paquet de modificateurs',
          body: [
            'Les 20 cartes standard, modifiées par chaque perk coché sur la fiche (J) : retirer ou ajouter les cartes indiquées, prises dans les cartes avancées de la classe.',
            'Les cartes bless, curse et à étoile ont été retirées à la fin du dernier scénario.',
          ],
          components: ['modificateurs'],
          crop: { page: 26, x: 0.06, y: 0.7, w: 0.4, h: 0.23 },
          ref: 'Perks — p.63 ; Attack Modifier Cards — p.26',
        },
        {
          id: 'rp10',
          kind: 'take',
          title: 'Ses objets, sa quête, ses coches',
          body: [
            'Les objets qu’il possède, achetés ou fabriqués. Ceux qu’il portera se choisissent à l’étape 15 de la mise en place.',
            'Sa quête personnelle, secrète ou publique selon ce que le groupe a décidé. Ses coches de battle goals (I) : trois font un perk.',
          ],
          components: ['objets', 'quetes'],
          crop: { page: 64, x: 0.5, y: 0.11, w: 0.42, h: 0.24 },
          ref: 'Items — p.35 ; Battle Goals — p.17',
        },
        {
          id: 'rp11',
          kind: 'info',
          title: 'Un personnage retraité à la dernière séance',
          body: [
            'Son joueur crée un nouveau personnage : classe sans personnage actif, deux quêtes piochées, une gardée.',
            'Or = 10 × prospérité + 20, à dépenser tout de suite en objets achetables ; un perk par retraité du joueur ; niveau 1, montée facultative jusqu’à la moitié de la prospérité.',
          ],
          components: ['feuille-campagne'],
          crop: { page: 65, x: 0.05, y: 0.44, w: 0.45, h: 0.36 },
          ref: 'Creating a New Character — p.65',
        },
        {
          id: 'rp12',
          kind: 'check',
          title: 'Avant de choisir le scénario',
          body: [
            'Niveau du scénario : niveau moyen ÷ 2, arrondi au supérieur, réglable de 0 à 7.',
            'En quittant Frosthaven pour un scénario, un événement de route de la saison du calendrier, sauf scénario lié, ou scénario perdu rejoué sans retour.',
            'Puis la mise en place du scénario, dans ses 18 étapes.',
          ],
          ref: 'Scenario Level — p.16 ; Road Events — p.12',
        },
        {
          id: 'rp13',
          kind: 'info',
          title: 'Trois règles qu’on oublie entre deux séances',
          body: [
            'Une attaque à distance sur un ennemi adjacent a désavantage.',
            'Un monstre ne fait que ce que sa carte liste, et attaque son focus.',
            'À la fin de son tour, un personnage pille son hexagone. Un élément s’infuse en fin de tour et se consomme en début de tour.',
          ],
          ref: 'Reminders — p.76',
        },
      ],
    },

    {
      id: 'r-scenario',
      title: 'Rappel : le scénario',
      kind: 'play',
      modes: ['recap'],
      goal: 'Les règles d’un scénario, dans l’ordre où elles servent.',
      steps: [
        {
          id: 'rr1',
          kind: 'info',
          title: 'La manche',
          body: [
            '1. Chacun choisit deux cartes de sa main, face cachée ; l’une donne l’initiative. Ou repos long, initiative 99, avec au moins deux cartes en défausse.',
            '2. On révèle, on tire une carte de capacité par groupe de monstres, on ordonne du plus petit au plus grand. 3. Chaque figure joue. 4. Fin de manche.',
          ],
          crop: { page: 18, x: 0.05, y: 0.19, w: 0.42, h: 0.11 },
          ref: 'Playing a Scenario — p.18',
        },
        {
          id: 'rr2',
          kind: 'info',
          title: 'Le tour d’un personnage',
          body: [
            'Le haut d’une carte et le bas de l’autre, dans l’ordre voulu. Toute carte vaut Attack 2 en haut ou Move 2 en bas.',
            'Après l’action, la carte va en zone active, en défausse ou en perte selon son icône. XP en bas à droite si une partie de l’action est faite.',
            'À la fin du tour, on pille son hexagone : jeton de butin ou trésor.',
          ],
          crop: { page: 34, x: 0.52, y: 0.38, w: 0.33, h: 0.28 },
          ref: 'Character Turn — p.34',
        },
        {
          id: 'rr3',
          kind: 'info',
          title: 'Les éléments',
          body: [
            'Infuser : à la fin de son tour, le jeton passe en colonne forte. Consommer : au début de son tour, un élément fort ou faiblissant passe inerte.',
            'En fin de manche, tout recule d’une colonne. Une consommation en haut à gauche de l’action est obligatoire.',
          ],
          crop: { page: 23, x: 0.54, y: 0.17, w: 0.42, h: 0.3 },
          ref: 'Elements — p.23',
        },
        {
          id: 'rr4',
          kind: 'info',
          title: 'Move, portée, ligne de vue',
          body: [
            'Move X : un hexagone par point, à travers les alliés seulement ; terrain difficile 2 points ; les pièges se déclenchent. Jump ignore ce qui est traversé, Flying aussi l’arrivée.',
            'Range X : pas à travers un mur. Ligne de vue : une ligne d’un point de l’hexagone à un point de la cible sans toucher un trait de mur.',
          ],
          crop: { page: 24, x: 0.05, y: 0.12, w: 0.42, h: 0.5 },
          ref: 'Move — p.24 ; Line of Sight — p.21',
        },
        {
          id: 'rr5',
          kind: 'info',
          title: 'Attack',
          body: [
            'Dégâts de base, puis : 1. bonus et malus ; 2. une carte de modificateur ; 3. Shield de la cible ; 4. Ward et Brittle. Une carte par cible.',
            'Avantage : deux cartes, la meilleure. Désavantage : la pire. Les deux s’annulent. Attaque à distance sur un adjacent : désavantage.',
            'Retaliate rend des dégâts à qui attaque à portée ; ce n’est pas une attaque.',
          ],
          crop: { page: 25, x: 0.09, y: 0.38, w: 0.41, h: 0.28 },
          ref: 'Attack — p.25 ; Advantage and Disadvantage — p.27',
        },
        {
          id: 'rr6',
          kind: 'info',
          title: 'Les conditions',
          body: [
            'Wound, Brittle, Bane, Poison : jusqu’à un soin. Immobilize, Disarm, Impair, Stun, Muddle, Invisible, Strengthen : jusqu’à la fin du prochain tour. Regenerate : jusqu’aux prochains dégâts.',
            'Bless : une carte 2x dans le paquet. Curse : une carte null. Une condition ne se cumule pas.',
          ],
          crop: { page: 28, x: 0.48, y: 0.09, w: 0.45, h: 0.66 },
          ref: 'Conditions — p.28-29',
        },
        {
          id: 'rr7',
          kind: 'info',
          title: 'Dégâts, repos, épuisement',
          body: [
            'Annuler des dégâts : perdre une carte de la main ou deux de la défausse. Repos court en fin de manche : une carte de la défausse perdue au hasard. Repos long : au choix, plus Heal 2 et récupération des objets.',
            'Épuisé : 0 point de vie, ou moins de deux cartes en main et moins de deux en défausse au début d’une manche.',
          ],
          crop: { page: 38, x: 0.05, y: 0.46, w: 0.42, h: 0.16 },
          ref: 'Damage, Resting, Exhaustion — p.38',
        },
        {
          id: 'rr8',
          kind: 'info',
          title: 'Le tour d’un monstre',
          body: [
            'Focus : l’ennemi attaquable en dépensant le moins de points de mouvement ; égalité, le plus proche, puis celui qui agit le plus tôt.',
            'Il ne fait que ce que sa carte liste, bouge le moins possible pour attaquer le plus de cibles, et attaque son focus. Élites d’abord, par numéro.',
            'Mort : jeton de butin sur son hexagone. Salle révélée ou apparition : les monstres jouent dans la manche.',
          ],
          crop: { page: 41, x: 0.09, y: 0.46, w: 0.42, h: 0.37 },
          ref: 'Monster Turn — p.41-45',
        },
        {
          id: 'rr9',
          kind: 'info',
          title: 'Les overlays',
          body: [
            'Le type est donné par la bordure dans le livre. Porte fermée : mur, sauf pour un personnage qui y entre et la retourne. Piège : 2 + niveau. Terrain dangereux : 1 + un tiers du niveau. Terrain difficile : 2 points. Glace : un hexagone de plus.',
            'Obstacle : Jump et Flying seulement. Objectif : une figure, initiative 99 pour le focus. Trésor : pillé une seule fois.',
          ],
          crop: { page: 14, x: 0.06, y: 0.34, w: 0.4, h: 0.3 },
          ref: 'Overlay Tiles — p.13-15',
        },
        {
          id: 'rr10',
          kind: 'info',
          title: 'Fin de manche',
          body: [
            '1. Effets de fin de manche. 2. Icône de mélange tirée : remélanger. 3. Bonus de manche retirés. 4. Repos court. 5. Éléments d’une colonne vers la gauche, marqueur de manche avancé.',
          ],
          crop: { page: 46, x: 0.05, y: 0.13, w: 0.9, h: 0.19 },
          ref: 'End of Round — p.46',
        },
        {
          id: 'rr11',
          kind: 'info',
          title: 'Fin de scénario',
          body: [
            'Perdu : tous épuisés, ou condition de perte. Réussi : objectif atteint. La manche se termine d’abord.',
            'Tout le monde se remet en état ; XP et or sur la fiche. Réussi : ressources de butin, coches, maîtrises, conclusion, récompenses, inspiration, scénario coché.',
            'Perdu : retour à Frosthaven, ou rejouer sans phase d’avant-poste.',
          ],
          crop: { page: 47, x: 0.08, y: 0.13, w: 0.86, h: 0.34 },
          ref: 'Ending a Scenario — p.47-48',
        },
        {
          id: 'rr12',
          kind: 'info',
          title: 'La phase d’avant-poste',
          body: [
            '1. Une semaine cochée sur le calendrier. 2. Événement d’avant-poste de la saison. 3. Opérations des bâtiments, dans l’ordre des numéros.',
            '4. Temps libre : niveau, retraite, création, artisanat, potions, vente. 5. Une construction ou amélioration ; la deuxième coûte 2 de morale.',
          ],
          crop: { page: 59, x: 0.53, y: 0.2, w: 0.42, h: 0.15 },
          ref: 'Outpost Phase — p.59',
        },
        {
          id: 'rr13',
          kind: 'info',
          title: 'En solo',
          only: [1],
          body: [
            'Au moins deux personnages. Niveau de scénario : (niveau moyen + 1) ÷ 2, arrondi au supérieur.',
          ],
          ref: 'Solo Variant — p.69',
        },
      ],
    },

    {
      id: 'rappels',
      title: 'Rappels du livret',
      kind: 'debrief',
      modes: ['recap'],
      goal: 'Les rappels de la page 76, dans l’ordre du livret.',
      steps: [
        {
          id: 'x1',
          kind: 'check',
          title: 'Attaques',
          body: [
            'Une carte de modificateur par cible. Un Shield ne joue que contre les attaques. Une carte null applique quand même ses effets.',
            'Annuler des dégâts : perdre une carte de la main ou deux de la défausse. Deux camps de monstres : paquets M et A.',
          ],
          ref: 'Reminders — p.76',
        },
        {
          id: 'x2',
          kind: 'check',
          title: 'Monstres',
          body: [
            'Une carte de capacité par groupe. Ils ne font que ce qui est listé. Aucun bonus actif avant leur tour.',
            'Tous les monstres lâchent du butin, sauf les alliés de scénario.',
          ],
          ref: 'Reminders — p.76',
        },
        {
          id: 'x3',
          kind: 'check',
          title: 'Personnages',
          body: [
            'Un paquet de 20 cartes au départ, numéroté 1 à 4. Jamais deux hauts ni deux bas ; Attack 2 en haut, Move 2 en bas.',
            'L’épuisement ne réduit pas le nombre de personnages pour les règles. Les invocations vont sur des hexagones vides adjacents. On pille son hexagone en fin de tour.',
          ],
          ref: 'Reminders — p.76',
        },
        {
          id: 'x4',
          kind: 'check',
          title: 'Éléments, niveau, fin',
          body: [
            'Un élément consommé doit être fort ou faiblissant au début du tour.',
            'Niveau de scénario : moitié du niveau moyen, arrondi au supérieur. Petits objets : moitié du niveau, arrondi au supérieur.',
            'Un scénario ne se termine qu’à la fin d’une manche.',
          ],
          ref: 'Reminders — p.76',
        },
        {
          id: 'x5',
          kind: 'info',
          title: 'La référence rapide',
          body: [
            'La page 84 tient sur une feuille : mise en place, phase de scénario, phase d’avant-poste, fin de scénario, ordre de modification d’attaque, fin de manche, table des niveaux.',
          ],
          crop: { page: 84, x: 0.05, y: 0.03, w: 0.9, h: 0.94 },
          ref: 'Quick Reference — p.84',
        },
      ],
    },

    {
      id: 'debrief',
      title: 'Après cette première partie',
      kind: 'debrief',
      goal: 'Savoir quoi lire ensuite, et ce que ce tutoriel n’a pas enseigné.',
      steps: [
        {
          id: 'd1',
          kind: 'info',
          title: 'Scénario 1, puis la suite du livret',
          body: [
            'Après le scénario 0, enchaînez le scénario 1 sans phase d’avant-poste.',
            'Après le scénario 1, lisez les pages 49 à 68 : la campagne, Frosthaven, la phase d’avant-poste. Le mode Rappel des règles de ce tutoriel les résume.',
          ],
          ref: 'The Adventure Begins — p.49',
        },
        {
          id: 'd2',
          kind: 'info',
          title: 'Ce qui n’a pas été enseigné',
          body: [
            'Le contenu sous autocollants, les enveloppes et les boîtes scellées : la campagne dit quand les ouvrir.',
            'Les améliorations de cartes (page 77, à ne pas lire avant le bâtiment 44), les faveurs, le puzzle book, les donjons aléatoires, les variantes.',
          ],
          ref: 'Variants — p.69 ; Random Dungeons — p.70',
        },
        {
          id: 'd3',
          kind: 'check',
          title: 'Trois pages à garder ouvertes',
          body: [
            'Page 74 : le guide du tour de monstre. Page 76 : les rappels. Page 84 : la référence rapide.',
            'L’index, pages 80 et 81, donne la page de chaque terme.',
          ],
          crop: { page: 84, x: 0.05, y: 0.03, w: 0.9, h: 0.94 },
          ref: 'Index — p.80',
        },
      ],
    },
  ],
}
