/**
 * Nemesis — première partie tutorielle.
 *
 * Source : « Nemesis — Règles du jeu », édition française (traduction
 * Antoine Prono, relecture Funforge), Awaken Realms. Les numéros de page
 * du champ `ref` et des découpes sont ceux imprimés sur le livret.
 *
 * Périmètre : le tutoriel installe une vraie partie et fait jouer les
 * premières manches. Il n'enseigne pas l'intégralité des règles ; ce qui
 * est volontairement laisse de côté est liste dans `scope.skipped` et
 * rappele au joueur dans le dernier chapitre.
 */

import type { Tutorial } from '../engine/types'

export const nemesis: Tutorial = {
  id: 'nemesis',
  title: 'Nemesis',
  tagline:
    'Vous vous réveillez d’hibernation sur un vaisseau infesté. Survivre ne suffit pas : il faut aussi remplir un objectif que personne d’autre ne connaît.',
  contentVersion: '1.0',
  publisher: 'Awaken Realms',
  author: 'Adam Kwapinski',
  players: {
    min: 1,
    max: 5,
    recommended: 3,
    labels: { 1: 'Solo' },
    notes: {
      1: 'Le mode solo a son propre paquet d’objectifs, et les salles contiennent moitié moins d’objets. Le tutoriel le signale au bon moment.',
      2: 'À deux, le sac Intrus est plus clément : 2 jetons Adulte ajoutés au lieu de 5.',
      5: 'À cinq, quatre nacelles de secours et un sac Intrus nettement plus dense.',
    },
  },
  minutes: 90,

  // Alerte orange sur métal froid : la couleur des voyants d'urgence du
  // vaisseau. Sans-serif technique, angles marqués.
  theme: {
    bg: '#0b0e14',
    bg2: '#121722',
    bg3: '#1a2130',
    stroke: '#2a3446',
    strokeSoft: '#202939',
    fg: '#eef2f8',
    fgDim: '#98a4b8',
    fgFaint: '#64708a',
    accent: '#f97316',
    accent2: '#ef4444',
    accentInk: '#180701',
    radius: '18px',
  },

  source: {
    pdf: 'Nemesis - Regles.pdf',
    assetId: 'nemesis',
    // Renseigné après ingestion : écart entre le numéro imprimé et l'index
    // de page dans le fichier. Voir GUIDE_CREATION_TUTO.md.
    pageOffset: 0,
    credit: 'Règles officielles FR — Awaken Realms',
  },

  // Couverture du livret : ce que le joueur reconnaît sur l'écran d'accueil.
  cover: { page: 1, x: 0.03, y: 0.3, w: 0.94, h: 0.32 },

  /*
   * Le tutoriel est écrit d'après les règles françaises ; beaucoup de boîtes
   * sont en anglais. Les termes ci-dessous sont ceux du « Nemesis Rulebook »,
   * dans l'ordre où on les rencontre : le vaisseau, les Intrus, le
   * personnage, les cartes, les marqueurs, les actions, la manche, les
   * blessures, puis les salles.
   */
  vo: {
    language: 'anglais',
    edition: 'Nemesis Rulebook, Awaken Realms',
    terms: [
      // Le vaisseau et le plateau
      { fr: 'plateau de jeu', en: 'Board', note: 'Recto-verso ; le côté standard est le basic side.' },
      { fr: 'salle', en: 'Room' },
      { fr: 'tuile Salle', en: 'Room tile', note: 'Room tiles « 1 » = Basic Rooms, « 2 » = Additional Rooms.' },
      { fr: 'couloir', en: 'Corridor' },
      { fr: 'couloirs techniques', en: 'Technical Corridors' },
      { fr: 'jeton Exploration', en: 'Exploration token' },
      { fr: 'compteur d’objets', en: 'Item Counter' },
      { fr: 'piste temporelle', en: 'Time Track' },
      { fr: 'marqueur Temps', en: 'Time marker' },
      { fr: 'autodestruction', en: 'Self-Destruct Sequence', note: 'La piste est le Self-Destruct Track.' },
      { fr: 'piste Destination', en: 'Destination Track' },
      { fr: 'marqueur Destination', en: 'Destination marker' },
      { fr: 'carte Coordonnées', en: 'Coordinates card' },
      { fr: 'nacelle de secours', en: 'Escape Pod', note: 'Verrouillée = Locked, déverrouillée = Unlocked.' },
      { fr: 'section d’évacuation', en: 'Evacuation Section', note: 'Sections « A » et « B » du plateau.' },
      { fr: 'tuile Moteur', en: 'Engine token', note: 'Opérationnel = Working, endommagé = Damaged.' },

      // Les Intrus
      { fr: 'Intrus', en: 'Intruder' },
      { fr: 'Larve', en: 'Larva', note: 'Pluriel Larvae sur le livret.' },
      { fr: 'Rôdeur', en: 'Creeper' },
      { fr: 'Adulte', en: 'Adult Intruder' },
      { fr: 'Hybride', en: 'Breeder' },
      { fr: 'Reine', en: 'Queen' },
      { fr: 'jeton vierge', en: 'Blank token' },
      { fr: 'sac Intrus', en: 'Intruder bag' },
      { fr: 'plateau Intrus', en: 'Intruder board' },
      { fr: 'jeton Intrus', en: 'Intruder token' },
      { fr: 'symbole d’Intrus', en: 'Intruder Symbol' },
      { fr: 'jeton Œuf', en: 'Intruder Egg token' },
      { fr: 'jeton Carcasse', en: 'Intruder Carcass token' },
      { fr: 'carte Point faible', en: 'Intruder Weakness card' },
      { fr: 'tache de sang', en: '« blood » icon', note: 'Le chiffre en haut à gauche des cartes Attaque d’Intrus.' },
      { fr: 'retraite', en: 'Retreat', note: 'L’icône est une flèche blanche dans la tache de sang.' },
      { fr: 'rencontre', en: 'Encounter' },
      { fr: 'attaque-surprise', en: 'Surprise Attack' },
      { fr: 'carte Attaque d’Intrus', en: 'Intruder Attack card' },
      { fr: 'marqueur Dégâts', en: 'Injury marker', note: 'Injury pour un Intrus, Wound pour un personnage.' },

      // Le personnage
      { fr: 'personnage', en: 'Character' },
      { fr: 'plateau individuel', en: 'Character board' },
      { fr: 'carte Rôle', en: 'Character draft card' },
      { fr: 'inventaire', en: 'Inventory card holder' },
      { fr: 'aide de jeu', en: 'Help card', note: 'Elle porte votre Player Number et se retourne côté Pass.' },
      { fr: 'jeton Premier joueur', en: 'First Player token' },
      { fr: 'carte Objectif', en: 'Objective card' },
      { fr: 'objectif Corporation', en: 'Corporate Objective' },
      { fr: 'objectif personnel', en: 'Personal Objective' },
      { fr: 'cadavre', en: 'Character Corpse' },
      { fr: 'corps lourd', en: 'Heavy Object' },
      { fr: 'arme', en: 'Weapon' },
      { fr: 'munition', en: 'Ammo' },

      // Les cartes
      { fr: 'carte Action', en: 'Action card' },
      { fr: 'carte Contamination', en: 'Contamination card', note: 'Le mot caché à chercher au Scanner est INFECTED.' },
      { fr: 'carte Événement', en: 'Event card' },
      { fr: 'carte Blessure grave', en: 'Serious Wound card' },
      { fr: 'carte Objet', en: 'Item card' },
      { fr: 'objet fabriqué', en: 'Crafted Item' },
      { fr: 'Vêtements', en: 'Clothes' },
      { fr: 'Antidote', en: 'Antidote' },

      // Les marqueurs
      { fr: 'marqueur Bruit', en: 'Noise marker' },
      { fr: 'marqueur Feu', en: 'Fire marker' },
      { fr: 'marqueur Panne', en: 'Malfunction marker' },
      { fr: 'marqueur standard', en: 'Status marker' },
      { fr: 'marqueur Slime', en: 'Slime marker' },
      { fr: 'Signal', en: 'Signal' },
      { fr: 'pion Porte', en: 'Door token' },
      { fr: 'Scanner', en: 'Scanner', note: 'Scanner une carte se dit to Scan.' },

      // Les actions
      { fr: 'déplacement', en: 'Movement' },
      { fr: 'déplacement vigilant', en: 'Careful Movement' },
      { fr: 'tir', en: 'Shoot' },
      { fr: 'corps-à-corps', en: 'Melee Attack' },
      { fr: 'ramasser un corps lourd', en: 'Pick up Heavy Object' },
      { fr: 'échange', en: 'Trade' },
      { fr: 'fabriquer', en: 'Craft Item' },
      { fr: 'fouiller', en: 'Search', note: 'Action de la Storage Room : Search for an Item.' },
      { fr: 'action de salle', en: 'Room Action' },
      { fr: 'fuir', en: 'Escape', note: 'Character Escape dans le livret.' },
      { fr: 'jet de bruit', en: 'Noise roll' },
      { fr: 'dé de bruit', en: 'Noise die', note: 'Résultats : 1 à 4, Silence, Danger.' },
      { fr: 'dé de combat', en: 'Combat die', note: 'Les d6 sont aussi appelés Attack dice.' },

      // La manche
      { fr: 'manche', en: 'turn' },
      { fr: 'tour', en: 'round', note: 'Le tour d’un joueur, deux actions.' },
      { fr: 'phase Joueur', en: 'Player Phase' },
      { fr: 'phase Événement', en: 'Event Phase' },
      { fr: 'passer', en: 'pass' },
      { fr: 'dégâts du feu', en: 'Fire Damage' },

      // Blessures et contamination
      { fr: 'blessure légère', en: 'Light Wound' },
      { fr: 'blessure grave', en: 'Serious Wound' },
      { fr: 'panser', en: 'Dress' },
      { fr: 'soigner', en: 'Heal' },

      // Les salles nommées
      { fr: 'hibernatorium', en: 'Hibernatorium' },
      { fr: 'cockpit', en: 'Cockpit' },
      { fr: 'nid', en: 'Nest' },
      { fr: 'laboratoire', en: 'Laboratory' },
      { fr: 'relais de transmission', en: 'Comms Room' },
      { fr: 'salle des Douches', en: 'Shower Room' },
    ],
  },

  scope: {
    covered: [
      'La mise en place complète, des 20 étapes officielles',
      'La structure d’une manche : phase Joueur puis phase Événement',
      'Payer ses actions en défaussant des cartes',
      'Se déplacer, explorer une salle, résoudre un jeton Exploration',
      'Le jet de bruit et les marqueurs Bruit',
      'Déclencher et résoudre une rencontre, subir une attaque-surprise',
      'Tirer, combattre au corps-à-corps, fuir',
      'Blessures légères et graves, cartes Contamination',
      'Les 5 étapes de la phase Événement et le sac Intrus',
      'Les deux conditions de victoire et le contrôle de fin de partie',
    ],
    skipped: [
      'Le détail des 20 salles et de leurs actions (index p.24-26)',
      'La fabrication d’objets et les objets de quête',
      'La séquence d’autodestruction et les nacelles de secours',
      'Les points faibles et l’analyse au laboratoire',
      'Les modes solo, coopératif, « jouer en tant qu’Intrus » et le plateau alternatif',
    ],
  },

  /* ------------------------------------------------------------ matériel */

  components: [
    {
      id: 'plateau',
      name: 'Plateau de jeu',
      qty: '1 recto-verso',
      note: 'Le vaisseau Nemesis. Le côté standard porte une triple flèche rouge en haut à gauche ; le verso est le plateau alternatif, réservé aux parties suivantes.',
      glyph: 'board',
      tint: '#f97316',
      crop: { page: 2, x: 0.374, y: 0.157, w: 0.252, h: 0.173 },
    },
    {
      id: 'salles1',
      name: 'Tuiles Salle « 1 »',
      qty: '11 tuiles',
      note: 'Les salles de base. Elles sont toutes en jeu à chaque partie : le relais de transmission, le laboratoire et le nid en font partie.',
      glyph: 'tile',
      crop: { page: 2, x: 0.374, y: 0.534, w: 0.252, h: 0.102 },
    },
    {
      id: 'salles2',
      name: 'Tuiles Salle « 2 »',
      qty: '9 tuiles',
      note: 'Les salles supplémentaires. Seules 5 sont en jeu à chaque partie : vous ne savez jamais lesquelles avant de les découvrir.',
      glyph: 'tile',
      crop: { page: 2, x: 0.374, y: 0.664, w: 0.252, h: 0.102 },
    },
    {
      id: 'exploration',
      name: 'Jetons Exploration',
      qty: '20 jetons',
      note: 'Posés face cachée sur chaque tuile Salle. Ils indiquent le nombre d’objets de la salle et un effet spécial déclenché à la première visite.',
      glyph: 'token',
      tint: '#22d3ee',
      crop: { page: 3, x: 0.056, y: 0.704, w: 0.129, h: 0.06 },
    },
    {
      id: 'moteurs',
      name: 'Tuiles Moteur',
      qty: '6 tuiles',
      note: '3 « opérationnel » et 3 « endommagé ». Deux moteurs sur trois doivent fonctionner pour que le vaisseau atteigne sa destination.',
      glyph: 'tile',
      tint: '#34d399',
      crop: { page: 3, x: 0.052, y: 0.531, w: 0.21, h: 0.079 },
    },
    {
      id: 'coordonnees',
      name: 'Cartes Coordonnées',
      qty: '8 cartes',
      note: 'Une seule est en jeu, face cachée dans le cockpit. Elle est révélée en fin de partie et décide de la destination réelle du vaisseau.',
      glyph: 'card',
      crop: { page: 3, x: 0.569, y: 0.267, w: 0.172, h: 0.065 },
    },
    {
      id: 'nacelles',
      name: 'Nacelles de secours',
      qty: '4 jetons',
      note: 'Verrouillées au début. Elles se déverrouillent automatiquement à la première mort d’un personnage.',
      glyph: 'token',
      tint: '#34d399',
      crop: { page: 3, x: 0.056, y: 0.633, w: 0.129, h: 0.058 },
    },
    {
      id: 'plateau-intrus',
      name: 'Plateau Intrus',
      qty: '1 plateau',
      note: 'Accueille les 5 œufs du nid et les 3 cartes Point faible. Il porte aussi la légende des symboles d’Intrus.',
      glyph: 'board',
      tint: '#ef4444',
      crop: { page: 2, x: 0.422, y: 0.794, w: 0.135, h: 0.086 },
    },
    {
      id: 'sac',
      name: 'Sac Intrus',
      qty: '1 sac',
      note: 'Contient les jetons Intrus. On y pioche à chaque rencontre et à la fin de chaque manche : c’est le moteur de la menace.',
      glyph: 'bag',
      tint: '#ef4444',
      crop: { page: 2, x: 0.566, y: 0.792, w: 0.068, h: 0.067 },
    },
    {
      id: 'jetons-intrus',
      name: 'Jetons Intrus',
      qty: '27 jetons',
      note: '8 Larves, 12 Adultes, 3 Rôdeurs, 2 Hybrides, 1 Reine, 1 vierge. Le recto donne le type, le verso un chiffre utilisé pour l’attaque-surprise.',
      glyph: 'token',
      tint: '#ef4444',
      crop: { page: 3, x: 0.199, y: 0.702, w: 0.129, h: 0.06 },
    },
    {
      id: 'figurines',
      name: 'Figurines d’Intrus',
      qty: '20 figurines',
      note: '6 Larves, 8 Adultes, 3 Rôdeurs, 2 Hybrides, 1 Reine. Seuls 8 Adultes existent : au-delà, les Adultes hors combat sont retirés du plateau.',
      glyph: 'figure',
      tint: '#ef4444',
      crop: { page: 2, x: 0.668, y: 0.456, w: 0.28, h: 0.134 },
    },
    {
      id: 'oeufs',
      name: 'Jetons Œuf d’Intrus',
      qty: '8 jetons',
      note: '5 sont placés sur le plateau Intrus : ce sont les œufs du nid. Un œuf est un corps lourd, il occupe une main.',
      glyph: 'egg',
      tint: '#84cc16',
      crop: { page: 3, x: 0.207, y: 0.633, w: 0.114, h: 0.055 },
    },
    {
      id: 'carcasses',
      name: 'Jetons Carcasse d’Intrus',
      qty: '8 jetons',
      note: 'Remplacent une figurine d’Intrus tuée. C’est un corps, analysable au laboratoire.',
      glyph: 'token',
      crop: { page: 3, x: 0.199, y: 0.812, w: 0.129, h: 0.055 },
    },
    {
      id: 'cadavre-bleu',
      name: 'Jeton Cadavre bleu',
      qty: '1 jeton',
      note: 'Le camarade retrouvé mort dans l’hibernatorium au début de la partie. C’est un corps comme un autre.',
      glyph: 'token',
      tint: '#38bdf8',
      crop: { page: 3, x: 0.056, y: 0.779, w: 0.129, h: 0.057 },
    },
    {
      id: 'cadavres-rouges',
      name: 'Jetons Cadavre rouge',
      qty: '4 jetons',
      note: 'Marquent l’endroit où un personnage joueur est mort.',
      glyph: 'token',
      tint: '#ef4444',
      crop: { page: 3, x: 0.056, y: 0.779, w: 0.129, h: 0.057 },
    },
    {
      id: 'plateaux-perso',
      name: 'Plateaux individuels',
      qty: '6 plateaux',
      note: 'Un par personnage. Ils portent la piste de blessures, les cases Slime et Signal, les deux mains et l’emplacement de défausse.',
      glyph: 'board',
      crop: { page: 2, x: 0.41, y: 0.358, w: 0.179, h: 0.149 },
    },
    {
      id: 'roles',
      name: 'Cartes Rôle',
      qty: '6 cartes',
      note: 'Servent uniquement à répartir les personnages au début de la partie.',
      glyph: 'card',
      crop: { page: 3, x: 0.589, y: 0.853, w: 0.131, h: 0.063 },
    },
    {
      id: 'actions',
      name: 'Cartes Action',
      qty: '60 cartes',
      note: '10 par personnage. Elles servent à la fois de main de jeu et de monnaie : on les défausse pour payer le coût des actions.',
      glyph: 'card',
      tint: '#38bdf8',
      crop: { page: 3, x: 0.363, y: 0.18, w: 0.175, h: 0.082 },
    },
    {
      id: 'contamination',
      name: 'Cartes Contamination',
      qty: '27 cartes',
      note: 'Même dos que les cartes Action mais paquet séparé. Elles encombrent la main et ne peuvent jamais payer une action.',
      glyph: 'card',
      tint: '#a78bfa',
      crop: { page: 3, x: 0.363, y: 0.383, w: 0.175, h: 0.079 },
    },
    {
      id: 'objectifs',
      name: 'Cartes Objectif',
      qty: '18 cartes',
      note: '9 Corporation et 9 Personnel. Chaque joueur en reçoit une de chaque et devra en abandonner une à la première rencontre.',
      glyph: 'card',
      tint: '#fbbf24',
      crop: { page: 3, x: 0.363, y: 0.276, w: 0.175, h: 0.082 },
    },
    {
      id: 'attaques',
      name: 'Cartes Attaque d’Intrus',
      qty: '20 cartes',
      note: 'Servent à deux choses : résoudre les attaques d’Intrus, et vérifier via la tache de sang si un Intrus blessé meurt.',
      glyph: 'card',
      tint: '#ef4444',
      crop: { page: 3, x: 0.363, y: 0.509, w: 0.175, h: 0.081 },
    },
    {
      id: 'evenements',
      name: 'Cartes Événement',
      qty: '20 cartes',
      note: 'Une par manche. Elles déplacent les Intrus par un couloir numéroté, puis appliquent un effet.',
      glyph: 'card',
      tint: '#f472b6',
      crop: { page: 3, x: 0.363, y: 0.694, w: 0.175, h: 0.082 },
    },
    {
      id: 'blessures',
      name: 'Cartes Blessure grave',
      qty: '16 cartes',
      note: 'Chaque blessure grave a un effet permanent. Trois blessures graves, et la moindre blessure suivante tue.',
      glyph: 'card',
      tint: '#fb7185',
      crop: { page: 3, x: 0.363, y: 0.604, w: 0.175, h: 0.076 },
    },
    {
      id: 'objets',
      name: 'Cartes Objet',
      qty: '30 rouges, 30 jaunes, 30 vertes, 12 bleues',
      note: 'Militaire, technique, médical, et les objets fabriqués. La couleur de la salle décide de la pioche que vous pouvez fouiller.',
      glyph: 'card',
      tint: '#34d399',
      crop: { page: 3, x: 0.579, y: 0.345, w: 0.152, h: 0.074 },
    },
    {
      id: 'inventaires',
      name: 'Porte-cartes (inventaires)',
      qty: '5 porte-cartes',
      note: 'Gardent vos objets secrets : les autres voient la couleur du dos, pas la carte.',
      glyph: 'card',
      crop: { page: 2, x: 0.672, y: 0.83, w: 0.138, h: 0.067 },
    },
    {
      id: 'de-bruit',
      name: 'Dés de bruit',
      qty: '2 d10',
      note: 'Le dé du jet de bruit. Ses résultats : un numéro de couloir de 1 à 4, Silence, ou Danger.',
      glyph: 'die',
      tint: '#22d3ee',
      crop: { page: 2, x: 0.558, y: 0.89, w: 0.084, h: 0.04 },
    },
    {
      id: 'de-combat',
      name: 'Dés d’attaque',
      qty: '2 d6',
      note: 'Le dé de combat. Ses faces disent quels types d’Intrus vous pouvez blesser, et combien.',
      glyph: 'die',
      tint: '#ef4444',
      crop: { page: 2, x: 0.558, y: 0.89, w: 0.084, h: 0.04 },
    },
    {
      id: 'marqueurs-bruit',
      name: 'Marqueurs Bruit',
      qty: '30 marqueurs',
      note: 'Posés dans les couloirs. Un deuxième marqueur sur le même couloir déclenche une rencontre au lieu d’être posé.',
      glyph: 'marker',
      tint: '#22d3ee',
      crop: { page: 3, x: 0.056, y: 0.375, w: 0.129, h: 0.057 },
    },
    {
      id: 'marqueurs-feu',
      name: 'Marqueurs Feu',
      qty: '8 marqueurs',
      note: 'Blessent qui finit son tour dans la salle, blessent les Intrus, et font exploser le vaisseau s’il faut en poser un 9e.',
      glyph: 'fire',
      tint: '#f97316',
      crop: { page: 3, x: 0.199, y: 0.377, w: 0.129, h: 0.057 },
    },
    {
      id: 'marqueurs-panne',
      name: 'Marqueurs Panne',
      qty: '8 marqueurs',
      note: 'Neutralisent l’action de la salle. Comme le feu, un 9e marqueur à poser fait exploser le vaisseau.',
      glyph: 'marker',
      tint: '#fbbf24',
      crop: { page: 3, x: 0.199, y: 0.445, w: 0.129, h: 0.055 },
    },
    {
      id: 'marqueurs-std',
      name: 'Marqueurs standard',
      qty: '18 marqueurs',
      note: 'Polyvalents : blessures légères, slime, signal, temps, destination, autodestruction.',
      glyph: 'marker',
      crop: { page: 3, x: 0.056, y: 0.309, w: 0.129, h: 0.054 },
    },
    {
      id: 'munitions',
      name: 'Marqueurs Munition / Dégâts',
      qty: '50 marqueurs',
      note: 'Munitions sur vos armes, marqueurs de dégâts sur les figurines d’Intrus.',
      glyph: 'marker',
      crop: { page: 3, x: 0.199, y: 0.309, w: 0.129, h: 0.054 },
    },
    {
      id: 'portes',
      name: 'Pions Porte',
      qty: '12 pions',
      note: 'Debout = porte fermée, couché = porte détruite. Toutes les portes sont ouvertes au début de la partie.',
      glyph: 'door',
      crop: { page: 3, x: 0.056, y: 0.448, w: 0.129, h: 0.062 },
    },
    {
      id: 'scanner',
      name: 'Scanner',
      qty: '1 filtre',
      note: 'Le filtre rouge révèle si une carte Contamination porte le mot « infectée ».',
      glyph: 'token',
      tint: '#a78bfa',
      crop: { page: 2, x: 0.345, y: 0.775, w: 0.087, h: 0.11 },
    },
    {
      id: 'premier-joueur',
      name: 'Jeton Premier joueur',
      qty: '1 jeton',
      note: 'Passe au voisin de gauche au début de chaque manche, sauf la première.',
      glyph: 'token',
      tint: '#fbbf24',
      crop: { page: 3, x: 0.097, y: 0.867, w: 0.041, h: 0.04 },
    },
    {
      id: 'aides',
      name: 'Aides de jeu',
      qty: '5 cartes',
      note: 'Elles portent votre numéro de joueur et se retournent côté « passé » quand vous passez.',
      glyph: 'card',
      crop: { page: 3, x: 0.371, y: 0.789, w: 0.161, h: 0.084 },
    },
  ],

  /* ------------------------------------------------------------ chapitres */

  chapters: [
    {
      id: 'brief',
      title: 'Briefing',
      kind: 'brief',
      goal: 'Savoir ce que vous allez apprendre et ce qu’il faut sortir de la boîte.',
      steps: [
        {
          id: 'brief-1',
          kind: 'info',
          title: 'Posez la tablette à côté du plateau',
          body: [
            'Vous allez installer le jeu étape par étape, puis jouer vos premières manches en suivant l’écran.',
            'Chaque étape vous dit une seule chose à faire. Vous validez quand c’est fait sur la table.',
          ],
          tip: 'Le chronomètre en haut à droite tourne pendant la partie. Vous pouvez le mettre en pause à tout moment ; il reprend même si vous fermez l’application.',
        },
        {
          id: 'brief-2',
          kind: 'info',
          title: 'Nemesis est semi-coopératif',
          body: [
            'Vous survivez ensemble, mais chacun a un objectif secret que les autres ignorent.',
            'Plusieurs joueurs peuvent gagner. Aucun ne le peut sans avoir survécu.',
            'Certains objectifs demandent qu’un autre joueur ne survive pas.',
          ],
          warn: 'Les personnages ne peuvent jamais s’attaquer directement : des implants anti-agression l’empêchent. Les dégâts indirects, eux, sont permis.',
          components: ['objectifs'],
          ref: 'p.4 et p.23',
        },
        {
          id: 'brief-3',
          kind: 'check',
          title: 'Sortez la boîte et faites de la place',
          body: [
            'Il faut de la place autour du plateau : plateau Intrus, 4 pioches d’objets, 4 pioches communes et leurs défausses.',
            'Chaque joueur a besoin de son plateau individuel, sa pioche et sa défausse à portée de main.',
          ],
          components: ['plateau', 'plateau-intrus'],
        },
      ],
    },

    {
      id: 'setup-board',
      title: 'Mise en place : le plateau',
      kind: 'setup',
      modes: ['tuto', 'setup'],
      goal: 'Les 13 premières étapes officielles : le vaisseau est prêt, les Intrus aussi.',
      steps: [
        {
          id: 's1',
          kind: 'place',
          title: 'Posez le plateau, côté standard',
          body: ['Le côté standard porte une triple flèche rouge en haut à gauche.'],
          warn: 'Le verso est le plateau alternatif : plus difficile, conçu pour le jeu en campagne. Gardez-le pour plus tard.',
          components: ['plateau'],
          ref: 'Mise en place, étape 1 — p.6',
        },
        {
          id: 's2',
          kind: 'shuffle',
          title: 'Placez les tuiles Salle « 2 »',
          body: [
            'Mélangez les 9 tuiles « 2 » sans les regarder.',
            'Posez-les face cachée au hasard sur les emplacements marqués « 2 ».',
            'Remettez les tuiles en trop dans la boîte, sans les regarder.',
          ],
          warn: 'Il y a plus de tuiles que d’emplacements : 5 salles supplémentaires sur 9 seront en jeu. C’est voulu, vous ne devez pas savoir lesquelles.',
          components: ['salles2'],
          ref: 'Mise en place, étape 2 — p.6',
        },
        {
          id: 's3',
          kind: 'shuffle',
          title: 'Placez les tuiles Salle « 1 »',
          body: [
            'Même procédure, sur les emplacements marqués « 1 ».',
            'Les 11 salles de base sont toutes en jeu.',
          ],
          tip: 'Le relais de transmission, le laboratoire et le nid sont des salles « 1 » : plusieurs objectifs en dépendent, ils sont donc toujours présents.',
          components: ['salles1'],
          ref: 'Mise en place, étape 3 — p.6',
        },
        {
          id: 's4',
          kind: 'shuffle',
          title: 'Posez un jeton Exploration sur chaque salle',
          body: [
            'Mélangez les jetons Exploration sans les regarder.',
            'Posez-en un, face cachée, sur chaque tuile Salle.',
            'Les jetons en trop retournent dans la boîte.',
          ],
          components: ['exploration'],
          ref: 'Mise en place, étape 4 — p.6',
        },
        {
          id: 's5',
          kind: 'place',
          title: 'Placez une carte Coordonnées dans le cockpit',
          body: [
            'Prenez une carte Coordonnées au hasard, face cachée, sur son emplacement du cockpit.',
            'Les autres retournent dans la boîte.',
          ],
          components: ['coordonnees'],
          ref: 'Mise en place, étape 5 — p.6',
        },
        {
          id: 's6',
          kind: 'place',
          title: 'Marqueur Destination sur la case « B »',
          body: ['Un marqueur standard sur la case « B » de la piste de destination.'],
          components: ['marqueurs-std'],
          ref: 'Mise en place, étape 6 — p.6',
        },
        {
          id: 's7-2',
          kind: 'place',
          title: 'Placez 2 nacelles de secours',
          only: [1, 2],
          body: [
            'Tirez 2 nacelles au hasard.',
            'La plus petit numéro en section A, l’autre en section B.',
            'Toutes deux face « verrouillé » visible. Les autres restent dans la boîte.',
          ],
          components: ['nacelles'],
          ref: 'Mise en place, étape 7 — p.6',
        },
        {
          id: 's7-3',
          kind: 'place',
          title: 'Placez 3 nacelles de secours',
          only: [3, 4],
          body: [
            'Tirez 3 nacelles au hasard.',
            'La plus petit numéro en section A, la suivante en section B, la dernière ensuite.',
            'Toutes face « verrouillé » visible. La quatrième reste dans la boîte.',
          ],
          components: ['nacelles'],
          ref: 'Mise en place, étape 7 — p.6',
        },
        {
          id: 's7-4',
          kind: 'place',
          title: 'Placez les 4 nacelles de secours',
          only: [5],
          body: [
            'À cinq joueurs, les 4 nacelles sont en jeu.',
            'Placez-les par numéro croissant : la plus petite en section A, puis la suivante, et ainsi de suite.',
            'Toutes face « verrouillé » visible.',
          ],
          components: ['nacelles'],
          ref: 'Mise en place, étape 7 — p.6',
        },
        {
          id: 's8',
          kind: 'shuffle',
          title: 'Empilez les tuiles Moteur',
          body: [
            'Prenez les deux tuiles marquées « 1 » : une endommagée, une opérationnelle.',
            'Mélangez-les face cachée et empilez-les sur l’emplacement du moteur 1.',
            'Recommencez pour les moteurs 2 et 3.',
          ],
          warn: 'Personne ne doit voir les tuiles pendant le mélange. L’état réel des moteurs doit rester inconnu de tous jusqu’à la fin de la partie.',
          components: ['moteurs'],
          ref: 'Mise en place, étape 8 — p.6',
        },
        {
          id: 's9',
          kind: 'place',
          title: 'Préparez le plateau Intrus',
          body: [
            'Posez le plateau Intrus à côté du plateau de jeu.',
            'Placez 5 jetons Œuf sur leurs emplacements : ce sont les œufs du nid.',
            'Ajoutez 3 cartes Point faible prises au hasard, face cachée.',
          ],
          tip: 'Les points faibles se découvrent en apportant un corps au laboratoire. Face cachée, vous ne savez pas encore lesquels vous obtiendrez.',
          components: ['plateau-intrus', 'oeufs'],
          ref: 'Mise en place, étape 9 — p.6',
        },
        {
          id: 's10',
          kind: 'take',
          title: 'Remplissez le sac Intrus',
          body: [
            'Dans le sac : 1 vierge, 4 Larves, 1 Rôdeur, 1 Reine, 3 Adultes.',
            'Ajoutez ensuite 1 jeton Adulte supplémentaire par joueur.',
            'C’est ce dernier ajout qui rend le vaisseau plus dangereux à mesure que vous êtes nombreux.',
            'Le reste des jetons Intrus, et les jetons Carcasse, restent à portée de main à côté du plateau.',
          ],
          components: ['sac', 'jetons-intrus', 'carcasses'],
          ref: 'Mise en place, étape 10 — p.6',
        },
        {
          id: 's11',
          kind: 'shuffle',
          title: 'Mélangez et posez les paquets de cartes',
          body: [
            'Mélangés séparément : 3 paquets Objet (un par couleur), Événement, Attaque d’Intrus, Contamination, Blessure grave.',
            'Posez le paquet Objets fabriqués (bleu) à côté des autres objets, et le Scanner près du paquet Contamination.',
            'Laissez un espace de défausse libre à côté des objets, des événements, des attaques d’Intrus et des blessures graves.',
          ],
          warn: 'Les cartes Action d’Intrus et les objectifs Solo/Coop ne servent pas dans le jeu de base : laissez-les dans la boîte.',
          components: ['objets', 'evenements', 'attaques', 'contamination', 'blessures', 'scanner'],
          ref: 'Mise en place, étape 11 — p.6',
        },
        {
          id: 's12',
          kind: 'place',
          title: 'Sortez les marqueurs et les dés',
          body: [
            'À portée de tous : marqueurs Feu, Panne, Bruit, Munition/Dégâts et standard.',
            'Ajoutez les pions Porte, les jetons Cadavre rouges, les 2 dés de combat, les 2 dés de bruit et le jeton Premier joueur.',
          ],
          components: ['marqueurs-feu', 'marqueurs-panne', 'marqueurs-bruit', 'munitions', 'marqueurs-std', 'portes', 'de-combat', 'de-bruit'],
          ref: 'Mise en place, étape 12 — p.6',
        },
        {
          id: 's13',
          kind: 'place',
          title: 'Marqueur Temps sur la case verte',
          body: ['Un marqueur standard sur la case verte de la piste temporelle.'],
          tip: 'Ce marqueur avance d’un cran à chaque manche. Quand il atteint une case bleue, les compartiments d’hibernation s’ouvrent.',
          components: ['marqueurs-std'],
          ref: 'Mise en place, étape 13 — p.6',
        },
      ],
    },

    {
      id: 'setup-crew',
      title: 'Mise en place : l’équipage',
      kind: 'setup',
      modes: ['tuto', 'setup'],
      goal: 'Les étapes 14 à 20 : chaque joueur a son personnage, son objectif secret et son matériel.',
      steps: [
        {
          id: 's14',
          kind: 'take',
          title: 'Distribuez les aides de jeu',
          body: [
            'Autant d’aides que de joueurs, distribuées au hasard.',
            'À 3 joueurs, n’utilisez que les cartes 1 à 3 ; à 4 joueurs, les cartes 1 à 4, etc.',
            'Le numéro inscrit dessus est votre numéro de joueur.',
          ],
          components: ['aides'],
          ref: 'Mise en place, étape 14 — p.8',
        },
        {
          id: 's15',
          kind: 'take',
          title: 'Prenez votre inventaire',
          body: ['Chaque joueur prend le porte-cartes qui porte son numéro.'],
          tip: 'Les autres verront la couleur du dos de vos objets, jamais leur nature. Ils peuvent deviner que vous avez du matériel militaire, pas lequel.',
          components: ['inventaires'],
          ref: 'Mise en place, étape 15 — p.8',
        },
        {
          id: 's16-solo',
          kind: 'take',
          title: 'Piochez 2 objectifs Solo',
          only: [1],
          body: [
            'En solo, on utilise le paquet Objectif Solo/Coop, pas les paquets Corporation et Personnel.',
            'Piochez-en 2 et gardez-les face cachée devant vous.',
          ],
          warn: 'Vous choisirez lequel garder au moment de votre première rencontre avec un Intrus, comme en partie normale.',
          components: ['objectifs'],
          ref: 'Modes de jeu, mode solo — p.27',
        },
        {
          id: 's16',
          kind: 'take',
          title: 'Distribuez les objectifs',
          only: [2, 3, 4, 5],
          body: [
            'Retirez des deux paquets tous les objectifs qui impliquent plus de joueurs que vous n’êtes.',
            'Mélangez séparément Corporation et Personnel.',
            'Donnez à chaque joueur 1 objectif Corporation et 1 objectif Personnel.',
          ],
          warn: 'Les objectifs ne se montrent jamais. Vous en garderez un seul, au moment de la première rencontre avec un Intrus.',
          components: ['objectifs'],
          ref: 'Mise en place, étape 16 — p.8',
        },
        {
          id: 's17',
          kind: 'take',
          title: 'Choisissez les personnages',
          body: [
            'Mélangez les cartes Rôle.',
            'Le joueur 1 pioche 2 cartes Rôle au hasard, les révèle, en garde une et remet l’autre dans le paquet.',
            'Puis le joueur 2, et ainsi de suite. Les cartes restantes retournent dans la boîte.',
          ],
          tip: 'Vous avez reçu votre objectif avant votre personnage : choisissez le personnage le plus à même de le remplir.',
          components: ['roles'],
          ref: 'Mise en place, étape 17 — p.8',
        },
        {
          id: 's18',
          kind: 'take',
          title: 'Installez votre personnage',
          body: [
            'Prenez votre plateau individuel.',
            'Posez votre figurine dans l’hibernatorium, sur un socle coloré.',
            'Mélangez vos 10 cartes Action et posez la pioche face cachée à gauche de votre plateau.',
            'Placez votre arme de départ sur une main, avec ses marqueurs Munition.',
            'Posez vos 2 objets de quête à l’horizontale à côté du plateau : ils sont inactifs pour l’instant.',
            'Laissez libre l’emplacement de défausse.',
          ],
          components: ['plateaux-perso', 'actions', 'munitions'],
          ref: 'Mise en place, étape 18 — p.8',
        },
        {
          id: 's19',
          kind: 'take',
          title: 'Le joueur 1 prend le jeton Premier joueur',
          only: [2, 3, 4, 5],
          components: ['premier-joueur'],
          ref: 'Mise en place, étape 19 — p.8',
        },
        {
          id: 's20',
          kind: 'place',
          title: 'Posez le cadavre bleu dans l’hibernatorium',
          body: [
            'Il représente le camarade retrouvé mort dans une mare de sang.',
            'Traitez-le comme un cadavre de personnage, donc comme un corps.',
          ],
          components: ['cadavre-bleu'],
          ref: 'Mise en place, étape 20 — p.9',
        },
        {
          id: 's-check',
          kind: 'check',
          title: 'Vérifiez avant de commencer',
          body: [
            'Toutes les tuiles Salle sont face cachée, avec un jeton Exploration dessus.',
            'Les 3 piles de moteurs sont en place, personne n’en connaît l’état.',
            'Chaque joueur a : un plateau, une figurine dans l’hibernatorium, une pioche mélangée, une arme chargée, 2 objets de quête, 2 objectifs secrets.',
            'Le marqueur Temps est sur la case verte, le marqueur Destination sur « B ».',
          ],
          tip: 'Vous n’avez pas encore pioché de cartes : la première pioche fait partie de la première manche.',
        },
      ],
    },

    {
      id: 'turn',
      title: 'Comprendre le tour',
      kind: 'play',
      goal: 'Savoir de quoi une manche est faite et comment payer ce que vous faites.',
      steps: [
        {
          id: 't1',
          kind: 'info',
          title: 'Une manche, deux phases',
          body: [
            'Phase Joueur : tout le monde joue, tour par tour, jusqu’à ce que tous aient passé.',
            'Phase Événement : le vaisseau et les Intrus réagissent.',
            'On enchaîne les manches jusqu’à une condition de fin de partie.',
          ],
          ref: 'Comment jouer — p.10',
        },
        {
          id: 't2',
          kind: 'action',
          title: 'Piochez 5 cartes Action chacun',
          body: [
            'Début de phase Joueur : chacun complète sa main à 5 cartes.',
            'Pioche vide ? Mélangez votre défausse pour former une nouvelle pioche, puis piochez.',
          ],
          warn: 'À la première manche seulement, on ne passe pas le jeton Premier joueur. À partir de la deuxième, il va au voisin de gauche.',
          components: ['actions', 'premier-joueur'],
          ref: 'Phase Joueur, étapes 1 et 2 — p.10',
        },
        {
          id: 't3',
          kind: 'info',
          title: 'Votre tour, c’est 2 actions',
          body: [
            'En commençant par le premier joueur, dans le sens horaire, chacun joue 2 actions.',
            'Quand tout le monde a joué, un nouveau tour commence : encore 2 actions.',
            'Ça continue jusqu’à ce que tous les joueurs aient passé.',
          ],
          tip: 'Passer est définitif pour la manche. En passant, vous pouvez défausser autant de cartes de votre main que vous voulez, et vous retournez votre aide de jeu côté « passé ».',
          components: ['aides'],
          ref: 'Phase Joueur, étape 3 — p.10',
        },
        {
          id: 't4',
          kind: 'info',
          title: 'Payer une action, c’est défausser des cartes',
          body: [
            'Chaque action affiche une icône avec un chiffre : c’est le nombre de cartes à défausser de votre main.',
            'Action de base : 1 carte. Déplacement vigilant : 2 cartes. Action de salle : 2 cartes.',
            'Pour jouer une carte Action, vous la défaussez ELLE, plus le nombre de cartes indiqué dessus.',
          ],
          widget: {
            kind: 'counter',
            title: 'Votre main en début de manche',
            min: 0,
            max: 6,
            start: 5,
            unit: 'cartes',
          },
          tip: 'Vos cartes sont à la fois vos capacités et votre énergie. Une main pleine est aussi une protection : c’est elle qui vous évite les attaques-surprises.',
          components: ['actions'],
          ref: 'Actions — p.12 et résumé p.28',
        },
        {
          id: 't5',
          kind: 'info',
          title: 'Les cartes Contamination ne paient rien',
          body: [
            'Elles arrivent dans votre défausse, remontent dans votre main, et l’encombrent.',
            'Elles ne donnent aucune action et ne peuvent jamais payer un coût.',
            'Vous pouvez les défausser quand vous passez.',
          ],
          warn: 'Elles comptent en revanche dans le nombre de cartes en main lors d’une rencontre. Une main pleine de Contamination vous protège quand même de l’attaque-surprise.',
          components: ['contamination'],
          ref: 'Cartes Contamination — p.20',
        },
        {
          id: 't6',
          crop: { page: 13, x: 0.356, y: 0.568, w: 0.289, h: 0.361 },
          kind: 'info',
          title: 'Quatre familles d’actions',
          body: [
            'Actions de base : déplacement, déplacement vigilant, tir, corps-à-corps, ramasser un corps lourd, échanger, fabriquer.',
            'Cartes Action : les capacités propres à votre personnage.',
            'Cartes Objet : ce que permet l’objet, décrit sur sa carte.',
            'Actions de salle : ce que permet la pièce où vous vous trouvez.',
          ],
          warn: 'En combat, les seules actions de base autorisées sont : déplacement (donc fuite), tir et corps-à-corps.',
          ref: 'Actions — p.12-13',
        },
      ],
    },

    {
      id: 'explore',
      title: 'Explorer',
      kind: 'play',
      goal: 'Faire votre premier déplacement et comprendre la boucle exploration / bruit.',
      steps: [
        {
          id: 'e1',
          kind: 'action',
          title: 'Premier joueur : déplacez-vous',
          body: [
            'Défaussez 1 carte Action et déplacez votre figurine vers une salle adjacente.',
            'Deux salles sont adjacentes si un couloir les relie directement.',
            'Les personnages n’existent que dans les salles : on ne s’arrête jamais dans un couloir.',
          ],
          components: ['actions'],
          ref: 'Déplacement — p.14',
        },
        {
          id: 'e2',
          crop: { page: 16, x: 0.048, y: 0.155, w: 0.289, h: 0.684 },
          kind: 'action',
          title: 'Révélez la salle et son jeton',
          body: [
            'La salle était face cachée : retournez la tuile.',
            'Révélez ensuite le jeton Exploration qui était dessus.',
          ],
          warn: 'Les salles spéciales — hibernatorium, cockpit, moteurs — sont considérées comme déjà explorées. On n’y révèle rien.',
          components: ['exploration'],
          ref: 'Déplacement — p.14',
        },
        {
          id: 'e3-solo',
          kind: 'action',
          title: 'Réglez le compteur d’objets, moitié moins',
          only: [1],
          body: [
            'Le jeton porte un chiffre. En solo, la salle contient moitié moins d’objets, arrondi au supérieur.',
            'Jeton marqué 1 ou 2 : réglez le compteur sur 1.',
            'Jeton marqué 3 ou 4 : réglez le compteur sur 2.',
            'Faites pivoter la tuile Salle pour amener ce chiffre en face de la flèche rouge.',
          ],
          warn: 'C’est la seule règle de mise en place qui change en cours de partie en solo. Elle s’applique à chaque salle que vous découvrez.',
          components: ['salles1', 'exploration'],
          ref: 'Modes de jeu, mode solo — p.27',
        },
        {
          id: 'e3',
          kind: 'action',
          title: 'Réglez le compteur d’objets',
          only: [2, 3, 4, 5],
          body: [
            'Le jeton porte un chiffre : c’est le nombre d’objets que la salle contient.',
            'Faites pivoter la tuile Salle pour amener ce chiffre en face de la flèche rouge.',
          ],
          tip: 'Exceptions : ni le nid ni la salle de slime n’ont de compteur d’objets. On n’y fouille pas.',
          components: ['salles1', 'exploration'],
          ref: 'Jetons Exploration — p.14',
        },
        {
          id: 'e4',
          kind: 'info',
          title: 'Résolvez l’effet du jeton',
          body: [
            'Silence : rien ne se passe, et pas de jet de bruit pour ce déplacement.',
            'Danger : pas de jet de bruit, mais tout Intrus d’une salle adjacente hors combat vient ici.',
            'Slime : posez un marqueur standard sur la case Slime de votre plateau.',
            'Feu : posez un marqueur Feu dans cette salle.',
            'Panne : posez un marqueur Panne dans cette salle.',
            'Porte : posez un pion Porte dans le couloir que vous venez d’emprunter.',
          ],
          warn: 'Le jeton est retiré du jeu après résolution : chaque salle ne se révèle qu’une fois, au premier visiteur.',
          components: ['exploration', 'marqueurs-feu', 'marqueurs-panne', 'portes'],
          ref: 'Jetons Exploration — p.14-15',
        },
        {
          id: 'e5',
          kind: 'action',
          title: 'Lancez le dé de bruit',
          body: [
            'Vous venez d’entrer dans une salle vide : résolvez un jet de bruit.',
            'Lancez le dé sur la tablette pour voir ce que chaque résultat signifie, puis lancez le vrai dé.',
          ],
          widget: {
            kind: 'roller',
            title: 'Jet de bruit',
            cta: 'Lancer le dé de bruit',
            faces: [
              { label: '1', effect: 'Posez un marqueur Bruit dans le couloir n° 1 relié à cette salle.', tint: '#22d3ee' },
              { label: '2', effect: 'Posez un marqueur Bruit dans le couloir n° 2 relié à cette salle.', tint: '#22d3ee' },
              { label: '3', effect: 'Posez un marqueur Bruit dans le couloir n° 3 relié à cette salle.', tint: '#22d3ee' },
              { label: '4', effect: 'Posez un marqueur Bruit dans le couloir n° 4 relié à cette salle.', tint: '#22d3ee' },
              { label: 'Silence', effect: 'Rien ne se passe. Aucun marqueur Bruit n’est posé.', tint: '#34d399' },
              { label: 'Danger', effect: 'Tout Intrus d’une salle adjacente, hors combat, vient dans cette salle. S’il n’y en a aucun, posez un marqueur Bruit dans chaque couloir relié à la salle qui n’en a pas déjà un.', tint: '#ef4444' },
            ],
          },
          warn: 'Un couloir ne porte jamais deux marqueurs Bruit. Si vous devez en poser un là où il y en a déjà un, vous résolvez une rencontre à la place.',
          tip: 'Le simulateur tire au hasard parmi les résultats possibles ; il ne reproduit pas la répartition exacte des faces du d10. Lancez toujours le vrai dé.',
          components: ['de-bruit', 'marqueurs-bruit'],
          ref: 'Jet de bruit — p.15',
        },
        {
          id: 'e6',
          crop: { page: 14, x: 0.356, y: 0.264, w: 0.289, h: 0.586 },
          kind: 'info',
          title: 'Quand ne PAS lancer le dé',
          body: [
            'Il y a déjà quelqu’un dans la salle où vous entrez, personnage ou Intrus : pas de jet de bruit.',
            'Le jeton Exploration a donné Silence ou Danger : pas de jet de bruit non plus.',
          ],
          warn: 'Entrer dans une salle occupée par un Intrus ne déclenche pas de rencontre : vous êtes simplement en combat immédiatement.',
          ref: 'Déplacement — p.14 et p.18',
        },
        {
          id: 'e7',
          kind: 'info',
          title: 'Le slime change tout',
          body: [
            'Tant que vous avez un marqueur Slime, chaque résultat « Silence » se lit « Danger ».',
            'Ça vaut pour les jets de bruit comme pour les jetons Exploration.',
            'On ne peut avoir qu’un seul marqueur Slime à la fois.',
          ],
          tip: 'On s’en débarrasse avec l’action de salle des Douches ou la carte objet Vêtements.',
          components: ['marqueurs-std'],
          ref: 'Marqueur Slime — p.17',
        },
        {
          id: 'e8',
          kind: 'info',
          title: 'Le déplacement vigilant',
          body: [
            'Il coûte 2 cartes au lieu d’1.',
            'Au lieu de lancer le dé, vous choisissez vous-même le couloir où poser le marqueur Bruit.',
            'Impossible si tous les couloirs reliés à la salle d’arrivée ont déjà un marqueur, ou si vous êtes en combat.',
          ],
          tip: 'C’est la façon la plus sûre d’explorer : vous échangez une carte contre la certitude de ne pas déclencher de rencontre.',
          ref: 'Actions de base — p.13',
        },
        {
          id: 'e9-solo',
          kind: 'action',
          title: 'Enchaînez vos tours',
          only: [1],
          body: [
            'Vous jouez 2 actions, puis un nouveau tour de 2 actions, jusqu’à ce que vous passiez.',
            'Quand vous passez, la manche s’arrête et la phase Événement commence.',
          ],
          tip: 'Ne videz pas votre main. Vos cartes restantes décident si une rencontre vous surprend.',
        },
        {
          id: 'e9',
          kind: 'action',
          title: 'Continuez le tour de table',
          only: [2, 3, 4, 5],
          body: [
            'Chaque joueur joue ses 2 actions, dans le sens horaire.',
            'Puis un nouveau tour de 2 actions, jusqu’à ce que tout le monde ait passé.',
          ],
          tip: 'Ne videz pas votre main. Vos cartes restantes décident de qui les Intrus attaquent et si une rencontre vous surprend.',
        },
      ],
    },

    {
      id: 'encounter',
      title: 'La rencontre',
      kind: 'play',
      goal: 'Savoir ce qui se passe quand un Intrus apparaît devant vous.',
      steps: [
        {
          id: 'r1',
          kind: 'info',
          title: 'Ce qui déclenche une rencontre',
          body: [
            'Vous devez poser un marqueur Bruit sur un couloir qui en a déjà un.',
            'Ou une carte Événement, ou une carte Attaque d’Intrus, vous le demande.',
          ],
          warn: 'Un Intrus qui se déplace vers votre salle n’est pas une rencontre : c’est juste un combat qui commence.',
          ref: 'Rencontre — p.18',
        },
        {
          id: 'r2',
          crop: { page: 18, x: 0.356, y: 0.155, w: 0.289, h: 0.62 },
          kind: 'action',
          title: 'Résolvez la rencontre en 4 temps',
          body: [
            '1. Retirez tous les marqueurs Bruit des couloirs reliés à la salle, conduit compris.',
            '2. Piochez un jeton Intrus dans le sac.',
            '3. Posez la figurine correspondant au symbole du jeton dans votre salle.',
            '4. Comparez le chiffre au dos du jeton au nombre de cartes dans votre main.',
          ],
          components: ['sac', 'jetons-intrus', 'figurines'],
          ref: 'Rencontre — p.18',
        },
        {
          id: 'r3',
          kind: 'action',
          title: 'Attaque-surprise ou pas ?',
          body: [
            'Le jeton pioché indique 4. Comptez vos cartes en main, Contamination comprises.',
          ],
          widget: {
            kind: 'choice',
            title: 'Vous avez 3 cartes en main, le jeton indique 4',
            options: [
              {
                label: 'Moins de cartes que le chiffre',
                outcome: 'Attaque-surprise : piochez et résolvez immédiatement une carte Attaque d’Intrus. C’est bien votre cas ici, 3 < 4.',
                tint: '#ef4444',
              },
              {
                label: 'Autant ou plus que le chiffre',
                outcome: 'Rien ne se passe. L’Intrus est là, vous êtes en combat, mais il ne vous attaque pas tout de suite.',
                tint: '#34d399',
              },
            ],
          },
          warn: 'Mettez le jeton pioché de côté plutôt que de le remettre dans le sac : il n’y retourne que dans certains cas, par exemple si l’Intrus disparaît dans un conduit.',
          components: ['attaques'],
          ref: 'Attaque-surprise — p.18',
        },
        {
          id: 'r4',
          kind: 'action',
          title: 'Première rencontre : choisissez votre objectif',
          body: [
            'C’est la première figurine d’Intrus qui arrive sur le plateau, quel que soit son type.',
            'Chaque joueur choisit immédiatement l’un de ses deux objectifs.',
            'L’autre est retiré du jeu, face cachée, sans être montré.',
            'La rencontre se résout ensuite normalement.',
          ],
          warn: 'Ce moment n’arrive qu’une fois dans la partie. Ne le manquez pas : à partir de là, chacun poursuit son objectif unique, en le cachant.',
          tip: 'Personne n’a le droit de consulter les objectifs défaussés par les autres.',
          components: ['objectifs'],
          ref: 'Moments spéciaux — p.12',
        },
        {
          id: 'r5',
          kind: 'info',
          title: 'Le jeton vierge',
          body: [
            'Pioche pendant une rencontre : posez un marqueur Bruit dans chaque couloir et conduit relié à votre salle, remettez le jeton dans le sac, la rencontre s’arrête.',
            'S’il était le dernier jeton du sac, ajoutez-y d’abord 1 jeton Adulte s’il en reste.',
          ],
          warn: 'À l’étape sac Intrus de la phase Événement, le jeton vierge ne fait pas la même chose : il ajoute un jeton Adulte dans le sac.',
          components: ['jetons-intrus'],
          ref: 'Jeton vierge — p.18 et p.10',
        },
      ],
    },

    {
      id: 'combat',
      title: 'Le combat',
      kind: 'play',
      goal: 'Attaquer, vérifier si l’Intrus meurt, ou fuir.',
      steps: [
        {
          id: 'c1',
          kind: 'info',
          title: 'Un Intrus dans votre salle = combat',
          body: [
            'Vous pouvez attaquer ou fuir pendant votre tour.',
            'Les Intrus, eux, attaquent pendant la phase Événement.',
            'Les œufs ne sont pas des Intrus : leur présence ne vous met pas en combat.',
          ],
          ref: 'Combat — p.18',
        },
        {
          id: 'c2',
          crop: { page: 19, x: 0.048, y: 0.55, w: 0.289, h: 0.318 },
          kind: 'action',
          title: 'Tirez sur l’Intrus',
          body: [
            'Coût : 1 carte Action.',
            'Choisissez votre arme et votre cible, défaussez 1 munition de l’arme, lancez un dé de combat.',
          ],
          widget: {
            kind: 'roller',
            title: 'Dé de combat — action de Tir',
            cta: 'Lancer le dé de combat',
            faces: [
              { label: 'Larve / Rôdeur', effect: 'Si la cible est une Larve ou un Rôdeur : 1 dégât. Sinon, vous manquez.', tint: '#84cc16' },
              { label: '+ Adulte', effect: 'Si la cible est une Larve, un Rôdeur ou un Adulte : 1 dégât. Sinon, vous manquez.', tint: '#22d3ee' },
              { label: '1 dégât', effect: '1 dégât, quel que soit le type d’Intrus visé.', tint: '#fbbf24' },
              { label: '2 dégâts', effect: '2 dégâts, quel que soit le type d’Intrus visé.', tint: '#f97316' },
              { label: 'Manque', effect: 'Vous manquez la cible. La munition est dépensée quand même.', tint: '#64708a' },
            ],
          },
          warn: 'Certaines armes ont leurs propres règles et plafonnent les dégâts. Lisez toujours la carte de l’arme.',
          tip: 'Le simulateur montre les cinq résultats possibles ; il ne reproduit pas la répartition des faces du d6. Lancez le vrai dé.',
          components: ['de-combat', 'munitions'],
          ref: 'Action de Tir — p.18',
        },
        {
          id: 'c3',
          crop: { page: 20, x: 0.356, y: 0.53, w: 0.289, h: 0.364 },
          kind: 'action',
          title: 'L’Intrus est-il mort ?',
          body: [
            'Posez sur la figurine autant de marqueurs Dégâts que vous en avez infligé.',
            'Larve ou œuf : 1 dégât suffit, retirez la figurine.',
            'Rôdeur ou Adulte : piochez 1 carte Attaque d’Intrus et ne regardez que le chiffre dans la tache de sang.',
            'Ce chiffre est inférieur ou égal aux dégâts cumulés ? L’Intrus meurt, remplacez-le par un jeton Carcasse.',
            'Sinon il survit : défaussez la carte, vous en piocherez une autre à la prochaine attaque.',
          ],
          warn: 'Hybride et Reine : piochez 2 cartes et additionnez les deux chiffres. Il faut dépasser ce total.',
          tip: 'La tache de sang représente l’endurance de l’Intrus et change à chaque tirage : vous ne savez jamais à l’avance combien de dégâts il faudra.',
          components: ['attaques', 'munitions', 'carcasses'],
          ref: 'Dégâts et mort des Intrus — p.20',
        },
        {
          id: 'c4',
          kind: 'info',
          title: 'L’icône de retraite',
          body: [
            'Si la tache de sang affiche une icône de retraite au lieu d’un chiffre, l’Intrus s’enfuit.',
            'Piochez une carte Événement et déplacez-le par le couloir indiqué, puis défaussez l’événement.',
            'Il garde ses dégâts — sauf s’il disparaît dans un conduit, auquel cas ils sont perdus.',
          ],
          components: ['evenements'],
          ref: 'Retraite des Intrus — p.20',
        },
        {
          id: 'c5',
          kind: 'action',
          title: 'Le corps-à-corps, en dernier recours',
          body: [
            'Coût : 1 carte Action.',
            'Piochez d’abord 1 carte Contamination et mettez-la dans votre défausse.',
            'Puis choisissez votre cible et lancez un dé de combat.',
          ],
          widget: {
            kind: 'roller',
            title: 'Dé de combat — action de Corps-à-corps',
            cta: 'Lancer le dé de combat',
            faces: [
              { label: 'Larve / Rôdeur', effect: 'Si la cible est une Larve ou un Rôdeur : 1 dégât. Sinon vous manquez ET subissez 1 blessure grave.', tint: '#84cc16' },
              { label: '+ Adulte', effect: 'Si la cible est une Larve, un Rôdeur ou un Adulte : 1 dégât. Sinon vous manquez ET subissez 1 blessure grave.', tint: '#22d3ee' },
              { label: '1 dégât', effect: '1 dégât, quel que soit le type d’Intrus.', tint: '#fbbf24' },
              { label: '1 dégât', effect: '1 dégât seulement — le double résultat compte comme simple au corps-à-corps.', tint: '#fbbf24' },
              { label: 'Manque', effect: 'Vous manquez et subissez immédiatement 1 blessure grave.', tint: '#ef4444' },
            ],
          },
          warn: 'Le corps-à-corps coûte une carte Contamination à chaque tentative, même réussie. C’est le prix à payer quand on n’a plus de munitions.',
          components: ['contamination', 'de-combat'],
          ref: 'Action de Corps-à-corps — p.19',
        },
        {
          id: 'c6',
          crop: { page: 19, x: 0.356, y: 0.425, w: 0.289, h: 0.304 },
          kind: 'action',
          title: 'Fuir',
          body: [
            'Coût : 1 carte Action, comme un déplacement.',
            'Résolvez d’abord une attaque d’Intrus — une par Intrus présent dans la salle que vous quittez.',
            'Si vous survivez, votre déplacement se termine dans la salle adjacente : exploration et jet de bruit s’appliquent normalement.',
          ],
          warn: 'Si vous mourez en fuyant, votre corps reste dans la salle d’où vous tentiez de fuir.',
          components: ['attaques'],
          ref: 'Fuite — p.19',
        },
        {
          id: 'c7',
          kind: 'info',
          title: 'Blessures légères et graves',
          body: [
            'Blessure légère : un marqueur en haut de votre piste de blessures ; s’il y en a déjà un, il descend d’un cran.',
            'Le marqueur atteint la case « blessure grave » : défaussez-le et subissez une blessure grave.',
            'Blessure grave : piochez une carte Blessure grave, son effet est permanent.',
          ],
          warn: 'À 3 blessures graves, la moindre blessure suivante — légère ou grave — vous tue.',
          tip: 'Panser une blessure grave retourne sa carte face cachée : l’effet est ignoré, mais elle compte toujours dans la limite de 3.',
          components: ['blessures', 'marqueurs-std'],
          ref: 'Blessures — p.21',
        },
        {
          id: 'c8',
          kind: 'info',
          title: 'L’attaque de Larve est à part',
          body: [
            'Une Larve qui vous attaque ne fait pas piocher de carte Attaque d’Intrus.',
            'Retirez sa figurine du plateau et posez-la sur votre plateau individuel.',
            'Puis piochez une carte Contamination.',
          ],
          warn: 'Si vous aviez déjà une Larve sur votre plateau, gardez celle que vous avez et retirez l’autre du jeu.',
          components: ['figurines', 'contamination'],
          ref: 'Attaque de Larve — p.20',
        },
      ],
    },

    {
      id: 'event',
      title: 'La phase Événement',
      kind: 'play',
      goal: 'Clôturer la manche : le vaisseau et les Intrus jouent à leur tour.',
      steps: [
        {
          id: 'v1',
          kind: 'info',
          title: 'Tout le monde a passé : la phase Événement commence',
          body: ['Cinq étapes, toujours dans cet ordre, sans exception.'],
          ref: 'Phase Événement — p.10',
        },
        {
          id: 'v2',
          kind: 'action',
          title: '1. Avancez la piste temporelle',
          body: [
            'Le marqueur Temps avance d’un cran vers la droite.',
            'Si la séquence d’autodestruction est lancée, son marqueur avance aussi.',
          ],
          tip: 'Case bleue atteinte : les compartiments d’hibernation s’ouvrent. Avant, personne ne peut hiberner.',
          components: ['marqueurs-std'],
          ref: 'Phase Événement, étape 4 — p.10',
        },
        {
          id: 'v3',
          crop: { page: 20, x: 0.356, y: 0.53, w: 0.289, h: 0.364 },
          kind: 'action',
          title: '2. Les Intrus attaquent',
          body: [
            'Tout Intrus en combat avec un personnage l’attaque.',
            'Piochez une carte Attaque d’Intrus. Si un de ses symboles correspond au type de l’attaquant, l’effet s’applique. Sinon, l’attaque échoue.',
          ],
          warn: 'Plusieurs personnages dans la salle ? L’Intrus attaque celui qui a le moins de cartes Action en main. En cas d’égalité, le plus proche du premier joueur.',
          tip: 'Lors d’une attaque, on ignore le chiffre de la tache de sang : il ne sert qu’à vérifier la mort d’un Intrus.',
          components: ['attaques'],
          ref: 'Attaque d’Intrus — p.20',
        },
        {
          id: 'v4',
          kind: 'action',
          title: '3. Dégâts du feu',
          body: ['Tout Intrus dans une salle avec un marqueur Feu subit 1 dégât.'],
          warn: 'Le feu vous a déjà blessé plus tôt : vous subissez 1 blessure légère à chaque fois que vous terminez votre TOUR dans une salle en feu, pas à cette étape.',
          components: ['marqueurs-feu'],
          ref: 'Phase Événement, étape 6 — p.10 et p.17',
        },
        {
          id: 'v5',
          crop: { page: 10, x: 0.356, y: 0.551, w: 0.289, h: 0.377 },
          kind: 'action',
          title: '4. Piochez une carte Événement',
          body: [
            'Les symboles d’Intrus de la carte désignent qui bouge ; le numéro indique par quel couloir.',
            'Les Intrus en combat ne bougent pas.',
            'Couloir avec porte fermée : l’Intrus ne bouge pas mais détruit la porte.',
            'Couloir menant à un conduit : retirez la figurine et remettez son jeton dans le sac.',
            'Résolvez ensuite l’effet de la carte, puis défaussez-la.',
          ],
          components: ['evenements', 'portes'],
          ref: 'Phase Événement, étape 7 — p.10',
        },
        {
          id: 'v6',
          kind: 'action',
          title: '5. Piochez un jeton dans le sac Intrus',
          body: ['Le type de jeton décide de ce qui arrive. Testez les six cas ci-dessous.'],
          widget: {
            kind: 'roller',
            title: 'Sac Intrus',
            cta: 'Piocher un jeton',
            faces: [
              { label: 'Larve', effect: 'Retirez ce jeton du sac et remplacez-le par 1 jeton Adulte.', weight: 4, tint: '#84cc16' },
              { label: 'Adulte', effect: 'Tous les joueurs résolvent un jet de bruit, dans l’ordre. Ceux en combat sont exemptés. Le jeton retourne dans le sac.', weight: 3, tint: '#f97316' },
              { label: 'Rôdeur', effect: 'Retirez ce jeton du sac et remplacez-le par 1 jeton Hybride.', weight: 1, tint: '#22d3ee' },
              { label: 'Hybride', effect: 'Tous les joueurs résolvent un jet de bruit, dans l’ordre. Ceux en combat sont exemptés. Le jeton retourne dans le sac.', weight: 1, tint: '#a78bfa' },
              { label: 'Reine', effect: 'S’il y a un personnage dans le nid, placez-y la Reine et résolvez une rencontre. Sinon, ajoutez un jeton Œuf sur le plateau Intrus. Le jeton retourne dans le sac.', weight: 1, tint: '#ef4444' },
              { label: 'Vierge', effect: 'Ajoutez 1 jeton Adulte dans le sac. S’il n’en reste aucun, rien ne se passe. Le jeton retourne dans le sac.', weight: 1, tint: '#64708a' },
            ],
          },
          warn: 'Le sac se durcit tout seul : chaque Larve piochée devient un Adulte, chaque Rôdeur devient un Hybride. Le vaisseau ne devient jamais plus sûr.',
          tip: 'Les poids du simulateur suivent la composition de départ du sac, avant l’ajout des Adultes par joueur.',
          components: ['sac', 'jetons-intrus'],
          ref: 'Phase Événement, étape 8 — p.10',
        },
        {
          id: 'v7',
          kind: 'check',
          title: 'Manche terminée',
          body: [
            'La manche s’arrête après l’étape du sac Intrus : toutes les rencontres et attaques-surprises ont été jouées.',
            'Nouvelle manche : chacun complète sa main à 5 cartes, et le jeton Premier joueur passe à gauche.',
          ],
          tip: 'Rejouez maintenant deux ou trois manches par vous-mêmes. Revenez sur ce chapitre autant que nécessaire, la progression est sauvegardée.',
          ref: 'Phase Événement, étape 9 — p.10',
        },
      ],
    },

    /* --------------------------------------------- reprise d'une séance */

    {
      id: 'rp',
      title: 'Reprendre la séance',
      kind: 'setup',
      modes: ['reprise'],
      goal: 'Retrouver l’état exact d’une table laissée en plan, et repartir sans faute.',
      steps: [
        {
          id: 'rp1',
          kind: 'info',
          title: 'Nemesis n’a pas de sauvegarde',
          body: [
            'C’est une partie d’une séance : le livret ne prévoit ni fiche de sauvegarde, ni rangement intermédiaire.',
            'Reprendre veut donc dire : la table est restée montée, et on vérifie qu’elle n’a pas bougé.',
          ],
          warn: 'Si la table a été rangée, la partie est perdue : rien ne permet de reconstituer le contenu du sac Intrus ni les objectifs secrets.',
          ref: 'Déroulement — p.10',
        },
        {
          id: 'rp2',
          kind: 'check',
          title: 'Où en était-on ?',
          body: [
            'Phase Joueur ou phase Événement ? Si personne ne s’en souvient, reprenez au début de la phase Joueur.',
            'Le marqueur Premier joueur donne l’ordre du tour.',
            'Qui avait déjà passé ? Un joueur qui a passé ne rejoue pas avant la manche suivante.',
          ],
          components: ['premier-joueur'],
          ref: 'Déroulement — p.10',
        },
        {
          id: 'rp3',
          kind: 'check',
          title: 'Vérifiez chaque joueur',
          body: [
            'Sa main de cartes Action, face cachée : c’est elle qui paie les actions et protège des attaques-surprises.',
            'Ses cartes Blessure légère et grave, ses Contaminations, son inventaire et ses munitions.',
            'La position de sa figurine, et l’état de son personnage.',
          ],
          warn: 'Une main mélangée avec la défausse est irrécupérable. Comptez les cartes avant de reprendre : le nombre en main décide des attaques-surprises.',
          components: ['actions', 'blessures', 'contamination', 'inventaires'],
          ref: 'Actions — p.12',
        },
        {
          id: 'rp4',
          kind: 'check',
          title: 'Vérifiez le plateau',
          body: [
            'Marqueurs de Bruit dans les couloirs, figurines d’Intrus, œufs restants sur le plateau Intrus.',
            'Portes ouvertes ou fermées, feux, pannes, marqueur de Destination.',
          ],
          components: ['marqueurs-bruit', 'figurines', 'portes', 'marqueurs-feu', 'marqueurs-panne'],
          ref: 'Mise en place — p.6',
        },
        {
          id: 'rp5',
          kind: 'check',
          title: 'Le sac Intrus, surtout',
          body: [
            'Son contenu ne se déduit de rien : c’est la seule information de la partie qui n’existe qu’à l’intérieur du sac.',
            'Les jetons piochés sont restés à côté, ils n’y retournent pas.',
          ],
          warn: 'Un sac vidé sur la table, même en le remettant, fausse la partie pour de bon.',
          components: ['sac', 'jetons-intrus'],
          ref: 'Rencontre — p.17',
        },
        {
          id: 'rp6',
          kind: 'check',
          title: 'Relisez votre objectif',
          body: [
            'Le vôtre, seul, sans le montrer : c’est lui qui décide de ce que vous ferez au prochain tour.',
            'Vérifiez aussi l’état des moteurs déjà révélés, et la carte Coordonnées si elle a été vue.',
          ],
          tip: 'Le rappel des règles, sur l’accueil, remet la manche en tête en sept étapes.',
          components: ['objectifs', 'moteurs'],
          ref: 'Fin de partie — p.23',
        },
      ],
    },

    /* ------------------------------------------------- rappel des règles */

    {
      id: 'r-boucle',
      title: 'La manche',
      kind: 'play',
      modes: ['recap'],
      goal: 'Retrouver la structure d’une manche et l’ordre des phases.',
      steps: [
        {
          id: 'rr1',
          kind: 'info',
          title: 'Une manche, deux phases',
          body: [
            'Phase Joueur : chacun son tour, jusqu’à ce que tout le monde ait passé.',
            'Phase Événement : 5 étapes, dans l’ordre, pour tout le monde à la fois.',
            'Le marqueur Premier joueur avance d’un cran à la fin de la manche.',
          ],
          ref: 'Déroulement — p.10',
        },
        {
          id: 'rr2',
          kind: 'info',
          title: 'Votre tour : deux actions',
          body: [
            'Vous en faites deux, puis c’est au suivant. Passer met fin à votre manche.',
            'Presque toute action se paie en défaussant une carte Action de sa main.',
            'Une main pleine vous protège aussi des attaques-surprises.',
          ],
          warn: 'Une fois que vous avez passé, vous ne rejouez plus avant la manche suivante.',
          ref: 'Actions — p.12',
        },
        {
          id: 'rr3',
          kind: 'info',
          title: 'Se déplacer, et faire du bruit',
          body: [
            'Un déplacement vers une salle déjà explorée coûte 1 carte ; vers une salle inconnue, on explore.',
            'À l’arrivée dans une salle non explorée : tuile retournée, jeton Exploration résolu, puis jet de bruit.',
            'Le jet de bruit pose un marqueur dans le couloir tiré — ou déclenche une rencontre si le couloir en a déjà un.',
          ],
          ref: 'Déplacement et bruit — p.14-15',
        },
        {
          id: 'rr4',
          kind: 'info',
          title: 'La rencontre',
          body: [
            'Piochez un jeton dans le sac Intrus, placez la figurine correspondante, et vous êtes en combat.',
            'Comparez le chiffre du jeton à votre nombre de cartes en main : moins de cartes que le chiffre = attaque-surprise.',
          ],
          warn: 'Le jeton pioché ne retourne pas dans le sac : mettez-le de côté.',
          ref: 'Rencontre — p.17-18',
        },
        {
          id: 'rr5',
          kind: 'info',
          title: 'Combattre, ou fuir',
          body: [
            'Tir : 1 carte + 1 munition, un dé de combat. Corps-à-corps : 1 carte, sans munition, mais l’Intrus riposte.',
            'Fuir coûte 1 carte et vous déplace : l’Intrus reste sur place.',
            'Un Intrus tué laisse une carcasse ; un personnage blessé pioche une Blessure légère ou grave.',
          ],
          ref: 'Combat — p.19-21',
        },
        {
          id: 'rr6',
          kind: 'info',
          title: 'La phase Événement, 5 étapes',
          body: [
            '1. Carte Événement révélée et résolue. 2. Déplacement des Intrus attirés par le bruit.',
            '3. Attaque des Intrus en contact. 4. Un jeton tiré du sac par joueur encore en vie.',
            '5. Entretien : marqueurs de bruit retirés, mains complétées, premier joueur décalé.',
          ],
          ref: 'Phase Événement — p.22',
        },
        {
          id: 'rr7',
          kind: 'check',
          title: 'Gagner',
          body: [
            'Il faut survivre : être en hibernation ou dans une nacelle au moment où la partie s’arrête.',
            'Et remplir son objectif secret, que personne d’autre ne connaît.',
          ],
          warn: 'Survivre ne suffit pas, et l’objectif seul ne suffit pas non plus. Il faut les deux.',
          ref: 'Fin de partie — p.23',
        },
      ],
    },

    {
      id: 'win',
      title: 'Gagner',
      kind: 'debrief',
      goal: 'Savoir comment la partie s’arrête et ce qu’il faut pour l’emporter.',
      steps: [
        {
          id: 'w1',
          kind: 'info',
          title: 'Il faut remplir DEUX conditions',
          body: [
            '1. Remplir l’objectif de la carte que vous avez gardée.',
            '2. Survivre : être en hibernation au moment du saut, ou s’échapper en nacelle.',
          ],
          warn: 'Remplir son objectif sans survivre ne vaut rien. Survivre sans objectif non plus.',
          components: ['objectifs'],
          ref: 'Buts des joueurs — p.11',
        },
        {
          id: 'w2',
          kind: 'info',
          title: 'Comment la partie s’arrête',
          body: [
            'Le marqueur Temps atteint la dernière case : le vaisseau saute en hyperespace, tout personnage hors hibernation est tué.',
            'Le marqueur d’autodestruction atteint la dernière case, ou il faut poser un 9e marqueur Feu ou Panne : le vaisseau explose, tout le monde meurt.',
            'Le dernier joueur actif meurt, hiberne ou part en nacelle : plus rien ne peut se passer à bord.',
          ],
          warn: 'Les Intrus ne sont pas tués par le saut en hyperespace. Un objectif « tuer la Reine » ou « détruire le nid » échoue si vous comptiez sur le saut.',
          ref: 'Fin de la partie — p.11',
        },
        {
          id: 'w3',
          kind: 'info',
          title: 'Le contrôle de victoire, dans l’ordre',
          body: [
            '1. Moteurs : révélez les tuiles du dessus. Deux moteurs endommagés ou plus, le vaisseau explose.',
            '2. Coordonnées : révélez la carte. Si le vaisseau ne va pas vers la Terre, tous les personnages en hibernation meurent.',
            '3. Contamination : chaque survivant scanne ses cartes.',
            '4. Objectif : les survivants révèlent leur carte et vérifient qu’elle est remplie.',
          ],
          tip: 'Un marqueur Panne sur un moteur bloque seulement l’action de la salle. Il ne rend pas le moteur endommagé.',
          components: ['moteurs', 'coordonnees'],
          ref: 'Contrôle de victoire — p.11',
        },
        {
          id: 'w4',
          crop: { page: 21, x: 0.051, y: 0.293, w: 0.286, h: 0.464 },
          kind: 'info',
          title: 'La contamination tue après coup',
          body: [
            'Scannez vos cartes Contamination : pioche, défausse et main.',
            'Au moins une carte infectée ? Mélangez toutes vos cartes, piochez les 4 premières : s’il y a une seule carte Contamination parmi elles, infectée ou non, vous mourez.',
          ],
          warn: 'Si une Larve est sur votre plateau individuel, vous ne résolvez que la seconde étape. Vous piochez donc directement les 4 cartes.',
          tip: 'C’est le piège classique de la première partie : on rentre vivant, et on meurt au dernier contrôle. Passez au bloc opératoire ou utilisez un antidote pendant qu’il en est encore temps.',
          components: ['contamination', 'scanner'],
          ref: 'Contrôle de contamination — p.11 et p.20',
        },
        {
          id: 'w5',
          kind: 'info',
          title: 'Ce que ce tutoriel n’a pas couvert',
          body: [
            'Les actions des 20 salles, décrites dans l’index p.24 à 26.',
            'L’action Fouille, la fabrication d’objets, les objets de quête.',
            'La séquence d’autodestruction, les nacelles, l’hibernation en détail.',
            'Les points faibles et l’analyse de corps au laboratoire.',
            'Les modes solo, coopératif et « jouer en tant qu’Intrus ».',
          ],
          tip: 'Gardez le livret ouvert à l’index des salles pendant votre première partie : c’est la seule page que vous consulterez vraiment souvent.',
          ref: 'Index des salles — p.24-26',
        },
        {
          id: 'w6',
          kind: 'check',
          title: 'Le vaisseau est à vous',
          body: [
            'Vous savez installer la partie, jouer un tour, explorer, combattre et clôturer une manche.',
            'Terminez cette partie avec le livret à portée de main.',
          ],
          tip: 'Le chronomètre vous donnera la durée réelle de votre première partie. Comptez plus long que la durée annoncée, c’est normal.',
        },
      ],
    },
  ],
}
