/**
 * Oathsworn : Into the Deepwood — première partie tutorielle, partie Histoire.
 *
 * Source : « Oathsworn: Into the Deepwood — Story Rule Book », Shadowborne
 * Games, en ANGLAIS, livré en quatre fichiers PDF que `npm run merge`
 * réunit en un seul livret de 20 pages (voir GUIDE_CREATION_TUTO.md). La
 * page imprimée N est la N-ième page du PDF, d'où `pageOffset: 0`.
 *
 * PÉRIMÈTRE. Un chapitre d'Oathsworn se joue en deux temps : l'**Histoire**,
 * qui se lit dans le Story Book avec les cartes de cité, puis la
 * **Rencontre**, qui se joue sur le plateau avec les figurines. Ce livret ne
 * couvre que l'Histoire ; la Rencontre a son propre livret, l'Encounter Rule
 * Book, qui n'est pas ingéré ici. Le tutoriel couvre donc l'Histoire de bout
 * en bout et s'arrête au seuil de la Rencontre — ce que le livret lui-même
 * recommande pour une première séance de trois heures ou moins.
 *
 * Le texte des étapes est une traduction du livret. Les noms imprimés sur le
 * matériel restent en anglais quand les traduire égarerait le joueur
 * (Banksmith, Apothecary, Animus, Battleflow) ; pour tout le reste, le
 * glossaire `vo` donne le terme original, surligné dans les consignes.
 */

import type { Tutorial } from '../engine/types'

export const oathsworn: Tutorial = {
  id: 'oathsworn',
  title: 'Oathsworn',
  tagline:
    'Les cités survivantes ont scellé un pacte : des compagnies libres traquent les cauchemars de la Forêt Profonde. Vous avez prêté le serment.',
  contentVersion: '1.0',
  publisher: 'Shadowborne Games',
  author: 'Jamie Jolly',
  players: {
    min: 1,
    max: 4,
    recommended: 2,
    labels: { 1: 'Solo' },
    notes: {
      1: 'En solo, vous menez les quatre Oathsworn de la Compagnie. Les décisions secrètes se prennent à découvert, pour la Compagnie.',
      2: 'À deux, chacun mène deux Oathsworn : deux personnages complets, deux compagnons, ou un de chaque.',
      3: 'À trois, un joueur mène deux Oathsworn. La Compagnie compte toujours quatre personnages.',
      4: 'À quatre, un Oathsworn chacun. C’est l’effectif où les décisions secrètes prennent tout leur sel.',
    },
  },
  minutes: 60,

  // Le livret est un parchemin gris-bleu froid, titres à l'encre noire et
  // or du logo. Les découpes viennent de ces pages claires : un fond clair
  // les fait tenir dans la page au lieu de les y faire flotter.
  theme: {
    scheme: 'light',
    bg: '#dbe0e2',
    bg2: '#e9edee',
    bg3: '#f5f8f8',
    stroke: '#adb8b9',
    strokeSoft: '#c7cfd0',
    fg: '#1b2422',
    fgDim: '#46534f',
    fgFaint: '#65706c',
    accent: '#7d5c10',
    accent2: '#1f4d3f',
    accentInk: '#fff8e8',
    ok: '#2f6b45',
    warn: '#8a5a10',
    danger: '#9a2c1f',
    radius: '4px',
  },

  source: {
    pdf: 'Oathsworn - Regles.pdf',
    assetId: 'oathsworn',
    pageOffset: 0,
    credit: 'Story Rule Book officiel EN — Shadowborne Games (quatre PDF fusionnés)',
  },

  cover: { page: 1, x: 0.03, y: 0.318, w: 0.94, h: 0.229 },

  vo: {
    language: 'anglais',
    edition: 'Oathsworn: Into the Deepwood, Story Rule Book',
    terms: [
      // La partie et ses deux moitiés
      { fr: 'Compagnie Libre', en: 'Free Company' },
      { fr: 'chapitre', en: 'Chapter' },
      { fr: 'histoire', en: 'Story', note: 'La première moitié d’un chapitre.' },
      { fr: 'rencontre', en: 'Encounter', note: 'La seconde moitié : le combat sur plateau.' },
      { fr: 'livre d’histoire', en: 'Story Book' },
      { fr: 'application', en: 'Companion App' },
      { fr: 'journal', en: 'Journal' },
      { fr: 'livret de règles de la rencontre', en: 'Encounter Rule Book' },
      { fr: 'archiver', en: 'archive', note: 'Remettre le composant à sa place dans la boîte.' },

      // Les personnages
      { fr: 'personnage complet', en: 'full character' },
      { fr: 'compagnon', en: 'companion' },
      { fr: 'plateau de personnage', en: 'Player Board' },
      { fr: 'carte de Compagnon', en: 'Companion Card' },
      { fr: 'fiche de personnage', en: 'Character Sheet' },
      { fr: 'feuille de Compagnie Libre', en: 'Free Company Sheet' },
      { fr: 'figurine', en: 'Model' },
      { fr: 'carte de capacité', en: 'Ability Card' },
      { fr: 'carte d’archétype', en: 'Archetype Card' },
      { fr: 'points de vie', en: 'Hit Points (HP)' },
      { fr: 'dé de points de vie', en: 'HP die' },
      { fr: 'gemme d’Animus', en: 'Animus gem' },
      { fr: 'régénération', en: 'Regen' },
      { fr: 'jeton de suivi', en: 'Tracker Token' },
      { fr: 'défense', en: 'Defense' },
      { fr: 'complexité', en: 'Complexity' },

      // Puissance
      { fr: 'piste de Puissance', en: 'Might Track' },
      { fr: 'carte de Puissance', en: 'Might Card' },
      { fr: 'dé de Puissance', en: 'Might Dice' },
      { fr: 'paquet de Puissance', en: 'Might Deck' },
      { fr: 'cube', en: 'Might Cube' },
      { fr: 'critique', en: 'Critical' },
      { fr: 'carte vierge', en: 'blank' },

      // Objets et monnaie
      { fr: 'carte d’objet', en: 'Item Card' },
      { fr: 'objet commun', en: 'Common Item' },
      { fr: 'objet unique', en: 'Unique Item' },
      { fr: 'sac à dos', en: 'Backpack' },
      { fr: 'fer', en: 'Iron', note: 'La monnaie du jeu.' },
      { fr: 'équipement', en: 'gear' },
      { fr: 'organisateur de cartes', en: 'Card Organizer' },
      { fr: 'séparateur de cartes', en: 'Card Separator' },
      { fr: 'piste de KO', en: 'Knockout Track' },
      { fr: 'pétitionner la Flèche du Corbeau', en: 'petition the Raven Spire' },

      // La carte et le temps
      { fr: 'carte de la cité', en: 'City Map' },
      { fr: 'marqueur de Compagnie Libre', en: 'Free Company Marker' },
      { fr: 'lieu', en: 'Location' },
      { fr: 'jeton de lieu', en: 'Location Token' },
      { fr: 'piste de Temps', en: 'Time Track' },
      { fr: 'jeton de temps', en: 'Time Token' },
      { fr: 'carte de chemin', en: 'Path Card' },
      { fr: 'carte d’événement', en: 'Event Card' },
      { fr: 'événement de cité', en: 'City Event' },
      { fr: 'Forêt Profonde', en: 'the Deepwood' },
      { fr: 'indice', en: 'Clue' },
      { fr: 'jeton d’indice', en: 'Clue Token' },
      { fr: 'effet immédiat', en: 'Immediate Effect' },
      { fr: 'effet de fin d’histoire', en: 'End of Story Effect' },
      { fr: 'fin de rencontre', en: 'End of Encounter', note: 'Les effets de la piste de Temps résolus après la rencontre.' },

      // Jetons
      { fr: 'jeton de combat', en: 'Combat Token' },
      { fr: 'jeton permanent', en: 'Permanent Token' },
      { fr: 'jeton de défense', en: 'Defense Token' },
      { fr: 'jeton de nouveau tirage', en: 'Redraw Token' },
      { fr: 'jeton de statut', en: 'Status Token' },
      { fr: 'saignement', en: 'Bleed' },
      { fr: 'estropié', en: 'Crippled' },
      { fr: 'carte de soin', en: 'Curative Card' },
      { fr: 'carte de blessure', en: 'Injury Card' },
      { fr: 'allié', en: 'Ally' },

      // Les actions de l'histoire
      { fr: 'test', en: 'Check' },
      { fr: 'difficulté', en: 'difficulty' },
      { fr: 'succès', en: 'success' },
      { fr: 'décision secrète', en: 'Secret Decision' },
      { fr: 'round de combat', en: 'Round of Combat' },
      { fr: 'commencer un échange', en: 'START A TRADE' },
      { fr: 'envoyer un coursier', en: 'send a runner' },

      // Mise en place et sauvegarde
      { fr: 'plateau de règles spéciales', en: 'Special Rules Board' },
      { fr: 'enveloppe mystère', en: 'Mystery Envelope' },
      { fr: 'sac de la Compagnie Libre', en: 'Free Company Bag' },
      { fr: 'sac de sauvegarde', en: 'Save Bag' },
      { fr: 'aide de jeu', en: 'Player Aid Card' },
      { fr: 'mode Action Immédiate', en: 'Instant Action Mode' },
      { fr: 'variante Hardcore', en: 'Hardcore Variant' },
    ],
  },

  scope: {
    covered: [
      'Former une Compagnie Libre de quatre Oathsworn',
      'La mise en place d’un personnage complet et d’un compagnon',
      'La mise en place de l’histoire, des onze étapes du livret',
      'Les cinq niveaux de difficulté et la variante Hardcore',
      'Naviguer sur la carte : lieux, jetons de lieu, cartes de chemin',
      'La piste de Temps, ses trois familles d’effets, les cartes d’événement',
      'Objets, sac à dos, fer, indices, alliés, jetons de combat et permanents',
      'Les tests : cartes de Puissance, critiques, niveaux de succès',
      'Les décisions secrètes, le round de combat, le Banksmith et l’Apothecary',
      'Sauvegarder la campagne dans les sacs, et la reprendre',
    ],
    skipped: [
      'La Rencontre : plateau, figurines et combat au tour par tour, dans l’Encounter Rule Book',
      'L’histoire elle-même : elle est dans le Story Book et l’application',
      'Les capacités des douze personnages, leurs cartes de capacité et d’archétype',
      'Le mode Action Immédiate et la montée de niveau rapide, signalés mais pas déroulés',
    ],
  },

  /* ------------------------------------------------------------ matériel */

  components: [
    {
      id: 'livrets',
      name: 'Story Rule Book et Encounter Rule Book',
      qty: '2 livrets',
      note: 'Deux livrets pour deux moitiés de chapitre. Celui-ci ne couvre que l’histoire.',
      glyph: 'card',
      tint: '#7d5c10',
      crop: { page: 4, x: 0.13, y: 0.072, w: 0.29, h: 0.205 },
    },
    {
      id: 'story-books',
      name: 'Livres d’histoire',
      qty: '2 livres',
      note: 'Le texte de la campagne, en entrées numérotées. L’application peut les remplacer.',
      glyph: 'card',
      tint: '#1f4d3f',
      crop: { page: 4, x: 0, y: 0.505, w: 0.5, h: 0.44 },
    },
    {
      id: 'journal',
      name: 'Journal',
      qty: '1 journal',
      note: 'Le carnet de bord de la campagne.',
      glyph: 'card',
      crop: { page: 4, x: 0.285, y: 0.5, w: 0.235, h: 0.215 },
    },
    {
      id: 'cartes-cite',
      name: 'Cartes de la cité',
      qty: '8 cartes, dans des enveloppes mystère',
      note: 'Les lieux numérotés que la Compagnie visite pendant l’histoire.',
      glyph: 'board',
      tint: '#1f4d3f',
      crop: { page: 4, x: 0.355, y: 0.715, w: 0.6, h: 0.265 },
    },
    {
      id: 'figurines',
      name: 'Figurines Oathsworn',
      qty: '12 figurines',
      note: 'Une par personnage. L’une d’elles sert aussi de marqueur de Compagnie Libre sur la carte.',
      glyph: 'figure',
      crop: { page: 4, x: 0.435, y: 0.015, w: 0.28, h: 0.14 },
    },
    {
      id: 'plateaux',
      name: 'Plateaux de personnage',
      qty: '12 plateaux',
      note: 'Un par personnage. Ils portent la piste de Puissance, l’Animus, les emplacements de dé et de jetons.',
      glyph: 'board',
      tint: '#7d5c10',
      crop: { page: 4, x: 0.43, y: 0.152, w: 0.3, h: 0.135 },
    },
    {
      id: 'cartes-capacite',
      name: 'Cartes de capacité',
      qty: '193 cartes',
      note: 'Les capacités d’un personnage complet. Elles ne servent que pendant la rencontre.',
      glyph: 'card',
      crop: { page: 4, x: 0.75, y: 0.152, w: 0.19, h: 0.11 },
    },
    {
      id: 'cartes-compagnon',
      name: 'Cartes de Compagnon',
      qty: '12 cartes',
      note: 'La version simplifiée d’un personnage : deux capacités, des tours plus rapides.',
      glyph: 'card',
      crop: { page: 4, x: 0.14, y: 0.292, w: 0.15, h: 0.095 },
    },
    {
      id: 'cartes-archetype',
      name: 'Cartes d’archétype',
      qty: '48 cartes',
      note: 'Les spécialisations que les personnages débloquent au fil de la campagne.',
      glyph: 'card',
      crop: { page: 4, x: 0.14, y: 0.385, w: 0.155, h: 0.095 },
    },
    {
      id: 'objets-communs',
      name: 'Cartes d’objet commun',
      qty: '394 cartes',
      note: 'Rangées par chapitre : le grand chiffre au dos dit à partir de quand on peut les acheter.',
      glyph: 'card',
      tint: '#1f4d3f',
      crop: { page: 4, x: 0.625, y: 0.283, w: 0.195, h: 0.1 },
    },
    {
      id: 'objets-uniques',
      name: 'Cartes d’objet unique',
      qty: '100 cartes',
      note: 'Les récompenses d’épilogue et des rencontres.',
      glyph: 'card',
      crop: { page: 4, x: 0.818, y: 0.283, w: 0.152, h: 0.1 },
    },
    {
      id: 'sac-a-dos',
      name: 'Carte Sac à dos et aides de jeu',
      qty: '1 + 9 cartes',
      note: 'Le sac à dos porte les objets non équipés, douze au maximum.',
      glyph: 'card',
      crop: { page: 4, x: 0.5, y: 0.383, w: 0.175, h: 0.12 },
    },
    {
      id: 'cartes-soin',
      name: 'Cartes de soin et de blessure',
      qty: '40 cartes',
      note: 'Les soins s’achètent chez l’Apothecary et se mélangent au paquet de blessures.',
      glyph: 'card',
      tint: '#9a2c1f',
      crop: { page: 4, x: 0.322, y: 0.383, w: 0.19, h: 0.1 },
    },
    {
      id: 'cartes-evenement',
      name: 'Cartes d’événement',
      qty: '83 cartes',
      note: 'Deux paquets : cité et Forêt Profonde. Une carte tirée, appliquée, puis archivée.',
      glyph: 'card',
      crop: { page: 4, x: 0.645, y: 0.383, w: 0.175, h: 0.105 },
    },
    {
      id: 'cartes-allie',
      name: 'Cartes d’allié',
      qty: '58 cartes',
      note: 'Les alliés rejoignent la Compagnie pour un temps. Les non-combattants ne servent pas en rencontre.',
      glyph: 'card',
      crop: { page: 4, x: 0.42, y: 0.292, w: 0.175, h: 0.108 },
    },
    {
      id: 'piste-temps',
      name: 'Pistes de Temps',
      qty: '13 pistes',
      note: 'Une par chapitre. Chaque déplacement y consomme une case.',
      glyph: 'board',
      tint: '#7d5c10',
      crop: { page: 4, x: 0.52, y: 0.512, w: 0.45, h: 0.148 },
    },
    {
      id: 'jetons-lieu',
      name: 'Jetons de lieu',
      qty: '30 jetons',
      note: 'Numérotés de 1 à 30. Un lieu sans jeton ne se visite pas.',
      glyph: 'token',
      crop: { page: 4, x: 0.552, y: 0.652, w: 0.115, h: 0.088 },
    },
    {
      id: 'jetons-temps',
      name: 'Jetons de temps',
      qty: '20 jetons',
      note: 'L’histoire en ajoute directement sur la piste, en plus des déplacements.',
      glyph: 'token',
      crop: { page: 4, x: 0.685, y: 0.658, w: 0.098, h: 0.082 },
    },
    {
      id: 'jetons-indice',
      name: 'Jetons d’indice',
      qty: '6 jetons',
      note: 'Ce que la Compagnie a compris. L’histoire s’y réfère : « si vous avez l’indice 2… ».',
      glyph: 'token',
      tint: '#7d5c10',
      crop: { page: 4, x: 0.8, y: 0.655, w: 0.14, h: 0.075 },
    },
    {
      id: 'fer',
      name: 'Jetons de fer',
      qty: '70 jetons',
      note: 'La monnaie. Aucune limite de possession, échangeable à tout moment.',
      glyph: 'token',
      tint: '#7d5c10',
      crop: { page: 4, x: 0.838, y: 0.728, w: 0.135, h: 0.18 },
    },
    {
      id: 'cartes-puissance',
      name: 'Cartes de Puissance',
      qty: '72 + 72 cartes',
      note: 'Un paquet pour les Oathsworn, un pour les ennemis, chacun en blanc, jaune, rouge et noir.',
      glyph: 'card',
      tint: '#9a2c1f',
      crop: { page: 5, x: 0.428, y: 0.328, w: 0.375, h: 0.085 },
    },
    {
      id: 'des',
      name: 'Dés',
      qty: '49 dés',
      note: '28 dés de Puissance, 15 dés de points de vie rouges, 2 dés de direction, 4 dés de suivi.',
      glyph: 'die',
      crop: { page: 5, x: 0.425, y: 0.185, w: 0.375, h: 0.145 },
    },
    {
      id: 'cubes',
      name: 'Cubes de Puissance',
      qty: '44 cubes',
      note: '16 jaunes, 16 rouges, 12 noirs. Ils marquent sur la piste ce que vos armes vous font tirer.',
      glyph: 'token',
      crop: { page: 5, x: 0.05, y: 0.41, w: 0.14, h: 0.123 },
    },
    {
      id: 'jetons-combat',
      name: 'Jetons de combat',
      qty: '125 jetons',
      note: 'Défense, +2 Animus, nouveau tirage, Empowered x3, Battleflow. Utilisables dans l’histoire comme en rencontre.',
      glyph: 'token',
      tint: '#1f4d3f',
      crop: { page: 5, x: 0.34, y: 0.418, w: 0.175, h: 0.1 },
    },
    {
      id: 'jetons-suivi',
      name: 'Jetons de suivi',
      qty: '56 jetons',
      note: 'Numérotés. Ils tiennent la défense et la régénération sur le plateau.',
      glyph: 'token',
      crop: { page: 5, x: 0.19, y: 0.48, w: 0.152, h: 0.07 },
    },
    {
      id: 'jetons-statut',
      name: 'Jetons de statut',
      qty: '32 jetons',
      note: 'Poison, saignement, estropié, et la Létalité propre au Cur.',
      glyph: 'token',
      tint: '#9a2c1f',
      crop: { page: 5, x: 0.19, y: 0.412, w: 0.152, h: 0.07 },
    },
    {
      id: 'animus',
      name: 'Animus',
      qty: '44 gemmes',
      note: 'L’énergie qui alimente les capacités. Un personnage complet en a autant que son maximum, un compagnon toujours deux.',
      glyph: 'token',
      tint: '#9a2c1f',
      crop: { page: 5, x: 0.045, y: 0.748, w: 0.13, h: 0.155 },
    },
    {
      id: 'fiches',
      name: 'Blocs de fiches',
      qty: '2 blocs',
      note: 'Une fiche par personnage, une feuille pour la Compagnie Libre : c’est là que la campagne s’écrit.',
      glyph: 'card',
      crop: { page: 5, x: 0.36, y: 0.058, w: 0.365, h: 0.122 },
    },
    {
      id: 'regles-speciales',
      name: 'Plateaux de règles spéciales',
      qty: '22 plateaux',
      note: 'Un par chapitre, posé face cachée : on ne le retourne que lorsque le jeu le dit.',
      glyph: 'board',
      crop: { page: 5, x: 0.088, y: 0.052, w: 0.25, h: 0.108 },
    },
    {
      id: 'enveloppes',
      name: 'Enveloppes mystère',
      qty: '31 enveloppes',
      note: '« Do Not Open Until Told » : elles contiennent les cartes de cité et les surprises de la campagne.',
      glyph: 'card',
      tint: '#9a2c1f',
      crop: { page: 5, x: 0.638, y: 0.405, w: 0.245, h: 0.22 },
    },
  ],

  /* ------------------------------------------------------------ chapitres */

  chapters: [
    {
      id: 'brief',
      title: 'Avant de commencer',
      kind: 'brief',
      goal: 'Savoir ce que ce tutoriel installe, et où s’arrête le livret qu’il suit.',
      steps: [
        {
          id: 'b1',
          kind: 'info',
          title: 'Posez la tablette à côté du livre d’histoire',
          body: [
            'Oathsworn est un jeu coopératif de dark fantasy pour un à quatre joueurs. Une campagne se déroule en chapitres.',
            'Le livret est en anglais : le tutoriel le traduit, et les mots que votre matériel porte en anglais sont surlignés dans les consignes.',
          ],
          components: ['livrets'],
          crop: { page: 4, x: 0.13, y: 0.072, w: 0.29, h: 0.205 },
          ref: 'Game Overview — p.3',
        },
        {
          id: 'b2',
          kind: 'info',
          title: 'Un chapitre, deux moitiés',
          body: [
            'L’histoire : la première moitié raconte le voyage de votre Compagnie. Elle se lit dans le livre d’histoire, sur les cartes de cité, et dure 30 à 60 minutes.',
            'La rencontre : la seconde moitié est le combat contre ce que vous traquiez — ou contre ce qui vous traquait. Elle se joue sur le plateau, avec les figurines, et dure 90 à 120 minutes.',
          ],
          crop: { page: 3, x: 0.06, y: 0.55, w: 0.27, h: 0.42 },
          ref: 'Game Overview — p.3',
        },
        {
          id: 'b3',
          kind: 'info',
          title: 'Ce tutoriel couvre l’histoire',
          body: [
            'Les règles de l’histoire sont dans le Story Rule Book, celui que ce tutoriel suit page par page.',
            'Celles de la rencontre sont dans un second livret, l’Encounter Rule Book, qui n’est pas couvert ici.',
          ],
          warn: 'Le livret le conseille lui-même : pour une première séance de trois heures ou moins, ne jouez que l’histoire du chapitre 1. Vous n’avez alors pas besoin de lire l’autre livret.',
          components: ['livrets'],
          crop: { page: 3, x: 0.33, y: 0.86, w: 0.537, h: 0.1 },
          ref: 'First Play Session — p.3',
        },
        {
          id: 'b4',
          kind: 'info',
          title: 'Le matériel a toujours raison',
          body: [
            'Le texte écrit sur un composant prime sur tout ce que dit le livret — et donc sur tout ce que dit ce tutoriel.',
          ],
          tip: 'Quand on vous demande d’archiver un composant, remettez-le dans la boîte à sa place d’origine : vous le retrouverez au chapitre suivant.',
          ref: 'Rule Book vs Component Rules, Archiving — p.3',
        },
        {
          id: 'b5',
          kind: 'info',
          title: 'Cartes ou dés, au choix',
          body: [
            'Les dés de Puissance remplacent à tout moment les paquets de Puissance. Chaque joueur choisit pour lui-même, peut mélanger les deux, mais doit décider avant de tirer.',
            'Les règles sont écrites en cartes : partout, « tirer » et « cartes » peuvent se lire « lancer » et « dés ».',
          ],
          tip: 'Le livret conseille les cartes plutôt que les dés pour les dégâts ennemis : le résultat est plus régulier.',
          components: ['cartes-puissance', 'des'],
          crop: { page: 3, x: 0.6, y: 0.55, w: 0.28, h: 0.3 },
          ref: 'Cards or Dice? — p.3',
        },
        {
          id: 'b6',
          kind: 'info',
          title: 'La sauvegarde est prévue',
          body: [
            'Vous pouvez jouer un chapitre entier d’une traite, ou vous arrêter entre l’histoire et la rencontre.',
            'La progression se range dans des sacs de sauvegarde, un par personnage et un pour la Compagnie.',
          ],
          ref: 'Game Overview — p.3',
        },
        {
          id: 'b7',
          kind: 'check',
          title: 'Ce que vous saurez faire',
          body: [
            'Former votre Compagnie Libre et installer vos personnages.',
            'Mener l’histoire : la carte, les lieux, le temps qui passe, les événements.',
            'Résoudre un test, une décision secrète, un round de combat, un échange.',
            'Fermer la séance et ranger la campagne pour la reprendre plus tard.',
          ],
        },
      ],
    },

    {
      id: 'materiel',
      title: 'Le matériel',
      kind: 'setup',
      goal: 'Reconnaître ce qui sert à l’histoire, et ce qui attend la rencontre.',
      steps: [
        {
          id: 'm1',
          kind: 'take',
          title: 'Les livres',
          body: [
            'Deux livrets de règles, deux livres d’histoire, un journal, et le livre de rencontre.',
            'Huit cartes de cité dorment dans des enveloppes mystère : ne les ouvrez que lorsque le jeu le demande.',
          ],
          components: ['livrets', 'story-books', 'journal', 'cartes-cite', 'enveloppes'],
          ref: 'Components — p.4',
        },
        {
          id: 'm2',
          kind: 'take',
          title: 'Les personnages',
          body: [
            '12 figurines Oathsworn, 12 plateaux de personnage, 12 cartes de Compagnon.',
            '193 cartes de capacité et 48 cartes d’archétype : elles servent à la rencontre et à la progression.',
          ],
          components: ['figurines', 'plateaux', 'cartes-compagnon', 'cartes-capacite', 'cartes-archetype'],
          ref: 'Components — p.4',
        },
        {
          id: 'm3',
          kind: 'take',
          title: 'Les cartes de la Compagnie',
          body: [
            '394 objets communs, 100 objets uniques, la carte Sac à dos et neuf aides de jeu.',
            '58 alliés, 83 événements, 40 soins et blessures, 27 séparateurs de cartes.',
          ],
          components: ['objets-communs', 'objets-uniques', 'sac-a-dos', 'cartes-allie', 'cartes-evenement', 'cartes-soin'],
          ref: 'Components — p.4',
        },
        {
          id: 'm4',
          kind: 'take',
          title: 'Le temps, les lieux, la monnaie',
          body: [
            '13 pistes de Temps, une par chapitre. 30 jetons de lieu, 20 jetons de temps, 6 jetons d’indice.',
            '70 jetons de fer : c’est la monnaie du jeu.',
          ],
          components: ['piste-temps', 'jetons-lieu', 'jetons-temps', 'jetons-indice', 'fer'],
          ref: 'Components — p.4',
        },
        {
          id: 'm5',
          kind: 'take',
          title: 'La Puissance',
          body: [
            '72 cartes de Puissance Oathsworn et 72 cartes ennemies, en quatre couleurs : blanc, jaune, rouge, noir.',
            '49 dés, dont 28 dés de Puissance et 15 dés de points de vie. 44 cubes pour la piste de Puissance.',
          ],
          components: ['cartes-puissance', 'des', 'cubes'],
          ref: 'Components — p.5',
        },
        {
          id: 'm6',
          kind: 'take',
          title: 'Jetons et fiches',
          body: [
            '125 jetons de combat, 56 jetons de suivi, 32 jetons de statut, 44 gemmes d’Animus.',
            'Deux blocs de fiches : une par personnage, une pour la Compagnie. 22 plateaux de règles spéciales, un par chapitre.',
          ],
          components: ['jetons-combat', 'jetons-suivi', 'jetons-statut', 'animus', 'fiches', 'regles-speciales'],
          ref: 'Components — p.5',
        },
      ],
    },

    {
      id: 'compagnie',
      title: 'Former la Compagnie Libre',
      kind: 'setup',
      goal: 'Choisir quatre Oathsworn, et le niveau de difficulté.',
      steps: [
        {
          id: 'c1',
          kind: 'info',
          title: 'Quatre Oathsworn, toujours',
          body: [
            'Une Compagnie Libre compte quatre personnages, quel que soit le nombre de joueurs autour de la table.',
            'À deux joueurs, chacun en mène deux. À un joueur, vous les menez tous les quatre.',
          ],
          crop: { page: 6, x: 0.128, y: 0.07, w: 0.31, h: 0.27 },
          ref: 'Forming a Free Company — p.6',
        },
        {
          id: 'c2',
          kind: 'info',
          title: 'Personnage complet, ou compagnon',
          body: [
            'Chaque Oathsworn se joue en version complète ou en compagnon, la version simplifiée du même personnage.',
            'Un personnage complet donne accès à tous les mécanismes du jeu. Un compagnon est aussi puissant, mais n’a que deux capacités : ses tours sont bien plus rapides.',
          ],
          warn: 'Les deux comptent comme Oathsworn, autant dans l’histoire que dans la rencontre.',
          components: ['plateaux', 'cartes-compagnon'],
          crop: { page: 6, x: 0.02, y: 0.33, w: 0.43, h: 0.22 },
          ref: 'Full Characters and Companions — p.6',
        },
        {
          id: 'c3',
          kind: 'info',
          title: 'Douze personnages, de une à cinq étoiles',
          body: [
            'Complexité 1 : A’Dendri Ranger, Scar Tribe Exile. Complexité 2 : Priest.',
            'Complexité 3 : Ursus Warbear, Warden, Penitent, Cur, Thracian Blade. Complexité 4 : Avi Harbinger.',
            'Complexité 5 : Witch, Huntress, et l’A’Dendri Grove Maiden, qui se débloque en cours de campagne.',
          ],
          tip: 'La complexité est aussi imprimée au dos du plateau de personnage.',
          components: ['plateaux'],
          crop: { page: 6, x: 0.45, y: 0.14, w: 0.48, h: 0.836 },
          ref: 'Full Character Setup — p.6',
        },
        {
          id: 'c4',
          kind: 'take',
          title: 'Choisissez vos quatre Oathsworn',
          body: [
            'Pour une première partie, prenez plutôt des complexités basses : le Ranger, l’Exilé, le Prêtre.',
            'Rien n’empêche de panacher : deux personnages complets et deux compagnons, par exemple.',
          ],
          components: ['figurines', 'plateaux'],
          ref: 'Forming a Free Company — p.6',
        },
        {
          id: 'c5',
          kind: 'info',
          title: 'Choisissez votre difficulté',
          body: [
            'Journeyman : +2 de défense pour les Oathsworn et les alliés. Pilgrim : +1. Free Company, la difficulté standard : 6 points de vie au maximum, aucun bonus.',
            'Grim : 5 points de vie au maximum, mais un objet unique ou commun de plus par rencontre. Dread : 4 points de vie, deux objets de plus.',
          ],
          warn: 'La difficulté se change avant chaque chapitre. Un changement de défense se reporte sur le jeton de suivi de la défense.',
          components: ['jetons-suivi'],
          crop: { page: 9, x: 0.522, y: 0.185, w: 0.365, h: 0.455 },
          ref: 'Difficulty Levels — p.9',
        },
        {
          id: 'c6',
          kind: 'info',
          title: 'La variante Hardcore, si vous l’osez',
          body: [
            'À 0 point de vie, un Oathsworn ne tombe plus inconscient : il meurt. Notez sa classe sur la piste Hardcore de la feuille de Compagnie Libre.',
            'Tout Oathsworn qui finit une rencontre à 1 ou 2 points de vie prend en plus une carte de blessure.',
          ],
          warn: 'Un mort ne se rejoue pas de la campagne. S’il vous reste moins de quatre Oathsworn disponibles, le voyage s’arrête là.',
          crop: { page: 9, x: 0.522, y: 0.612, w: 0.365, h: 0.34 },
          ref: 'Hardcore Variant — p.9',
        },
      ],
    },

    {
      id: 'setup-perso',
      title: 'Mise en place : les personnages',
      kind: 'setup',
      modes: ['tuto', 'setup'],
      goal: 'Chaque Oathsworn est prêt, plateau réglé et objets en main.',
      steps: [
        {
          id: 'sp1',
          kind: 'place',
          title: '1. Le plateau de personnage, face visible',
          body: ['Laissez la place d’une carte sur ses quatre côtés : les objets viendront s’y glisser.'],
          components: ['plateaux'],
          crop: { page: 7, x: 0.47, y: 0.018, w: 0.45, h: 0.225 },
          ref: 'Full Character Setup — p.7',
        },
        {
          id: 'sp2',
          kind: 'place',
          title: '2. Un dé de points de vie dans son emplacement',
          body: [
            'Début de chapitre : réglez-le sur son maximum, 6 par défaut.',
            'Si vous enchaînez sur une rencontre, réglez-le sur les points de vie notés sur la fiche de personnage.',
          ],
          components: ['des'],
          crop: { page: 7, x: 0.47, y: 0.018, w: 0.45, h: 0.225 },
          ref: 'Full Character Setup — p.7',
        },
        {
          id: 'sp3',
          kind: 'take',
          title: '3. Une fiche de personnage',
          body: [
            'Début de campagne : donnez un nom à votre personnage.',
            'Reportez ensuite la régénération et l’Animus maximum imprimés sur le plateau, en cochant les cases correspondantes de la fiche.',
          ],
          tip: 'On coche des cases, on n’écrit pas de chiffre : quand la valeur monte en campagne, on coche simplement une case de plus.',
          components: ['fiches'],
          crop: { page: 7, x: 0.325, y: 0.195, w: 0.145, h: 0.085 },
          ref: 'Full Character Setup — p.7 ; FAQ — p.17',
        },
        {
          id: 'sp4',
          kind: 'place',
          title: '4. Régénération et gemmes d’Animus',
          body: [
            'Un jeton de suivi sur l’emplacement de régénération, à la valeur notée sur la fiche.',
            'Prenez autant de gemmes d’Animus que votre Animus maximum, et posez-les sur la réserve, à gauche de la piste d’Animus.',
          ],
          components: ['jetons-suivi', 'animus'],
          crop: { page: 7, x: 0.47, y: 0.018, w: 0.45, h: 0.225 },
          ref: 'Full Character Setup — p.7',
        },
        {
          id: 'sp5',
          kind: 'take',
          title: '5 et 6. La figurine, et trois fers',
          body: ['La figurine du personnage devant vous. Trois fers, si c’est le début de la campagne.'],
          components: ['figurines', 'fer'],
          crop: { page: 7, x: 0.352, y: 0.018, w: 0.115, h: 0.135 },
          ref: 'Full Character Setup — p.7',
        },
        {
          id: 'sp6',
          kind: 'take',
          title: '7. Les objets de départ',
          body: [
            'Prenez les objets communs du chapitre 1 dans l’organisateur de cartes 1 — ils portent un « 1 » au dos — et équipez votre personnage de ceux que la liste lui attribue.',
            'Ranger : arc court et bandages de cuir. Exilé : deux hachettes et bandages. Prêtre : masse d’armes et cotte de fer. Warden : épée courte, cotte de fer, bouclier.',
          ],
          warn: 'Les cartes d’objet se tiennent en main, face visible. Remettez le reste des objets communs du chapitre 1 dans l’organisateur.',
          components: ['objets-communs'],
          crop: { page: 7, x: 0.077, y: 0.4, w: 0.302, h: 0.56 },
          ref: 'Starting Item Cards — p.7',
        },
        {
          id: 'sp7',
          kind: 'place',
          title: '8. Les cubes sur la piste de Puissance',
          body: [
            'Vos objets indiquent des cubes colorés : posez-les sur votre piste de Puissance.',
            'À court de place sur la piste, empilez les cubes les uns sur les autres.',
          ],
          components: ['cubes'],
          crop: { page: 7, x: 0.395, y: 0.388, w: 0.455, h: 0.165 },
          ref: 'Full Character Setup — p.7',
        },
        {
          id: 'sp8',
          kind: 'place',
          title: '9. La défense',
          body: [
            'Un jeton de suivi sur l’emplacement de défense, à la somme des valeurs de défense de vos objets.',
            'Aucun objet ne donne de défense ? Posez un jeton de valeur 1 : c’est le minimum.',
          ],
          warn: 'Ajoutez 1 si vous jouez en Pilgrim, 2 en Journeyman.',
          components: ['jetons-suivi'],
          crop: { page: 7, x: 0.395, y: 0.388, w: 0.455, h: 0.165 },
          ref: 'Full Character Setup — p.7',
        },
        {
          id: 'sp9',
          kind: 'place',
          title: 'Un compagnon s’installe presque pareil',
          body: [
            'Sa carte de Compagnon sort de son sac de sauvegarde. Dé de points de vie, objets, cubes, trois fers, figurine et fiche : comme un personnage complet.',
            'Deux différences : il reçoit toujours 2 gemmes d’Animus, quel que soit son niveau, et sa défense vaut la somme de ses objets plus 2, avec un minimum de 3.',
          ],
          components: ['cartes-compagnon', 'animus'],
          crop: { page: 7, x: 0.393, y: 0.556, w: 0.475, h: 0.4 },
          ref: 'Companion Setup — p.7',
        },
        {
          id: 'sp10',
          kind: 'check',
          title: 'Personnage prêt',
          body: [
            'Plateau, dé de points de vie, fiche, régénération, Animus, figurine, fer, objets en main, cubes, défense.',
            'Vérifiez que la défense correspond bien aux objets équipés : c’est ce qui se déphase le plus vite.',
          ],
          ref: 'Full Character Setup — p.7',
        },
      ],
    },

    {
      id: 'setup-histoire',
      title: 'Mise en place : l’histoire',
      kind: 'setup',
      modes: ['tuto', 'setup'],
      goal: 'La table est prête, dans les onze étapes du livret.',
      steps: [
        {
          id: 'sh1',
          kind: 'place',
          title: '1 à 3. Jetons, dés, organisateur',
          body: [
            'Le plateau de rangement des jetons près de la zone de jeu.',
            'Le sac de dés, tous les dés sortis à côté. L’organisateur de cartes 1, à portée.',
          ],
          components: ['des'],
          crop: { page: 8, x: 0.128, y: 0.148, w: 0.328, h: 0.1 },
          ref: 'Component Setup — p.8',
        },
        {
          id: 'sh2',
          kind: 'place',
          title: '4. Les organisateurs de paquets de Puissance',
          body: [
            'Celui des joueurs et celui des rencontres, près de la zone de jeu.',
            'Leurs couvercles servent de défausses : posez-les en chevauchant les boîtes pour gagner de la place.',
          ],
          components: ['cartes-puissance'],
          crop: { page: 8, x: 0.522, y: 0.452, w: 0.47, h: 0.08 },
          ref: 'Component Setup — p.8',
        },
        {
          id: 'sh3',
          kind: 'place',
          title: '5 et 6. Cubes et fer',
          body: ['Les cubes de Puissance et les jetons de fer, en réserve commune près du plateau.'],
          components: ['cubes', 'fer'],
          ref: 'Component Setup — p.8',
        },
        {
          id: 'sh4',
          kind: 'take',
          title: '7. Videz le sac de la Compagnie Libre',
          body: [
            'Il contient ce qui appartient à la Compagnie : les alliés, et les objets que personne n’équipe.',
            'Sortez les cartes d’allié, face visible. Posez la carte Sac à dos sur la pile des objets. Donnez deux aides de jeu à chaque joueur.',
          ],
          warn: 'Au début du chapitre 1, le sac contient une feuille de Compagnie Libre, la carte Sac à dos vide, quatre alliés Men-at-Arms et huit aides de jeu.',
          components: ['sac-a-dos', 'cartes-allie', 'fiches'],
          crop: { page: 8, x: 0.118, y: 0.6, w: 0.332, h: 0.37 },
          ref: 'Free Company Bag — p.8',
        },
        {
          id: 'sh5',
          kind: 'place',
          title: '8. Le plateau de règles spéciales, face cachée',
          body: [
            'Prenez celui qui porte le numéro de votre chapitre et posez-le de côté, face cachée.',
          ],
          warn: 'Ne regardez pas son autre face avant qu’on vous le dise. C’est une règle, pas une politesse.',
          components: ['regles-speciales'],
          crop: { page: 5, x: 0.088, y: 0.052, w: 0.25, h: 0.108 },
          ref: 'Component Setup — p.8',
        },
        {
          id: 'sh6',
          kind: 'place',
          title: '9. Jetons de temps et de lieu',
          body: ['À côté du plateau, chiffre visible. Les jetons de lieu sont numérotés de 1 à 30.'],
          components: ['jetons-temps', 'jetons-lieu'],
          crop: { page: 4, x: 0.552, y: 0.652, w: 0.235, h: 0.088 },
          ref: 'Component Setup — p.8',
        },
        {
          id: 'sh7',
          kind: 'shuffle',
          title: '10. Les deux paquets d’événements',
          body: [
            'Début de campagne : prenez les cartes d’événement de cité 1 à 6, mélangez-les et posez-les chiffre visible — c’est le paquet d’événements de cité.',
            'Faites de même avec les événements de la Forêt Profonde 1 à 6. Le reste retourne dans l’organisateur.',
          ],
          tip: 'Aux chapitres suivants, les paquets courants dorment dans le sac de la Compagnie : il suffit de les ressortir.',
          components: ['cartes-evenement'],
          crop: { page: 8, x: 0.478, y: 0.746, w: 0.408, h: 0.212 },
          ref: 'Event Decks — p.8',
        },
        {
          id: 'sh8',
          kind: 'info',
          title: '11. Ce qu’on ne pose pas encore',
          body: [
            'La carte de la cité, la piste de Temps et la carte de chemin ne sont pas installées à la mise en place.',
            'L’histoire vous dira quand les sortir.',
          ],
          components: ['cartes-cite', 'piste-temps'],
          crop: { page: 8, x: 0.122, y: 0.53, w: 0.328, h: 0.07 },
          ref: 'Component Setup — p.8',
        },
        {
          id: 'sh9',
          kind: 'take',
          title: 'Ouvrez le livre d’histoire au chapitre 1',
          body: [
            'Ou lancez l’application compagnon et choisissez le chapitre 1 : les deux racontent la même histoire.',
            'Puis lisez, et laissez l’aventure se dérouler.',
          ],
          components: ['story-books', 'journal'],
          crop: { page: 10, x: 0.128, y: 0.126, w: 0.268, h: 0.205 },
          ref: 'Story Overview — p.10',
        },
        {
          id: 'sh10',
          kind: 'check',
          title: 'Vérifiez avant de commencer',
          body: [
            'Quatre Oathsworn installés, chacun avec ses objets et sa défense à jour.',
            'Le plateau de règles spéciales face cachée, les deux paquets d’événements prêts, les jetons à portée.',
            'Le sac de la Compagnie vidé : alliés visibles, sac à dos sur la pile d’objets.',
          ],
          ref: 'Story Setup — p.8',
        },
        {
          id: 'sh11',
          kind: 'info',
          title: 'Si vous préférez le mode Action Immédiate',
          modes: ['tuto'],
          body: [
            'Ce mode joue les rencontres sans l’histoire complète : un résumé, quelques tests, des récompenses, un échange, puis le combat.',
            'Il demande la mise en place des personnages et les étapes 1 à 8 ci-dessus, puis la page correspondante du livre de rencontre.',
          ],
          crop: { page: 9, x: 0.059, y: 0.72, w: 0.448, h: 0.243 },
          ref: 'Instant Action Mode — p.9',
        },
      ],
    },

    {
      id: 'navigation',
      title: 'Naviguer dans l’histoire',
      kind: 'play',
      goal: 'Savoir où la Compagnie peut aller, et ce que coûte un déplacement.',
      steps: [
        {
          id: 'n1',
          kind: 'info',
          title: 'On lit, on décide en groupe',
          body: [
            'Le livre d’histoire ou l’application déroule le récit. Les décisions se prennent en groupe, sauf quand le texte désigne un personnage précis.',
          ],
          components: ['story-books'],
          crop: { page: 10, x: 0.128, y: 0.126, w: 0.268, h: 0.205 },
          ref: 'Story Overview — p.10',
        },
        {
          id: 'n2',
          kind: 'place',
          title: 'Posez la carte de la cité quand on vous le dit',
          body: [
            'L’histoire vous demandera de sortir une carte de cité et de poser le marqueur de Compagnie Libre.',
            'Ce marqueur, c’est l’une de vos figurines Oathsworn : choisissez-en une et posez-la sur la carte.',
          ],
          components: ['cartes-cite', 'figurines'],
          crop: { page: 10, x: 0.17, y: 0.49, w: 0.73, h: 0.26 },
          ref: 'Story Overview — p.10',
        },
        {
          id: 'n3',
          kind: 'info',
          title: 'Un lieu se visite s’il porte un jeton',
          body: [
            'Les cartes portent des lieux numérotés. Un jeton de lieu posé sur un numéro signale que ce lieu est ouvert.',
            'La position du marqueur de Compagnie indique où vous êtes.',
          ],
          warn: 'Vous ne pouvez jamais vous rendre dans un lieu qui n’a pas de jeton dessus.',
          components: ['jetons-lieu'],
          crop: { page: 10, x: 0.402, y: 0.126, w: 0.263, h: 0.382 },
          ref: 'Locations — p.10',
        },
        {
          id: 'n4',
          kind: 'action',
          title: '« Placez les jetons de lieu »',
          body: ['Prenez les jetons indiqués et posez-les, chiffre visible, sur les emplacements correspondants de la carte.'],
          components: ['jetons-lieu'],
          ref: 'Locations — p.10',
        },
        {
          id: 'n5',
          kind: 'action',
          title: 'Se déplacer, en trois gestes',
          body: [
            'Déplacez le marqueur de Compagnie sur le lieu choisi.',
            'Retirez le jeton de ce lieu et posez-le sur la case suivante de la piste de Temps.',
            'Si cette case porte un effet immédiat, résolvez-le avant de lire l’entrée du lieu.',
          ],
          components: ['jetons-lieu', 'piste-temps'],
          crop: { page: 10, x: 0.17, y: 0.49, w: 0.73, h: 0.26 },
          ref: 'Locations — p.10',
        },
        {
          id: 'n6',
          kind: 'action',
          title: 'Lire l’entrée du lieu',
          body: [
            'Avec le livre : retournez le jeton de lieu et lisez l’entrée indiquée, selon que vous suivez le chemin A ou le chemin B.',
            'Avec l’application : cliquez le nom du lieu, elle vous emmène à la bonne entrée.',
          ],
          components: ['story-books'],
          crop: { page: 10, x: 0.674, y: 0.126, w: 0.266, h: 0.125 },
          ref: 'Locations — p.10',
        },
        {
          id: 'n7',
          kind: 'info',
          title: 'Les cartes de chemin',
          body: [
            'L’histoire vous demandera parfois de prendre un chemin. Si vous êtes déjà sur un chemin, retournez simplement la carte sur la bonne face.',
          ],
          crop: { page: 10, x: 0.674, y: 0.252, w: 0.266, h: 0.32 },
          ref: 'Path Cards — p.10',
        },
        {
          id: 'n8',
          kind: 'info',
          title: 'Fin de la partie Histoire',
          body: [
            'Quand l’histoire est terminée, vous enchaînez la rencontre, ou vous sauvegardez et vous arrêtez là.',
            'Dans ce cas, la rencontre se jouera à la séance suivante.',
          ],
          crop: { page: 10, x: 0.128, y: 0.365, w: 0.268, h: 0.135 },
          ref: 'End of Play Session — p.10',
        },
      ],
    },

    {
      id: 'temps',
      title: 'Le temps qui passe',
      kind: 'play',
      goal: 'Comprendre la piste de Temps et ce qu’elle déclenche.',
      steps: [
        {
          id: 't1',
          kind: 'info',
          title: 'Un déplacement coûte une unité de temps',
          body: [
            'Peu importe la distance sur la carte : aller quelque part coûte une case de la piste de Temps, matérialisée par le jeton de lieu qu’on y pose.',
            'L’histoire ajoute parfois des jetons de temps directement sur la piste.',
          ],
          components: ['piste-temps', 'jetons-temps'],
          crop: { page: 11, x: 0.345, y: 0.055, w: 0.6, h: 0.175 },
          ref: 'Time Track — p.11',
        },
        {
          id: 't2',
          kind: 'info',
          title: 'On remplit la piste dans l’ordre',
          body: ['Rangée du haut, de gauche à droite. Puis rangée du bas, de gauche à droite.'],
          components: ['piste-temps'],
          crop: { page: 11, x: 0.07, y: 0.046, w: 0.254, h: 0.229 },
          ref: 'Time Track — p.11',
        },
        {
          id: 't3',
          kind: 'info',
          title: 'Effets immédiats',
          body: [
            'Ils se résolvent au moment où le jeton est posé sur la case.',
            'C’est soit une carte d’événement à tirer, soit un déclencheur d’histoire qui vous renvoie à une entrée du livre.',
          ],
          warn: 'Avec l’application, les déclencheurs d’histoire partent tout seuls ; les cartes d’événement, non : c’est à vous de les tirer.',
          crop: { page: 11, x: 0.072, y: 0.508, w: 0.262, h: 0.145 },
          ref: 'Time Track — p.11',
        },
        {
          id: 't4',
          kind: 'info',
          title: 'Effets de fin d’histoire, et de fin de rencontre',
          body: [
            'Ils se résolvent à la fin de leur moitié de chapitre, et **si la case est restée vide**. Les premiers donnent souvent des jetons de combat.',
            'Un « objet unique supplémentaire » se coche dans la case Unique Item de la feuille de Compagnie : vous le gagnerez à l’épilogue.',
          ],
          tip: 'C’est tout le nerf du jeu : plus vous êtes efficaces, moins vous consommez de cases, plus vous récoltez.',
          components: ['fiches'],
          crop: { page: 11, x: 0.072, y: 0.28, w: 0.262, h: 0.617 },
          ref: 'Time Track — p.11',
        },
        {
          id: 't5',
          kind: 'info',
          title: 'Les effets du chapitre 1',
          body: [
            'Gain Token : tous les personnages gagnent un jeton de combat Battleflow.',
            'City Event : tirez et résolvez une carte d’événement de cité.',
            'Extra Unique Item : un objet unique de plus dans les récompenses de l’épilogue.',
          ],
          components: ['jetons-combat', 'cartes-evenement'],
          crop: { page: 11, x: 0.34, y: 0.249, w: 0.51, h: 0.161 },
          ref: 'Example Track Effects — p.11',
        },
        {
          id: 't6',
          kind: 'action',
          title: 'Tirer une carte d’événement',
          body: [
            'Deux paquets : cité et Forêt Profonde. Prenez la carte du dessus du paquet demandé, suivez ses instructions, puis archivez-la.',
            'Beaucoup d’événements sont dangereux, quelques-uns sont une aubaine.',
          ],
          components: ['cartes-evenement'],
          crop: { page: 11, x: 0.6, y: 0.5, w: 0.379, h: 0.28 },
          ref: 'Event Cards — p.11',
        },
        {
          id: 't7',
          kind: 'info',
          title: 'Les paquets grossissent avec la campagne',
          body: [
            'On vous demandera d’ajouter de nouvelles cartes d’événement, désignées par le numéro imprimé en haut à droite.',
            'Après un ajout, remélangez le paquet.',
          ],
          components: ['cartes-evenement'],
          ref: 'Event Cards — p.11',
        },
      ],
    },

    {
      id: 'compagnie-vie',
      title: 'La vie de la Compagnie',
      kind: 'play',
      goal: 'Gérer indices, objets, fer, points de vie, jetons et alliés.',
      steps: [
        {
          id: 'v1',
          kind: 'action',
          title: 'Les indices',
          body: [
            'Un indice représente une information importante que la Compagnie a comprise. Quand on vous en donne un, prenez le jeton correspondant et posez-le près de la piste de Temps.',
            'L’histoire s’y réfère ensuite : « si vous avez l’indice 2, placez le lieu 14 ».',
          ],
          components: ['jetons-indice'],
          crop: { page: 12, x: 0.128, y: 0.072, w: 0.47, h: 0.12 },
          ref: 'Gaining Clues — p.12',
        },
        {
          id: 'v2',
          kind: 'info',
          title: 'Ce qu’un Oathsworn peut porter',
          body: [
            'Au plus : une armure, un équipement, et deux mains d’armes ou de boucliers — soit une arme à deux mains, soit deux à une main, soit une arme et un bouclier.',
            'Chaque classe a ses restrictions, imprimées en bas à gauche de son plateau et rappelées sur la carte d’objet. L’équipement, lui, n’en a aucune.',
          ],
          components: ['objets-communs', 'plateaux'],
          crop: { page: 12, x: 0.128, y: 0.183, w: 0.272, h: 0.365 },
          ref: 'Item Cards — p.12',
        },
        {
          id: 'v3',
          kind: 'info',
          title: 'Le sac à dos',
          body: [
            'Tout ce qui n’est pas équipé va dans le sac à dos de la Compagnie, sous la carte Sac à dos : douze cartes au maximum.',
            'Au-delà, défaussez l’excédent vers le paquet du chapitre de ces objets — à vous de choisir quoi jeter, parmi les nouveaux comme les anciens.',
          ],
          warn: 'Les objets s’échangent librement entre joueurs et avec le sac pendant l’histoire, jamais pendant la rencontre.',
          components: ['sac-a-dos'],
          crop: { page: 12, x: 0.128, y: 0.69, w: 0.272, h: 0.105 },
          ref: 'Item Cards — p.12',
        },
        {
          id: 'v4',
          kind: 'action',
          title: 'Gagner des objets',
          body: [
            'Piochez à l’aveugle le nombre annoncé, sur le dessus du paquet d’objets du chapitre courant. Équipez-les, ou mettez-les au sac.',
          ],
          warn: 'Dès qu’un personnage change d’arme ou d’armure, ajustez sa piste de Puissance et sa valeur de défense.',
          components: ['objets-communs', 'cubes', 'jetons-suivi'],
          crop: { page: 12, x: 0.128, y: 0.855, w: 0.272, h: 0.1 },
          ref: 'Gaining Items — p.12',
        },
        {
          id: 'v5',
          kind: 'info',
          title: 'Quand la Compagnie n’a plus rien à porter',
          body: [
            'Si elle ne peut plus équiper quatre personnages avec deux mains, une armure et un équipement, elle peut « pétitionner la Flèche du Corbeau » : prendre autant d’objets que voulu dans les paquets communs du chapitre courant ou des précédents.',
            'Chaque objet ainsi obtenu coûte une case cochée sur la piste de KO de la feuille de Compagnie.',
          ],
          warn: 'Cette piste est votre score de campagne : plus elle monte, plus le résultat final est mauvais.',
          components: ['fiches'],
          crop: { page: 12, x: 0.66, y: 0.41, w: 0.291, h: 0.128 },
          ref: 'Running Out of Items — p.12',
        },
        {
          id: 'v6',
          kind: 'info',
          title: 'Le fer',
          body: [
            'C’est la monnaie. Un gain se répartit comme vous voulez entre les Oathsworn ; il n’y a pas de limite, et le fer s’échange à tout moment.',
            '« Gagnez X fers » désigne un total pour la Compagnie ; « chaque Oathsworn gagne X fers » désigne X pour chacun.',
          ],
          components: ['fer'],
          crop: { page: 12, x: 0.66, y: 0.55, w: 0.29, h: 0.218 },
          ref: 'Gaining and Losing Iron — p.12 ; FAQ — p.17',
        },
        {
          id: 'v7',
          kind: 'info',
          title: 'Payer quand on n’a pas assez de fer',
          body: [
            'Vous perdez aussi des objets du sac à dos. Chaque objet perdu réduit la dette de la moitié de sa valeur, arrondie au supérieur — la valeur est au dos de la carte.',
            'On perd des objets entiers, jamais un objet équipé. Si vous ne pouvez pas tout payer, vous payez ce que vous pouvez.',
          ],
          tip: 'Rien n’interdit d’échanger un objet équipé contre un objet du sac juste avant de choisir ce que vous perdez.',
          components: ['fer', 'sac-a-dos'],
          crop: { page: 12, x: 0.67, y: 0.78, w: 0.268, h: 0.092 },
          ref: 'Gaining and Losing Iron — p.12',
        },
        {
          id: 'v8',
          kind: 'action',
          title: 'Perdre des points de vie',
          body: ['Tournez le dé de points de vie sur sa nouvelle valeur. « L’échelle cède et vous tombez : perdez 1 point de vie » — le 5 devient un 4.'],
          components: ['des'],
          crop: { page: 13, x: 0.058, y: 0.04, w: 0.275, h: 0.29 },
          ref: 'Losing Hit Points — p.13',
        },
        {
          id: 'v9',
          kind: 'info',
          title: 'Les cartes de Puissance',
          body: [
            'On les tire au hasard des paquets de Puissance : les paquets Oathsworn pour un test ou une attaque des vôtres, le paquet ennemi pour les attaques adverses.',
            'Quatre niveaux, du plus faible au plus fort : blanc, jaune, rouge, noir. Une icône vaut une carte **ou** un dé de cette couleur, à votre choix.',
          ],
          warn: 'Paquet épuisé : remélangez sa défausse et continuez le tirage. Les défausses sont publiques, on peut les consulter.',
          components: ['cartes-puissance'],
          crop: { page: 13, x: 0.058, y: 0.322, w: 0.275, h: 0.275 },
          ref: 'Might Cards — p.13',
        },
        {
          id: 'v10',
          kind: 'info',
          title: 'Les jetons de combat',
          body: [
            'Ils se gagnent dans l’histoire comme dans la rencontre, se posent sur le plateau du personnage, et servent dans les deux moitiés du chapitre. Une fois dépensés, ils retournent à la réserve.',
            'Pendant l’histoire seulement, un Oathsworn peut dépenser un jeton de combat pour réinitialiser autant de paquets de Puissance qu’il veut.',
          ],
          warn: 'Les jetons non utilisés sont défaussés à la fin du chapitre, après l’épilogue : ils ne passent pas au chapitre suivant.',
          components: ['jetons-combat'],
          crop: { page: 13, x: 0.61, y: 0.024, w: 0.356, h: 0.196 },
          ref: 'Combat Tokens — p.13',
        },
        {
          id: 'v11',
          kind: 'info',
          title: 'Jetons permanents et alliés',
          body: [
            'Un jeton permanent se note sur la fiche de personnage : au début de chaque chapitre, il donne le jeton de combat correspondant. Une seule fois par chapitre.',
            'Un allié rejoint la Compagnie : prenez sa carte et posez-la avec les autres. Les alliés non-combattants ne peuvent pas servir pendant les rencontres.',
          ],
          components: ['fiches', 'cartes-allie'],
          crop: { page: 13, x: 0.62, y: 0.24, w: 0.321, h: 0.19 },
          ref: 'Permanent Tokens, Allies — p.13',
        },
      ],
    },

    {
      id: 'actions',
      title: 'Les actions de l’histoire',
      kind: 'play',
      goal: 'Résoudre un test, une décision secrète, un round de combat, un échange.',
      steps: [
        {
          id: 'a1',
          kind: 'action',
          title: 'Faire un test',
          body: [
            'L’histoire annonce un test et sa difficulté : test d’observation, de survie, ou test de base. Tous se résolvent de la même façon.',
            'Sauf mention contraire, **un seul test pour toute la Compagnie**. Parfois le texte dit « chaque Oathsworn », ou en désigne un seul.',
          ],
          components: ['cartes-puissance'],
          crop: { page: 14, x: 0.13, y: 0.1, w: 0.39, h: 0.29 },
          ref: 'Checks — p.14',
        },
        {
          id: 'a2',
          kind: 'action',
          title: 'Décidez combien de cartes blanches tirer',
          body: [
            'Jusqu’à dix, dans le paquet blanc des Oathsworn. La décision est collective si le test l’est.',
            'Tirez, additionnez. Total au moins égal à la difficulté et moins de deux cartes vierges : réussi.',
          ],
          warn: 'Deux cartes vierges ou plus, après les nouveaux tirages : le test échoue, quel que soit le total.',
          components: ['cartes-puissance'],
          crop: { page: 14, x: 0.13, y: 0.39, w: 0.39, h: 0.401 },
          ref: 'Checks — p.14',
        },
        {
          id: 'a3',
          kind: 'info',
          title: 'Les critiques',
          body: [
            'Une carte marquée d’un symbole critique fait tirer une carte de plus, de la même couleur, dont la valeur s’ajoute. Un nouveau critique relance le processus.',
          ],
          tip: 'Les cartes vierges tirées grâce à un critique ne font pas rater le test.',
          crop: { page: 14, x: 0.542, y: 0.05, w: 0.392, h: 0.44 },
          ref: 'Criticals — p.14',
        },
        {
          id: 'a4',
          kind: 'info',
          title: 'Les niveaux de succès',
          body: [
            'Quand le texte dit « pour chaque succès », comptez un succès par multiple de la difficulté.',
            'Difficulté 3 : 0 à 2 échec, 3 à 5 un succès, 6 à 8 deux succès, 9 à 11 trois succès.',
          ],
          crop: { page: 14, x: 0.542, y: 0.435, w: 0.392, h: 0.2 },
          ref: 'Levels of Success — p.14',
        },
        {
          id: 'a5',
          kind: 'info',
          title: 'Retirer une carte',
          body: [
            'Les jetons de nouveau tirage s’utilisent sur n’importe quel test : défaussez une carte tirée et tirez-en une autre du même type.',
            'Les jetons Empowered x3 ne s’utilisent que sur un test de Puissance : ils font monter trois fois de couleur, blanc vers jaune vers rouge vers noir.',
          ],
          warn: 'Empowered x3 ne s’applique jamais aux cartes supplémentaires tirées grâce à un critique.',
          components: ['jetons-combat'],
          crop: { page: 16, x: 0.128, y: 0.383, w: 0.378, h: 0.19 },
          ref: 'Checks — p.14 ; Appendix I — p.16',
        },
        {
          id: 'a6',
          kind: 'action',
          title: 'Une décision secrète',
          body: [
            'Sans aucune discussion, chacun prend un dé de points de vie et le règle sur la valeur de son choix.',
            'Révélez tous les dés en même temps, puis appliquez la règle donnée à cet endroit du livre.',
          ],
          tip: 'En solo, vous décidez pour la Compagnie, sans avoir à cacher quoi que ce soit.',
          components: ['des'],
          crop: { page: 14, x: 0.542, y: 0.645, w: 0.392, h: 0.135 },
          ref: 'Secret Decisions — p.14',
        },
        {
          id: 'a7',
          kind: 'action',
          title: 'Un round de combat',
          body: [
            'Une escarmouche résumée en une salve : **chaque** Oathsworn tire une attaque. Les jetons de combat sont autorisés, les capacités spéciales et d’objet non.',
            'Tirez autant de cartes de Puissance que votre piste l’autorise, plus jusqu’à dix blanches. Deux vierges ou plus : l’attaque manque.',
            'Sinon, la somme des valeurs est votre dégât : s’il atteint la défense de l’ennemi, c’est réussi.',
          ],
          warn: 'Les Oathsworn gagnent toujours un round de combat qui se déroule pendant l’histoire — mais chacun de ceux qui échouent perd 1 point de vie.',
          components: ['cartes-puissance'],
          crop: { page: 15, x: 0.058, y: 0.495, w: 0.285, h: 0.46 },
          ref: 'Round of Combat — p.15',
        },
        {
          id: 'a8',
          kind: 'action',
          title: 'Le Banksmith : acheter et vendre',
          body: [
            'Commencez un échange : étalez face visible tout le paquet d’objets communs du chapitre courant. Le prix d’un objet est le chiffre au dos de sa carte.',
            'Vous pouvez aussi vendre n’importe quel objet de la Compagnie, équipé ou non, pour la moitié de ce chiffre, arrondie au supérieur. Les objets vendus sont archivés.',
          ],
          tip: 'À la fin de l’échange, remélangez les cartes restantes dans le paquet du chapitre.',
          components: ['objets-communs', 'fer'],
          crop: { page: 15, x: 0.612, y: 0.062, w: 0.275, h: 0.19 },
          ref: 'The Banksmith — p.15',
        },
        {
          id: 'a9',
          kind: 'action',
          title: 'L’Apothecary : acheter des soins',
          body: [
            'Une carte de soin coûte autant de fers que le numéro du chapitre courant, et cinq au maximum par chapitre.',
            'Les soins obtenus vont dans le paquet de blessures, que l’on remélange aussitôt.',
          ],
          components: ['cartes-soin'],
          crop: { page: 15, x: 0.338, y: 0.388, w: 0.265, h: 0.152 },
          ref: 'The Apothecary — p.15',
        },
        {
          id: 'a10',
          kind: 'action',
          title: 'Envoyer un coursier',
          body: [
            'Sur une carte de cité, de ville ou de village, vous pouvez commencer un échange avec le Banksmith ou l’Apothecary sans y aller : payez un coursier.',
            'Le coursier coûte autant de fers que le numéro du chapitre, à chaque envoi. Vous pouvez en envoyer plusieurs au même endroit.',
          ],
          warn: 'Le marqueur de Compagnie ne bouge pas : c’est justement l’intérêt, vous ne dépensez pas de temps.',
          components: ['fer'],
          crop: { page: 15, x: 0.338, y: 0.222, w: 0.265, h: 0.155 },
          ref: 'Sending a Runner — p.15',
        },
      ],
    },

    {
      id: 'fin',
      title: 'Finir la séance',
      kind: 'debrief',
      goal: 'Enchaîner sur la rencontre, ou ranger la campagne proprement.',
      steps: [
        {
          id: 'f1',
          kind: 'info',
          title: 'Deux façons de terminer l’histoire',
          body: [
            'Vous enchaînez immédiatement la rencontre — c’est l’autre livret qui prend le relais.',
            'Ou vous sauvegardez, et la rencontre attendra la prochaine séance.',
          ],
          crop: { page: 10, x: 0.128, y: 0.365, w: 0.268, h: 0.135 },
          ref: 'End of Play Session — p.10',
        },
        {
          id: 'f2',
          kind: 'check',
          title: 'Les effets de fin d’histoire',
          body: [
            'Avant de ranger, parcourez la piste de Temps : chaque case portant un effet de fin d’histoire et **restée vide** se déclenche maintenant.',
            'Ces effets donnent le plus souvent des jetons de combat.',
          ],
          components: ['piste-temps', 'jetons-combat'],
          crop: { page: 11, x: 0.072, y: 0.28, w: 0.262, h: 0.2 },
          ref: 'Time Track — p.11',
        },
        {
          id: 'f3',
          kind: 'place',
          title: 'Le sac de sauvegarde de chaque personnage',
          body: [
            '1. La fiche de personnage. Si vous sauvegardez après l’histoire, notez-y vos points de vie courants ; après une rencontre, ne notez rien : vous repartirez au maximum.',
            '2. Les cartes de capacité, débloquées et verrouillées séparées par un séparateur. 3. La carte de Compagnon et les cartes d’archétype, séparées de même.',
            '4. Les cartes de blessure, les objets et le fer. 5. Les jetons de combat, uniquement si vous vous arrêtez entre l’histoire et la rencontre — sinon, archivez-les.',
          ],
          components: ['fiches', 'cartes-capacite', 'cartes-archetype', 'objets-communs', 'fer', 'jetons-combat'],
          crop: { page: 15, x: 0.338, y: 0.682, w: 0.265, h: 0.262 },
          ref: 'Saving the Game — p.15',
        },
        {
          id: 'f4',
          kind: 'place',
          title: 'Le sac de la Compagnie Libre',
          body: [
            '1. La feuille de Compagnie Libre. Entre l’histoire et la rencontre, cochez-y ce qui doit l’être : objet unique supplémentaire gagné sur la piste de Temps, plateau de règles spéciales révélé, embuscade.',
            '2. La carte Sac à dos et tous les objets non équipés. 3. Les cartes d’allié. 4. Les deux paquets d’événements.',
          ],
          components: ['fiches', 'sac-a-dos', 'cartes-allie', 'cartes-evenement'],
          crop: { page: 15, x: 0.608, y: 0.722, w: 0.29, h: 0.25 },
          ref: 'Saving the Game — p.15',
        },
        {
          id: 'f5',
          kind: 'check',
          title: 'Puis archivez tout le reste',
          body: [
            'Chaque composant retourne à sa place dans la boîte. C’est ce qui rend la reprise possible sans tout réinstaller.',
          ],
          warn: 'Les jetons de combat inutilisés sont défaussés à la fin d’un chapitre, après l’épilogue. Ils ne passent jamais au chapitre suivant.',
          ref: 'Saving the Game — p.15',
        },
      ],
    },

    {
      id: 'rp',
      title: 'Reprendre la campagne',
      kind: 'setup',
      modes: ['reprise'],
      goal: 'Ressortir les sacs et remonter la table exactement où vous l’aviez laissée.',
      steps: [
        {
          id: 'rp1',
          kind: 'info',
          title: 'Tout est dans les sacs',
          body: [
            'Oathsworn se sauvegarde pour de bon : un sac par personnage, un pour la Compagnie. Reprendre, c’est les vider dans l’ordre.',
            'Le reste du matériel a été archivé à sa place dans la boîte.',
          ],
          warn: 'Ne refaites pas la mise en place de campagne : elle écraserait tout ce que vous avez gagné.',
          components: ['fiches'],
          crop: { page: 15, x: 0.338, y: 0.608, w: 0.562, h: 0.34 },
          ref: 'Saving the Game — p.15',
        },
        {
          id: 'rp2',
          kind: 'check',
          title: 'Où vous en étiez',
          body: [
            'Vous vous êtes arrêté entre l’histoire et la rencontre : la feuille de Compagnie porte les cases cochées, et vos jetons de combat sont dans les sacs. Reprenez à la rencontre.',
            'Vous vous êtes arrêté après une rencontre : c’est un nouveau chapitre qui commence, avec une nouvelle histoire.',
          ],
          components: ['fiches'],
          ref: 'Saving the Game — p.15',
        },
        {
          id: 'rp3',
          kind: 'take',
          title: 'Chacun reprend son sac',
          body: [
            'Sortez la fiche de personnage : elle porte le nom, la régénération, l’Animus maximum, les jetons permanents et, si vous avez sauvegardé après l’histoire, les points de vie courants.',
          ],
          components: ['fiches'],
          crop: { page: 13, x: 0.62, y: 0.24, w: 0.321, h: 0.19 },
          ref: 'Saving the Game — p.15',
        },
        {
          id: 'rp4',
          kind: 'place',
          title: 'Remontez le plateau',
          body: [
            'Plateau de personnage face visible, dé de points de vie dans son emplacement — au maximum si un nouveau chapitre commence, à la valeur notée sinon.',
            'Jeton de suivi de régénération à la valeur de la fiche, gemmes d’Animus sur la réserve, figurine devant vous.',
          ],
          components: ['plateaux', 'des', 'jetons-suivi', 'animus', 'figurines'],
          crop: { page: 7, x: 0.47, y: 0.018, w: 0.45, h: 0.225 },
          ref: 'Full Character Setup — p.7',
        },
        {
          id: 'rp5',
          kind: 'take',
          title: 'Vos cartes, dans l’ordre du sac',
          body: [
            'Les cartes de capacité, débloquées devant le séparateur, verrouillées derrière. La carte de Compagnon et les archétypes, rangés de même.',
            'Les cartes de blessure, les objets équipés, et votre fer.',
          ],
          components: ['cartes-capacite', 'cartes-archetype', 'objets-communs', 'fer'],
          ref: 'Saving the Game — p.15',
        },
        {
          id: 'rp6',
          kind: 'place',
          title: 'Puissance et défense',
          body: [
            'Reposez les cubes sur la piste de Puissance d’après vos objets équipés, et le jeton de suivi de défense à la somme de leurs valeurs de défense.',
          ],
          warn: 'Minimum 1 pour un personnage complet, 3 pour un compagnon. Ajoutez 1 en Pilgrim, 2 en Journeyman.',
          components: ['cubes', 'jetons-suivi'],
          crop: { page: 7, x: 0.395, y: 0.388, w: 0.455, h: 0.165 },
          ref: 'Full Character Setup — p.7',
        },
        {
          id: 'rp7',
          kind: 'take',
          title: 'Le sac de la Compagnie',
          body: [
            'La feuille de Compagnie Libre : elle porte la piste de KO, la piste Hardcore et les cases cochées du chapitre.',
            'La carte Sac à dos avec les objets non équipés, les cartes d’allié face visible, et les deux paquets d’événements.',
          ],
          warn: 'Ne remélangez pas les paquets d’événements : ils ont été rangés dans l’état où vous les aviez laissés.',
          components: ['fiches', 'sac-a-dos', 'cartes-allie', 'cartes-evenement'],
          crop: { page: 8, x: 0.118, y: 0.6, w: 0.332, h: 0.37 },
          ref: 'Free Company Bag — p.8 ; Saving the Game — p.15',
        },
        {
          id: 'rp8',
          kind: 'place',
          title: 'Ressortez le reste du matériel commun',
          body: [
            'Le plateau de rangement des jetons, les dés, l’organisateur de cartes du chapitre, les organisateurs de paquets de Puissance, les cubes et le fer.',
            'Le plateau de règles spéciales du chapitre courant, face cachée — sauf si la feuille de Compagnie indique qu’il a déjà été révélé.',
          ],
          components: ['des', 'cartes-puissance', 'cubes', 'fer', 'regles-speciales'],
          crop: { page: 8, x: 0.128, y: 0.148, w: 0.328, h: 0.44 },
          ref: 'Component Setup — p.8',
        },
        {
          id: 'rp9',
          kind: 'check',
          title: 'Si vous repreniez au milieu d’une histoire',
          body: [
            'Le livret ne prévoit la sauvegarde qu’entre les deux moitiés d’un chapitre : au milieu d’une histoire, il faut avoir laissé la table montée.',
            'Dans ce cas, vérifiez la carte de la cité, la position du marqueur de Compagnie, les jetons de lieu restants et la piste de Temps.',
          ],
          components: ['cartes-cite', 'jetons-lieu', 'piste-temps'],
          crop: { page: 10, x: 0.17, y: 0.49, w: 0.73, h: 0.26 },
          ref: 'End of Play Session — p.10',
        },
        {
          id: 'rp10',
          kind: 'info',
          title: 'Trois règles qu’on oublie entre deux séances',
          body: [
            'Les jetons de combat ne survivent pas à la fin d’un chapitre, mais les jetons permanents en redonnent au début du suivant.',
            'Un déplacement coûte une case de piste de Temps, quelle que soit la distance.',
            'Un lieu sans jeton de lieu ne se visite pas.',
          ],
          ref: 'Time Track — p.11 ; Combat Tokens — p.13',
        },
      ],
    },

    {
      id: 'r-histoire',
      title: 'Rappel : mener l’histoire',
      kind: 'play',
      modes: ['recap'],
      goal: 'La boucle de l’histoire, dans l’ordre où elle se joue.',
      steps: [
        {
          id: 'rr1',
          kind: 'info',
          title: 'La boucle',
          body: [
            'On lit l’entrée courante, on décide en groupe, on choisit un lieu qui porte un jeton, on s’y déplace.',
            'Le jeton de lieu passe sur la piste de Temps ; s’il y a un effet immédiat, il se résout avant la lecture.',
          ],
          crop: { page: 10, x: 0.402, y: 0.126, w: 0.263, h: 0.382 },
          ref: 'Locations — p.10',
        },
        {
          id: 'rr2',
          kind: 'info',
          title: 'La piste de Temps',
          body: [
            'Rangée du haut de gauche à droite, puis rangée du bas. Immédiat à la pose ; fin d’histoire et fin de rencontre seulement si la case est restée vide.',
            'Chapitre 1 : Gain Token, City Event, Extra Unique Item.',
          ],
          crop: { page: 11, x: 0.345, y: 0.055, w: 0.6, h: 0.175 },
          ref: 'Time Track — p.11',
        },
        {
          id: 'rr3',
          kind: 'info',
          title: 'Les tests',
          body: [
            'Un seul test pour la Compagnie, sauf mention contraire. Jusqu’à dix cartes blanches, total contre la difficulté.',
            'Deux vierges ou plus, l’échec est acquis. Un critique fait tirer une carte de plus de la même couleur.',
          ],
          crop: { page: 14, x: 0.13, y: 0.39, w: 0.39, h: 0.401 },
          ref: 'Checks — p.14',
        },
        {
          id: 'rr4',
          kind: 'info',
          title: 'Le round de combat',
          body: [
            'Chaque Oathsworn tire une attaque : ses cartes de Puissance plus jusqu’à dix blanches. Deux vierges, l’attaque manque.',
            'Les Oathsworn gagnent toujours pendant l’histoire, mais chaque échec coûte 1 point de vie.',
          ],
          crop: { page: 15, x: 0.058, y: 0.495, w: 0.285, h: 0.46 },
          ref: 'Round of Combat — p.15',
        },
        {
          id: 'rr5',
          kind: 'info',
          title: 'Les échanges',
          body: [
            'Banksmith : achat au prix du dos de la carte, revente à la moitié arrondie au supérieur.',
            'Apothecary : cinq soins par chapitre au maximum, au prix du numéro du chapitre. Un coursier coûte aussi le numéro du chapitre.',
          ],
          crop: { page: 15, x: 0.338, y: 0.038, w: 0.562, h: 0.57 },
          ref: 'Banksmith and Apothecary — p.15',
        },
        {
          id: 'rr6',
          kind: 'info',
          title: 'Objets et fer',
          body: [
            'Une armure, un équipement, deux mains. Le reste au sac à dos, douze cartes au maximum, échangeable pendant l’histoire seulement.',
            'Pas assez de fer : on perd des objets du sac, chacun valant la moitié de son prix, arrondie au supérieur.',
          ],
          crop: { page: 12, x: 0.128, y: 0.183, w: 0.272, h: 0.365 },
          ref: 'Item Cards, Iron — p.12',
        },
        {
          id: 'rr7',
          kind: 'info',
          title: 'Les jetons',
          body: [
            'Défense et +2 Animus servent en rencontre. Nouveau tirage et Empowered x3 servent aussi dans l’histoire.',
            'Un jeton de combat dépensé pendant l’histoire réinitialise autant de paquets de Puissance que vous voulez.',
          ],
          crop: { page: 16, x: 0.13, y: 0.087, w: 0.38, h: 0.863 },
          ref: 'Appendix I — p.16',
        },
      ],
    },

    {
      id: 'debrief',
      title: 'Après cette première partie',
      kind: 'debrief',
      goal: 'Savoir ce qui vous attend, et ce que ce tutoriel n’a pas couvert.',
      steps: [
        {
          id: 'z1',
          kind: 'info',
          title: 'La rencontre vous attend',
          body: [
            'La seconde moitié du chapitre se joue sur le plateau, avec les figurines : c’est là que se règle ce que l’histoire a mis en place.',
            'Ses règles sont dans l’Encounter Rule Book. Ce tutoriel ne les couvre pas.',
          ],
          components: ['livrets'],
          crop: { page: 5, x: 0.72, y: 0.024, w: 0.246, h: 0.176 },
          ref: 'Game Overview — p.3',
        },
        {
          id: 'z2',
          kind: 'info',
          title: 'Ce que la campagne va ajouter',
          body: [
            'Des cartes d’événement nouvelles dans les deux paquets, des objets de chapitres supérieurs, des archétypes, des alliés, et l’A’Dendri Grove Maiden.',
            'La montée de niveau et le changement de personnage passent par le système de niveau rapide de l’autre livret.',
          ],
          ref: 'FAQ — p.17',
        },
        {
          id: 'z3',
          kind: 'info',
          title: 'Régler la difficulté au fil des chapitres',
          body: [
            'Le niveau se change avant chaque chapitre : montez en Grim ou en Dread pour plus d’objets et moins de points de vie, redescendez en Pilgrim si la Forêt Profonde vous a trop coûté.',
          ],
          crop: { page: 9, x: 0.522, y: 0.185, w: 0.365, h: 0.455 },
          ref: 'Difficulty Levels — p.9',
        },
        {
          id: 'z4',
          kind: 'check',
          title: 'Avant de ranger',
          body: [
            'Résolvez les effets de fin d’histoire restés vides, remplissez les sacs de sauvegarde, archivez le reste.',
            'Et notez sur le journal où vous en êtes : c’est ce que vous relirez dans trois semaines.',
          ],
          components: ['journal', 'fiches'],
          ref: 'Saving the Game — p.15',
        },
      ],
    },
  ],
}
