/**
 * Tainted Grail : Rois de la Ruine — première partie tutorielle.
 *
 * Source : « Tainted Grail : Rois de la Ruine — Livret de Règles », édition
 * française (Awaken Realms). Les numéros de page du champ `ref` et des
 * découpes sont ceux imprimés sur le livret, qui coïncident avec l'index des
 * pages du PDF (pageOffset 0).
 *
 * Périmètre : le tutoriel installe la campagne, déroule un jour complet —
 * aube, journée, crépuscule — et enseigne les deux systèmes de rencontre,
 * combat et diplomatie. Il ne raconte pas l'histoire : le journal
 * d'exploration s'en charge, et les règles secrètes de la page 37 ne sont
 * pas lues tant que la campagne ne le demande pas.
 *
 * Le jeu est un standalone : il ne demande pas *La Chute d'Avalon*, et les
 * deux tutoriels sont indépendants l'un de l'autre.
 */

import type { Tutorial } from '../engine/types'

export const taintedgrailkor: Tutorial = {
  id: 'taintedgrailkor',
  title: 'Rois de la Ruine',
  tagline:
    'À l’ouest d’Avalon, coupés du Vrai Roi par les brumes, trois héros sont revenus changés. On les appelle désormais les Rois de la Ruine.',
  contentVersion: '1.0',
  publisher: 'Awaken Realms',
  author: 'Krzysztof Piskorski, Marcin Świerkot',
  players: {
    min: 1,
    max: 4,
    recommended: 1,
    labels: { 1: 'Solo' },
    notes: {
      1: 'En solo, un seul personnage à gérer et la carte « Vous êtes mourant ! » version solo. Le livret rappelle que le nombre de personnages en jeu change le coût des Pierres de Passage.',
      2: 'À deux, le livret conseille d’associer Elgan à Iunis, ou Gerdwyn à Osbert : leurs objectifs personnels se terminent dans la même région.',
      3: 'À trois, activer une Pierre de Passage coûte le triple : trois personnages en jeu, trois fois le prix.',
      4: 'À quatre, le prix des Pierres de Passage est le plus lourd, et le temps le plus court : plus vous êtes nombreux, plus vite les conséquences tombent.',
    },
  },
  minutes: 120,

  // Le livret est un parchemin gris-bleu à titres rouge sang, très différent
  // du beige chaud de « La Chute d'Avalon » : les deux jeux se distinguent
  // d'un coup d'œil sur l'accueil, et les découpes se posent dans la page.
  theme: {
    scheme: 'light',
    bg: '#dde2e6',
    bg2: '#eaeef1',
    bg3: '#f5f8fa',
    stroke: '#aab5bd',
    strokeSoft: '#c4ced5',
    fg: '#1d242a',
    fgDim: '#4a555e',
    fgFaint: '#68737c',
    accent: '#8e1420',
    accent2: '#2c5f63',
    accentInk: '#fdf6f4',
    ok: '#2f6b3f',
    warn: '#8a5a10',
    danger: '#9d2418',
    radius: '6px',
  },

  source: {
    pdf: 'Tainted Grail Rois de la Ruine - Regles.pdf',
    assetId: 'taintedgrailkor',
    pageOffset: 0,
    credit: 'Règles officielles FR — Awaken Realms',
  },

  cover: { page: 1, x: 0.08, y: 0.545, w: 0.84, h: 0.27 },

  scope: {
    covered: [
      'La mise en place de la campagne, des 13 étapes officielles',
      'Les quatre personnages et ce qui les distingue',
      'Le cours du jour : aube, journée, crépuscule',
      'Les six actions de la journée et leurs trois coûts',
      'Explorer, et lire le journal d’exploration',
      'Les lieux, les faces Wyrd et dégagée, les Pierres de Passage',
      'Les Gardiens et le dé Gardien',
      'Une rencontre de combat complète, tour par tour',
      'Une rencontre de diplomatie, durée et affinité',
      'Le crépuscule : repos, récupération, progression, visions',
      'Sauvegarder la campagne, et la reprendre',
    ],
    skipped: [
      'Les règles secrètes de la page 37, à ne pas lire sans permission',
      'L’histoire elle-même : le journal d’exploration s’en charge',
      'Le guide d’initiation, qui a son propre livret et son paquet',
      'Le détail des cartes Combat et Diplomatie de chaque personnage',
      'Les modes Histoire et Défi, signalés mais pas déroulés',
    ],
  },

  /* ------------------------------------------------------------ matériel */

  components: [
    {
      id: 'plateaux',
      name: 'Plateaux Personnage',
      qty: '4 plateaux',
      note: 'Avec leurs tuiles amovibles. Ils portent les trois pistes, les caractéristiques, les ressources et la capacité du personnage.',
      glyph: 'board',
      tint: '#8e1420',
      crop: { page: 3, x: 0.09, y: 0.755, w: 0.21, h: 0.13 },
    },
    {
      id: 'figurines',
      name: 'Figurines de Personnage',
      qty: '4 + 4 figurines',
      note: 'Une par personnage, et sa version Wyrdforme pour plus tard dans la campagne.',
      glyph: 'figure',
      crop: { page: 2, x: 0.04, y: 0.545, w: 0.35, h: 0.13 },
    },
    {
      id: 'lettres',
      name: 'Lettres de départ',
      qty: '4 lettres',
      note: 'Une par personnage. C’est par elle que commence la partie : on la lit avant de prendre son plateau.',
      glyph: 'card',
      crop: { page: 2, x: 0.395, y: 0.205, w: 0.115, h: 0.145 },
    },
    {
      id: 'journal',
      name: 'Journal d’exploration',
      qty: '1 journal',
      note: 'Quatre sections : les Lieux, le Livre des secrets, les Échos de la Ruine et le journal du Guide d’Initiation.',
      glyph: 'card',
      tint: '#8e1420',
      crop: { page: 2, x: 0.785, y: 0.19, w: 0.115, h: 0.165 },
    },
    {
      id: 'fiches-sauvegarde',
      name: 'Fiches de sauvegarde',
      qty: '15 fiches',
      note: 'Un schéma de plateau par personnage. C’est là qu’on écrit l’état de la campagne quand on range la boîte.',
      glyph: 'card',
      crop: { page: 2, x: 0.525, y: 0.205, w: 0.115, h: 0.14 },
    },
    {
      id: 'fiches-statut',
      name: 'Fiches de statut',
      qty: '5 fiches',
      note: 'Les statuts obtenus par le groupe, qui changent définitivement la façon dont le monde réagit. Au verso, les statuts « Le temps passe ».',
      glyph: 'card',
      crop: { page: 2, x: 0.65, y: 0.205, w: 0.125, h: 0.14 },
    },
    {
      id: 'cartes-lieu',
      name: 'Cartes Lieu',
      qty: '74 cartes',
      note: 'Grand format, recto-verso : une face dégagée et une face Wyrd. Leur numéro renvoie au journal d’exploration.',
      glyph: 'card',
      tint: '#2c5f63',
      crop: { page: 3, x: 0.1, y: 0.52, w: 0.16, h: 0.145 },
    },
    {
      id: 'cartes-combat',
      name: 'Cartes Combat et Diplomatie',
      qty: '60 standard, 80 avancées',
      note: 'Le paquet de chaque personnage. La lettre à côté du numéro dit son type : B de base, A avancée, Q gagnée en quête.',
      glyph: 'card',
      tint: '#8e1420',
      crop: { page: 3, x: 0.095, y: 0.155, w: 0.155, h: 0.145 },
    },
    {
      id: 'cartes-rencontre',
      name: 'Cartes Rencontre',
      qty: '46 vertes, 38 violettes, 38 bleues',
      note: 'Les vertes et les violettes sont des combats, les bleues des défis de diplomatie. Le dos donne la couleur.',
      glyph: 'card',
      crop: { page: 3, x: 0.435, y: 0.155, w: 0.29, h: 0.145 },
    },
    {
      id: 'cartes-evenement',
      name: 'Cartes Événement',
      qty: '18 Aléatoire, 77 Histoire',
      note: 'Une carte révélée chaque aube. Les Aléatoires reviennent sous leur pile, les autres retournent dans la boîte.',
      glyph: 'card',
      crop: { page: 3, x: 0.1, y: 0.315, w: 0.29, h: 0.145 },
    },
    {
      id: 'cartes-secret',
      name: 'Cartes Secret',
      qty: '219 standard, 38 petit format',
      note: 'Le grand paquet ne se regarde pas et ne se mélange jamais : on n’y prend que la carte dont le jeu donne le numéro.',
      glyph: 'card',
      tint: '#8e1420',
      crop: { page: 3, x: 0.475, y: 0.315, w: 0.19, h: 0.145 },
    },
    {
      id: 'cartes-objet',
      name: 'Cartes Objet',
      qty: '82 cartes',
      note: 'Petit format. Les objets « A » et les Consommables forment les deux paquets de départ.',
      glyph: 'card',
      crop: { page: 3, x: 0.68, y: 0.335, w: 0.115, h: 0.12 },
    },
    {
      id: 'cartes-reference',
      name: 'Cartes Référence',
      qty: '7 cartes',
      note: 'Cours du Jour avec le résumé des actions au verso, symboles et traits, rencontres, modes Histoire et Défi.',
      glyph: 'card',
      crop: { page: 3, x: 0.275, y: 0.52, w: 0.155, h: 0.145 },
    },
    {
      id: 'cartes-roi',
      name: 'Cartes Roi de la Ruine',
      qty: '18 cartes',
      note: 'Elles n’entrent en jeu que quand la campagne le dit. Trois figurines les accompagnent.',
      glyph: 'card',
      tint: '#8e1420',
      crop: { page: 3, x: 0.45, y: 0.52, w: 0.16, h: 0.145 },
    },
    {
      id: 'pierres',
      name: 'Figurines de Pierre de Passage',
      qty: '3 figurines',
      note: 'Elles repoussent le Wyrd. Une seule figurine couvre jusqu’à quatre cartes Lieu voisines.',
      glyph: 'figure',
      tint: '#2c5f63',
      crop: { page: 2, x: 0.04, y: 0.785, w: 0.175, h: 0.15 },
    },
    {
      id: 'gardiens',
      name: 'Silhouettes Gardien',
      qty: '21 silhouettes',
      note: 'Les rencontres errantes. Tant qu’un Gardien est dans un lieu, on n’y explore pas et on n’y fait pas l’action de lieu.',
      glyph: 'figure',
      tint: '#8e1420',
      crop: { page: 3, x: 0.45, y: 0.745, w: 0.16, h: 0.15 },
    },
    {
      id: 'compagnons',
      name: 'Silhouettes Compagnon',
      qty: '5 silhouettes',
      note: 'Les alliés rencontrés en chemin. Ils se posent sur la carte Lieu, comme les Gardiens.',
      glyph: 'figure',
      crop: { page: 3, x: 0.28, y: 0.755, w: 0.145, h: 0.13 },
    },
    {
      id: 'competences',
      name: 'Pions Compétence',
      qty: '48 pions',
      note: 'Deux compétences dos à dos par pion : en gagner une fait renoncer à l’autre. Chaque pion ajoute une case de caractéristique.',
      glyph: 'token',
      crop: { page: 3, x: 0.625, y: 0.755, w: 0.16, h: 0.13 },
    },
    {
      id: 'des',
      name: 'Dés',
      qty: '1 standard, 1 Gardien, 1 Durée',
      note: 'Le standard pour les tests du journal, le Gardien à chaque aube, le Durée pour les rencontres de diplomatie.',
      glyph: 'die',
      tint: '#8e1420',
      crop: { page: 2, x: 0.41, y: 0.545, w: 0.35, h: 0.095 },
      variants: [
        { label: 'Dé standard', effect: 'Crânes et Graals : c’est lui qu’on lance quand une carte demande un jet.' },
        { label: 'Dé Gardien', effect: 'Une direction, « rien », ou la défausse du gardien.', tint: '#8a2b2b' },
        { label: 'Dé Durée', effect: 'Combien de temps un effet reste en jeu, quand la carte ne le dit pas elle-même.', tint: '#38bdf8' },
      ],
    },
    {
      id: 'marqueurs-sante',
      name: 'Marqueurs Santé',
      qty: '4 marqueurs',
      note: 'En forme de L : la barre rappelle que le marqueur d’énergie ne monte jamais au-dessus de la santé.',
      glyph: 'marker',
      tint: '#8e1420',
      crop: { page: 2, x: 0.75, y: 0.53, w: 0.165, h: 0.135 },
    },
    {
      id: 'marqueurs-univ',
      name: 'Marqueurs universels',
      qty: '80 petits, 20 grands',
      note: 'Ils servent à tout : pistes, caractéristiques, ressources, potentiel de combat. Un grand violet en vaut cinq.',
      glyph: 'token',
      crop: { page: 2, x: 0.405, y: 0.66, w: 0.34, h: 0.13 },
    },
    {
      id: 'marqueurs-temps',
      name: 'Marqueurs Temps',
      qty: '20 sombres, 6 clairs',
      note: 'Les sombres pour les capacités différées et les activations, les clairs pour les situations liées à l’histoire.',
      glyph: 'token',
      crop: { page: 2, x: 0.395, y: 0.79, w: 0.265, h: 0.135 },
      variants: [
        { label: 'Temps sombre', qty: '20 marqueurs', effect: 'Le temps qui passe pour de bon : il fait avancer le statut « Le temps passe ».', tint: '#27272a' },
        { label: 'Temps clair', qty: '6 marqueurs', effect: 'Le temps réversible : certains effets le retirent au lieu de le laisser courir.', tint: '#d4d4d8' },
      ],
    },
    {
      id: 'marqueurs-quete',
      name: 'Marqueurs Quête',
      qty: '6 marqueurs',
      note: 'Ils suivent l’avancement d’une quête et ne sont jamais retirés à l’aube.',
      glyph: 'token',
      tint: '#c8901a',
      crop: { page: 2, x: 0.745, y: 0.66, w: 0.16, h: 0.13 },
    },
    {
      id: 'pointeurs',
      name: 'Pointeurs de combat et d’affinité',
      qty: '2 pointeurs',
      note: 'Deux roues qui remplacent les piles de marqueurs : le potentiel de combat, et l’affinité en diplomatie.',
      glyph: 'marker',
      tint: '#2c5f63',
      crop: { page: 3, x: 0.635, y: 0.52, w: 0.29, h: 0.145 },
    },
    {
      id: 'filtre',
      name: 'Filtre de révélation coloré',
      qty: '1 filtre',
      note: 'Il révèle certains textes cachés du journal et des cartes.',
      glyph: 'token',
      crop: { page: 2, x: 0.655, y: 0.795, w: 0.11, h: 0.125 },
    },
    {
      id: 'enveloppe',
      name: 'Enveloppe Secrète',
      qty: '1 enveloppe',
      note: 'Scellée. Elle ne s’ouvre que quand la campagne en donne l’instruction.',
      glyph: 'card',
      crop: { page: 3, x: 0.79, y: 0.7, w: 0.145, h: 0.22 },
    },
    {
      id: 'exploits',
      name: 'Fiches d’exploits « Échos de la Ruine »',
      qty: '8 fiches',
      note: 'L’extension incluse : des exploits personnels qui débloquent des souvenirs, puis des cartes Action Légendaire.',
      glyph: 'card',
      crop: { page: 2, x: 0.375, y: 0.36, w: 0.155, h: 0.135 },
    },
    {
      id: 'guide',
      name: 'Guide d’initiation',
      qty: '1 livret et 1 paquet',
      note: 'Un scénario d’apprentissage séparé, avec son propre paquet de cartes et sa section dans le journal.',
      glyph: 'card',
      crop: { page: 2, x: 0.645, y: 0.36, w: 0.13, h: 0.135 },
    },
  ],

  /* ------------------------------------------------------------ chapitres */

  chapters: [
    {
      id: 'brief',
      title: 'Avant de commencer',
      kind: 'brief',
      goal: 'Savoir ce que ce tutoriel installe, et ce qu’il laisse au journal.',
      steps: [
        {
          id: 'b1',
          kind: 'info',
          title: 'Posez la tablette à côté du plateau de jeu',
          body: [
            'Ce tutoriel installe la campagne, déroule un jour complet et enseigne les deux systèmes de rencontre.',
            'Il ne raconte pas l’histoire : c’est le journal d’exploration qui la porte, et lui seul.',
          ],
          warn: 'Les règles secrètes de la page 37 ne se lisent pas avant que le jeu n’en donne la permission. Ce tutoriel n’y touche pas.',
          components: ['journal'],
        },
        {
          id: 'b2',
          kind: 'info',
          title: 'Rois de la Ruine se joue seul',
          body: [
            'C’est un jeu complet : il ne demande pas *La Chute d’Avalon*, et ne se mélange pas avec lui.',
            'Vous incarnez l’un des quatre héros d’un peuple isolé à l’ouest d’Avalon, coupé du Vrai Roi par les brumes du Wyrd.',
          ],
          crop: { page: 4, x: 0.11, y: 0.6, w: 0.82, h: 0.32 },
          ref: 'Introduction — p.4',
        },
        {
          id: 'b3',
          kind: 'info',
          title: 'Une journée, et tout recommence',
          body: [
            'À l’aube, le temps avance et un événement tombe. Pendant la journée, vous dépensez votre énergie en actions.',
            'Au crépuscule, vous vous reposez, vous récupérez et vous faites progresser votre personnage.',
          ],
          tip: 'Plus les personnages sont nombreux, moins vous disposez de temps avant que les conséquences ne s’abattent sur vous.',
          ref: 'Déroulement général d’une partie — p.4',
        },
        {
          id: 'b4',
          kind: 'info',
          title: 'Les trois règles d’or',
          body: [
            'Le texte des cartes l’emporte toujours sur le livret.',
            'Quand des effets se déclenchent en même temps, ou ont plusieurs cibles, les joueurs choisissent l’ordre et la cible.',
            'En cas de doute sur la résolution d’un effet, choisissez ce qui est le plus avantageux pour les joueurs ou pour l’histoire.',
          ],
          crop: { page: 4, x: 0.05, y: 0.29, w: 0.16, h: 0.24 },
          ref: 'Règles d’or — p.4',
        },
        {
          id: 'b5',
          kind: 'info',
          title: 'Le guide d’initiation existe aussi',
          body: [
            'La boîte contient un scénario d’apprentissage séparé : un livret, un paquet de cartes, et sa propre section dans le journal.',
            'Ce tutoriel installe la campagne complète. Si vous préférez commencer par le guide, suivez-le : les règles enseignées ici restent les mêmes.',
          ],
          components: ['guide'],
          ref: 'Liste du matériel — p.2',
        },
        {
          id: 'b6',
          kind: 'check',
          title: 'Ce que vous saurez faire',
          body: [
            'Installer la campagne et votre personnage.',
            'Passer une journée entière : explorer, voyager, activer une Pierre de Passage.',
            'Résoudre un combat et une diplomatie.',
            'Fermer la journée au crépuscule, et sauvegarder la campagne.',
          ],
        },
      ],
    },

    {
      id: 'perso',
      title: 'Les quatre personnages',
      kind: 'brief',
      goal: 'Choisir son personnage en connaissance de cause.',
      steps: [
        {
          id: 'p1',
          kind: 'info',
          title: 'Elgan, le maître des Wyrdchandelles',
          body: [
            'Un vagabond errant qui cherche à retrouver son foyer et sa famille. Ses chandelles lui ouvrent un chemin dans les brumes.',
            'Ses effets différés sont très puissants quand ils sont bien synchronisés. Personnage équilibré, il peut aussi assister les autres.',
          ],
          crop: { page: 5, x: 0.11, y: 0.13, w: 0.35, h: 0.16 },
          ref: 'Personnages — p.5',
        },
        {
          id: 'p2',
          kind: 'info',
          title: 'Gerdwyn, l’arbalétrière en armure lourde',
          body: [
            'Ancienne d’une célèbre bande de mercenaires. Des attaques dévastatrices mais peu fréquentes, qui demandent de la préparation.',
            'Elle possède l’une des meilleures cartes d’annulation de dégâts du jeu. En diplomatie, elle tire parti de la défausse et du retrait de cartes.',
          ],
          crop: { page: 5, x: 0.53, y: 0.13, w: 0.35, h: 0.16 },
          ref: 'Personnages — p.5',
        },
        {
          id: 'p3',
          kind: 'info',
          title: 'Iunis, l’ancienne reine de l’arène',
          body: [
            'Une fomoire en fuite, dotée d’une endurance naturelle et de capacités de régénération.',
            'Certaines de ses cartes sacrifient sa santé pour des effets redoutables : plus la situation est mauvaise, meilleures sont ses cartes.',
          ],
          crop: { page: 5, x: 0.11, y: 0.53, w: 0.35, h: 0.16 },
          ref: 'Personnages — p.5',
        },
        {
          id: 'p4',
          kind: 'info',
          title: 'Osbert, le flambeur et sa belette',
          body: [
            'Un artiste itinérant qui voyage avec Clyfar. Il fabrique des objets utiles et négocie mieux que personne — il sait même en tirer profit.',
            'C’est le plus fragile des quatre : son combat repose sur l’évitement des attaques.',
          ],
          crop: { page: 5, x: 0.53, y: 0.53, w: 0.35, h: 0.16 },
          ref: 'Personnages — p.5',
        },
        {
          id: 'p5',
          kind: 'info',
          title: 'À deux, deux duos conseillés',
          only: [2],
          body: ['Elgan avec Iunis, ou Gerdwyn avec Osbert : leurs objectifs personnels se terminent dans la même région.'],
          crop: { page: 5, x: 0.88, y: 0.47, w: 0.11, h: 0.11 },
          ref: 'Meilleurs duos — p.5',
        },
      ],
    },

    {
      id: 'setup-perso',
      title: 'Mise en place : les personnages',
      kind: 'setup',
      modes: ['tuto', 'setup'],
      goal: 'Chaque joueur a son plateau réglé et ses deux paquets de dix cartes.',
      steps: [
        {
          id: 'sp0',
          kind: 'info',
          title: 'Vous reprenez une campagne en cours ?',
          modes: ['tuto'],
          body: [
            'Inutile de refaire la mise en place complète : le mode « Reprendre » de ce tutoriel déroule la procédure de chargement.',
          ],
          ref: 'Mise en place de la campagne — p.6',
        },
        {
          id: 'sp1',
          kind: 'take',
          title: '1. Choisissez votre personnage',
          body: [
            'Lisez sa lettre de départ. Prenez ensuite son plateau et sa figurine.',
            'Les tuiles du plateau montrent ses atouts et ses défauts : sa capacité, en général une action supplémentaire, et sa faiblesse, liée aux lieux et à sa façon de voyager.',
          ],
          components: ['lettres', 'plateaux', 'figurines'],
          crop: { page: 6, x: 0.26, y: 0.375, w: 0.29, h: 0.16 },
          ref: 'Mise en place des personnages, étape 1 — p.6',
        },
        {
          id: 'sp2',
          kind: 'place',
          title: '2. Réglez l’énergie et la terreur',
          body: [
            'Repérez les pistes d’énergie et de terreur sur votre plateau.',
            'Placez un marqueur universel sur chacune, dans la case de départ signalée par deux repères rouges.',
          ],
          components: ['marqueurs-univ'],
          crop: { page: 6, x: 0.055, y: 0.44, w: 0.155, h: 0.17 },
          ref: 'Mise en place des personnages, étape 2 — p.6',
        },
        {
          id: 'sp3',
          kind: 'place',
          title: '3. Posez le marqueur Santé',
          body: ['Dans la case de départ de la piste de santé, elle aussi marquée de deux repères rouges.'],
          warn: 'Sa forme en L n’est pas décorative : elle rappelle que votre marqueur d’énergie ne doit jamais dépasser votre santé.',
          components: ['marqueurs-sante'],
          crop: { page: 6, x: 0.26, y: 0.375, w: 0.29, h: 0.16 },
          ref: 'Mise en place des personnages, étape 3 — p.6',
        },
        {
          id: 'sp4',
          kind: 'place',
          title: '4. Caractéristiques et ressources de départ',
          body: [
            'Un marqueur universel sous chacun des six noms de caractéristique, aux repères rouges.',
            'Puis les ressources de départ : Elgan 2 Nourriture et 1 Magie ; Gerdwyn 2 Nourriture et 1 Richesse ; Iunis 3 Nourriture ; Osbert 1 Nourriture, 1 Richesse et 1 Magie.',
          ],
          components: ['marqueurs-univ'],
                    ref: 'Mise en place des personnages, étape 4 — p.6',
        },
        {
          id: 'sp5',
          kind: 'shuffle',
          title: '5. Construisez vos deux paquets de départ',
          body: [
            'Prenez les 10 cartes Combat et les 10 cartes Diplomatie portant le nom de votre personnage et la lettre « B » en bas de carte.',
            'Mélangez-les séparément : le paquet Combat à gauche de votre plateau, le paquet Diplomatie à droite.',
          ],
          warn: 'Les autres cartes à votre nom, celles marquées « A », forment votre réserve de progression : rangez-les derrière leurs séparateurs, elles s’achètent en cours de partie.',
          components: ['cartes-combat'],
                    ref: 'Mise en place des personnages, étape 5 — p.6',
        },
      ],
    },

    {
      id: 'setup-monde',
      title: 'Mise en place : le monde',
      kind: 'setup',
      modes: ['tuto', 'setup'],
      goal: 'Le plateau de départ, les paquets et le premier chapitre sont en place.',
      steps: [
        {
          id: 'sm6',
          kind: 'place',
          title: '6. Le lieu de départ : la carte Lieu 101',
          body: [
            'Au centre de votre zone de jeu, face dégagée visible.',
            'Posez-y les figurines de tous les personnages qui participent à la campagne.',
          ],
          components: ['cartes-lieu', 'figurines'],
                    ref: 'Mise en place du monde, étape 6 — p.6',
        },
        {
          id: 'sm7',
          kind: 'place',
          title: '7. Construisez le plateau de départ',
          body: [
            'Regardez la clé de direction sur le bord supérieur du lieu de départ : elle indique le lieu 102.',
            'Cherchez cette carte et attachez-la à la clé, face Wyrd visible.',
          ],
          tip: 'Laissez de la place tout autour : le plateau s’agrandit vite.',
          components: ['cartes-lieu'],
                    ref: 'Mise en place du monde, étape 7 — p.6',
        },
        {
          id: 'sm8',
          kind: 'shuffle',
          title: '8. Préparez les paquets Secret et Objet',
          body: [
            'Les cartes Objet « A », les cartes Objet « Consommable » et les cartes Secret petit format, en piles séparées sur la table.',
            'Mélangez les deux paquets Objet. Les cartes Secret format standard vont dans la boîte de sauvegarde du monde, avec leurs séparateurs.',
          ],
          warn: 'Le paquet Secret ne se mélange jamais et ne se consulte pas : on n’y prend que la carte dont le jeu donne le numéro.',
          components: ['cartes-objet', 'cartes-secret'],
                    ref: 'Mise en place du monde, étape 8 — p.6',
        },
        {
          id: 'sm9',
          kind: 'take',
          title: '9. Une fiche de statut vierge',
          body: [
            'Elle portera les statuts obtenus par votre groupe, ceux qui changent définitivement la façon dont le monde vous traite.',
            'Le verso sert de bloc-notes.',
          ],
          components: ['fiches-statut'],
          crop: { page: 21, x: 0.11, y: 0.845, w: 0.34, h: 0.075 },
          ref: 'Mise en place du monde, étape 9 — p.6',
        },
        {
          id: 'sm10',
          kind: 'take',
          title: '10. Distribuez les cartes Référence',
          body: [
            'Chaque joueur reçoit une carte Cours du Jour : le résumé des actions est à son verso.',
            'Gardez à portée les autres cartes Référence, et les deux cartes État « Vous êtes mourant ! » et « Vous devenez fou ! ».',
          ],
          components: ['cartes-reference'],
          crop: { page: 3, x: 0.275, y: 0.52, w: 0.155, h: 0.145 },
          ref: 'Mise en place du monde, étape 10 — p.6',
        },
        {
          id: 'sm11',
          kind: 'shuffle',
          title: '11. Triez les rencontres en trois piles',
          body: ['Selon la couleur de leur dos : vertes, violettes, bleues. Elles serviront à construire les paquets Rencontre du chapitre.'],
          components: ['cartes-rencontre'],
          crop: { page: 3, x: 0.435, y: 0.155, w: 0.29, h: 0.145 },
          ref: 'Mise en place du monde, étape 11 — p.6',
        },
        {
          id: 'sm12',
          kind: 'place',
          title: '12. Marqueurs et dés à portée',
          body: ['Les marqueurs Temps, Quête et universels, avec les trois dés, au bord de la table.'],
          components: ['marqueurs-temps', 'marqueurs-quete', 'marqueurs-univ', 'des'],
          crop: { page: 2, x: 0.395, y: 0.53, w: 0.52, h: 0.4 },
          ref: 'Mise en place du monde, étape 12 — p.6',
        },
        {
          id: 'sm13',
          kind: 'take',
          title: '13. Mettez le premier chapitre en place',
          body: [
            'Journal d’exploration à portée de main. Mélangez les cartes Événement Aléatoire et posez-les à côté de votre zone de jeu.',
            'Cherchez la carte « Mise en place du Chapitre 1 » et suivez ses instructions, en commençant par le recto : elles construisent les paquets Événement et Rencontre.',
          ],
          warn: 'Les rencontres et les événements inutilisés retournent dans la boîte, derrière leurs séparateurs. Ils reviendront aux chapitres suivants.',
          components: ['journal', 'cartes-evenement', 'cartes-rencontre'],
                    ref: 'Mise en place du monde, étape 13 — p.6',
        },
        {
          id: 'sm14',
          kind: 'check',
          title: 'Avant de lire la dernière ligne',
          body: [
            'La fin de la carte « Mise en place du Chapitre 1 » donne les instructions pour commencer la partie.',
            'Le livret demande de lire d’abord « Déroulement du jeu », « Journal d’exploration » et « Règles de base » — c’est exactement la suite de ce tutoriel.',
          ],
          ref: 'Mise en place du monde — p.6',
        },
      ],
    },

    {
      id: 'jour',
      title: 'Le cours du jour',
      kind: 'play',
      goal: 'Savoir ce qui se passe à l’aube, pendant la journée et au crépuscule.',
      steps: [
        {
          id: 'j1',
          kind: 'info',
          title: 'Le jour est l’unité de temps du jeu',
          body: [
            'Trois périodes s’enchaînent : l’aube, la journée, le crépuscule. Puis un nouveau jour commence.',
            'Le résumé tient sur votre carte Cours du Jour.',
          ],
          components: ['cartes-reference'],
                    ref: 'Cours du jour — p.8',
        },
        {
          id: 'j2',
          kind: 'action',
          title: 'Aube, 1 et 2 : effets et marqueurs Temps',
          body: [
            'Résolvez d’abord tous les effets qui doivent prendre effet à l’aube, dans l’ordre que vous choisissez.',
            'Puis retirez 1 marqueur Temps sombre et 1 marqueur Temps clair de chaque carte qui en porte au moins un.',
          ],
          components: ['marqueurs-temps'],
                    ref: 'L’aube — p.8',
        },
        {
          id: 'j3',
          kind: 'action',
          title: 'Aube, 3 : le Wyrd reprend le terrain',
          body: [
            'Vérifiez chaque lieu en jeu. Tous ceux qui n’ont pas de Pierre de Passage dans l’un de leurs coins sont retournés sur leur face Wyrd.',
          ],
          warn: 'Retourner un lieu ne déclenche jamais son effet immédiat.',
          components: ['cartes-lieu', 'pierres'],
                    ref: 'L’aube — p.8',
        },
        {
          id: 'j4',
          kind: 'action',
          title: 'Aube, 4 : activez les Gardiens',
          body: [
            'S’il y a des Gardiens sur la table, lancez le dé Gardien pour chacun, dans l’ordre de votre choix, et appliquez le résultat.',
          ],
          components: ['gardiens', 'des'],
          crop: { page: 17, x: 0.58, y: 0.285, w: 0.25, h: 0.16 },
          ref: 'L’aube — p.8 ; Gardiens — p.17',
        },
        {
          id: 'j5',
          kind: 'action',
          title: 'Aube, 5 et 6 : l’événement du jour',
          body: [
            'Videz la zone Événements Actifs : défaussez tous les événements qui ne portent pas de quête. Les Aléatoires reviennent sous leur pile, les autres dans la boîte.',
            'Puis révélez et lisez la première carte du paquet Événement, et placez-la dans la zone Événements Actifs.',
          ],
          warn: 'Un événement qui porte une quête reste sur la table jusqu’au moment indiqué. Ne le défaussez jamais de vous-même.',
          components: ['cartes-evenement'],
                    ref: 'L’aube — p.8',
        },
        {
          id: 'j6',
          kind: 'info',
          title: 'La journée : chacun agit quand il veut',
          body: [
            'Les joueurs effectuent leurs actions l’un après l’autre, dans l’ordre de leur choix, et peuvent en enchaîner plusieurs.',
            'La journée s’arrête quand tout le monde accepte de passer au crépuscule.',
          ],
          crop: { page: 8, x: 0.615, y: 0.16, w: 0.34, h: 0.15 },
          ref: 'La journée — p.8',
        },
        {
          id: 'j7',
          kind: 'info',
          title: 'Trois façons de payer une action',
          body: [
            'Coût d’énergie : faites descendre le marqueur de la piste d’énergie d’autant de cases.',
            'Coût de santé : descendez le marqueur de santé ; si l’énergie se retrouve au-dessus, alignez-la sur la santé.',
            'Coût de terreur : faites monter le marqueur de terreur.',
          ],
          warn: 'Si vous ne pouvez pas payer la totalité du coût, vous ne pouvez pas effectuer l’action.',
          crop: { page: 8, x: 0.615, y: 0.32, w: 0.34, h: 0.234 },
          ref: 'La journée — p.8',
        },
        {
          id: 'j8',
          kind: 'info',
          title: 'Deux personnages dans un lieu peuvent former un groupe',
          body: [
            'Un groupe agit ensemble : les règles propres au groupe sont écrites en bleu dans le livret.',
            'Un membre peut payer à la place d’un autre, sauf pour une action venant de sa propre tuile Personnage, d’une compétence, d’un secret ou d’un objet : là, il paie toujours au moins 1 point lui-même.',
          ],
          warn: 'On ne quitte jamais un groupe au milieu d’une action.',
          crop: { page: 9, x: 0.49, y: 0.44, w: 0.38, h: 0.53 },
          ref: 'Groupes et actions de groupe — p.9',
        },
      ],
    },

    {
      id: 'actions',
      title: 'Les six actions',
      kind: 'play',
      goal: 'Savoir ce que coûte chaque action et ce qu’elle rapporte.',
      steps: [
        {
          id: 'a1',
          kind: 'action',
          title: 'Explorer — 0 énergie',
          body: [
            'Disponible seulement dans un lieu face dégagée, et seulement s’il n’y a pas de Gardien.',
            'Ouvrez le journal à la page du lieu et lisez depuis le haut, jusqu’à « Fin de l’exploration ».',
          ],
          tip: 'L’action coûte 0, mais les décisions que vous prendrez pendant l’exploration, elles, coûtent souvent de l’énergie.',
          components: ['journal'],
                    ref: 'Explorer — p.8',
        },
        {
          id: 'a2',
          kind: 'action',
          title: 'Voyager — 1 énergie',
          body: [
            'Déplacez votre figurine vers n’importe quelle carte Lieu reliée à la vôtre par une clé de direction.',
            'Deux lieux côte à côte sans clé qui les relie ne communiquent pas : montagne, muraille, rivière.',
          ],
          warn: 'En groupe, le voyage coûte 1 énergie par membre.',
          components: ['cartes-lieu'],
                    ref: 'Voyager — p.8',
        },
        {
          id: 'a3',
          kind: 'action',
          title: 'Voyager : ce qui suit l’arrivée',
          body: [
            'Vérifiez si le recto du nouveau lieu porte un symbole Éclair : tout effet précédé de ce symbole se résout dès que vous entrez.',
            'Puis reliez les nouvelles cartes Lieu indiquées par les clés de direction : face Wyrd si elles n’ont pas de Pierre de Passage dans un coin, face dégagée sinon.',
          ],
          tip: 'Juste avant qu’un effet Éclair ne se déclenche, les personnages déjà présents dans le lieu peuvent se joindre à vous pour le résoudre en groupe.',
          components: ['cartes-lieu'],
                    ref: 'Voyager — p.9',
        },
        {
          id: 'a4',
          kind: 'action',
          title: 'Activer une Pierre de Passage — 2 énergie',
          body: [
            'Possible seulement si votre lieu a une case de Pierre de Passage vide. Choisissez l’une des deux options :',
            'pour chaque personnage en jeu, payez 1 Magie et soit 1 Richesse soit 1 Nourriture ;',
            'ou le « Prix du sang » : 3 santé perdues et 2 terreur gagnées, par personnage en jeu.',
          ],
          warn: 'Le compte se fait sur les personnages en jeu, pas sur les joueurs autour de la table : seul, vous payez une fois ; à quatre, quatre fois.',
          components: ['pierres'],
                    ref: 'Activer une Pierre de Passage — p.9',
        },
        {
          id: 'a5',
          kind: 'action',
          title: 'La Pierre repousse le Wyrd',
          body: [
            'Posez une figurine de Pierre de Passage dans une case vide de votre lieu.',
            'Tous les lieux face Wyrd qui touchent cette Pierre sont retournés face dégagée. Une seule figurine peut couvrir jusqu’à quatre cartes.',
          ],
          warn: 'Les trois figurines sont déjà sur la table ? Prenez-en une n’importe où et déplacez-la dans votre lieu.',
          components: ['pierres', 'cartes-lieu'],
          crop: { page: 21, x: 0.495, y: 0.6, w: 0.45, h: 0.13 },
          ref: 'Pierres de Passage — p.21',
        },
        {
          id: 'a6',
          kind: 'action',
          title: 'Défier un Gardien — 0 énergie',
          body: [
            'Disponible seulement dans un lieu où se trouve un Gardien.',
            'Vous commencez une rencontre avec lui : combat ou diplomatie, selon sa carte. En groupe, vous la résolvez ensemble.',
          ],
          components: ['gardiens'],
                    ref: 'Défier un Gardien — p.9',
        },
        {
          id: 'a7',
          kind: 'action',
          title: 'Action de lieu — coût sur la carte',
          body: [
            'La plupart des lieux portent une action au recto : chasser, échanger, récolter. Elle est indisponible s’il y a un Gardien.',
            'En groupe, le coût est payé une fois et le résultat s’applique une fois — mais les membres peuvent se partager la note.',
          ],
          tip: 'Ce sont ces actions qui remplissent vos réserves. Planifiez vos voyages en fonction d’elles.',
          components: ['cartes-lieu'],
                    ref: 'Action de lieu — p.9',
        },
        {
          id: 'a8',
          kind: 'action',
          title: 'Capacité, secret, objet, compétence',
          body: [
            'Le coût est imprimé sur le pion Personnage ou Compétence, ou sur la carte Secret ou Objet.',
            'Chaque personnage a une capacité personnelle sur sa tuile Personnage ; certains objets, secrets et compétences en ajoutent d’autres.',
          ],
          warn: 'Seul le propriétaire peut utiliser sa capacité. Les autres l’aident à payer, mais il paie toujours au moins 1 point d’énergie, de santé ou de terreur.',
          components: ['competences'],
                    ref: 'Capacité de personnage — p.9',
        },
      ],
    },

    {
      id: 'monde',
      title: 'Le monde : lieux, journal, Gardiens',
      kind: 'play',
      goal: 'Lire une carte Lieu, une entrée du journal, et savoir ce que fait un Gardien.',
      steps: [
        {
          id: 'w1',
          kind: 'info',
          title: 'Lire une carte Lieu',
          body: [
            '1 le nom. 2 le numéro, qui renvoie à la section du journal, et l’indicateur de face. 3 les symboles : Vision, Communauté, Rituel.',
            '4 l’action de lieu. 5 l’effet immédiat, à chaque entrée. 6 la case de Pierre de Passage. 7 la description. 8 les clés de direction.',
          ],
          components: ['cartes-lieu'],
          crop: { page: 19, x: 0.115, y: 0.155, w: 0.4, h: 0.23 },
          ref: 'Lieux — p.19',
        },
        {
          id: 'w2',
          kind: 'info',
          title: 'Face dégagée, face Wyrd',
          body: [
            'Un lieu face Wyrd se joue comme un autre, à deux différences près : on n’y explore pas, et au crépuscule on y perd 2 santé et on y gagne 2 terreur.',
            'Une Pierre de Passage dans un coin le retourne face dégagée ; à l’aube, tout lieu dégagé qui n’en a plus repasse face Wyrd.',
          ],
          components: ['cartes-lieu', 'pierres'],
                    ref: 'Lieux Wyrd — p.19',
        },
        {
          id: 'w3',
          kind: 'info',
          title: 'Le sablier limite ce qui se répète',
          body: [
            'Un symbole Sablier à côté d’une action ou d’un effet : vous ne pouvez l’utiliser que si le lieu ne porte pas de marqueur Temps sombre.',
            'Après usage, posez-y autant de marqueurs que le lieu affiche de sabliers — l’action revient dans autant de jours.',
          ],
          components: ['marqueurs-temps'],
                    ref: 'Lieux avec des symboles — p.19',
        },
        {
          id: 'w4',
          kind: 'info',
          title: 'Le journal d’exploration, en quatre sections',
          body: [
            'Les Lieux, classés par numéro. Le Livre des secrets (LdS). Les Échos de la Ruine (EDR), pour les souvenirs. Le journal du Guide d’Initiation (JGI).',
            'Le bord des pages porte les repères : n’allez jamais lire une section que le jeu ne vous indique pas.',
          ],
          components: ['journal'],
                    ref: 'Structure du journal — p.11',
        },
        {
          id: 'w5',
          kind: 'info',
          title: 'Choix, conditions, redirections',
          body: [
            'Les choix sont marqués par des puces ; certains exigent une condition : un personnage précis, un statut, une caractéristique minimale, une ressource à payer, une carte Secret.',
            'En groupe, il suffit qu’un membre remplisse chaque condition. Une redirection automatique se suit immédiatement, sans lire la suite.',
          ],
          crop: { page: 11, x: 0.49, y: 0.14, w: 0.38, h: 0.416 },
          ref: 'Choix et conditions — p.11',
        },
        {
          id: 'w6',
          kind: 'info',
          title: 'Lancer un dé, dans le journal',
          body: [
            'C’est le dé à six faces, auquel on ajoute la caractéristique demandée.',
            'En groupe, on prend la plus haute valeur du groupe. Jamais la somme.',
          ],
          components: ['des'],
                    ref: 'Lancers et tests — p.11',
        },
        {
          id: 'w7',
          kind: 'info',
          title: 'Les Gardiens errent',
          body: [
            'Ils empêchent d’explorer et d’utiliser l’action du lieu où ils se trouvent, et peuvent estomper les Pierres de Passage.',
            'Une rencontre de Gardien perdue laisse sa silhouette dans le lieu, et sa carte à côté du plateau pour la prochaine fois.',
          ],
          components: ['gardiens'],
                    ref: 'Gardiens — p.17',
        },
        {
          id: 'w8',
          kind: 'action',
          title: 'Le dé Gardien, à chaque aube',
          body: [
            'Un point cardinal : déplacez le Gardien vers le lieu relié dans cette direction, ou, à défaut, vers le lieu relié au numéro le plus élevé.',
            'Un « X » : première option applicable — une rencontre s’il y a un personnage dans son lieu ; sinon il estompe une Pierre de Passage du lieu ; sinon il se déplace vers le numéro le plus élevé.',
          ],
          warn: 'Le résultat W du dé désigne l’ouest.',
          components: ['des', 'gardiens'],
          crop: { page: 17, x: 0.58, y: 0.285, w: 0.25, h: 0.16 },
          ref: 'Dé Gardien — p.17',
        },
      ],
    },

    {
      id: 'combat',
      title: 'Le combat',
      kind: 'play',
      goal: 'Résoudre une rencontre de combat, tour par tour.',
      steps: [
        {
          id: 'c1',
          kind: 'info',
          title: 'Une ligne de cartes contre une carte Rencontre',
          body: [
            'Le combat oppose un personnage, ou un groupe, à une carte Rencontre. Les joueurs construisent ensemble une ligne de cartes : la séquence.',
            'Le but est d’ajouter assez de marqueurs au potentiel de combat pour atteindre la valeur de la rencontre.',
          ],
          components: ['cartes-rencontre', 'cartes-combat'],
                    ref: 'Déroulement du combat — p.22',
        },
        {
          id: 'c2',
          kind: 'info',
          title: 'Lire la carte Rencontre',
          body: [
            '1 la difficulté, en gouttes. 2 le symbole Gardien : cette rencontre continue à errer si elle n’est pas vaincue. 3 la valeur à atteindre. 4 le nom. 6 les traits ennemis.',
            '7 le tableau de combat : l’attaque de l’ennemi selon le potentiel actuel. 8 l’opportunité, si le personnage actif ne joue aucune carte. 9 le butin.',
          ],
          components: ['cartes-rencontre'],
          crop: { page: 22, x: 0.615, y: 0.235, w: 0.315, h: 0.235 },
          ref: 'Carte Rencontre — p.22',
        },
        {
          id: 'c3',
          kind: 'action',
          title: 'Début du combat : trois cartes',
          body: [
            'Chaque membre du groupe pioche 3 cartes de son paquet Combat.',
            'Si votre main ne vous plaît pas, posez-la de côté et repiochez une main d’une carte de moins, puis remélangez l’ancienne. On peut recommencer jusqu’à n’avoir qu’une carte.',
          ],
          warn: 'Si l’ennemi a des traits, lisez-les tout de suite : certains agissent dès cette phase.',
          components: ['cartes-combat'],
                    ref: 'Début du combat — p.24',
        },
        {
          id: 'c4',
          kind: 'action',
          title: 'Phase I : qui est le personnage actif',
          body: [
            'Le groupe désigne un personnage qui n’a pas encore été actif ce tour-ci.',
            'Posez un marqueur Temps sombre sur son plateau : il se souviendra qu’il a joué.',
          ],
          warn: 'Les pertes de santé, gains de terreur et pénalités de ce tour ne touchent que le personnage actif, sauf mention contraire.',
          components: ['marqueurs-temps'],
                    ref: 'Tour de combat, I — p.24',
        },
        {
          id: 'c5',
          kind: 'action',
          title: 'Phase II : capacités différées, puis vos cartes',
          body: [
            'Retirez un marqueur Temps sombre de chaque carte de la séquence, en partant de la carte Rencontre. Le dernier marqueur retiré déclenche la capacité différée de sa carte.',
            'Puis jouez votre première carte : alignez-la à la précédente dans la séquence.',
          ],
          components: ['cartes-combat'],
          crop: { page: 23, x: 0.1, y: 0.085, w: 0.35, h: 0.15 },
          ref: 'Tour de combat, II — p.24',
        },
        {
          id: 'c6',
          kind: 'info',
          title: 'Relier les clés',
          body: [
            'Les moitiés de fermeture sont à gauche d’une carte, les moitiés d’ouverture à droite. Deux moitiés reliées donnent le bonus de la fermeture, si la condition de l’ouverture est remplie.',
            'Clé de caractéristique : il faut la valeur demandée. Clé magique : payez 1 Magie pour le bonus. Clé gratuite, en bas : aucune condition, mais un multiplicateur.',
          ],
          warn: 'Aucune clé ne doit être cachée, et les bonus de clé sont obligatoires : si vous pouvez les prendre, vous les prenez.',
          components: ['cartes-combat'],
          crop: { page: 23, x: 0.5, y: 0.085, w: 0.4, h: 0.2 },
          ref: 'Carte Combat — p.23',
        },
        {
          id: 'c7',
          kind: 'action',
          title: 'Jouer une deuxième carte',
          body: [
            'Chaque carte jouée après la première doit rapporter un bonus « carte supplémentaire » grâce à l’une de ses clés.',
            'Sans ce bonus, votre activation s’arrête là.',
          ],
          components: ['cartes-combat'],
                    ref: 'Tour de combat, II — p.24',
        },
        {
          id: 'c8',
          kind: 'action',
          title: 'Phase III : l’ennemi frappe',
          body: [
            'Cherchez dans le tableau de combat la ligne correspondant au potentiel de combat actuel.',
            'Appliquez cette attaque au dernier personnage actif, effets de gauche à droite.',
          ],
          warn: 'Si l’attaque fait passer le potentiel sous zéro, défaussez la carte du dessus de votre paquet pour chaque marqueur manquant : le potentiel ne devient jamais négatif.',
          components: ['cartes-rencontre'],
                    ref: 'Tour de combat, III — p.24',
        },
        {
          id: 'c9',
          kind: 'action',
          title: 'Phases IV et V : on recommence',
          body: [
            'S’il reste des personnages sans marqueur sur leur plateau, retournez à la phase I.',
            'Sinon, chacun défausse pour ne garder que 3 cartes au plus, pioche 1 carte, et un nouveau tour commence.',
          ],
          crop: { page: 24, x: 0.615, y: 0.79, w: 0.34, h: 0.169 },
          ref: 'Tour de combat, IV et V — p.24',
        },
        {
          id: 'c10',
          kind: 'check',
          title: 'La victoire est immédiate',
          body: [
            'Dès que le potentiel de combat atteint ou dépasse la valeur de la rencontre, vous gagnez et prenez le butin.',
            'On ne résout aucun autre effet : même une capacité qui allait vous coûter de la santé ne s’applique plus.',
          ],
          components: ['pointeurs'],
                    ref: 'Condition de victoire — p.22',
        },
        {
          id: 'c11',
          kind: 'info',
          title: 'Fuir, ou faire fuir',
          body: [
            'Fuir : à votre activation, perdez 1 énergie et subissez l’attaque ennemie. La carte Rencontre repart au bas de son paquet. C’est une défaite.',
            'Repli : certaines créatures s’enfuient d’elles-mêmes. La rencontre s’arrête, sans butin — pour les règles, c’est une victoire.',
          ],
          crop: { page: 22, x: 0.22, y: 0.66, w: 0.34, h: 0.31 },
          ref: 'Fuir le combat, Repli — p.22',
        },
        {
          id: 'c12',
          kind: 'info',
          title: 'Les traits qu’on croise le plus',
          body: [
            'Crainte : avant l’attaque, avec 1 carte ou moins en main, gagnez 1 terreur. Enfermement : au début, chacun défausse 1 carte ou perd 1 santé.',
            'Épuisant : avant l’attaque, défaussez 1 carte du haut de votre paquet. Rapide : 3 cartes au maximum par activation. Destructeur : à la victoire, défaussez une arme utilisée.',
          ],
          components: ['cartes-rencontre'],
                    ref: 'Traits de combat — p.26',
        },
      ],
    },

    {
      id: 'diplomatie',
      title: 'La diplomatie',
      kind: 'play',
      goal: 'Résoudre une rencontre bleue : durée, affinité, conclusion.',
      steps: [
        {
          id: 'd1',
          kind: 'info',
          title: 'Toutes les rencontres ne finissent pas dans le sang',
          body: [
            'Le paquet Rencontre bleu contient les défis diplomatiques. La structure est celle du combat : une séquence de cartes, un tour en cinq phases.',
            'Le but change : faire monter le marqueur de la piste Affinité jusqu’à la case verte avant que la durée ne s’épuise.',
          ],
          components: ['cartes-rencontre'],
                    ref: 'Diplomatie — p.27',
        },
        {
          id: 'd2',
          kind: 'action',
          title: 'Début : trois cartes, le dé, le seuil',
          body: [
            'Chacun pioche 3 cartes Diplomatie et peut repiocher comme en combat.',
            'Posez le dé Durée sur le nombre indiqué en haut de la carte Rencontre, et un marqueur universel sur la case de seuil, marquée « S », de la piste Affinité.',
          ],
          components: ['des', 'cartes-rencontre'],
          crop: { page: 27, x: 0.21, y: 0.63, w: 0.28, h: 0.19 },
          ref: 'Début de la diplomatie — p.29',
        },
        {
          id: 'd3',
          kind: 'action',
          title: 'Le tour, en cinq phases',
          body: [
            'I on désigne le personnage actif. II capacités différées, puis il joue des cartes Diplomatie en fin de séquence.',
            'III l’adversaire répond. IV s’il reste des personnages, retour en I. V chacun défausse jusqu’à 3 cartes et en pioche 1.',
          ],
          components: ['cartes-combat'],
                    ref: 'Déroulement de la diplomatie — p.27',
        },
        {
          id: 'd4',
          kind: 'action',
          title: 'La réponse adverse',
          body: [
            'Elle s’applique au dernier personnage actif, effets de gauche à droite. Elle fait en général baisser l’affinité et la durée.',
            'Si elle fait descendre le marqueur sous la dernière case de la piste, défaussez une carte du haut de votre paquet pour chaque cran non honoré.',
          ],
          crop: { page: 29, x: 0.49, y: 0.545, w: 0.38, h: 0.208 },
          ref: 'Réponse adverse — p.29',
        },
        {
          id: 'd5',
          kind: 'check',
          title: 'La conclusion, quand la durée tombe à 0',
          body: [
            'Regardez la couleur de la case où se trouve le marqueur d’affinité. Verte : conclusion favorable, avec récompenses. Grise : neutre, petites récompenses ou petites punitions. Rouge : quelque chose a mal tourné.',
            'Puis rangez la carte Rencontre au bas de son paquet.',
          ],
          warn: 'Atteindre la case verte avant la fin du temps ne gagne pas la rencontre : la conclusion ne se lit qu’au moment où la durée atteint 0.',
          components: ['pointeurs'],
                    ref: 'Conclusion de la rencontre — p.27',
        },
        {
          id: 'd6',
          kind: 'action',
          title: 'Éviter la diplomatie',
          body: [
            'Pendant l’activation, si tout le groupe est d’accord : descendez le marqueur d’affinité de 4 cases et perdez toute la durée.',
            'La rencontre s’arrête aussitôt et sa conclusion se résout.',
          ],
          warn: 'C’est une décision de groupe. Si un seul membre refuse, la rencontre continue.',
          crop: { page: 27, x: 0.615, y: 0.4, w: 0.34, h: 0.143 },
          ref: 'Éviter la diplomatie — p.27',
        },
        {
          id: 'd7',
          kind: 'info',
          title: 'Après la rencontre, on remet tout en place',
          body: [
            'Mélangez tous les paquets Combat et Diplomatie, cartes en main, séquence et défausse comprises.',
            'Retirez les marqueurs Temps sombre des plateaux Personnage. Si la rencontre venait d’une exploration, reprenez-la où vous l’aviez laissée.',
          ],
          warn: 'Une rencontre de Gardien perdue laisse sa silhouette dans votre lieu. Une rencontre venue du paquet Secret y retourne.',
          crop: { page: 44, x: 0.627, y: 0.215, w: 0.3, h: 0.16 },
          ref: 'Entretien de la rencontre — p.44',
        },
        {
          id: 'd8',
          kind: 'info',
          title: 'La panique',
          body: [
            'Un personnage devenu fou panique : à l’étape 2 de son activation, il joue la carte du dessus de son paquet au lieu de choisir dans sa main.',
            'Il peut ensuite jouer normalement des cartes supplémentaires, mais il ne pioche pas en fin de tour.',
          ],
          crop: { page: 26, x: 0.22, y: 0.415, w: 0.34, h: 0.182 },
          ref: 'Panique — p.26',
        },
      ],
    },

    {
      id: 'crepuscule',
      title: 'Le crépuscule',
      kind: 'play',
      goal: 'Fermer la journée et faire progresser son personnage.',
      steps: [
        {
          id: 'x1',
          kind: 'action',
          title: '1 et 2 : effets, puis repos',
          body: [
            'Résolvez d’abord les effets qui prennent effet au crépuscule.',
            'Puis reposez-vous : remettez le marqueur d’énergie sur la case de départ de sa piste. Si vous étiez épuisé, gagnez seulement 4 énergie.',
          ],
          warn: 'Le marqueur d’énergie ne dépasse jamais le marqueur de santé.',
          crop: { page: 10, x: 0.22, y: 0.13, w: 0.34, h: 0.195 },
          ref: 'Le crépuscule — p.10',
        },
        {
          id: 'x2',
          kind: 'action',
          title: '3 et 4 : récupérer, et souffrir',
          body: [
            'Récupérez : vous pouvez payer 1 Nourriture, une seule fois, pour gagner 1 santé, 1 énergie de plus et perdre 1 terreur.',
            'Puis, si vous êtes dans un lieu Wyrd, perdez 2 santé et gagnez 2 terreur.',
          ],
          components: ['cartes-lieu'],
                    ref: 'Le crépuscule — p.10',
        },
        {
          id: 'x3',
          kind: 'action',
          title: '5 : dépensez votre expérience',
          body: [
            'Augmenter une caractéristique coûte 2 Exp, plus 1 Exp par point déjà présent dans sa paire.',
            'Acquérir une compétence, quand la caractéristique est à son maximum, coûte 4 Exp, plus 4 Exp par compétence déjà prise dans la paire.',
            'Améliorer un paquet coûte 2 Exp : piochez 3 cartes de la réserve de progression correspondante, gardez-en 1 et mélangez-la dans le paquet.',
          ],
          warn: 'Les trois paires sont Agression/Empathie, Courage/Prudence, Pragmatisme/Spiritualité. Sans compétence, une caractéristique plafonne à 2.',
          components: ['competences', 'cartes-combat'],
          crop: { page: 13, x: 0.16, y: 0.2, w: 0.34, h: 0.13 },
          ref: 'Caractéristiques et progression — p.13',
        },
        {
          id: 'x4',
          kind: 'action',
          title: '6 : construisez vos paquets',
          body: [
            'Vous pouvez ajouter les cartes remportées, et en retirer d’autres pour alléger vos paquets.',
            'Les cartes retirées ne retournent pas dans la réserve de progression : posez-les à côté de votre plateau, ou dans votre compartiment de sauvegarde.',
          ],
          warn: 'Chaque paquet doit toujours contenir au moins 10 cartes.',
          components: ['cartes-combat'],
                    ref: 'Le crépuscule — p.10',
        },
        {
          id: 'x5',
          kind: 'action',
          title: '7 et 8 : la vision, puis un nouveau jour',
          body: [
            'Si votre lieu porte le symbole Vision, vous pouvez lire la vision correspondante dans le journal. Tous les personnages du lieu la résolvent en groupe.',
            'Puis un nouveau jour commence : retour à l’aube.',
          ],
          tip: 'Les visions ne sont pas obligatoires, mais elles donnent souvent des conseils ou des morceaux d’histoire. Lisez-les.',
          components: ['journal'],
                    ref: 'Le crépuscule — p.10',
        },
        {
          id: 'x6',
          kind: 'info',
          title: 'Un chroniqueur, si vous êtes plusieurs',
          only: [2, 3, 4],
          body: [
            'À 2 à 4 joueurs, le livret conseille qu’un joueur endosse ce rôle : il lit le journal, révèle les événements, retire les marqueurs Temps, lance le dé Gardien.',
            'Il tient aussi la fiche de sauvegarde à jour et tranche les situations conflictuelles.',
          ],
          crop: { page: 10, x: 0.615, y: 0.09, w: 0.34, h: 0.416 },
          ref: 'Le chroniqueur — p.10',
        },
      ],
    },

    {
      id: 'sante',
      title: 'Mourir, et devenir fou',
      kind: 'play',
      goal: 'Savoir ce qui arrive quand une piste atteint sa case rouge.',
      steps: [
        {
          id: 'm1',
          kind: 'info',
          title: 'Les trois pistes',
          body: [
            'Énergie : votre endurance, récupérée chaque jour. La dernière case est rouge : vous êtes épuisé, et vous récupérerez moins.',
            'Santé : votre condition physique. À court, vous êtes mourant. Terreur : les troubles mentaux. En haut, la case rouge, c’est la folie.',
          ],
          components: ['plateaux'],
                    ref: 'Pistes de personnage — p.14',
        },
        {
          id: 'm2',
          kind: 'info',
          title: 'À l’article de la mort',
          body: [
            'Santé à 0 : attachez la carte « Vous êtes mourant ! » à votre plateau et retirez-vous immédiatement de la rencontre en cours.',
            'Ne résolvez plus rien de cette rencontre. Si vous en étiez le dernier personnage, elle est perdue — sauf s’il s’agit d’un Gardien.',
          ],
          warn: 'Il y a deux versions de la carte : solo et coop. Prenez celle qui correspond au nombre de personnages en jeu.',
          crop: { page: 14, x: 0.615, y: 0.33, w: 0.34, h: 0.312 },
          ref: 'À l’article de la mort — p.14',
        },
        {
          id: 'm3',
          kind: 'info',
          title: 'La mort, et la folie',
          body: [
            'Un personnage à 0 santé qui remplit les critères de la carte meurt. Sans carte Secret 6, 8 ou 9, la partie se termine pour tout le monde.',
            'Terreur au rouge : attachez « Vous devenez fou ! » et suivez ses instructions. Vous paniquerez en rencontre, et l’exploration deviendra plus difficile.',
          ],
          crop: { page: 14, x: 0.615, y: 0.6, w: 0.34, h: 0.312 },
          ref: 'Mort et folie — p.14',
        },
        {
          id: 'm4',
          kind: 'info',
          title: 'Les quatre ressources',
          body: [
            'Nourriture, pour récupérer au crépuscule. Richesse, pour acheter. Magie, pour les rencontres et les Pierres de Passage. Expérience, pour progresser.',
            '20 de chaque au maximum, sauf l’Exp qui n’a pas de limite. L’Exp est gagnée par tous les personnages en même temps.',
          ],
          warn: 'Nourriture et Richesse s’échangent entre personnages d’un même lieu. L’Exp et la Magie ne s’échangent pas — mais on peut payer de la Magie pour un membre de son groupe.',
          crop: { page: 20, x: 0.22, y: 0.09, w: 0.34, h: 0.468 },
          ref: 'Ressources — p.20',
        },
      ],
    },

    {
      id: 'rp',
      title: 'Reprendre la campagne',
      kind: 'setup',
      modes: ['reprise'],
      goal: 'Remonter la table exactement comme vous l’aviez rangée, en inversant la sauvegarde.',
      steps: [
        {
          id: 'rp1',
          kind: 'info',
          title: 'La sauvegarde se déroule à l’envers',
          body: [
            'Le livret l’écrit en une ligne : « Pour charger une partie sauvegardée, inversez ce processus. »',
            'On remonte donc dans l’ordre : les personnages d’abord, puis le monde.',
          ],
          warn: 'Ne refaites pas la mise en place de la campagne : elle écraserait tout ce que vous avez gagné.',
          components: ['fiches-sauvegarde'],
                    ref: 'Sauvegarder la partie — p.20',
        },
        {
          id: 'rp2',
          kind: 'take',
          title: 'Sortez les fiches',
          body: [
            'La fiche de sauvegarde de chaque personnage, et la fiche de statut du groupe.',
            'Le schéma qui porte votre nom est le vôtre : il dit tout ce que votre plateau affichait.',
          ],
          components: ['fiches-sauvegarde', 'fiches-statut'],
          crop: { page: 2, x: 0.525, y: 0.19, w: 0.25, h: 0.165 },
          ref: 'Sauvegarder la partie, I — p.20',
        },
        {
          id: 'rp3',
          kind: 'place',
          title: 'Reposez vos marqueurs',
          body: [
            'Les six caractéristiques, les quatre ressources, l’énergie, la santé et la terreur, aux valeurs écrites sur votre schéma.',
            'Les numéros notés à côté d’une caractéristique sont ceux de vos compétences : ressortez les pions correspondants et attachez-les au bord de votre plateau.',
          ],
          warn: 'Vérifiez que votre marqueur d’énergie n’est pas au-dessus de votre santé : c’est l’erreur classique du remontage.',
          components: ['marqueurs-univ', 'marqueurs-sante', 'competences'],
                    ref: 'Sauvegarder la partie, I.a — p.20',
        },
        {
          id: 'rp4',
          kind: 'take',
          title: 'Reprenez vos cartes, dans l’ordre du compartiment',
          body: [
            'Elles ont été rangées dans cet ordre : paquets Diplomatie et Combat, séparateurs de réserve de progression, cartes de réserve, objets et secrets, compétences.',
            'Reposez les deux paquets de part et d’autre de votre plateau, la réserve derrière ses séparateurs.',
          ],
          components: ['cartes-combat', 'cartes-objet'],
                    ref: 'Sauvegarder la partie, I.c — p.20',
        },
        {
          id: 'rp5',
          kind: 'place',
          title: 'Posez votre figurine sur son lieu',
          body: ['La fiche indique le lieu où se trouvait votre personnage. Cherchez cette carte quand le monde sera remonté.'],
          components: ['figurines'],
          ref: 'Sauvegarder la partie, I.a — p.20',
        },
        {
          id: 'rp6',
          kind: 'place',
          title: 'Remontez la carte du monde',
          body: [
            'Ressortez les lieux révélés du compartiment grand format : ils ont été rangés sans être retournés, chacun est donc sur la bonne face.',
            'Reconstituez le plateau autour du lieu de départ, en suivant les clés de direction.',
          ],
          components: ['cartes-lieu'],
                    ref: 'Sauvegarder la partie, II.d — p.20',
        },
        {
          id: 'rp7',
          kind: 'place',
          title: 'Replacez figurines et silhouettes',
          body: [
            'Les Pierres de Passage, les silhouettes de Gardien et de Compagnon, et la figurine Roi de la Ruine si elle était en jeu : la fiche note le lieu de chacune.',
            'Reposez ensuite les marqueurs sur les lieux qui en portaient.',
          ],
          warn: 'Une Pierre de Passage dans un coin décide de la face d’un lieu : reposez-les avant de vous demander si un lieu doit être retourné.',
          components: ['pierres', 'gardiens', 'compagnons', 'marqueurs-temps'],
                    ref: 'Sauvegarder la partie, II.a et II.b — p.20',
        },
        {
          id: 'rp8',
          kind: 'take',
          title: 'Ressortez les paquets du monde',
          body: [
            'Les Gardiens actifs, les trois paquets Rencontre et les cartes Secret standard actives, derrière leurs séparateurs.',
            'Le paquet Événement, les événements et les quêtes actives : eux non plus n’ont pas été retournés, l’ordre est intact.',
          ],
          warn: 'Ne remélangez rien. Un paquet Événement remélangé, c’est un chapitre qui perd sa progression.',
          components: ['cartes-rencontre', 'cartes-evenement', 'cartes-secret'],
                    ref: 'Sauvegarder la partie, II.e et II.f — p.20',
        },
        {
          id: 'rp9',
          kind: 'take',
          title: 'Et les petits paquets',
          body: ['Les paquets Objet et Secret petit format reviennent du compartiment de petite taille. Le reste du matériel sort de la boîte principale.'],
          components: ['cartes-objet', 'cartes-secret'],
          ref: 'Sauvegarder la partie, II.g — p.20',
        },
        {
          id: 'rp10',
          kind: 'check',
          title: 'Relisez la fiche de statut',
          body: [
            'C’est elle qui porte ce que votre groupe a changé dans le monde, et le verso porte les cases « Le temps passe » du chapitre en cours.',
            'Un statut de la fiche s’applique à tous les personnages.',
          ],
          components: ['fiches-statut'],
          crop: { page: 21, x: 0.11, y: 0.845, w: 0.34, h: 0.075 },
          ref: 'Fiche de statut — p.21',
        },
        {
          id: 'rp11',
          kind: 'check',
          title: 'Où reprend-on ?',
          body: [
            'La sauvegarde est conseillée au tout début d’une journée : dans ce cas, reprenez à l’aube, étape 1.',
            'Sinon, la section « Notes » de votre fiche dit où vous vous étiez arrêté.',
          ],
          tip: 'Avant de vous lancer, relisez l’événement actif et vos quêtes en cours : c’est ce qui donne sa direction à la journée.',
          components: ['cartes-evenement'],
          ref: 'Sauvegarder la partie — p.20',
        },
        {
          id: 'rp12',
          kind: 'info',
          title: 'Trois règles qu’on oublie entre deux séances',
          body: [
            'À l’aube, tout lieu sans Pierre de Passage repasse face Wyrd, et on retire 1 marqueur Temps sombre et 1 clair de chaque carte qui en a.',
            'Le marqueur d’énergie ne dépasse jamais le marqueur de santé.',
            'Activer une Pierre de Passage se paie par personnage en jeu, pas par membre du groupe.',
          ],
          ref: 'Résumé des règles — p.44',
        },
      ],
    },

    {
      id: 'r-jour',
      title: 'Rappel : la journée',
      kind: 'play',
      modes: ['recap'],
      goal: 'Le cours du jour, dans l’ordre du résumé officiel.',
      steps: [
        {
          id: 'rr1',
          kind: 'info',
          title: 'L’aube, en six temps',
          body: [
            '1 les effets de l’aube. 2 retirer 1 marqueur Temps sombre et 1 clair de chaque carte. 3 retourner face Wyrd les lieux sans Pierre de Passage.',
            '4 le dé Gardien pour chaque Gardien. 5 vider la zone Événements Actifs, sauf les quêtes. 6 révéler et lire un nouvel événement.',
          ],
          crop: { page: 44, x: 0.04, y: 0.155, w: 0.295, h: 0.33 },
          ref: 'Résumé des règles — p.44',
        },
        {
          id: 'rr2',
          kind: 'info',
          title: 'Les six actions et leurs coûts',
          body: [
            'Explorer 0. Voyager 1 énergie. Activer une Pierre de Passage 2 énergie, plus le coût en ressources ou le Prix du sang, par personnage en jeu.',
            'Défier un Gardien 0. Action de lieu : le coût est sur la carte. Capacité, compétence, objet, secret : le coût est sur le pion ou la carte.',
          ],
          crop: { page: 8, x: 0.615, y: 0.555, w: 0.34, h: 0.415 },
          ref: 'La journée — p.8-9',
        },
        {
          id: 'rr3',
          kind: 'info',
          title: 'Voyager, pas à pas',
          body: [
            'Payer, se déplacer vers un lieu relié par une clé, résoudre l’effet Éclair du recto, puis attacher les nouvelles cartes révélées.',
            'Face Wyrd si le lieu attaché n’a pas de Pierre de Passage dans un coin, face dégagée sinon.',
          ],
          crop: { page: 9, x: 0.11, y: 0.075, w: 0.38, h: 0.286 },
          ref: 'Voyager — p.9',
        },
        {
          id: 'rr4',
          kind: 'info',
          title: 'Le crépuscule, en huit temps',
          body: [
            '1 effets de crépuscule. 2 repos : énergie à la case de départ, ou 4 si épuisé. 3 récupérer contre 1 Nourriture. 4 lieu Wyrd : −2 santé, +2 terreur.',
            '5 dépenser l’Exp. 6 modifier ses paquets, 10 cartes minimum. 7 la vision du lieu. 8 nouveau jour.',
          ],
          crop: { page: 44, x: 0.04, y: 0.525, w: 0.295, h: 0.41 },
          ref: 'Résumé des règles — p.44',
        },
        {
          id: 'rr5',
          kind: 'info',
          title: 'Le Gardien, à l’aube',
          body: [
            'Point cardinal : il se déplace dans cette direction, ou vers le lieu relié au numéro le plus élevé.',
            '« X » : rencontre s’il y a un personnage chez lui ; sinon il estompe une Pierre de Passage ; sinon il se déplace vers le numéro le plus élevé.',
          ],
          crop: { page: 17, x: 0.58, y: 0.285, w: 0.25, h: 0.16 },
          ref: 'Dé Gardien — p.17',
        },
      ],
    },

    {
      id: 'r-rencontre',
      title: 'Rappel : les rencontres',
      kind: 'play',
      modes: ['recap'],
      goal: 'Combat et diplomatie côte à côte, comme sur la carte Référence.',
      steps: [
        {
          id: 'rs1',
          kind: 'info',
          title: 'Le début, dans les deux cas',
          body: [
            'Chacun pioche 3 cartes de son paquet et peut refaire sa main, une carte de moins à chaque fois.',
            'En diplomatie, on ajoute le dé Durée sur le nombre de la carte, et un marqueur sur la case de seuil « S » de la piste Affinité.',
            'On lit les traits de l’ennemi ou de l’adversaire tout de suite.',
          ],
          crop: { page: 44, x: 0.328, y: 0.155, w: 0.3, h: 0.18 },
          ref: 'Résumé des règles — p.44',
        },
        {
          id: 'rs2',
          kind: 'info',
          title: 'Le tour, en cinq phases',
          body: [
            'I marquer le personnage actif. II retirer 1 marqueur Temps sombre de chaque carte de la séquence, puis jouer ; les cartes suivantes exigent un bonus « carte supplémentaire ».',
            'III attaque ennemie ou réponse adverse. IV s’il reste des personnages, retour en I. V défausser jusqu’à 3 cartes, piocher 1, retirer les marqueurs d’activation.',
          ],
          crop: { page: 44, x: 0.328, y: 0.32, w: 0.3, h: 0.42 },
          ref: 'Résumé des règles — p.44',
        },
        {
          id: 'rs3',
          kind: 'info',
          title: 'Les clés',
          body: [
            'Fermetures à gauche, ouvertures à droite. Une clé de caractéristique exige la valeur demandée ; la clé magique exige 1 Magie ; la clé gratuite du bas n’exige rien mais porte un multiplicateur.',
            'Les bonus de clé sont obligatoires. Un multiplicateur « 0× » annule le bonus.',
          ],
          crop: { page: 23, x: 0.5, y: 0.085, w: 0.4, h: 0.2 },
          ref: 'Carte Combat — p.23',
        },
        {
          id: 'rs4',
          kind: 'info',
          title: 'La fin',
          body: [
            'Combat : dès que le potentiel atteint la valeur de la rencontre, victoire et butin.',
            'Diplomatie : quand le dernier point de durée tombe, la couleur de la case du marqueur donne la conclusion.',
            'Fuite, repli ou carte « Vous êtes mourant ! » : la rencontre se termine sans butin.',
          ],
          crop: { page: 44, x: 0.328, y: 0.895, w: 0.3, h: 0.09 },
          ref: 'Fin de la rencontre — p.44',
        },
        {
          id: 'rs5',
          kind: 'info',
          title: 'Après, on remet tout en place',
          body: [
            'Mélangez tous les paquets Combat et Diplomatie, main, séquence et défausse comprises. Retirez les marqueurs Temps sombre des plateaux.',
            'Une rencontre perdue contre un Gardien laisse sa silhouette dans le lieu ; sinon, la carte repart au bas de son paquet.',
          ],
          crop: { page: 44, x: 0.627, y: 0.215, w: 0.3, h: 0.16 },
          ref: 'Entretien de la rencontre — p.44',
        },
        {
          id: 'rs6',
          kind: 'info',
          title: 'Les cas particuliers',
          body: [
            'Potentiel de combat qui passerait sous zéro, ou affinité sous le minimum : le dernier personnage actif défausse une carte par cran manquant.',
            'Main vide alors qu’il faut défausser : on défausse la première carte de son paquet. Paquet vide : il ne se passe rien, la rencontre continue.',
          ],
          crop: { page: 44, x: 0.627, y: 0.495, w: 0.3, h: 0.31 },
          ref: 'Résumé des règles — p.44',
        },
      ],
    },

    {
      id: 'debrief',
      title: 'Après cette première partie',
      kind: 'debrief',
      goal: 'Savoir ce qui vient ensuite, et ce que le tutoriel n’a pas couvert.',
      steps: [
        {
          id: 'z1',
          kind: 'check',
          title: 'Sauvegardez avant de ranger',
          body: [
            'La procédure est en page 20 : chaque joueur enregistre son personnage sur une fiche, puis le chroniqueur enregistre le monde.',
            'Sauvegardez de préférence au tout début d’une journée, et aux endroits que la campagne vous indique — surtout entre deux chapitres.',
          ],
          components: ['fiches-sauvegarde'],
                    ref: 'Sauvegarder la partie — p.20',
        },
        {
          id: 'z2',
          kind: 'info',
          title: 'Les Échos de la Ruine, à partir du chapitre 2',
          body: [
            'L’extension est dans la boîte : chaque personnage reçoit sa fiche d’exploits quand le journal le demande.',
            'Trois exploits d’une même section donnent une carte Action Légendaire ; les neuf exploits ouvrent une Capacité Avancée.',
          ],
          components: ['exploits'],
          crop: { page: 15, x: 0.11, y: 0.4, w: 0.38, h: 0.28 },
          ref: 'Échos de la Ruine — p.15',
        },
        {
          id: 'z3',
          kind: 'info',
          title: 'Si le jeu est trop dur, ou trop tendre',
          body: [
            'Mode Histoire : un objet de départ, la carte Secret 49, des paquets préparés comme s’il y avait un personnage de moins, le limiteur de santé retiré, des Pierres de Passage moins chères.',
            'Mode Défi : la carte Secret 48, la fuite au dé, des progressions plus chères, cinq objets au maximum, le repos qui coûte 1 Nourriture.',
          ],
          tip: 'On peut n’appliquer qu’une partie de ces règles : le livret le dit explicitement.',
          crop: { page: 36, x: 0.22, y: 0.15, w: 0.34, h: 0.715 },
          ref: 'Variantes — p.36',
        },
        {
          id: 'z4',
          kind: 'check',
          title: 'Ce que ce tutoriel n’a pas enseigné',
          body: [
            'Les règles secrètes de la page 37, à ne pas lire sans permission — les Rois de la Ruine en font partie.',
            'Le guide d’initiation, qui a son propre livret. Et l’histoire, qui est tout le jeu : elle est dans le journal.',
          ],
          ref: 'Comment utiliser ce livret de règles — p.4',
        },
      ],
    },
  ],
}
