/**
 * Tainted Grail : La Chute d'Avalon — première partie tutorielle.
 *
 * Source : « Tainted Grail — Livret de Règles », édition française
 * (Edge Entertainment, traduction Hervé Daubet), Awaken Realms. Les numéros
 * de page du champ `ref` et des découpes sont ceux imprimés sur le livret,
 * qui coïncident ici avec l'index des pages du PDF (pageOffset 0).
 *
 * Périmètre : le tutoriel installe la campagne complète, fait jouer le
 * premier jour, une rencontre de combat et une rencontre de diplomatie,
 * puis l'aube du jour 2. Il n'enseigne pas la campagne elle-même : le
 * journal d'exploration prend le relais. Ce qui est volontairement laissé
 * de côté est listé dans `scope.skipped` et rappelé au dernier chapitre.
 */

import type { Tutorial } from '../engine/types'

export const taintedgrail: Tutorial = {
  id: 'taintedgrail',
  title: 'Tainted Grail',
  tagline:
    'Les menhirs d’Avalon s’éteignent un à un et le Wyrd engloutit l’île. Vous partez chercher de l’aide avant qu’il ne reste plus rien à sauver.',
  contentVersion: '1.0',
  publisher: 'Awaken Realms',
  author: 'Krzysztof Piskorski, Marcin Świerkot',
  players: {
    min: 1,
    max: 4,
    recommended: 1,
    labels: { 1: 'Solo' },
    notes: {
      1: 'Le livret conseille d’apprendre le jeu en solitaire : un seul personnage à gérer, et le cadran du menhir de départ vous laisse 8 jours, le maximum.',
      2: 'À deux, le menhir de départ ne tient que 7 jours. Vous pouvez voyager ensemble et payer les actions en groupe.',
      3: 'À trois, 6 jours seulement avant que le menhir de départ ne s’éteigne. Le rythme se tend nettement.',
      4: 'À quatre, 5 jours au menhir de départ, et vos mains de combat et de diplomatie tombent à 2 cartes. C’est l’effectif le plus exigeant.',
    },
  },
  minutes: 120,

  // Le livret lui-même : parchemin vieilli, encre sépia, titres au rouge de
  // rubrique. Les découpes des règles sont sur ce même fond clair — elles se
  // posent dans la page au lieu d'y flotter en rectangles lumineux.
  theme: {
    scheme: 'light',
    bg: '#e7dcc3',
    bg2: '#f3ebd8',
    bg3: '#fbf5e7',
    stroke: '#c0a97f',
    strokeSoft: '#d6c5a1',
    fg: '#2b2118',
    fgDim: '#5e4f3c',
    fgFaint: '#695c49',
    accent: '#82190f',
    accent2: '#a8551a',
    accentInk: '#fdf6e6',
    ok: '#3f6b2f',
    warn: '#8a5a10',
    danger: '#9d2418',
    radius: '6px',
  },

  source: {
    pdf: 'Tainted Grail - Regles.pdf',
    assetId: 'taintedgrail',
    pageOffset: 0,
    credit: 'Règles officielles FR — Awaken Realms / Edge Entertainment',
  },

  // Couverture du livret : ce que le joueur reconnaît sur l'écran d'accueil.
  cover: { page: 1, x: 0.03, y: 0.02, w: 0.94, h: 0.32 },

  scope: {
    covered: [
      'La mise en place des personnages, des 12 étapes officielles',
      'La mise en place du monde et du chapitre 1',
      'Lire un plateau Personnage : Énergie, Santé, Terreur, caractéristiques, ressources',
      'Les six actions de la journée et ce qu’elles coûtent',
      'Voyager, révéler des lieux, lire une carte Lieu et ses symboles',
      'Le crépuscule : repos, récupération, progression, rêve',
      'Une rencontre de combat complète, tour par tour',
      'Relier les clés : caractéristique, bonus, magique, gratuite',
      'Une rencontre de diplomatie et la piste Affinité',
      'Les neuf étapes de l’aube, et les menhirs qui s’éteignent',
    ],
    skipped: [
      'Le journal d’exploration et le déroulement du chapitre 1',
      'Les quêtes, les tâches et les pions Quête',
      'La progression avancée : compétences, caractéristiques, réserves',
      'La mort, la folie et la Grâce de la Toute-Mère',
      'Les modes Histoire et Défi, et le jeu libre',
    ],
  },

  /* ------------------------------------------------------------ matériel */

  components: [
    {
      id: 'figurines',
      name: 'Figurines de personnage',
      qty: '4 figurines',
      note: 'Béor, Ailei, Arev et « Larve ». Chacune a la couleur de son plateau, de sa tuile et de ses cartes.',
      glyph: 'figure',
      tint: '#d3a34d',
      crop: { page: 2, x: 0.37, y: 0.185, w: 0.27, h: 0.32 },
    },
    {
      id: 'fig-menhir',
      name: 'Figurines de menhir',
      qty: '3 figurines',
      note: 'Les pierres gardiennes d’Avalon. Une figurine posée sur un lieu signale un menhir actif ; le cadran glissé sous sa base compte ses jours.',
      glyph: 'figure',
      tint: '#9ec6d0',
      crop: { page: 2, x: 0.352, y: 0.712, w: 0.272, h: 0.235 },
    },
    {
      id: 'fig-precurseur',
      name: 'Figurine de Précurseur',
      qty: '1 figurine',
      note: 'Le gardien errant. Il apparaît quand une rencontre dotée du trait Gardien n’est pas vaincue.',
      glyph: 'figure',
      tint: '#9d3220',
      crop: { page: 2, x: 0.435, y: 0.505, w: 0.14, h: 0.205 },
    },
    {
      id: 'plateaux',
      name: 'Plateaux Personnage',
      qty: '4 plateaux',
      note: 'Vert, bleu, marron, gris. Le plateau porte les trois pistes Survie, les caractéristiques et les cases Ressource.',
      glyph: 'board',
      tint: '#d3a34d',
      crop: { page: 2, x: 0.665, y: 0.585, w: 0.29, h: 0.22 },
    },
    {
      id: 'tuiles-perso',
      name: 'Tuiles Personnage',
      qty: '4 tuiles',
      note: 'Se glissent dans le plateau de la même couleur. Le recto donne l’action propre au personnage, le verso ses valeurs de départ.',
      glyph: 'tile',
      tint: '#d3a34d',
      crop: { page: 2, x: 0.682, y: 0.806, w: 0.262, h: 0.132 },
    },
    {
      id: 'lettres',
      name: 'Lettres de départ',
      qty: '4 lettres',
      note: 'Une par personnage. Elle raconte sa situation initiale et donne son numéro, qui départage les égalités.',
      glyph: 'card',
      crop: { page: 2, x: 0.665, y: 0.185, w: 0.15, h: 0.1 },
    },
    {
      id: 'plans',
      name: 'Plans d’aventure',
      qty: '4 plans',
      note: 'Une carte d’Avalon dessinée il y a plus d’un siècle. Utile pour se repérer, pas toujours exacte.',
      glyph: 'tile',
      crop: { page: 2, x: 0.822, y: 0.185, w: 0.128, h: 0.1 },
    },
    {
      id: 'fiches',
      name: 'Fiches de sauvegarde',
      qty: '30 fiches',
      note: 'Le carnet de bord de la campagne : statuts obtenus, position des personnages, valeur des cadrans.',
      glyph: 'card',
      crop: { page: 2, x: 0.665, y: 0.29, w: 0.152, h: 0.115 },
    },
    {
      id: 'journal',
      name: 'Journal d’exploration',
      qty: '1 livret',
      note: 'Le cœur narratif du jeu. Chaque carte Lieu y renvoie à un chapitre numéroté.',
      glyph: 'card',
      tint: '#9d3220',
      crop: { page: 2, x: 0.818, y: 0.402, w: 0.14, h: 0.168 },
    },
    {
      id: 'cartes-lieu',
      name: 'Cartes Lieu',
      qty: '63 cartes',
      note: 'Le plateau modulaire du jeu. Elles se relient par leurs clés de direction et se retournent quand on les explore.',
      glyph: 'card',
      tint: '#7ba05b',
      crop: { page: 3, x: 0.03, y: 0.782, w: 0.15, h: 0.145 },
    },
    {
      id: 'cartes-reference',
      name: 'Cartes Référence',
      qty: '10 cartes',
      note: 'Glossaire des symboles, Cours du Jour et résumé des actions, Référence Combat/Diplomatie.',
      glyph: 'card',
      crop: { page: 3, x: 0.183, y: 0.782, w: 0.15, h: 0.145 },
    },
    {
      id: 'rencontres',
      name: 'Cartes Rencontre',
      qty: '4 × 31 cartes',
      note: 'Vert : la nature. Gris : les hommes. Violet : le surnaturel. Bleu : les épreuves sociales, résolues en diplomatie.',
      glyph: 'card',
      tint: '#9d3220',
      crop: { page: 3, x: 0.038, y: 0.344, w: 0.297, h: 0.271 },
    },
    {
      id: 'cartes-standard',
      name: 'Cartes Combat et Diplomatie standard',
      qty: '4 × 50 cartes',
      note: 'Une couleur par plateau. Les 15 premières de chaque type portent une bannière : ce sont vos cartes de départ.',
      glyph: 'card',
      crop: { page: 3, x: 0.348, y: 0.342, w: 0.352, h: 0.268 },
    },
    {
      id: 'cartes-avancees',
      name: 'Cartes Combat et Diplomatie avancées',
      qty: '4 × 30 cartes',
      note: 'Elles portent le nom du personnage au-dessus du titre. Elles alimentent la réserve de progression, pas la main de départ.',
      glyph: 'card',
      tint: '#d3a34d',
      crop: { page: 3, x: 0.706, y: 0.342, w: 0.256, h: 0.268 },
    },
    {
      id: 'evenements',
      name: 'Cartes Événement',
      qty: '70 Histoire + 22 Aléatoire',
      note: 'Une carte Événement est révélée à chaque aube. Ce sont elles qui font avancer l’histoire et déclenchent les quêtes.',
      glyph: 'card',
      tint: '#9d3220',
      crop: { page: 3, x: 0.688, y: 0.612, w: 0.276, h: 0.148 },
    },
    {
      id: 'cartes-secret',
      name: 'Cartes Secret',
      qty: '43 cartes',
      note: 'Objets et pouvoirs numérotés, liés à l’histoire. Ils ne se perdent ni ne se vendent jamais.',
      glyph: 'card',
      tint: '#8a6fb0',
      crop: { page: 3, x: 0.355, y: 0.788, w: 0.115, h: 0.14 },
    },
    {
      id: 'cartes-objet',
      name: 'Cartes Objet',
      qty: '65 cartes',
      note: 'L’équipement courant : arme, armure, bouclier, compagnon, relique. Un seul objet actif par mot-clé.',
      glyph: 'card',
      crop: { page: 3, x: 0.494, y: 0.786, w: 0.108, h: 0.142 },
    },
    {
      id: 'cartes-competence',
      name: 'Cartes Compétence',
      qty: '36 cartes',
      note: 'Recto-verso : chaque carte propose deux compétences exclusives. On en gagne une à chaque 3ᵉ point d’une caractéristique.',
      glyph: 'card',
      tint: '#d3a34d',
      crop: { page: 3, x: 0.635, y: 0.788, w: 0.12, h: 0.14 },
    },
    {
      id: 'cadrans',
      name: 'Cadrans',
      qty: '10 cadrans',
      note: 'Glissés sous les menhirs, ils décomptent les jours restants. Ils servent aussi de compteurs ailleurs, et de pile ou face.',
      glyph: 'token',
      tint: '#9ec6d0',
      crop: { page: 3, x: 0.032, y: 0.122, w: 0.152, h: 0.169 },
    },
    {
      id: 'pions-temps',
      name: 'Pions Temps',
      qty: '8 pions',
      note: 'Marquent ce qui a déjà servi : un personnage activé, une action de lieu utilisée, une capacité différée.',
      glyph: 'token',
      crop: { page: 3, x: 0.192, y: 0.122, w: 0.136, h: 0.092 },
    },
    {
      id: 'pions-quete',
      name: 'Pions Quête',
      qty: '4 pions',
      note: 'Posés sur un cadran, ils en font un compteur de quête : celui-là ne baisse pas tout seul à l’aube.',
      glyph: 'token',
      tint: '#d3a34d',
      crop: { page: 3, x: 0.192, y: 0.214, w: 0.136, h: 0.096 },
    },
    {
      id: 'marqueur-t',
      name: 'Marqueurs Santé en T',
      qty: '4 marqueurs',
      note: 'Un seul marqueur, trois informations : votre Santé, le plafond de votre Énergie, et le seuil de panique de votre Terreur.',
      glyph: 'marker',
      tint: '#9d3220',
      crop: { page: 3, x: 0.332, y: 0.122, w: 0.162, h: 0.188 },
    },
    {
      id: 'marqueurs-univ',
      name: 'Marqueurs universels',
      qty: '90 marqueurs',
      note: 'Les cubes rouges. Ils servent de ressources, de points sur les pistes, et de potentiel de combat.',
      glyph: 'marker',
      tint: '#9d3220',
      crop: { page: 3, x: 0.498, y: 0.122, w: 0.188, h: 0.188 },
    },
    {
      id: 'grands-marqueurs',
      name: 'Grands marqueurs',
      qty: '25 marqueurs',
      note: 'Les cubes violets. Un grand marqueur vaut cinq marqueurs universels.',
      glyph: 'marker',
      tint: '#8a6fb0',
      crop: { page: 3, x: 0.692, y: 0.122, w: 0.135, h: 0.188 },
    },
    {
      id: 'de-standard',
      name: 'Dé standard',
      qty: '1 dé',
      note: 'Faces Crâne et Graal, utilisées quand une carte vous demande de « lancer un cadran ».',
      glyph: 'die',
      crop: { page: 3, x: 0.826, y: 0.124, w: 0.124, h: 0.088 },
    },
    {
      id: 'de-gardien',
      name: 'Dé Gardien',
      qty: '1 dé',
      note: 'Lancé à chaque aube pour chaque gardien en jeu. Il donne une direction, « rien », ou la défausse du gardien.',
      glyph: 'die',
      tint: '#9d3220',
      crop: { page: 3, x: 0.826, y: 0.208, w: 0.124, h: 0.094 },
    },
    {
      id: 'mourant',
      name: 'Cartes « Vous Êtes Mourant » et « Vous Devenez Fou »',
      qty: '9 cartes',
      note: 'Attachées au plateau quand la Santé tombe à 0 ou que la Terreur atteint le haut de sa piste.',
      glyph: 'card',
      tint: '#9d3220',
      crop: { page: 3, x: 0.038, y: 0.618, w: 0.312, h: 0.136 },
    },
  ],

  /* ------------------------------------------------------------ chapitres */

  chapters: [
    {
      id: 'brief',
      title: 'Briefing',
      kind: 'brief',
      goal: 'Savoir ce que vous allez apprendre, et ce que ce tutoriel ne fera pas à votre place.',
      steps: [
        {
          id: 'b1',
          kind: 'info',
          title: 'Posez la tablette à côté de la table',
          body: [
            'Vous allez installer la campagne étape par étape, puis jouer votre premier jour en suivant l’écran.',
            'Une étape = une chose à faire. Vous validez quand c’est fait sur la table.',
          ],
          tip: 'Le chronomètre en haut à droite tourne pendant la partie. Vous pouvez le mettre en pause ; il reprend même si vous fermez l’application.',
        },
        {
          id: 'b2',
          kind: 'info',
          title: 'Ce que le jeu vous demande',
          body: [
            'Avalon s’efface. Seuls les lieux à portée d’un menhir actif restent en jeu.',
            'Chaque menhir a un cadran qui perd 1 jour à chaque aube. À zéro, le menhir s’éteint et les lieux qu’il tenait disparaissent.',
            'Vous voyagez, vous récoltez, et vous activez le menhir suivant avant que le vôtre ne meure.',
          ],
          components: ['fig-menhir', 'cadrans'],
          ref: 'Menhirs et Wyrd — p.11',
        },
        {
          id: 'b3',
          kind: 'info',
          title: 'C’est une campagne, pas une partie',
          body: [
            'La Chute d’Avalon se joue en plusieurs séances, sur des chapitres successifs.',
            'On sauvegarde à la fin d’un chapitre, quand le journal ou une carte Événement vous y invite.',
          ],
          components: ['fiches', 'journal'],
          ref: 'Sauvegarder la Partie — p.13',
        },
        {
          id: 'b4',
          kind: 'info',
          title: 'Désignez un chroniqueur',
          only: [2, 3, 4],
          body: [
            'Un joueur lit les paragraphes du journal aux autres, tient la fiche de sauvegarde et s’occupe des tâches d’entretien de l’aube.',
            'Il reste un joueur normal : il n’a aucun pouvoir sur la partie.',
          ],
          tip: 'Ce rôle est optionnel, mais il fait gagner beaucoup de temps et évite les oublis.',
          ref: 'Le Chroniqueur — p.7',
        },
        {
          id: 'b5',
          kind: 'check',
          title: 'Ce que vous saurez faire à la fin',
          body: [
            'Installer la campagne en entier, personnages et monde.',
            'Jouer un jour complet : aube, journée, crépuscule.',
            'Gagner une rencontre de combat et une rencontre de diplomatie.',
          ],
          warn: 'Le tutoriel s’arrête au seuil de l’histoire. Le journal d’exploration prendra le relais : ne l’ouvrez pas avant que le tutoriel vous le dise.',
        },
      ],
    },

    {
      id: 'materiel',
      title: 'Le matériel',
      kind: 'setup',
      goal: 'Reconnaître d’un coup d’œil ce que vous allez manipuler pendant deux heures.',
      steps: [
        {
          id: 'm1',
          kind: 'take',
          title: 'Sortez les quatre plateaux Personnage',
          body: [
            'Vert, bleu, marron, gris. Chaque plateau va avec une figurine, une tuile et 80 cartes de la même couleur.',
          ],
          components: ['plateaux', 'figurines', 'tuiles-perso'],
          crop: { page: 2, x: 0.665, y: 0.585, w: 0.29, h: 0.22 },
          ref: 'Liste du matériel — p.2',
        },
        {
          id: 'm2',
          kind: 'take',
          title: 'Mettez les cartes Lieu de côté',
          body: [
            '63 grandes cartes. C’est le plateau de jeu : il n’existe pas avant que vous ne le construisiez.',
          ],
          components: ['cartes-lieu'],
          crop: { page: 3, x: 0.03, y: 0.782, w: 0.15, h: 0.145 },
          ref: 'Lieux — p.10',
        },
        {
          id: 'm3',
          kind: 'take',
          title: 'Repérez les quatre paquets Rencontre',
          body: [
            'Ils se distinguent par la couleur du dos : vert, gris, violet, bleu.',
            'Le paquet bleu est le seul qui se résout en diplomatie ; les trois autres se résolvent en combat.',
          ],
          tip: 'Les daltoniens peuvent se repérer au quart de cercle imprimé au dos : bas-gauche gris, bas-droit vert, haut-droit violet, haut-gauche bleu.',
          components: ['rencontres'],
          crop: { page: 3, x: 0.038, y: 0.344, w: 0.297, h: 0.271 },
          ref: 'Rencontres — p.12',
        },
        {
          id: 'm4',
          kind: 'take',
          title: 'Sortez les cubes, les cadrans et les pions',
          body: [
            'Cubes rouges : ressources et potentiel de combat. Cubes violets : cinq rouges d’un coup.',
            'Cadrans : les jours restants. Pions Temps : ce qui a déjà servi.',
          ],
          components: ['marqueurs-univ', 'grands-marqueurs', 'cadrans', 'pions-temps', 'pions-quete'],
          crop: { page: 3, x: 0.03, y: 0.118, w: 0.8, h: 0.192 },
          ref: 'Éléments en plastique — p.3',
        },
        {
          id: 'm5',
          kind: 'take',
          title: 'Sortez les deux dés',
          body: [
            'Le dé standard porte des Crânes et des Graals : c’est lui qu’on lance quand une carte dit « lancez un cadran ».',
            'Le dé Gardien donne une direction, « rien », ou la défausse du gardien.',
          ],
          components: ['de-standard', 'de-gardien'],
          crop: { page: 3, x: 0.822, y: 0.118, w: 0.13, h: 0.19 },
          ref: 'Gardiens — p.12',
        },
        {
          id: 'm6',
          kind: 'info',
          title: 'Voilà à quoi ressemble une partie en cours',
          body: [
            'Les lieux au centre, les plateaux Personnage devant chaque joueur, les paquets Rencontre à portée.',
          ],
          crop: { page: 5, x: 0.24, y: 0.3, w: 0.5, h: 0.53 },
          ref: 'Aperçu du matériel — p.5',
        },
      ],
    },

    {
      id: 'perso',
      title: 'Mise en place des personnages',
      kind: 'setup',
      modes: ['tuto', 'setup'],
      goal: 'Chaque joueur repart avec un plateau prêt, deux paquets de 15 cartes et deux réserves de 25.',
      steps: [
        {
          id: 'p1',
          kind: 'info',
          title: 'Jouez en mode Normal',
          body: [
            'Trois modes existent : Histoire, Normal, Défi.',
            'Normal est le mode par défaut. Il suffit largement pour une première partie.',
          ],
          tip: 'Les modes Histoire et Défi demandent de placer leur carte Référence dans la zone de jeu. En Normal, il n’y a rien à poser.',
          ref: 'Mise en place, étape I — p.6',
        },
        {
          id: 'p2-solo',
          kind: 'take',
          title: 'Choisissez votre personnage',
          only: [1],
          body: [
            'Prenez une figurine, la tuile Personnage correspondante et le plateau de la même couleur.',
            'Pour découvrir le jeu, Béor (bleu) est le plus simple : il frappe fort et pardonne les erreurs.',
          ],
          components: ['figurines', 'tuiles-perso', 'plateaux'],
          crop: { page: 2, x: 0.37, y: 0.185, w: 0.27, h: 0.32 },
          ref: 'Mise en place, étape II — p.6',
        },
        {
          id: 'p2',
          kind: 'take',
          title: 'Chaque joueur choisit son personnage',
          only: [2, 3, 4],
          body: [
            'Un joueur = une figurine, une tuile Personnage et le plateau de la même couleur.',
            'Les personnages se distinguent surtout par leur action propre et leur trait négatif, tous deux au recto de la tuile.',
          ],
          tip: 'La longueur des pistes Survie diffère d’un personnage à l’autre : regardez-les avant de choisir.',
          components: ['figurines', 'tuiles-perso', 'plateaux'],
          crop: { page: 2, x: 0.37, y: 0.185, w: 0.27, h: 0.32 },
          ref: 'Mise en place, étape II — p.6',
        },
        {
          id: 'p3',
          kind: 'place',
          title: 'Placez vos marqueurs d’Énergie et de Terreur',
          body: [
            'Repérez les deux pistes sur le plateau Personnage.',
            'Posez un marqueur universel dans la case de départ de chacune, celle qu’encadrent deux repères rouges.',
          ],
          components: ['marqueurs-univ'],
          crop: { page: 3, x: 0.498, y: 0.122, w: 0.188, h: 0.188 },
          ref: 'Mise en place, étape III — p.6',
        },
        {
          id: 'p4',
          kind: 'place',
          title: 'Placez le marqueur Santé en T',
          body: [
            'Sur la piste Santé, dans la case indiquée par deux repères rouges.',
            'Ses deux ailes dépassent sur les pistes voisines : ce n’est pas décoratif.',
          ],
          warn: 'Votre Énergie ne peut jamais dépasser l’aile du marqueur en T. Et si votre Terreur passe au-dessus de l’autre aile, vous paniquez en combat et en diplomatie.',
          components: ['marqueur-t'],
          crop: { page: 6, x: 0.438, y: 0.853, w: 0.128, h: 0.083 },
          ref: 'Mise en place, étape IV — p.6',
        },
        {
          id: 'p5',
          kind: 'place',
          title: 'Reportez vos caractéristiques de départ',
          body: [
            'Les valeurs sont au dos de votre tuile Personnage.',
            'Six caractéristiques, en trois paires opposées : Agression/Empathie, Courage/Prudence, Pragmatisme/Spiritualité.',
          ],
          components: ['tuiles-perso'],
          crop: { page: 10, x: 0.078, y: 0.763, w: 0.218, h: 0.108 },
          ref: 'Mise en place, étape V — p.6',
        },
        {
          id: 'p6',
          kind: 'place',
          title: 'Reportez vos ressources de départ',
          body: [
            'Toujours au dos de la tuile. Posez le nombre indiqué de marqueurs universels dans les cases Ressource du plateau.',
            'Cinq ressources : Nourriture, Richesse, Réputation, Magie, Expérience.',
          ],
          components: ['marqueurs-univ', 'tuiles-perso'],
          crop: { page: 6, x: 0.71, y: 0.398, w: 0.182, h: 0.1 },
          ref: 'Mise en place, étape VI — p.6',
        },
        {
          id: 'p7',
          kind: 'take',
          title: 'Prenez vos 80 cartes Combat et Diplomatie',
          body: [
            'Celles de la couleur de votre plateau : 50 cartes standard et 30 cartes avancées.',
            'Les avancées portent le nom de votre personnage au-dessus du titre.',
          ],
          tip: 'Les numéros aident au tri. Ailei, en vert, prend les Combat 1 à 25 V, les Diplomatie 1 à 25 V, puis les avancées 1 à 15 V de chaque type.',
          components: ['cartes-standard', 'cartes-avancees'],
          crop: { page: 3, x: 0.348, y: 0.342, w: 0.612, h: 0.268 },
          ref: 'Mise en place, étape VII — p.6',
        },
        {
          id: 'p8',
          kind: 'shuffle',
          title: 'Construisez vos deux paquets de départ',
          body: [
            'Prenez les 15 cartes Combat standard et les 15 cartes Diplomatie standard qui portent une bannière de votre couleur, sous le titre.',
            'Mélangez chaque paquet séparément. Combat à gauche du plateau, Diplomatie à droite.',
          ],
          warn: 'Les cartes de départ ne portent JAMAIS de nom de personnage. Dans La Chute d’Avalon, ce sont les numéros 1 à 15/25.',
          components: ['cartes-standard'],
          crop: { page: 6, x: 0.738, y: 0.78, w: 0.132, h: 0.056 },
          ref: 'Mise en place, étape VIII — p.6',
        },
        {
          id: 'p9',
          kind: 'shuffle',
          title: 'Construisez vos deux réserves de progression',
          body: [
            'Combat : vos 15 cartes avancées au nom du personnage, plus les 10 cartes standard sans bannière écartées à l’étape précédente. Mélangez : 25 cartes.',
            'Recommencez à l’identique avec la Diplomatie.',
            'Rangez les deux réserves dans un compartiment, ou couvrez-les d’une carte « Réserve de Progression ».',
          ],
          tip: 'C’est là-dedans que vous piocherez pour améliorer vos paquets, en payant 2 Expérience au crépuscule.',
          components: ['cartes-avancees'],
          ref: 'Mise en place, étape IX — p.7',
        },
        {
          id: 'p10',
          kind: 'place',
          title: 'Glissez votre tuile dans son plateau',
          body: [
            'La face « Mise en place » doit être cachée.',
            'C’est l’action de votre personnage qui doit être visible.',
          ],
          components: ['tuiles-perso'],
          crop: { page: 7, x: 0.1, y: 0.28, w: 0.19, h: 0.1 },
          ref: 'Mise en place, étape X — p.7',
        },
        {
          id: 'p11',
          kind: 'info',
          title: 'Lisez votre lettre de départ',
          body: [
            'Elle a été écrite par votre ancien mentor, disparu lors de la précédente expédition.',
            'Notez le numéro de votre personnage : il départage les égalités lors des votes, et fixe l’ordre du jeu en cas de désaccord.',
          ],
          components: ['lettres'],
          crop: { page: 2, x: 0.665, y: 0.185, w: 0.15, h: 0.1 },
          ref: 'Mise en place, étape XI — p.7',
        },
        {
          id: 'p12',
          kind: 'take',
          title: 'Prenez votre plan d’aventure',
          body: ['Une carte d’Avalon pour vous repérer.'],
          warn: 'Le cartographe a vécu il y a plus d’un siècle. Ses indications ne sont pas forcément à jour.',
          components: ['plans'],
          crop: { page: 2, x: 0.822, y: 0.185, w: 0.128, h: 0.1 },
          ref: 'Mise en place, étape XII — p.7',
        },
      ],
    },

    {
      id: 'monde',
      title: 'Mise en place du monde',
      kind: 'setup',
      modes: ['tuto', 'setup'],
      goal: 'Le plateau de départ est monté, les paquets sont prêts, le chapitre 1 est en place.',
      steps: [
        {
          id: 'w1',
          kind: 'place',
          title: 'Posez le lieu de départ au centre',
          body: [
            'Cherchez la carte Lieu 101 : c’est le point de départ de La Chute d’Avalon.',
            'Posez-la au milieu de la table et mettez toutes les figurines de personnage dessus.',
          ],
          components: ['cartes-lieu', 'figurines'],
          ref: 'Mise en place du monde, étape I — p.7',
        },
        {
          id: 'w2-1',
          kind: 'place',
          title: 'Menhir de départ : réglez le cadran sur 8',
          only: [1],
          body: [
            'Posez une figurine de menhir sur le lieu de départ.',
            'Glissez un cadran dans l’emplacement sous sa base et tournez-le jusqu’à 8.',
          ],
          warn: 'C’est le compte à rebours de toute la partie : 8 jours avant que ce menhir ne s’éteigne.',
          components: ['fig-menhir', 'cadrans'],
          crop: { page: 7, x: 0.398, y: 0.324, w: 0.194, h: 0.112 },
          ref: 'Mise en place du monde, étape II — p.7',
        },
        {
          id: 'w2-2',
          kind: 'place',
          title: 'Menhir de départ : réglez le cadran sur 7',
          only: [2],
          body: [
            'Posez une figurine de menhir sur le lieu de départ.',
            'Glissez un cadran dans l’emplacement sous sa base et tournez-le jusqu’à 7.',
          ],
          warn: 'À deux joueurs, un jour de moins qu’en solo : le menhir s’éteindra après la 7ᵉ aube.',
          components: ['fig-menhir', 'cadrans'],
          crop: { page: 7, x: 0.398, y: 0.324, w: 0.194, h: 0.112 },
          ref: 'Mise en place du monde, étape II — p.7',
        },
        {
          id: 'w2-3',
          kind: 'place',
          title: 'Menhir de départ : réglez le cadran sur 6',
          only: [3],
          body: [
            'Posez une figurine de menhir sur le lieu de départ.',
            'Glissez un cadran dans l’emplacement sous sa base et tournez-le jusqu’à 6.',
          ],
          warn: 'À trois joueurs, six jours seulement. Vous couvrez plus de terrain, mais vous avez moins de temps.',
          components: ['fig-menhir', 'cadrans'],
          crop: { page: 7, x: 0.398, y: 0.324, w: 0.194, h: 0.112 },
          ref: 'Mise en place du monde, étape II — p.7',
        },
        {
          id: 'w2-4',
          kind: 'place',
          title: 'Menhir de départ : réglez le cadran sur 5',
          only: [4],
          body: [
            'Posez une figurine de menhir sur le lieu de départ.',
            'Glissez un cadran dans l’emplacement sous sa base et tournez-le jusqu’à 5.',
          ],
          warn: 'À quatre joueurs, cinq jours. C’est le réglage le plus serré du jeu : il faudra vous séparer très vite.',
          components: ['fig-menhir', 'cadrans'],
          crop: { page: 7, x: 0.398, y: 0.324, w: 0.194, h: 0.112 },
          ref: 'Mise en place du monde, étape II — p.7',
        },
        {
          id: 'w3',
          kind: 'place',
          title: 'Montez le plateau de départ',
          body: [
            'Les quatre bords du lieu 101 portent chacun une clé de direction avec un numéro.',
            'Bosquet des Chasseurs (102) en haut, Foire du Guerrier (103) à gauche, Conclave Calciné (104) à droite, Lames de la Mélancolie (105) en bas.',
            'Chaque carte se pose face à sa clé de direction.',
          ],
          components: ['cartes-lieu'],
          crop: { page: 7, x: 0.393, y: 0.542, w: 0.218, h: 0.156 },
          ref: 'Mise en place du monde, étape III — p.7',
        },
        {
          id: 'w4',
          kind: 'shuffle',
          title: 'Séparez les cartes Rencontre en quatre piles',
          body: [
            'Une pile par couleur : vert, gris, violet, bleu.',
            'Chaque pile doit contenir 31 cartes, dont une rencontre spéciale « Votre Première Rencontre ».',
          ],
          tip: 'Ces piles servent de réserve. Les vrais paquets Rencontre seront construits à l’étape de mise en place du chapitre.',
          components: ['rencontres'],
          ref: 'Mise en place du monde, étape IV — p.7',
        },
        {
          id: 'w5',
          kind: 'shuffle',
          title: 'Préparez les paquets Secret et Objet',
          body: [
            'Deux piles à côté des rencontres.',
            'Triez les Secrets par numéro : vous en chercherez souvent un précis.',
            'Mélangez le paquet Objet.',
          ],
          components: ['cartes-secret', 'cartes-objet'],
          ref: 'Mise en place du monde, étape V — p.7',
        },
        {
          id: 'w6',
          kind: 'take',
          title: 'Prenez une fiche de sauvegarde vierge',
          body: [
            'Elle sert à sauvegarder la partie et à noter les statuts qui changent définitivement le monde.',
          ],
          components: ['fiches'],
          ref: 'Mise en place du monde, étape VI — p.7',
        },
        {
          id: 'w7',
          kind: 'take',
          title: 'Distribuez les cartes Référence',
          body: [
            'Chaque joueur reçoit un Glossaire des Symboles et une carte Cours du Jour, dont le verso liste les actions.',
            'Laissez la carte Référence Combat/Diplomatie au milieu de la table.',
          ],
          tip: 'Gardez la carte Cours du Jour sous les yeux les premiers jours : elle vous évitera d’oublier une étape de l’aube.',
          components: ['cartes-reference'],
          crop: { page: 3, x: 0.183, y: 0.782, w: 0.15, h: 0.145 },
          ref: 'Mise en place du monde, étape VII — p.7',
        },
        {
          id: 'w8',
          kind: 'place',
          title: 'Mettez le chapitre 1 en place',
          body: [
            'Cherchez la carte Événement « Mise en Place du Chapitre 1 » et lisez son recto.',
            'Suivez ses instructions : elles construisent les paquets Événement et Rencontre de ce chapitre.',
          ],
          components: ['evenements'],
          crop: { page: 7, x: 0.708, y: 0.286, w: 0.182, h: 0.042 },
          ref: 'Mise en place du monde, étape IX — p.7',
        },
        {
          id: 'w9',
          kind: 'shuffle',
          title: 'Mettez les Événements Aléatoires de côté',
          body: [
            'Prenez les 22 cartes Événement Aléatoire, mélangez-les et posez-les à part.',
            'Certains événements d’histoire vous demanderont d’en ajouter au sommet du paquet Événement.',
          ],
          warn: 'Quand le jeu vous dit de piocher un événement, piochez toujours dans le paquet Événement, jamais directement dans la pile Aléatoire.',
          components: ['evenements'],
          ref: 'Mise en place du monde, étape IX — p.7',
        },
        {
          id: 'w10',
          kind: 'check',
          title: 'La table est prête',
          body: [
            'Le lieu 101 et ses quatre voisins au centre, un menhir dessus avec son cadran.',
            'Devant vous : plateau, paquets Combat et Diplomatie, réserves, lettre et plan.',
            'À portée : rencontres, secrets, objets, événements, cubes et cadrans.',
          ],
          crop: { page: 5, x: 0.393, y: 0.373, w: 0.27, h: 0.285 },
          ref: 'Aperçu du matériel — p.5',
        },
      ],
    },

    {
      id: 'lire',
      title: 'Lire votre plateau',
      kind: 'brief',
      goal: 'Savoir ce que chaque piste, chaque ressource et chaque symbole de lieu veut dire.',
      steps: [
        {
          id: 'l1',
          kind: 'info',
          title: 'Énergie : ce que vous pouvez faire aujourd’hui',
          body: [
            'Presque toutes les actions de la journée coûtent de l’Énergie.',
            'Les deux dernières cases de la piste sont rouges : vous y êtes épuisé, et vous récupérerez moins bien au crépuscule.',
          ],
          warn: 'Votre Énergie ne peut jamais dépasser votre Santé, matérialisée par l’aile du marqueur en T.',
          crop: { page: 5, x: 0.393, y: 0.655, w: 0.255, h: 0.142 },
          ref: 'Pistes Survie — p.10',
        },
        {
          id: 'l2',
          kind: 'info',
          title: 'Santé : votre condition physique',
          body: [
            'À court de Santé, vous êtes à l’agonie.',
            'Si elle tombe à 0, vous recevez la carte « Vous Êtes Mourant » et vous fuyez immédiatement la rencontre en cours.',
          ],
          components: ['mourant'],
          ref: 'Pistes Survie — p.10',
        },
        {
          id: 'l3',
          kind: 'info',
          title: 'Terreur : le stress et la folie',
          body: [
            'Si la Terreur atteint l’une des deux cases rouges, vous recevez la carte « Vous Devenez Fou ».',
            'Et dès que votre Terreur passe au-dessus de votre Santé, vous êtes en proie à la panique.',
          ],
          warn: 'La panique se joue à chaque tour de combat : au lieu de choisir votre première carte, vous jouez celle du sommet de votre paquet, et vous ne piochez pas en fin de tour.',
          components: ['mourant', 'marqueur-t'],
          ref: 'Pistes Survie — p.10 et Panique — p.16',
        },
        {
          id: 'l4',
          kind: 'info',
          title: 'Six caractéristiques, trois paires opposées',
          body: [
            'Agression contre Empathie. Courage contre Prudence. Pragmatisme contre Spiritualité.',
            'Elles décident des clés que vous pouvez relier en combat et en diplomatie, et des options qui s’ouvrent en explorant.',
          ],
          tip: 'Le coût en Expérience se calcule par paire : plus vous montez d’un côté, plus l’autre côté devient cher.',
          crop: { page: 10, x: 0.078, y: 0.763, w: 0.218, h: 0.108 },
          ref: 'Caractéristiques des Personnages — p.10',
        },
        {
          id: 'l5',
          kind: 'info',
          title: 'Cinq ressources',
          body: [
            'Nourriture pour vous reposer. Richesse pour acheter. Réputation pour être aidé.',
            'Magie pour relier les clés magiques et activer les menhirs. Expérience pour progresser.',
          ],
          warn: 'Vous ne portez jamais plus de 20 unités d’une même ressource. L’Expérience est la seule exception : elle n’a pas de limite.',
          components: ['marqueurs-univ', 'grands-marqueurs'],
          ref: 'Ressources — p.10',
        },
        {
          id: 'l6',
          kind: 'info',
          title: 'Les symboles d’un lieu',
          body: [
            'Menhir : ce lieu abrite un menhir que vous pouvez activer.',
            'Rêves : y dormir déclenche un rêve, ou un cauchemar.',
            'Communauté hostile : une rencontre se déclenche dès que vous entrez.',
          ],
          crop: { page: 10, x: 0.661, y: 0.102, w: 0.294, h: 0.162 },
          ref: 'Lieux — p.10',
        },
        {
          id: 'l7',
          kind: 'info',
          title: 'Les clés de direction',
          body: [
            'Chaque bord d’une carte Lieu porte des numéros : ce sont ses voisins possibles.',
            'On ne voyage que d’une carte à une carte reliée par des clés qui se correspondent.',
          ],
          warn: 'Deux lieux côte à côte sans clés communes ne communiquent pas : montagnes, falaises ou fleuves les séparent.',
          components: ['cartes-lieu'],
          crop: { page: 7, x: 0.393, y: 0.542, w: 0.218, h: 0.156 },
          ref: 'Lieux — p.10',
        },
      ],
    },

    {
      id: 'jour1',
      title: 'Votre premier jour',
      kind: 'play',
      goal: 'Jouer une journée entière et son crépuscule, avec les six actions du jeu.',
      steps: [
        {
          id: 'j1',
          kind: 'info',
          title: 'Le premier jour saute l’aube',
          body: [
            'Un jour se déroule en trois temps : Aube, Journée, Crépuscule.',
            'Au premier jour de la campagne, on commence directement par la journée.',
          ],
          ref: 'Cours du Jour — p.8',
        },
        {
          id: 'j2',
          kind: 'info',
          title: 'La journée, une action à la fois',
          only: [1],
          body: [
            'Vous effectuez une action, puis une autre, jusqu’à épuiser votre Énergie ou décider de passer.',
            'Chaque action porte un symbole qui en indique le coût.',
          ],
          ref: 'La Journée — p.8',
        },
        {
          id: 'j2-multi',
          kind: 'info',
          title: 'La journée, chacun son tour',
          only: [2, 3, 4],
          body: [
            'Un joueur effectue une action, puis les autres, dans l’ordre décidé ensemble.',
            'À défaut d’accord, c’est le plus petit numéro de personnage, sur la lettre de départ, qui commence.',
            'Quand tout le monde a agi, on recommence un tour, jusqu’à ce que tous aient passé ou soient à court d’Énergie.',
          ],
          ref: 'La Journée — p.8',
        },
        {
          id: 'j3',
          kind: 'action',
          title: 'Explorez votre lieu de départ',
          body: [
            'Coût : 1 Énergie. Retournez la carte Lieu et lisez le texte au dos.',
            'Le texte renvoie souvent au journal d’exploration ; continuez jusqu’à un paragraphe « Fin de l’exploration ».',
            'Remettez ensuite la carte Lieu dans sa position initiale.',
          ],
          tip: 'Explorer son lieu de départ est le meilleur premier geste : c’est là que vous verrez ce que le jeu vous propose.',
          widget: {
            kind: 'counter',
            title: 'Énergie restante après cette action',
            min: 0,
            max: 12,
            start: 4,
            unit: 'points',
          },
          components: ['cartes-lieu', 'journal'],
          ref: 'Exploration — p.8',
        },
        {
          id: 'j4',
          kind: 'action',
          title: 'Voyagez vers un lieu voisin',
          body: [
            'Coût : 1 Énergie. Déplacez votre figurine vers une carte Lieu reliée à la vôtre.',
            'À l’arrivée, vérifiez si de nouvelles cartes Lieu se révèlent, puis résolvez tout effet marqué du symbole Éclair.',
          ],
          warn: 'On ne voyage qu’orthogonalement. Jamais en diagonale.',
          components: ['cartes-lieu'],
          crop: { page: 8, x: 0.655, y: 0.28, w: 0.3, h: 0.26 },
          ref: 'Voyage — p.8',
        },
        {
          id: 'j5',
          kind: 'info',
          title: 'Révéler de nouveaux lieux',
          body: [
            'Cherchez les cartes qui correspondent aux clés de direction de votre nouveau lieu.',
            'Attachez-les seulement si elles ne sont pas à plus d’une carte, diagonale comprise, d’un menhir actif.',
          ],
          tip: 'Si la carte indiquée par une clé n’existe plus, cherchez le numéro « souche » : un lieu transformé garde l’ancien numéro écrit à côté du nouveau.',
          components: ['cartes-lieu'],
          ref: 'Lieux — p.10 et Numéros souche — p.11',
        },
        {
          id: 'j6',
          kind: 'action',
          title: 'Faites une action de lieu',
          body: [
            'Le coût est imprimé sur la carte Lieu. C’est ainsi qu’on récolte et qu’on échange des ressources.',
            'Une action marquée « une fois par jour » se couvre d’un pion Temps après usage.',
          ],
          warn: 'Si le lieu porte déjà un pion Temps pour autre chose, utilisez un marqueur universel pour l’action de lieu, et retirez-le à l’étape 4 de l’aube.',
          components: ['pions-temps'],
          ref: 'Action de lieu — p.8',
        },
        {
          id: 'j7',
          kind: 'action',
          title: 'Utilisez l’action de votre personnage',
          body: [
            'Elle est imprimée au recto de votre tuile, et son coût varie d’un personnage à l’autre.',
            'Elle ne s’utilise jamais pendant une rencontre ou une exploration.',
          ],
          components: ['tuiles-perso'],
          ref: 'Action de personnage — p.9',
        },
        {
          id: 'j8',
          kind: 'action',
          title: 'Inspectez un menhir — c’est gratuit',
          body: [
            'Dans un lieu portant le symbole Menhir, retournez la carte et lisez la section menhir en bas.',
            'Elle vous dit ce qu’il faut posséder pour l’activer.',
          ],
          tip: 'Sachez toujours quel est le prochain menhir à activer, et ce qu’il coûte. C’est la seule vraie contrainte de la partie.',
          warn: 'Le coût d’activation d’un menhir dépend du nombre de joueurs de la partie, pas de la taille de votre groupe.',
          components: ['fig-menhir'],
          crop: { page: 10, x: 0.663, y: 0.103, w: 0.292, h: 0.045 },
          ref: 'Inspection de menhir — p.9',
        },
        {
          id: 'j9',
          kind: 'action',
          title: 'Passer — gratuit et définitif',
          body: [
            'Vous décidez d’arrêter votre journée, même s’il vous reste de l’Énergie.',
          ],
          warn: 'Une fois que vous avez passé, vous ne pouvez plus rien faire avant le jour suivant.',
          ref: 'Passer — p.9',
        },
        {
          id: 'j10',
          kind: 'info',
          title: 'Agir en groupe',
          only: [2, 3, 4],
          body: [
            'Plusieurs personnages sur un même lieu peuvent effectuer une action ensemble.',
            'En voyage de groupe, le coût passe à 1 Énergie par membre. En action de lieu, on ne paie le coût qu’une fois, et on se le partage comme on veut.',
          ],
          warn: 'On ne rejoint un groupe qu’avant le début de l’action, et on ne le quitte jamais au milieu d’une action.',
          ref: 'Groupes et Actions de Groupe — p.11',
        },
        {
          id: 'j11',
          kind: 'info',
          title: 'Le crépuscule commence',
          body: [
            'Il démarre dès que tout le monde a passé ou n’a plus assez d’Énergie.',
            'Six étapes, dans l’ordre, pour chaque personnage.',
          ],
          ref: 'Le Crépuscule — p.9',
        },
        {
          id: 'j12',
          kind: 'action',
          title: 'Crépuscule 1 et 2 : effets, puis repos',
          body: [
            'Résolvez d’abord les effets d’objets ou de compétences marqués « au crépuscule ».',
            'Puis, si vous le souhaitez, payez 1 Nourriture pour récupérer 1 Santé et perdre 1 Terreur.',
          ],
          widget: {
            kind: 'choice',
            title: 'Vous avez 3 Nourriture. Vous reposez-vous ?',
            options: [
              {
                label: 'Payer 1 Nourriture',
                outcome: '+1 Santé et −1 Terreur. Il vous reste 2 Nourriture. C’est presque toujours le bon choix.',
                tint: '#7ba05b',
              },
              {
                label: 'Garder la Nourriture',
                outcome: 'Rien ne se passe : ni soin, ni Terreur en moins. Vous gardez vos 3 Nourriture pour un menhir ou un échange.',
                tint: '#a89e8c',
              },
            ],
          },
          tip: 'Des personnages sur un même lieu peuvent s’échanger Nourriture et Richesse à tout moment, tant qu’ils ne sont pas en pleine action.',
          ref: 'Le Crépuscule, étapes 1 et 2 — p.9',
        },
        {
          id: 'j13',
          kind: 'action',
          title: 'Crépuscule 3 : récupérez votre Énergie',
          body: [
            'Replacez votre marqueur d’Énergie dans sa case de départ.',
            'Si vous étiez épuisé, dans une case rouge, vous ne récupérez que 4 points.',
          ],
          warn: 'Votre Énergie ne peut jamais dépasser votre Santé. Si vous êtes blessé, la case de départ est hors d’atteinte.',
          ref: 'Le Crépuscule, étape 3 — p.9',
        },
        {
          id: 'j14',
          kind: 'action',
          title: 'Crépuscule 4 et 5 : progressez et reconstruisez',
          body: [
            'Dépensez votre Expérience : augmenter une caractéristique, acheter une compétence, ou piocher dans une réserve de progression.',
            'Pour 2 Expérience, piochez les 3 premières cartes de la réserve, gardez-en une, remélangez les autres.',
            'Retirez ensuite de vos paquets les cartes qui ne vous servent pas.',
          ],
          warn: 'Vos paquets Combat et Diplomatie doivent toujours contenir au moins 15 cartes chacun.',
          components: ['cartes-avancees', 'cartes-competence'],
          ref: 'Le Crépuscule, étapes 4 et 5 — p.9',
        },
        {
          id: 'j15',
          kind: 'action',
          title: 'Crépuscule 6 : plongez dans un rêve',
          body: [
            'Si votre lieu porte le symbole Rêve, lisez l’entrée correspondante du journal d’exploration.',
            'Si la carte « Vous Devenez Fou » est attachée à votre plateau, lisez le cauchemar à la place.',
          ],
          tip: 'Chaque rêve ne se lit qu’une seule fois pour l’ensemble des personnages présents dans le lieu.',
          ref: 'Le Crépuscule, étape 6 — p.9',
        },
      ],
    },

    {
      id: 'combat',
      title: 'Votre première rencontre : le combat',
      kind: 'play',
      goal: 'Gagner un combat en construisant une séquence de cartes et en reliant ses clés.',
      steps: [
        {
          id: 'c1',
          kind: 'info',
          title: 'Ce qu’est un combat ici',
          body: [
            'Un affrontement tour par tour contre une carte Rencontre.',
            'Vous alignez des cartes Combat côte à côte — c’est la séquence — pour accumuler assez de marqueurs dans le potentiel de combat.',
          ],
          tip: 'Pour votre premier combat, utilisez la carte « Votre Première Rencontre » : elle est conçue pour apprendre.',
          components: ['rencontres'],
          ref: 'Combat — p.14',
        },
        {
          id: 'c2',
          kind: 'take',
          title: 'Piochez la carte Rencontre',
          body: [
            'Dans le paquet gris, vert ou violet, selon ce que le jeu vous indique.',
            'Posez-la à gauche de votre zone de jeu, en gardant de la place à droite pour aligner la séquence.',
          ],
          components: ['rencontres'],
          crop: { page: 17, x: 0.05, y: 0.165, w: 0.28, h: 0.185 },
          ref: 'Commencer le Combat — p.14',
        },
        {
          id: 'c3',
          kind: 'check',
          title: 'Lisez les traits et vérifiez votre équipement',
          body: [
            'Certains traits agissent dès maintenant : Lent fait piocher une carte de plus, Fonceur fait subir 2 dégâts au premier activé.',
            'Vous ne pouvez utiliser qu’un seul objet de chaque mot-clé : Arme, Armure, Bouclier, Compagnon, Relique.',
          ],
          warn: 'Une fois le combat commencé, vous ne pouvez plus ajouter d’objet. Mettez de côté ce que vous n’utilisez pas.',
          components: ['cartes-objet'],
          ref: 'Traits des Rencontres de Combat — p.16',
        },
        {
          id: 'c4',
          kind: 'take',
          title: 'Piochez 3 cartes Combat',
          only: [1, 2, 3],
          body: ['Votre main de départ, prise dans votre paquet Combat.'],
          tip: 'Main décevante ? Défaussez-la et repiochez, avec une carte de moins à chaque fois, jusqu’à n’en garder qu’une.',
          components: ['cartes-standard'],
          ref: 'Commencer le Combat — p.14',
        },
        {
          id: 'c4-4',
          kind: 'take',
          title: 'Piochez 2 cartes Combat',
          only: [4],
          body: [
            'À quatre personnages impliqués dans la rencontre, la main de départ tombe à 2 cartes.',
          ],
          tip: 'Main décevante ? Défaussez-la et repiochez, avec une carte de moins, jusqu’à n’en garder qu’une.',
          components: ['cartes-standard'],
          ref: 'Commencer le Combat — p.14',
        },
        {
          id: 'c5',
          kind: 'info',
          title: 'Phase I : qui est le personnage actif',
          only: [2, 3, 4],
          body: [
            'Le groupe désigne un personnage n’ayant pas encore été activé ce tour-ci.',
            'Posez un pion Temps sur son plateau pour s’en souvenir.',
          ],
          warn: 'À défaut d’accord unanime, c’est le personnage non activé au plus petit numéro qui est activé.',
          components: ['pions-temps'],
          ref: 'Tour de Combat, phase I — p.15',
        },
        {
          id: 'c5-solo',
          kind: 'info',
          title: 'Phase I : posez votre pion Temps',
          only: [1],
          body: [
            'Vous êtes le seul personnage actif. Posez un pion Temps sur votre plateau pour marquer que vous avez été activé ce tour.',
          ],
          components: ['pions-temps'],
          ref: 'Tour de Combat, phase I — p.15',
        },
        {
          id: 'c6',
          kind: 'action',
          title: 'Phase II.1 : les capacités différées',
          body: [
            'Retirez 1 pion Temps de chaque carte de la séquence qui en porte.',
            'Si vous retirez le dernier pion d’une carte, sa capacité se déclenche immédiatement — une seule fois.',
          ],
          warn: 'Une carte posée par-dessus une capacité différée fait perdre le pion Temps : la capacité ne se déclenchera jamais.',
          components: ['pions-temps'],
          ref: 'Tour de Combat, phase II.1 — p.15',
        },
        {
          id: 'c7',
          kind: 'action',
          title: 'Phase II.2 : jouez votre première carte',
          body: [
            'Elle n’a aucune condition à remplir. Elle doit seulement s’aligner sur la carte précédente de la séquence.',
            'Résolvez ensuite ses clés dans l’ordre : caractéristique, magique, gratuite, puis la capacité de la carte.',
          ],
          crop: { page: 17, x: 0.05, y: 0.165, w: 0.28, h: 0.185 },
          ref: 'Tour de Combat, phase II.2a — p.15',
        },
        {
          id: 'c8',
          kind: 'info',
          title: 'Les quatre sortes de clés',
          body: [
            'Clé de caractéristique : elle ne se relie que si vous avez le niveau indiqué dans cette caractéristique.',
            'Clé magique : elle se relie en payant 1 Magie.',
            'Clé gratuite : elle se relie toujours, et porte souvent un multiplicateur.',
            'Clé bonus, en forme d’éclair : c’est elle qui autorise à jouer une carte de plus.',
          ],
          warn: 'La clé éclair doit apparaître sur la carte que vous voulez jouer, pas sur la précédente, et elle doit pouvoir être reliée.',
          ref: 'Relier des Clés — p.16 et Bonus de Combat — p.16',
        },
        {
          id: 'c9',
          kind: 'action',
          title: 'Phase II.2b : enchaînez les cartes suivantes',
          body: [
            'Chaque carte jouée après la première DOIT être reliée par une clé éclair.',
            'Sans clé éclair reliable, votre activation s’arrête là.',
          ],
          crop: { page: 17, x: 0.05, y: 0.44, w: 0.28, h: 0.175 },
          ref: 'Tour de Combat, phase II.2b — p.15',
        },
        {
          id: 'c10',
          kind: 'check',
          title: 'Phase II.2c et 2d : opportunité, puis victoire',
          body: [
            'Si vous n’avez joué aucune carte pendant votre activation, l’ennemi effectue son attaque d’opportunité, et vous piochez une carte.',
            'Sinon, comptez les marqueurs du potentiel de combat.',
          ],
          warn: 'Dès que le potentiel atteint la valeur de la rencontre, vous gagnez immédiatement.',
          ref: 'Contrôle de Victoire — p.15',
        },
        {
          id: 'c11',
          kind: 'action',
          title: 'Phase II.3 : l’ennemi attaque',
          body: [
            'Sur la carte Rencontre, cherchez la ligne du tableau qui correspond au nombre de marqueurs du potentiel.',
            'Appliquez le résultat au personnage actif, de gauche à droite.',
          ],
          warn: 'Si l’attaque retire plus de marqueurs que le potentiel n’en contient, défaussez 1 carte de votre main par marqueur manquant.',
          crop: { page: 17, x: 0.36, y: 0.1, w: 0.27, h: 0.2 },
          ref: 'Tour de Combat, phase II.3 — p.15',
        },
        {
          id: 'c12',
          kind: 'action',
          title: 'Phase III : fin du tour',
          body: [
            'Défaussez jusqu’à n’avoir que 3 cartes en main.',
            'Piochez 1 carte, puis retirez les pions Temps des plateaux Personnage.',
            'Un nouveau tour commence.',
          ],
          warn: 'Les pions Temps posés sur les cartes de la séquence ne sont pas retirés à cette étape : eux se décomptent en phase II.1.',
          ref: 'Tour de Combat, phase III — p.15',
        },
        {
          id: 'c13',
          kind: 'info',
          title: 'Simulation : Béor contre le Vagabond',
          body: [
            'Rencontre grise, valeur 5, trait Rapide : Béor ne peut jouer que 2 cartes par tour.',
            'On va dérouler les deux tours de l’exemple officiel, coup par coup.',
          ],
          crop: { page: 17, x: 0.05, y: 0.165, w: 0.28, h: 0.185 },
          ref: 'Exemple de Combat — p.17',
        },
        {
          id: 'c14',
          kind: 'action',
          title: 'Tour 1 — Béor joue « Attaque »',
          body: [
            'Il pioche 3 cartes et pose « Attaque » comme première carte de la séquence.',
            'Béor a 2 points en Agression : la clé Agression se relie et ajoute 1 marqueur.',
            'La clé bonus se relie aussi : 1 marqueur de plus.',
          ],
          crop: { page: 17, x: 0.05, y: 0.165, w: 0.28, h: 0.185 },
          widget: {
            kind: 'counter',
            title: 'Potentiel de combat',
            min: 0,
            max: 8,
            start: 2,
            unit: 'marqueurs',
          },
          ref: 'Exemple de Combat, tour 1 — p.17',
        },
        {
          id: 'c15',
          kind: 'action',
          title: 'Tour 1 — puis « Défense », en payant 1 Magie',
          body: [
            'Rapide l’empêche d’en jouer une troisième : autant que la seconde serve.',
            'Il relie la clé magique en payant 1 Magie, ce qui active le bonus éclair nécessaire pour jouer cette carte.',
            'La carte porte un symbole différé : Béor y pose 1 pion Temps.',
          ],
          components: ['pions-temps'],
          crop: { page: 17, x: 0.05, y: 0.44, w: 0.28, h: 0.175 },
          ref: 'Exemple de Combat, tour 1 — p.17',
        },
        {
          id: 'c16',
          kind: 'action',
          title: 'Tour 1 — le Vagabond riposte',
          body: [
            'Le potentiel contient 2 marqueurs : la ligne correspondante inflige 2 dégâts et retire 1 marqueur.',
            '« Défense » réduit les dégâts subis de 2 : il ne reste que la perte d’un marqueur.',
            'Potentiel : 1. Béor pioche 1 carte.',
          ],
          widget: {
            kind: 'counter',
            title: 'Potentiel de combat après l’attaque',
            min: 0,
            max: 8,
            start: 1,
            unit: 'marqueurs',
          },
          crop: { page: 17, x: 0.36, y: 0.1, w: 0.27, h: 0.2 },
          ref: 'Exemple de Combat, tour 1 — p.17',
        },
        {
          id: 'c17',
          kind: 'action',
          title: 'Tour 2 — « Lancer » ouvre le tour',
          body: [
            'Béor retire le pion Temps de « Défense » et pioche 1 carte.',
            'Première carte du tour : elle n’a pas besoin du bonus éclair.',
            'Il relie la clé de caractéristique — 1 marqueur — et la clé gratuite, dotée d’un multiplicateur ×2 — 2 marqueurs.',
          ],
          tip: 'Il choisit de ne pas relier la clé magique : sa Magie servira mieux à la carte suivante.',
          widget: {
            kind: 'counter',
            title: 'Potentiel de combat',
            min: 0,
            max: 8,
            start: 4,
            unit: 'marqueurs',
          },
          crop: { page: 17, x: 0.36, y: 0.44, w: 0.27, h: 0.175 },
          ref: 'Exemple de Combat, tour 2 — p.17',
        },
        {
          id: 'c18',
          kind: 'action',
          title: 'Tour 2 — « Rage » emporte le combat',
          body: [
            'Béor paie 1 Magie pour relier la clé magique : c’est le bonus qui l’autorise à jouer une carte de plus.',
            'La capacité au placement lui fait dépenser 1 Énergie et ajouter 1 marqueur par clé de caractéristique reliée dans toute la séquence.',
            'Il y en a 2 : le potentiel passe à 6, au-dessus de la valeur 5 de la rencontre.',
          ],
          widget: {
            kind: 'counter',
            title: 'Potentiel de combat — valeur à atteindre : 5',
            min: 0,
            max: 8,
            start: 6,
            unit: 'marqueurs',
          },
          crop: { page: 17, x: 0.66, y: 0.1, w: 0.29, h: 0.2 },
          ref: 'Exemple de Combat, tour 2 — p.17',
        },
        {
          id: 'c19',
          kind: 'check',
          title: 'Après la victoire',
          body: [
            'Prenez le butin indiqué sur la carte Rencontre, ici 1 objet d’artisanat.',
            'Replacez la carte Rencontre au bas de son paquet d’origine.',
            'Remélangez votre paquet Combat, cartes jouées et défaussées comprises, et remettez-le à sa place.',
          ],
          ref: 'Contrôle de Victoire — p.15',
        },
        {
          id: 'c20',
          kind: 'info',
          title: 'Si vous ne pouvez pas gagner : fuyez',
          body: [
            'On fuit à n’importe quel moment de son activation. Vous perdez 1 Énergie et subissez l’attaque d’opportunité.',
            'La carte Rencontre retourne au bas de son paquet, et vous remélangez votre paquet Combat.',
          ],
          warn: 'Si votre paquet Combat n’a plus assez de cartes à piocher, vous êtes contraint de fuir.',
          ref: 'Fuir le Combat — p.14 et Plus de Cartes dans le Paquet — p.16',
        },
      ],
    },

    {
      id: 'diplo',
      title: 'La diplomatie',
      kind: 'play',
      goal: 'Résoudre une rencontre bleue sans verser de sang.',
      steps: [
        {
          id: 'd1',
          kind: 'info',
          title: 'Même moteur, autre objectif',
          body: [
            'Le paquet bleu se résout en diplomatie : mêmes séquences, mêmes clés, même tour en trois phases.',
            'Ce que vous faites monter, ici, c’est le marqueur sur la piste Affinité de la carte Rencontre.',
          ],
          components: ['rencontres'],
          ref: 'Diplomatie — p.18',
        },
        {
          id: 'd2',
          kind: 'take',
          title: 'Posez la rencontre et piochez votre main',
          only: [1, 2, 3],
          body: [
            'Vérifiez votre équipement comme en combat, puis piochez 3 cartes Diplomatie.',
            'Placez un marqueur dans la case grise de la piste Affinité.',
          ],
          components: ['rencontres', 'marqueurs-univ'],
          ref: 'Commencer la Diplomatie — p.18',
        },
        {
          id: 'd2-4',
          kind: 'take',
          title: 'Posez la rencontre et piochez votre main',
          only: [4],
          body: [
            'Vérifiez votre équipement comme en combat, puis piochez 2 cartes Diplomatie : vous êtes quatre.',
            'Placez un marqueur dans la case grise de la piste Affinité.',
          ],
          components: ['rencontres', 'marqueurs-univ'],
          ref: 'Commencer la Diplomatie — p.18',
        },
        {
          id: 'd3',
          kind: 'action',
          title: 'Jouez vos cartes comme en combat',
          body: [
            'Première carte sans condition, cartes suivantes reliées par une clé éclair.',
            'Résolvez les clés dans le même ordre : caractéristique, magique, gratuite, puis capacité.',
          ],
          ref: 'Tour de Diplomatie, phase II — p.19',
        },
        {
          id: 'd4',
          kind: 'check',
          title: 'Le contrôle d’affinité',
          body: [
            'Marqueur sur la case la plus basse : vous perdez la rencontre, et chacun subit les pénalités de la partie « Échec ».',
            'Marqueur sur la case la plus haute : vous remportez le palier en cours.',
          ],
          warn: 'S’il ne s’agissait pas du dernier palier, remettez le marqueur sur la case grise, posez-en un sur le palier accompli, et continuez.',
          ref: 'Contrôle d’Affinité — p.19',
        },
        {
          id: 'd5',
          kind: 'info',
          title: 'Éviter la rencontre',
          body: [
            'Si la carte comporte une partie « Éviter », vous pouvez la contourner en payant le coût indiqué.',
            'La carte retourne alors au bas du paquet bleu et la partie reprend.',
          ],
          warn: 'On ne peut éviter une rencontre qu’avant de l’avoir commencée, c’est-à-dire avant de piocher des cartes.',
          ref: 'Fuir ou Éviter la Diplomatie — p.18',
        },
        {
          id: 'd6',
          kind: 'info',
          title: 'Décider ensemble',
          only: [2, 3, 4],
          body: [
            'Éviter ou échouer est une décision de groupe : tous les membres évitent ou échouent ensemble.',
            'Pour éviter, prenez toujours la plus haute valeur de Réputation ou de caractéristique requise, sans jamais les additionner.',
          ],
          ref: 'Fuir ou Éviter la Diplomatie — p.18',
        },
      ],
    },

    {
      id: 'aube',
      title: 'L’aube du jour 2',
      kind: 'play',
      goal: 'Enchaîner les neuf étapes de l’aube sans en oublier une.',
      steps: [
        {
          id: 'a1',
          kind: 'action',
          title: 'Aube 1 et 2 : effets, puis menhirs éteints',
          body: [
            'Résolvez les effets marqués « à l’aube », dans l’ordre de votre choix.',
            'Un menhir sans cadran sous sa base s’éteint : retirez-le du plateau. Les autres restent actifs.',
          ],
          components: ['fig-menhir', 'cadrans'],
          ref: 'L’Aube, étapes 1 et 2 — p.8',
        },
        {
          id: 'a2',
          kind: 'action',
          title: 'Aube 3 : retirez les lieux hors de portée',
          body: [
            'Tout lieu en jeu doit être adjacent, orthogonalement ou en diagonale, à un lieu contenant un menhir actif.',
            'Défaussez les autres.',
          ],
          warn: 'Les personnages présents sur un lieu retiré perdent 2 Santé et gagnent 2 Terreur, puis sont déplacés vers le lieu restant le plus proche.',
          components: ['cartes-lieu'],
          ref: 'L’Aube, étape 3 — p.8 et Menhirs et Wyrd — p.11',
        },
        {
          id: 'a3',
          kind: 'action',
          title: 'Aube 4 : baissez les cadrans des menhirs',
          body: [
            'Réduisez de 1 le cadran de chaque menhir actif.',
            'Si un cadran était déjà sur 1, retirez-le de la base du menhir.',
          ],
          warn: 'Le menhir ne disparaît pas tout de suite : il ne deviendra inactif qu’à l’aube suivante. Il vous reste une journée.',
          components: ['cadrans'],
          ref: 'L’Aube, étape 4 — p.8',
        },
        {
          id: 'a4',
          kind: 'action',
          title: 'Aube 5 : cadrans Temps et pions Temps',
          body: [
            'Réduisez de 1 tous les cadrans dotés d’un pion Temps, y compris ceux posés sur des cartes Secret.',
            'Retirez 1 pion Temps de chaque lieu qui en porte un.',
          ],
          warn: 'Les cadrans dotés d’un pion Quête ne se réduisent PAS automatiquement : ils suivent les règles de leur carte.',
          components: ['pions-temps', 'pions-quete'],
          ref: 'L’Aube, étape 5 — p.8',
        },
        {
          id: 'a5',
          kind: 'action',
          title: 'Aube 6 : déplacez les gardiens',
          body: [
            'Lancez le dé Gardien pour chaque gardien présent sur le plateau.',
            'Un point cardinal le déplace ; « rien » le laisse sur place ; la défausse le renvoie au bas de son paquet Rencontre.',
          ],
          warn: 'Si un gardien arrive dans un lieu occupé, la rencontre se déclenche immédiatement, et tous les personnages présents combattent en groupe.',
          components: ['de-gardien', 'fig-precurseur'],
          crop: { page: 3, x: 0.826, y: 0.208, w: 0.124, h: 0.094 },
          ref: 'L’Aube, étape 6 — p.8 et Gardiens — p.12',
        },
        {
          id: 'a6',
          kind: 'action',
          title: 'Aube 7 : révélez une carte Événement',
          body: [
            'Piochez la carte suivante du paquet Événement et lisez-la à voix haute.',
            'Si elle contient une quête, marquée d’un cadenas rouge, placez-la dans la pile Quête Active.',
          ],
          warn: 'Ne défaussez jamais une carte contenant une quête tant que le jeu ne vous le dit pas clairement.',
          components: ['evenements'],
          ref: 'L’Aube, étape 7 — p.8 et Événements, Quêtes et Tâches — p.11',
        },
        {
          id: 'a7',
          kind: 'info',
          title: 'Aube 8 : établissez votre stratégie',
          only: [2, 3, 4],
          body: [
            'Prenez le temps de décider ensemble qui va où, et qui paie quoi.',
            'C’est une aventure coopérative : vous gagnez ou vous perdez ensemble.',
          ],
          tip: 'Se séparer permet de couvrir plus de terrain. Rester groupés rend les rencontres bien moins dangereuses. Il faut choisir.',
          ref: 'L’Aube, étape 8 — p.8',
        },
        {
          id: 'a8',
          kind: 'check',
          title: 'Aube 9 : équipez-vous',
          body: [
            'Vérifiez que vous n’avez pas plusieurs objets révélés portant le même mot-clé.',
            'Retournez face cachée les objets surnuméraires.',
          ],
          components: ['cartes-objet'],
          ref: 'L’Aube, étape 9 — p.8 et Objets et Équipement — p.12',
        },
        {
          id: 'a9',
          kind: 'check',
          title: 'Le jour 2 peut commencer',
          body: [
            'Vous savez maintenant enchaîner un jour complet, tout seuls.',
            'Le reste de la campagne se joue exactement comme ça, jour après jour.',
          ],
          ref: 'Cours du Jour — p.8 et Résumé des Règles — p.24',
        },
      ],
    },

    /* -------------------------------------------------- reprise de campagne */

    {
      id: 'rp-perso',
      title: 'Reprendre : les personnages',
      kind: 'setup',
      modes: ['reprise'],
      goal: 'Remonter chaque plateau Personnage à partir de la fiche de sauvegarde.',
      steps: [
        {
          id: 'rp1',
          kind: 'take',
          title: 'Sortez la fiche de sauvegarde',
          body: [
            'C’est le carnet de bord de la campagne : elle porte tout ce qui ne tient pas dans la boîte.',
            'La remise en place consiste à dérouler la sauvegarde à l’envers, dans cet ordre.',
          ],
          components: ['fiches'],
          crop: { page: 2, x: 0.665, y: 0.29, w: 0.152, h: 0.115 },
          ref: 'Sauvegarder la Partie — p.13',
        },
        {
          id: 'rp2',
          kind: 'take',
          title: 'Chacun reprend son personnage',
          body: [
            'Plateau, tuile Personnage et figurine de la même couleur qu’à la séance précédente.',
            'Le schéma qui porte votre nom sur la fiche est le vôtre.',
          ],
          components: ['plateaux', 'tuiles-perso', 'figurines'],
          ref: 'Sauvegarder la Partie, I.1 — p.13',
        },
        {
          id: 'rp3',
          kind: 'place',
          title: 'Reportez vos caractéristiques, ressources et pistes Survie',
          body: [
            'Tout est écrit au crayon sur votre schéma : les six caractéristiques, les cinq ressources, Énergie, Santé et Terreur.',
            'Reposez les marqueurs universels et le marqueur en T aux valeurs notées.',
          ],
          warn: 'Vérifiez que votre Énergie ne dépasse pas votre Santé : c’est l’erreur la plus fréquente au remontage.',
          components: ['marqueurs-univ', 'marqueur-t'],
          crop: { page: 10, x: 0.078, y: 0.763, w: 0.218, h: 0.108 },
          ref: 'Sauvegarder la Partie, I.1 — p.13',
        },
        {
          id: 'rp4',
          kind: 'take',
          title: 'Reprenez vos compétences',
          body: [
            'Leur numéro unique est noté à côté de la caractéristique correspondante.',
            'Cherchez-les dans le paquet Compétence et reposez-les devant vous.',
          ],
          components: ['cartes-competence'],
          ref: 'Sauvegarder la Partie, I.2 — p.13',
        },
        {
          id: 'rp5',
          kind: 'take',
          title: 'Reprenez vos Objets et vos Secrets',
          body: [
            'Ils sont dans votre compartiment de sauvegarde, celui que vous aviez choisi.',
            'Reposez aussi les cadrans Quête ou Secret aux valeurs notées sur la fiche.',
          ],
          components: ['cartes-objet', 'cartes-secret', 'cadrans', 'pions-quete'],
          ref: 'Sauvegarder la Partie, I.3 et I.5 — p.13',
        },
        {
          id: 'rp6',
          kind: 'shuffle',
          title: 'Reconstituez vos quatre piles de cartes',
          body: [
            'Votre paquet Combat et votre paquet Diplomatie, mélangés, de part et d’autre du plateau.',
            'Vos deux réserves de progression, sous leur carte « Réserve de Progression ».',
          ],
          warn: 'La carte séparatrice marque le sommet de la réserve : ce qui est au-dessus est votre paquet de jeu, ce qui est en dessous votre réserve.',
          components: ['cartes-standard', 'cartes-avancees'],
          ref: 'Sauvegarder la Partie, I.6 — p.13',
        },
        {
          id: 'rp7',
          kind: 'check',
          title: 'Votre personnage est remonté',
          body: [
            'Caractéristiques, ressources et pistes Survie aux valeurs de la fiche ; compétences devant vous ; Objets et Secrets sortis du compartiment ; les quatre piles reconstituées.',
            'Les cartes Secret, Objet, Rencontre ou Événement non utilisées sont restées dans la boîte : elles ne font pas partie de la partie sauvegardée.',
          ],
          ref: 'Sauvegarder la Partie, I et II.6 — p.13',
        },
      ],
    },

    {
      id: 'rp-monde',
      title: 'Reprendre : le monde',
      kind: 'setup',
      modes: ['reprise'],
      goal: 'Remonter la carte, les menhirs et les paquets exactement comme ils étaient.',
      steps: [
        {
          id: 'rp8',
          kind: 'place',
          title: 'Reconstruisez la carte',
          body: [
            'Reprenez la pile de cartes Lieu : au-dessus du séparateur « Lieux Révélés », les lieux qui étaient en jeu.',
            'Reposez-les selon leurs clés de direction, autour du lieu où se trouvaient les personnages.',
          ],
          warn: 'Les lieux retirés de la partie sont rangés à part, dans le petit compartiment. Ils ne reviennent jamais.',
          components: ['cartes-lieu'],
          crop: { page: 7, x: 0.393, y: 0.542, w: 0.218, h: 0.156 },
          ref: 'Sauvegarder la Partie, II.3 — p.13',
        },
        {
          id: 'rp9',
          kind: 'place',
          title: 'Replacez menhirs, gardiens et cadrans',
          body: [
            'La fiche note le lieu de chaque menhir et de chaque gardien, et la valeur de chaque cadran.',
            'Glissez chaque cadran sous son menhir à la valeur écrite.',
          ],
          warn: 'Un menhir noté sans cadran s’éteindra à la prochaine aube : ne lui en remettez pas un.',
          components: ['fig-menhir', 'cadrans', 'fig-precurseur'],
          crop: { page: 7, x: 0.398, y: 0.324, w: 0.194, h: 0.112 },
          ref: 'Sauvegarder la Partie, II.1 — p.13',
        },
        {
          id: 'rp10',
          kind: 'place',
          title: 'Posez les figurines sur leur lieu',
          body: ['Chaque personnage retrouve le lieu noté sur la fiche.'],
          components: ['figurines'],
          ref: 'Sauvegarder la Partie, II.1 — p.13',
        },
        {
          id: 'rp11',
          kind: 'take',
          title: 'Ressortez les paquets sauvegardés',
          body: [
            'Les quatre paquets Rencontre, sous le séparateur « Rencontres Sauvegardées ».',
            'Le paquet Événement et vos quêtes actives, sous le séparateur « Événements Sauvegardés ».',
          ],
          warn: 'Ne remélangez rien : ces paquets ont été rangés dans l’ordre où vous les aviez laissés.',
          components: ['rencontres', 'evenements'],
          ref: 'Sauvegarder la Partie, II.4 et II.5 — p.13',
        },
        {
          id: 'rp12',
          kind: 'info',
          title: 'Ajouter ou retirer un joueur',
          only: [2, 3, 4],
          body: [
            'À chaque nouvelle séance, l’effectif peut changer, dans la limite de 1 à 4.',
            'Les Secrets d’un personnage qui s’en va sont répartis entre ceux qui restent.',
            'Une recrue démarre sur le lieu d’un ancien, avec ses paquets et ses ressources de départ.',
          ],
          warn: 'Un Secret ne sort jamais de la partie, sauf instruction contraire de la carte.',
          components: ['cartes-secret'],
          ref: 'Ajouter ou Retirer des Joueurs — p.13',
        },
        {
          id: 'rp13',
          kind: 'check',
          title: 'Relisez avant de reprendre',
          body: [
            'Vos quêtes actives : ce sont elles qui disent où aller.',
            'Les statuts notés sur la fiche : ils ont changé le monde pour de bon.',
            'Le cadran du menhir le plus faible : c’est votre compte à rebours.',
          ],
          tip: 'Le rappel des règles, sur l’accueil, remet le cours du jour en tête en huit étapes.',
          components: ['fiches'],
          ref: 'Sauvegarder la Partie — p.13',
        },
        {
          id: 'rp14',
          kind: 'info',
          title: 'Où reprend-on ?',
          body: [
            'Une sauvegarde faite en fin de chapitre reprend à l’aube suivante.',
            'Une sauvegarde faite en cours de journée reprend là où elle s’est arrêtée, si vous l’avez notée.',
          ],
          warn: 'Le livret déconseille de sauvegarder en pleine journée : on oublie le détail d’une quête en cours, et les actions « une fois par jour » se retrouvent disponibles trop tôt.',
          ref: 'Sauvegarder la Partie — p.13',
        },
      ],
    },

    /* ------------------------------------------------- rappel des règles */

    {
      id: 'r-jour',
      title: 'Le cours du jour',
      kind: 'play',
      modes: ['recap'],
      goal: 'Retrouver les trois temps d’une journée et ce qu’on y fait.',
      steps: [
        {
          id: 'r1',
          kind: 'info',
          title: 'Ce qui vous presse',
          body: [
            'Un lieu ne reste en jeu que s’il touche, même en diagonale, un lieu portant un menhir actif.',
            'Chaque menhir a un cadran qui perd 1 jour à chaque aube. À zéro, il s’éteint, et la carte disparaît.',
          ],
          warn: 'Un personnage sur un lieu retiré perd 2 Santé, gagne 2 Terreur, et se retrouve sur le lieu restant le plus proche.',
          crop: { page: 7, x: 0.398, y: 0.324, w: 0.194, h: 0.112 },
          ref: 'Menhirs et Wyrd — p.11',
        },
        {
          id: 'r2',
          kind: 'info',
          title: 'L’aube, neuf étapes',
          body: [
            '1. Effets d’aube. 2. Menhirs sans cadran retirés. 3. Lieux hors de portée défaussés.',
            '4. Cadrans des menhirs réduits de 1. 5. Cadrans Temps réduits, pions Temps retirés des lieux.',
            '6. Gardiens déplacés au dé. 7. Carte Événement révélée. 8. Concertation. 9. Équipement vérifié.',
          ],
          ref: 'L’Aube — p.8',
        },
        {
          id: 'r3-solo',
          kind: 'info',
          title: 'La journée : six actions',
          only: [1],
          body: [
            'Exploration (1 Énergie), Voyage (1 Énergie), action de lieu (coût imprimé), action de personnage.',
            'Inspection de menhir et Passer sont gratuites.',
            'Vous enchaînez vos actions jusqu’à passer ou manquer d’Énergie.',
          ],
          warn: 'On ne voyage qu’orthogonalement, et seulement entre lieux reliés par des clés de direction.',
          crop: { page: 8, x: 0.655, y: 0.28, w: 0.3, h: 0.26 },
          ref: 'La Journée — p.8-9',
        },
        {
          id: 'r3',
          kind: 'info',
          title: 'La journée : six actions',
          only: [2, 3, 4],
          body: [
            'Exploration (1 Énergie), Voyage (1 Énergie), action de lieu (coût imprimé), action de personnage.',
            'Inspection de menhir et Passer sont gratuites.',
            'On joue chacun son tour, jusqu’à ce que tous aient passé ou manquent d’Énergie.',
          ],
          warn: 'On ne voyage qu’orthogonalement, et seulement entre lieux reliés par des clés de direction.',
          crop: { page: 8, x: 0.655, y: 0.28, w: 0.3, h: 0.26 },
          ref: 'La Journée — p.8-9',
        },
        {
          id: 'r4',
          kind: 'info',
          title: 'Le crépuscule, six étapes',
          body: [
            '1. Effets de crépuscule. 2. Repos : 1 Nourriture pour +1 Santé et −1 Terreur.',
            '3. Énergie remise à sa case de départ — 4 points seulement si vous étiez épuisé.',
            '4. Expérience dépensée. 5. Paquets reconstruits, 15 cartes minimum. 6. Rêve, si le lieu en porte le symbole.',
          ],
          warn: 'Votre Énergie ne dépasse jamais votre Santé, quelle que soit l’étape.',
          ref: 'Le Crépuscule — p.9',
        },
      ],
    },

    {
      id: 'r-rencontre',
      title: 'Combat et diplomatie',
      kind: 'play',
      modes: ['recap'],
      goal: 'Retrouver le tour de rencontre et l’usage des clés.',
      steps: [
        {
          id: 'r5',
          kind: 'info',
          title: 'Le même moteur, deux buts',
          body: [
            'Paquets vert, gris et violet : combat, on remplit le potentiel de combat.',
            'Paquet bleu : diplomatie, on fait monter le marqueur sur la piste Affinité.',
            'Main de départ : 3 cartes, 2 si quatre personnages sont impliqués. Mulligan possible, une carte de moins à chaque fois.',
          ],
          ref: 'Combat — p.14, Diplomatie — p.18',
        },
        {
          id: 'r6',
          kind: 'info',
          title: 'Le tour, en trois phases',
          body: [
            'I. Un personnage non activé est désigné : pion Temps sur son plateau.',
            'II. 1 capacités différées, 2 cartes jouées, 3 attaque de l’ennemi, 4 disponibilité.',
            'III. Défausser jusqu’à 3 cartes, en piocher 1, retirer les pions Temps des plateaux.',
          ],
          ref: 'Tour de Combat — p.15',
        },
        {
          id: 'r7',
          kind: 'info',
          title: 'Relier les clés',
          body: [
            'Caractéristique : il faut le niveau indiqué. Magique : 1 Magie. Gratuite : toujours.',
            'Clé éclair : c’est elle, et elle seule, qui autorise à jouer une carte de plus.',
          ],
          warn: 'La première carte du tour n’a besoin de rien. Toutes les suivantes exigent une clé éclair reliable sur la carte qu’on pose.',
          crop: { page: 17, x: 0.05, y: 0.165, w: 0.28, h: 0.185 },
          ref: 'Relier des Clés — p.16',
        },
        {
          id: 'r8',
          kind: 'check',
          title: 'Sortir de là',
          body: [
            'Victoire dès que le potentiel atteint la valeur de la rencontre, ou que l’affinité atteint le haut de la piste.',
            'Fuir coûte 1 Énergie et une attaque d’opportunité ; la carte retourne au bas de son paquet.',
          ],
          warn: 'Terreur au-dessus de la Santé : vous paniquez. Votre première carte est celle du dessus du paquet, et vous ne piochez pas en fin de tour.',
          ref: 'Contrôle de Victoire — p.15, Panique — p.16',
        },
      ],
    },

    {
      id: 'debrief',
      title: 'La suite',
      kind: 'debrief',
      goal: 'Savoir ranger la partie, et savoir ce qu’il vous reste à découvrir.',
      steps: [
        {
          id: 'x1',
          kind: 'info',
          title: 'Ouvrez le journal d’exploration',
          body: [
            'Lisez d’abord son chapitre « Comment utiliser le journal d’exploration ».',
            'C’est lui qui porte l’histoire ; les règles, vous les connaissez maintenant.',
          ],
          components: ['journal'],
          ref: 'Journal d’Exploration — p.12',
        },
        {
          id: 'x2',
          kind: 'info',
          title: 'Suivez vos quêtes, notez vos tâches',
          body: [
            'Les quêtes vous mènent à la fin du chapitre : elles sont sur des cartes Événement ou Secret.',
            'Les tâches sont des missions secondaires, souvent profitables, mais jamais obligatoires.',
          ],
          tip: 'Vous ne savez pas quoi faire ? Commencez toujours par relire vos quêtes actives.',
          ref: 'Événements, Quêtes et Tâches — p.11',
        },
        {
          id: 'x3',
          kind: 'info',
          title: 'Si votre personnage meurt',
          only: [1],
          body: [
            'En solitaire, la mort du personnage met fin à la partie.',
            'La Grâce de la Toute-Mère vous permet de reprendre au début du chapitre, avec des ressources prédéfinies.',
          ],
          warn: 'Le statut « Vous Êtes Mourant » laisse un peu de temps pour récupérer, mais chaque action peut être la dernière.',
          components: ['mourant'],
          ref: 'Mort et Folie — p.13',
        },
        {
          id: 'x3-coop',
          kind: 'info',
          title: 'Si un personnage meurt',
          only: [2, 3, 4],
          body: [
            'La partie continue : un joueur peut reprendre un personnage resté dans la boîte, placé sur le lieu révélé au plus petit numéro.',
            'Les objets du défunt restent sur le lieu de sa mort ; ses secrets se partagent entre les survivants.',
          ],
          warn: 'Si tous les personnages meurent, la partie se termine sur une défaite pour tout le monde.',
          components: ['mourant'],
          ref: 'Mort et Folie — p.13',
        },
        {
          id: 'x4',
          kind: 'check',
          title: 'Sauvegarder la partie',
          body: [
            'Sauvegardez à la fin d’un chapitre, quand le journal ou une carte Événement vous y invite.',
            'Chaque joueur note sur la fiche ses caractéristiques, ses ressources et ses pistes Survie.',
            'Puis on note le lieu de chaque personnage, la valeur de chaque cadran, et on empile les cartes par catégorie.',
          ],
          warn: 'Séparez bien les lieux retirés de la partie des lieux simplement non révélés : ils ne reviendront pas.',
          components: ['fiches'],
          ref: 'Sauvegarder la Partie — p.13',
        },
        {
          id: 'x5',
          kind: 'check',
          title: 'Ce que ce tutoriel n’a pas couvert',
          body: [
            'Les quêtes et tâches en détail, l’activation d’un menhir, la progression avancée.',
            'La folie, la mort, la Grâce de la Toute-Mère.',
            'Les modes Histoire et Défi, et le jeu libre — tout est page 22.',
          ],
          tip: 'Le résumé des règles, page 24 du livret, tient sur une page : gardez-le sous la main pour vos prochaines séances.',
          ref: 'Variantes & Appendices — p.22',
        },
        {
          id: 'x6',
          kind: 'info',
          title: 'Bon voyage',
          body: [
            'Explorez souvent : les meilleures trouvailles ne se révèlent qu’en explorant, parfois deux fois le même lieu.',
            'Gardez toujours de quoi tenir deux ou trois jours.',
            'Et sachez déjà quel menhir vous activerez ensuite.',
          ],
          ref: 'Conseils Généraux — p.13',
        },
      ],
    },
  ],
}
